ALTER TABLE USERS
ADD COLUMN IF NOT EXISTS IS_MANAGER BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE USERS u
SET IS_MANAGER = TRUE
FROM ROLES r
WHERE u.ID_ROLE = r.ID_ROLE
  AND r.NAMA_ROLE IN ('SUPER_ADMIN', 'MANAGER');

DROP INDEX IF EXISTS idx_users_id_role;

ALTER TABLE USERS
ALTER COLUMN ID_ROLE DROP NOT NULL;

ALTER TABLE USERS DROP CONSTRAINT IF EXISTS fk_users_role;
ALTER TABLE USERS
ADD CONSTRAINT fk_users_role FOREIGN KEY (ID_ROLE) REFERENCES ROLES(ID_ROLE) ON DELETE SET NULL;

DROP INDEX IF EXISTS idx_hak_akses_kode_permission;

ALTER TABLE HAK_AKSES
DROP COLUMN IF EXISTS AKSI_PERMISSION,
DROP COLUMN IF EXISTS DOMAIN_PERMISSION,
DROP COLUMN IF EXISTS DESKRIPSI,
DROP COLUMN IF EXISTS KODE_PERMISSION;
