-- Revert role name from ADMIN_SISTEM back to OPERATOR
UPDATE ROLES 
SET NAMA_ROLE = 'OPERATOR' 
WHERE NAMA_ROLE = 'ADMIN_SISTEM';

-- Delete the added Surat Jalan permissions
DELETE FROM HAK_AKSES
WHERE KODE_PERMISSION IN (
    'SURAT_JALAN_CLIENT_CREATE',
    'SURAT_JALAN_CLIENT_UPDATE',
    'SURAT_JALAN_CLIENT_DELETE',
    'SURAT_JALAN_INTERNAL_CREATE',
    'SURAT_JALAN_INTERNAL_UPDATE',
    'SURAT_JALAN_INTERNAL_DELETE'
);
