ALTER TABLE PR_INTERNAL
ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'draft',
ADD COLUMN IF NOT EXISTS approved_by_user_id INT,
ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ;

ALTER TABLE PR_INTERNAL
DROP CONSTRAINT IF EXISTS pr_internal_approved_by_user_id_fkey;

ALTER TABLE PR_INTERNAL
ADD CONSTRAINT pr_internal_approved_by_user_id_fkey
FOREIGN KEY (approved_by_user_id) REFERENCES USERS(ID_USER);

ALTER TABLE WORK_ORDER
ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'open',
ADD COLUMN IF NOT EXISTS closed_by_user_id INT,
ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ;

ALTER TABLE WORK_ORDER
DROP CONSTRAINT IF EXISTS work_order_closed_by_user_id_fkey;

ALTER TABLE WORK_ORDER
ADD CONSTRAINT work_order_closed_by_user_id_fkey
FOREIGN KEY (closed_by_user_id) REFERENCES USERS(ID_USER);
