CREATE TABLE IF NOT EXISTS MASTER_PAYMENT_TERM (
    ID_PAYMENT_TERM SERIAL PRIMARY KEY,
    KODE VARCHAR(100) NOT NULL UNIQUE,
    NAMA VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Seed COD and TRANSFER
INSERT INTO MASTER_PAYMENT_TERM (KODE, NAMA) VALUES 
('COD', 'COD'),
('TRANSFER', 'Transfer')
ON CONFLICT (KODE) DO NOTHING;

-- Add column ID_PAYMENT_TERM to PO_CLIENT
ALTER TABLE PO_CLIENT ADD COLUMN ID_PAYMENT_TERM INT;

-- Update existing rows based on string match
UPDATE PO_CLIENT 
SET ID_PAYMENT_TERM = (SELECT ID_PAYMENT_TERM FROM MASTER_PAYMENT_TERM WHERE KODE = 'COD')
WHERE UPPER(TRIM(PAYMENT_TERM)) = 'COD';

UPDATE PO_CLIENT 
SET ID_PAYMENT_TERM = (SELECT ID_PAYMENT_TERM FROM MASTER_PAYMENT_TERM WHERE KODE = 'TRANSFER')
WHERE UPPER(TRIM(PAYMENT_TERM)) != 'COD' OR PAYMENT_TERM IS NULL OR PAYMENT_TERM = '';

-- If there are still nulls, default them to TRANSFER
UPDATE PO_CLIENT
SET ID_PAYMENT_TERM = (SELECT ID_PAYMENT_TERM FROM MASTER_PAYMENT_TERM WHERE KODE = 'TRANSFER')
WHERE ID_PAYMENT_TERM IS NULL;

-- Now make it NOT NULL and add Foreign Key constraint
ALTER TABLE PO_CLIENT ALTER COLUMN ID_PAYMENT_TERM SET NOT NULL;
ALTER TABLE PO_CLIENT ADD CONSTRAINT fk_po_client_payment_term FOREIGN KEY (ID_PAYMENT_TERM) REFERENCES MASTER_PAYMENT_TERM(ID_PAYMENT_TERM);

-- Drop the old column
ALTER TABLE PO_CLIENT DROP COLUMN PAYMENT_TERM;
