ALTER TABLE PACKING_LIST_ITEM_SIZE DROP CONSTRAINT IF EXISTS UQ_PACKING_LIST_ITEM_SIZE;
ALTER TABLE PACKING_LIST_ITEM_SIZE DROP CONSTRAINT IF EXISTS FK_PACKING_LIST_ITEM_SIZE_WO_SIZE;
ALTER TABLE PACKING_LIST_ITEM_SIZE DROP COLUMN IF EXISTS ID_WO_SHELL_SIZE;

ALTER TABLE PACKING_LIST_REJECT_SIZE DROP CONSTRAINT IF EXISTS UQ_PACKING_LIST_REJECT_SIZE;
ALTER TABLE PACKING_LIST_REJECT_SIZE DROP CONSTRAINT IF EXISTS FK_PACKING_LIST_REJECT_SIZE_WO_SIZE;
ALTER TABLE PACKING_LIST_REJECT_SIZE DROP COLUMN IF EXISTS ID_WO_SHELL_SIZE;
