ALTER TABLE BARANG
ADD COLUMN IF NOT EXISTS satuan VARCHAR(50) NOT NULL DEFAULT 'pcs',
ADD COLUMN IF NOT EXISTS lokasi_rak VARCHAR(100) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS stok_minimum INT NOT NULL DEFAULT 0;
