-- Truncate existing packing list item sizes and reject sizes because we are refactoring their schema
TRUNCATE TABLE PACKING_LIST_ITEM_SIZE CASCADE;
TRUNCATE TABLE PACKING_LIST_REJECT_SIZE CASCADE;

-- Modify PACKING_LIST_ITEM_SIZE
ALTER TABLE PACKING_LIST_ITEM_SIZE ADD COLUMN ID_WO_SHELL_SIZE INT NOT NULL;
ALTER TABLE PACKING_LIST_ITEM_SIZE ADD CONSTRAINT FK_PACKING_LIST_ITEM_SIZE_WO_SIZE FOREIGN KEY (ID_WO_SHELL_SIZE) REFERENCES WORK_ORDER_SHELL_SIZE(ID_WO_SHELL_SIZE) ON DELETE CASCADE;
ALTER TABLE PACKING_LIST_ITEM_SIZE ADD CONSTRAINT UQ_PACKING_LIST_ITEM_SIZE UNIQUE (ID_PACKING_LIST_ITEM, ID_WO_SHELL_SIZE);

-- Modify PACKING_LIST_REJECT_SIZE
ALTER TABLE PACKING_LIST_REJECT_SIZE ADD COLUMN ID_WO_SHELL_SIZE INT NOT NULL;
ALTER TABLE PACKING_LIST_REJECT_SIZE ADD CONSTRAINT FK_PACKING_LIST_REJECT_SIZE_WO_SIZE FOREIGN KEY (ID_WO_SHELL_SIZE) REFERENCES WORK_ORDER_SHELL_SIZE(ID_WO_SHELL_SIZE) ON DELETE CASCADE;
ALTER TABLE PACKING_LIST_REJECT_SIZE ADD CONSTRAINT UQ_PACKING_LIST_REJECT_SIZE UNIQUE (ID_PACKING_LIST, ID_WO_SHELL_SIZE);
