ALTER TABLE RATIO_MARKER 
    ADD COLUMN PLOT INT NOT NULL DEFAULT 1,
    ADD COLUMN LEBAR_KAIN DECIMAL(15,3) NOT NULL DEFAULT 0,
    ADD COLUMN PANJANG_MARKER_UNIT VARCHAR(50) NOT NULL DEFAULT 'yard',
    ADD COLUMN KET TEXT NOT NULL DEFAULT '';
