-- Recreate the retired permission and its former default role assignments.
-- Custom role assignments removed by the up migration cannot be reconstructed.
INSERT INTO HAK_AKSES (
    KODE_PERMISSION,
    NAMA_HALAMAN,
    DESKRIPSI,
    DOMAIN_PERMISSION,
    AKSI_PERMISSION
)
VALUES (
    'AI_ESTIMATION_READ',
    'Ai Estimation Read',
    'Allows ai estimation read',
    'ai_estimation',
    'read'
)
ON CONFLICT (KODE_PERMISSION) DO UPDATE
SET NAMA_HALAMAN = EXCLUDED.NAMA_HALAMAN,
    DESKRIPSI = EXCLUDED.DESKRIPSI,
    DOMAIN_PERMISSION = EXCLUDED.DOMAIN_PERMISSION,
    AKSI_PERMISSION = EXCLUDED.AKSI_PERMISSION;

INSERT INTO ROLE_HAK_AKSES (ID_ROLE, ID_HAK_AKSES)
SELECT r.ID_ROLE, h.ID_HAK_AKSES
FROM ROLES r
JOIN HAK_AKSES h ON h.KODE_PERMISSION = 'AI_ESTIMATION_READ'
WHERE r.NAMA_ROLE IN ('ADMIN_PRODUKSI', 'MANAGER')
ON CONFLICT (ID_ROLE, ID_HAK_AKSES) DO NOTHING;
