DROP TABLE IF EXISTS MATERIAL_LIST_ITEM CASCADE;
CREATE TABLE MATERIAL_LIST_ITEM (
    ID_MATERIAL_LIST_ITEM SERIAL PRIMARY KEY,
    LEGACY_ID_MATERIAL_LIST INT UNIQUE,
    DESCRIPTION TEXT NOT NULL DEFAULT '',
    ID_WO INT NOT NULL,
    ID_WO_SHELL INT,
    ID_WO_TRIM INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO) REFERENCES WORK_ORDER(ID_WO) ON DELETE CASCADE,
    FOREIGN KEY (ID_WO_SHELL) REFERENCES WORK_ORDER_SHELL(ID_WO_SHELL) ON DELETE CASCADE,
    FOREIGN KEY (ID_WO_TRIM) REFERENCES WORK_ORDER_TRIM(ID_WO_TRIM) ON DELETE CASCADE
);

ALTER TABLE MATERIAL_LIST ADD COLUMN IF NOT EXISTS ID_MATERIAL_LIST_ITEM INT;
ALTER TABLE SURAT_JALAN_CLIENT ADD COLUMN IF NOT EXISTS ID_MATERIAL_LIST_ITEM INT;
ALTER TABLE RECEIVED ADD COLUMN IF NOT EXISTS ID_MATERIAL_LIST_ITEM INT;

INSERT INTO MATERIAL_LIST_ITEM (
    LEGACY_ID_MATERIAL_LIST,
    DESCRIPTION,
    ID_WO,
    ID_WO_SHELL,
    ID_WO_TRIM,
    created_at
)
SELECT
    ml.ID_MATERIAL_LIST,
    ml.DESCRIPTION,
    ml.ID_WO,
    (
        SELECT wos.ID_WO_SHELL
        FROM WORK_ORDER_SHELL wos
        WHERE wos.ID_WO = ml.ID_WO
          AND LOWER(COALESCE(wos.COLOR, '')) = LOWER(COALESCE(ml.COLOR, ''))
          AND (
              LOWER(COALESCE(ml.DESCRIPTION, '')) LIKE '%' || LOWER(COALESCE(wos.FABRIC, '')) || '%'
              OR LOWER(COALESCE(wos.FABRIC, '')) LIKE '%' || LOWER(COALESCE(ml.DESCRIPTION, '')) || '%'
          )
        ORDER BY wos.ID_WO_SHELL
        LIMIT 1
    ) AS ID_WO_SHELL,
    (
        SELECT wot.ID_WO_TRIM
        FROM WORK_ORDER_TRIM wot
        WHERE wot.ID_WO = ml.ID_WO
          AND LOWER(COALESCE(wot.COLOR, '')) = LOWER(COALESCE(ml.COLOR, ''))
          AND (
              LOWER(COALESCE(ml.DESCRIPTION, '')) LIKE '%' || LOWER(COALESCE(wot.DESCRIPTION, '')) || '%'
              OR LOWER(COALESCE(wot.DESCRIPTION, '')) LIKE '%' || LOWER(COALESCE(ml.DESCRIPTION, '')) || '%'
              OR LOWER(COALESCE(ml.DESCRIPTION, '')) LIKE '%' || LOWER(COALESCE(wot.ITEM, '')) || '%'
              OR LOWER(COALESCE(wot.ITEM, '')) LIKE '%' || LOWER(COALESCE(ml.DESCRIPTION, '')) || '%'
              OR (
                  SPLIT_PART(LOWER(COALESCE(wot.DESCRIPTION, '')), ' ', 1) <> ''
                  AND LOWER(COALESCE(ml.DESCRIPTION, '')) LIKE '%' || SPLIT_PART(LOWER(COALESCE(wot.DESCRIPTION, '')), ' ', 1) || '%'
              )
          )
          AND (
              COALESCE(ml.UOM, '') = ''
              OR LOWER(COALESCE(wot.UOM, '')) = LOWER(COALESCE(ml.UOM, ''))
          )
        ORDER BY wot.ID_WO_TRIM
        LIMIT 1
    ) AS ID_WO_TRIM,
    ml.created_at
FROM MATERIAL_LIST ml;

UPDATE MATERIAL_LIST ml
SET ID_MATERIAL_LIST_ITEM = mli.ID_MATERIAL_LIST_ITEM
FROM MATERIAL_LIST_ITEM mli
WHERE mli.LEGACY_ID_MATERIAL_LIST = ml.ID_MATERIAL_LIST;

UPDATE SURAT_JALAN_CLIENT sjc
SET ID_MATERIAL_LIST_ITEM = ml.ID_MATERIAL_LIST_ITEM
FROM MATERIAL_LIST ml
WHERE sjc.ID_MATERIAL_LIST = ml.ID_MATERIAL_LIST;

UPDATE RECEIVED r
SET ID_MATERIAL_LIST_ITEM = ml.ID_MATERIAL_LIST_ITEM
FROM MATERIAL_LIST ml
WHERE r.ID_MATERIAL_LIST = ml.ID_MATERIAL_LIST;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM MATERIAL_LIST WHERE ID_MATERIAL_LIST_ITEM IS NULL) THEN
        RAISE EXCEPTION 'material_list backfill to material_list_item failed';
    END IF;

    IF EXISTS (SELECT 1 FROM SURAT_JALAN_CLIENT WHERE ID_MATERIAL_LIST_ITEM IS NULL) THEN
        RAISE EXCEPTION 'surat_jalan_client backfill to material_list_item failed';
    END IF;

    IF EXISTS (SELECT 1 FROM RECEIVED WHERE ID_MATERIAL_LIST_ITEM IS NULL) THEN
        RAISE EXCEPTION 'received backfill to material_list_item failed';
    END IF;
END $$;

ALTER TABLE RECEIVED DROP CONSTRAINT IF EXISTS received_id_material_list_fkey;
ALTER TABLE SURAT_JALAN_CLIENT DROP CONSTRAINT IF EXISTS surat_jalan_client_id_material_list_fkey;

ALTER TABLE MATERIAL_LIST DROP COLUMN IF EXISTS DESCRIPTION CASCADE;
ALTER TABLE MATERIAL_LIST DROP COLUMN IF EXISTS SIZE CASCADE;
ALTER TABLE MATERIAL_LIST DROP COLUMN IF EXISTS COLOR CASCADE;
ALTER TABLE MATERIAL_LIST DROP COLUMN IF EXISTS UOM CASCADE;
ALTER TABLE MATERIAL_LIST DROP COLUMN IF EXISTS ID_WO CASCADE;
ALTER TABLE MATERIAL_LIST ALTER COLUMN ID_MATERIAL_LIST_ITEM SET NOT NULL;
ALTER TABLE MATERIAL_LIST DROP CONSTRAINT IF EXISTS fk_ml_mli;
ALTER TABLE MATERIAL_LIST ADD CONSTRAINT fk_ml_mli FOREIGN KEY (ID_MATERIAL_LIST_ITEM) REFERENCES MATERIAL_LIST_ITEM(ID_MATERIAL_LIST_ITEM) ON DELETE CASCADE;

ALTER TABLE SURAT_JALAN_CLIENT DROP COLUMN IF EXISTS ID_MATERIAL_LIST CASCADE;
ALTER TABLE SURAT_JALAN_CLIENT ALTER COLUMN ID_MATERIAL_LIST_ITEM SET NOT NULL;
ALTER TABLE SURAT_JALAN_CLIENT DROP CONSTRAINT IF EXISTS fk_sjc_mli;
ALTER TABLE SURAT_JALAN_CLIENT ADD CONSTRAINT fk_sjc_mli FOREIGN KEY (ID_MATERIAL_LIST_ITEM) REFERENCES MATERIAL_LIST_ITEM(ID_MATERIAL_LIST_ITEM) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_surat_jalan_client_id_material_list_item ON SURAT_JALAN_CLIENT (ID_MATERIAL_LIST_ITEM);

ALTER TABLE RECEIVED DROP COLUMN IF EXISTS ID_MATERIAL_LIST CASCADE;
ALTER TABLE RECEIVED ALTER COLUMN ID_MATERIAL_LIST_ITEM SET NOT NULL;
ALTER TABLE RECEIVED DROP CONSTRAINT IF EXISTS fk_recv_mli;
ALTER TABLE RECEIVED ADD CONSTRAINT fk_recv_mli FOREIGN KEY (ID_MATERIAL_LIST_ITEM) REFERENCES MATERIAL_LIST_ITEM(ID_MATERIAL_LIST_ITEM) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_received_id_material_list_item ON RECEIVED (ID_MATERIAL_LIST_ITEM);

ALTER TABLE MATERIAL_LIST_ITEM DROP COLUMN IF EXISTS LEGACY_ID_MATERIAL_LIST;
