DROP TABLE IF EXISTS RATIO_SIZE_SPREADING;
DROP TABLE IF EXISTS RATIO_SPREADING;
DROP TABLE IF EXISTS KOMPONEN_SPREADING_CUTTING_PLAN;
DROP TABLE IF EXISTS SPREADING_CUTTING_PLAN;

ALTER TABLE RATIO_MARKER ADD COLUMN IF NOT EXISTS ROLL_QTY INT NOT NULL DEFAULT 0;
ALTER TABLE RATIO_MARKER ADD COLUMN IF NOT EXISTS SAMBUNGAN_ROLL INT NOT NULL DEFAULT 0;
