-- =================================================================================
-- 1. PENYESUAIAN RBAC (PILIHAN 2: ROLE + OVERRIDE USER_AKSES)
-- =================================================================================

CREATE TABLE IF NOT EXISTS ROLES (
    ID_ROLE SERIAL PRIMARY KEY,
    NAMA_ROLE VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ROLE_HAK_AKSES (
    ID_ROLE INT NOT NULL,
    ID_HAK_AKSES INT NOT NULL,
    PRIMARY KEY (ID_ROLE, ID_HAK_AKSES),
    FOREIGN KEY (ID_ROLE) REFERENCES ROLES(ID_ROLE) ON DELETE CASCADE,
    FOREIGN KEY (ID_HAK_AKSES) REFERENCES HAK_AKSES(ID_HAK_AKSES) ON DELETE CASCADE
);

-- Tambahkan kolom ID_ROLE ke USERS
ALTER TABLE USERS 
ADD COLUMN IF NOT EXISTS ID_ROLE INT,
ADD CONSTRAINT fk_users_role FOREIGN KEY (ID_ROLE) REFERENCES ROLES(ID_ROLE) ON DELETE SET NULL;

-- =================================================================================
-- 2. PENAMBAHAN FITUR: VALIDASI TERPUSAT & DOKUMEN GABUNGAN
-- =================================================================================

CREATE TABLE IF NOT EXISTS ARSIP_DOKUMEN_GABUNGAN (
    ID_ARSIP SERIAL PRIMARY KEY,
    NAMA_DOKUMEN VARCHAR(150) NOT NULL,
    TIPE_DOKUMEN VARCHAR(100) NOT NULL,
    PARAMETER_QUERY TEXT NOT NULL,
    FILE_URL TEXT NOT NULL DEFAULT '',
    ID_PEMBUAT INT NOT NULL REFERENCES USERS(ID_USER) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS OTORITAS_DOKUMEN (
    ID_OTORITAS SERIAL PRIMARY KEY,
    NAMA_TABEL_DOKUMEN VARCHAR(100) NOT NULL, 
    ID_DOKUMEN INT NOT NULL,
    STATUS_GLOBAL VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_otoritas_dok_global ON OTORITAS_DOKUMEN (NAMA_TABEL_DOKUMEN, ID_DOKUMEN);

CREATE TABLE IF NOT EXISTS OTORITAS_DOKUMEN_DETAIL (
    ID_OTORITAS_DETAIL SERIAL PRIMARY KEY,
    ID_OTORITAS INT NOT NULL,
    ID_USER INT NOT NULL,
    TIPE_PERAN VARCHAR(50) NOT NULL,
    IS_ACTION_DONE BOOLEAN NOT NULL DEFAULT FALSE,
    WAKTU_AKSI TIMESTAMPTZ,
    CATATAN TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_OTORITAS) REFERENCES OTORITAS_DOKUMEN(ID_OTORITAS) ON DELETE CASCADE,
    FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER) ON DELETE CASCADE
);
