CREATE TABLE IF NOT EXISTS MATERIAL_LIST_ITEM (
    ID_MATERIAL_LIST_ITEM SERIAL PRIMARY KEY,
    DESCRIPTION TEXT NOT NULL DEFAULT '',
    ID_WO_SHELL INT,
    ID_WO_TRIM INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO_SHELL) REFERENCES WORK_ORDER_SHELL(ID_WO_SHELL) ON DELETE CASCADE,
    FOREIGN KEY (ID_WO_TRIM) REFERENCES WORK_ORDER_TRIM(ID_WO_TRIM) ON DELETE CASCADE
);

ALTER TABLE MATERIAL_LIST DROP COLUMN IF EXISTS DESCRIPTION CASCADE;
ALTER TABLE MATERIAL_LIST DROP COLUMN IF EXISTS SIZE CASCADE;
ALTER TABLE MATERIAL_LIST DROP COLUMN IF EXISTS COLOR CASCADE;
ALTER TABLE MATERIAL_LIST DROP COLUMN IF EXISTS UOM CASCADE;
ALTER TABLE MATERIAL_LIST DROP COLUMN IF EXISTS ID_WO CASCADE;
ALTER TABLE MATERIAL_LIST ADD COLUMN ID_MATERIAL_LIST_ITEM INT NOT NULL;
ALTER TABLE MATERIAL_LIST ADD CONSTRAINT fk_ml_mli FOREIGN KEY (ID_MATERIAL_LIST_ITEM) REFERENCES MATERIAL_LIST_ITEM(ID_MATERIAL_LIST_ITEM) ON DELETE CASCADE;

ALTER TABLE SURAT_JALAN_CLIENT DROP COLUMN IF EXISTS ID_MATERIAL_LIST CASCADE;
ALTER TABLE SURAT_JALAN_CLIENT ADD COLUMN ID_MATERIAL_LIST_ITEM INT NOT NULL;
ALTER TABLE SURAT_JALAN_CLIENT ADD CONSTRAINT fk_sjc_mli FOREIGN KEY (ID_MATERIAL_LIST_ITEM) REFERENCES MATERIAL_LIST_ITEM(ID_MATERIAL_LIST_ITEM) ON DELETE CASCADE;

ALTER TABLE RECEIVED DROP COLUMN IF EXISTS ID_MATERIAL_LIST CASCADE;
ALTER TABLE RECEIVED ADD COLUMN ID_MATERIAL_LIST_ITEM INT NOT NULL;
ALTER TABLE RECEIVED ADD CONSTRAINT fk_recv_mli FOREIGN KEY (ID_MATERIAL_LIST_ITEM) REFERENCES MATERIAL_LIST_ITEM(ID_MATERIAL_LIST_ITEM) ON DELETE CASCADE;
