-- 1. Tabel Master (Tanpa Dependencies)
CREATE TABLE IF NOT EXISTS COMPANY (
    ID_COMPANY INT PRIMARY KEY,
    NAMA VARCHAR(100),
    ALAMAT VARCHAR(100),
    EMAIL VARCHAR(100),
    NO_TELP VARCHAR(100),
    ABOUT VARCHAR(100),
    LOGO VARCHAR, -- PostgreSQL mendukung VARCHAR tanpa length
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "USER" ( -- USER adalah keyword, gunakan kutip
    ID_USER INT PRIMARY KEY,
    USERNAME VARCHAR(100),
    PASSWORD VARCHAR(100),
    KARYAWAN BOOLEAN,
    DEPARTEMEN VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS LOG_AKTIVITAS (
    ID_LOG INT PRIMARY KEY,
    AKSI VARCHAR(100),
    WAKTU TIMESTAMP, -- PostgreSQL menggunakan TIMESTAMP/TIMESTAMPTZ bukan DATETIME
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS HAK_AKSES (
    ID_HAK_AKSES INT PRIMARY KEY,
    NAMA_HALAMAN VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS MITRA (
    ID_MITRA INT PRIMARY KEY,
    NAMA_PERUSAHAAN VARCHAR(100),
    TIPE_PERUSAHAAN VARCHAR(100),
    EMAIL VARCHAR(100),
    NO_TELP VARCHAR(100),
    ALAMAT VARCHAR(100),
    KOTA VARCHAR(100),
    KODE_POS VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS JENIS_BARANG (
    ID_JENIS_BARANG INT PRIMARY KEY,
    NAMA_JENIS_BARANG VARCHAR(100),
    KODE VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS PO_CLIENT_ITEM (
    ID_PO_CLIENT_ITEM INT PRIMARY KEY,
    STYLE VARCHAR(100),
    COLOUR VARCHAR(100),
    "DESC" VARCHAR(100), -- DESC adalah keyword, gunakan kutip
    QTY INT,
    PRICE DECIMAL(10,3),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS SURAT_JALAN_INTERNAL (
    ID_SURAT_JALAN_INTERNAL INT PRIMARY KEY, -- Tambah tipe data INT
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS PACKING_LIST_ITEM (
    ID_PACKING_LIST_ITEM INT PRIMARY KEY,
    COLOR VARCHAR(100),
    QTY_BOX INT,
    QTY_PER_BOX INT,
    BOX_NO_START INT,
    BOX_NO_END INT,
    NOTE VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Tabel Level 2 (Relasi ke Master)
CREATE TABLE IF NOT EXISTS DEPARTEMEN (
    ID_DEPARTEMEN INT PRIMARY KEY,
    NAMA_DEPARTEMEN VARCHAR(100),
    ID_USER INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_USER) REFERENCES "USER"(ID_USER)
);

CREATE TABLE IF NOT EXISTS LOG_AKTIVITAS_DETAIL (
    ID_LOG_DETAIL INT PRIMARY KEY,
    NAMA VARCHAR(100),
    "TABLE" VARCHAR(100), -- TABLE adalah keyword, gunakan kutip
    DESKRIPSI VARCHAR(100),
    ID_LOG INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_LOG) REFERENCES LOG_AKTIVITAS(ID_LOG)
);

CREATE TABLE IF NOT EXISTS USER_AKSES (
    ID_USER INT,
    ID_HAK_AKSES INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID_USER, ID_HAK_AKSES),
    FOREIGN KEY (ID_USER) REFERENCES "USER"(ID_USER),
    FOREIGN KEY (ID_HAK_AKSES) REFERENCES HAK_AKSES(ID_HAK_AKSES)
);

CREATE TABLE IF NOT EXISTS PO_CLIENT (
    ID_PO_CLIENT INT PRIMARY KEY,
    PO_NUMBER VARCHAR(100),
    TANGGAL DATE,
    SEASON VARCHAR(100),
    DELIVERY DATE,
    PAYMENT_TERM VARCHAR(100),
    FILE VARCHAR(100),
    ID_MITRA INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_MITRA) REFERENCES MITRA(ID_MITRA)
);

CREATE TABLE IF NOT EXISTS BARANG (
    ID_BARANG INT PRIMARY KEY,
    NAMA_BARANG VARCHAR(100),
    KODE VARCHAR(100),
    ID_JENIS_BARANG INT,
    ID_MITRA INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_JENIS_BARANG) REFERENCES JENIS_BARANG(ID_JENIS_BARANG),
    FOREIGN KEY (ID_MITRA) REFERENCES MITRA(ID_MITRA)
);

CREATE TABLE IF NOT EXISTS PACKING_LIST_ITEM_SIZE (
    ID_PACKING_LIST_ITEM_SIZE INT PRIMARY KEY,
    QTY INT,
    ID_PACKING_LIST_ITEM INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_PACKING_LIST_ITEM) REFERENCES PACKING_LIST_ITEM(ID_PACKING_LIST_ITEM)
);

-- 3. Tabel Level 3 (Work Order & Client Details)
CREATE TABLE IF NOT EXISTS PENANGGUNG_JAWAB (
    ID_PENANGGUNG_JAWAB INT PRIMARY KEY,
    NAMA VARCHAR(100),
    NO_TELP VARCHAR(100),
    EMAIL VARCHAR(100),
    ID_PO_CLIENT INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_PO_CLIENT) REFERENCES PO_CLIENT(ID_PO_CLIENT)
);

CREATE TABLE IF NOT EXISTS WORK_ORDER (
    ID_WO INT PRIMARY KEY,
    BUYER VARCHAR(100),
    MODEL VARCHAR(100),
    QTY INT,
    FOB_CMT BOOLEAN,
    DELIVERY DATE,
    ID_PO_Client_Item INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_PO_Client_Item) REFERENCES PO_CLIENT_ITEM(ID_PO_CLIENT_ITEM)
);

-- 4. Tabel Level 4 (Dependencies of Work Order)
CREATE TABLE IF NOT EXISTS WORK_ORDER_SHELL (
    ID_WO_SHELL INT PRIMARY KEY,
    FABRIC VARCHAR(100),
    CONS DECIMAL(10,3),
    COLOR VARCHAR(100),
    ALLOW INT,
    BERAT_1_YD DECIMAL(10,3),
    ID_WO INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO) REFERENCES WORK_ORDER(ID_WO)
);

CREATE TABLE IF NOT EXISTS WORK_ORDER_TRIM (
    ID_WO_TRIM INT PRIMARY KEY,
    ITEM VARCHAR(100),
    "DESC" VARCHAR(100),
    COLOR VARCHAR(100),
    CODE VARCHAR(100),
    CONS DECIMAL(10,3),
    QTY INT,
    UOM VARCHAR(10),
    POSITION VARCHAR(100),
    "BY" VARCHAR(100),
    ALLOW INT,
    ID_WO INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO) REFERENCES WORK_ORDER(ID_WO)
);

CREATE TABLE IF NOT EXISTS MATERIAL_LIST (
    ID_MATERIAL_LIST INT PRIMARY KEY,
    "DESC" VARCHAR(100),
    SIZE VARCHAR(10),
    COLOR VARCHAR(100),
    UOM VARCHAR(10),
    ID_WO INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO) REFERENCES WORK_ORDER(ID_WO)
);

CREATE TABLE IF NOT EXISTS REKONSILIASI_MATERIAL (
    ID_REKONSILIASI_MATERIAL INT PRIMARY KEY,
    DESCRIPTION VARCHAR(100),
    SIZE VARCHAR(100),
    RATIO INT,
    QTY_PER_PCS DECIMAL(10,3),
    QTY_WO INT,
    TOLERANSI INT,
    SATUAN VARCHAR(10),
    ACTUAL_KIRIM INT,
    CONS_ACTUAL DECIMAL(10,3),
    BALANCE INT,
    REJECT INT,
    RETUR INT,
    LAST_BALANCE INT,
    KETERANGAN VARCHAR(10),
    ID_WO INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO) REFERENCES WORK_ORDER(ID_WO)
);

CREATE TABLE IF NOT EXISTS PR_INTERNAL (
    ID_PR_INTERNAL INT PRIMARY KEY,
    TANGGAL DATE,
    NAMA VARCHAR(100),
    DEPARTEMEN VARCHAR(100),
    VENDOR_NAME VARCHAR(100),
    VENDOR_ADDRESS VARCHAR(100),
    VENDOR_TELP VARCHAR(100),
    PROJEK VARCHAR(100),
    ID_WO INT,
    ID_USER INT, -- Tambah tipe data INT
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO) REFERENCES WORK_ORDER(ID_WO),
    FOREIGN KEY (ID_USER) REFERENCES "USER"(ID_USER)
);

CREATE TABLE IF NOT EXISTS PACKING_LIST (
    ID_PACKING_LIST INT PRIMARY KEY,
    TOTAL_GARMENT_PER_BOX INT,
    TOTAL_REJECT INT,
    ID_WO INT,
    ID_SURAT_JALAN_INTERNAL INT, -- Sesuaikan nama dengan kolom yang ada
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO) REFERENCES WORK_ORDER(ID_WO),
    FOREIGN KEY (ID_SURAT_JALAN_INTERNAL) REFERENCES SURAT_JALAN_INTERNAL(ID_SURAT_JALAN_INTERNAL)
);

-- 5. Tabel Level Terakhir (Deepest Dependencies)
CREATE TABLE IF NOT EXISTS WORK_ORDER_SHELL_SIZE (
    ID_WO_SHELL_SIZE INT PRIMARY KEY,
    SIZE VARCHAR(10),
    QTY INT,
    RATIO INT,
    ID_WO_SHELL INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO_SHELL) REFERENCES WORK_ORDER_SHELL(ID_WO_SHELL)
);

CREATE TABLE IF NOT EXISTS SURAT_JALAN_CLIENT (
    ID_SURAT_JALAN_CLIENT INT PRIMARY KEY,
    TANGGAL DATE,
    QTY INT,
    KETERANGAN VARCHAR(100),
    ID_MATERIAL_LIST INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_MATERIAL_LIST) REFERENCES MATERIAL_LIST(ID_MATERIAL_LIST)
);

CREATE TABLE IF NOT EXISTS RECEIVED (
    ID_RECEIVED INT PRIMARY KEY,
    TANGGAL DATE,
    QTY INT,
    KETERANGAN VARCHAR(100),
    ID_MATERIAL_LIST INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_MATERIAL_LIST) REFERENCES MATERIAL_LIST(ID_MATERIAL_LIST)
);

CREATE TABLE IF NOT EXISTS PR_INTERNAL_ITEM (
    ID_PR_INTERNAL_ITEM INT PRIMARY KEY,
    ITEM VARCHAR(100),
    QTY INT,
    UNIT VARCHAR(10),
    "DESC" VARCHAR(100),
    EST_PRICE DECIMAL(10,3),
    ID_PR_INTERNAL INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_PR_INTERNAL) REFERENCES PR_INTERNAL(ID_PR_INTERNAL)
);

CREATE TABLE IF NOT EXISTS PO_INTERNAL (
    ID_PO_INTERNAL INT PRIMARY KEY, -- Perbaiki nama PK agar konsisten
    TANGGAL DATE,
    NAMA_PO VARCHAR(100),
    SUPPLIER_NAME VARCHAR(100),
    SUPPLIER_ADDR VARCHAR(100),
    SUPPLIER_CONTACT VARCHAR(100),
    SUPPLIER_EMAIL VARCHAR(100),
    SUPPLIER_TELP VARCHAR(100),
    SUPPLIER_FAX VARCHAR(100),
    CURRENCY VARCHAR(10),
    CPO VARCHAR(255),
    TERM VARCHAR(255),
    SHIP_DATE DATE,
    ID_PR_INTERNAL INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_PR_INTERNAL) REFERENCES PR_INTERNAL(ID_PR_INTERNAL)
);

CREATE TABLE IF NOT EXISTS PO_INTERNAL_ITEM (
    ID_PO_INTERNAL_ITEM INT PRIMARY KEY,
    ITEM VARCHAR(100),
    "DESC" VARCHAR(100),
    QTY INT,
    UNIT VARCHAR(10),
    UNIT_PRICE DECIMAL(10,3),
    ID_PO_INTERNAL INT, -- Sesuai dengan PO_INTERNAL
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_PO_INTERNAL) REFERENCES PO_INTERNAL(ID_PO_INTERNAL)
);

CREATE TABLE IF NOT EXISTS REKONSILIASI_MATERIAL_TERIMA (
    ID_REKONSILIASI_MATERIAL_TERIMA INT PRIMARY KEY,
    KETERANGAN VARCHAR(100),
    QTY INT,
    ID_REKONSILIASI_MATERIAL INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_REKONSILIASI_MATERIAL) REFERENCES REKONSILIASI_MATERIAL(ID_REKONSILIASI_MATERIAL)
);

-- Report Tables (Semua tergantung pada WORK_ORDER_SHELL_SIZE)
CREATE TABLE IF NOT EXISTS REPORT_CUTTING (
    ID_REPORT_CUTTING INT PRIMARY KEY,
    TANGGAL DATE,
    QTY INT,
    ID_WO_SHELL_SIZE INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO_SHELL_SIZE) REFERENCES WORK_ORDER_SHELL_SIZE(ID_WO_SHELL_SIZE)
);

CREATE TABLE IF NOT EXISTS REPORT_SEWING (
    ID_REPORT_SEWING INT PRIMARY KEY,
    TANGGAL DATE,
    QTY INT,
    ID_WO_SHELL_SIZE INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO_SHELL_SIZE) REFERENCES WORK_ORDER_SHELL_SIZE(ID_WO_SHELL_SIZE)
);

CREATE TABLE IF NOT EXISTS REPORT_QC_FINISH (
    ID_REPORT_QC_FINISHING INT PRIMARY KEY,
    TANGGAL DATE,
    QTY INT,
    ID_WO_SHELL_SIZE INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO_SHELL_SIZE) REFERENCES WORK_ORDER_SHELL_SIZE(ID_WO_SHELL_SIZE)
);

CREATE TABLE IF NOT EXISTS REPORT_PACKING (
    ID_REPORT_PACKING INT PRIMARY KEY,
    TANGGAL DATE,
    QTY INT,
    ID_WO_SHELL_SIZE INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO_SHELL_SIZE) REFERENCES WORK_ORDER_SHELL_SIZE(ID_WO_SHELL_SIZE)
);

CREATE TABLE IF NOT EXISTS REPORT_PENGIRIMAN (
    ID_REPORT_PENGIRIMAN INT PRIMARY KEY,
    "DATE" DATE,
    Quantity INT,
    ID_WO_SHELL_SIZE INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO_SHELL_SIZE) REFERENCES WORK_ORDER_SHELL_SIZE(ID_WO_SHELL_SIZE)
);