
-- Rollback schema created in 000001_init.up.sql
-- Drop from deepest dependencies to master tables.

DROP TABLE IF EXISTS REPORT_PENGIRIMAN;
DROP TABLE IF EXISTS REPORT_PACKING;
DROP TABLE IF EXISTS REPORT_QC_FINISH;
DROP TABLE IF EXISTS REPORT_SEWING;
DROP TABLE IF EXISTS REPORT_CUTTING;

DROP TABLE IF EXISTS REKONSILIASI_MATERIAL_TERIMA;
DROP TABLE IF EXISTS PO_INTERNAL_ITEM;
DROP TABLE IF EXISTS PO_INTERNAL;
DROP TABLE IF EXISTS PR_INTERNAL_ITEM;
DROP TABLE IF EXISTS RECEIVED;
DROP TABLE IF EXISTS SURAT_JALAN_CLIENT;
DROP TABLE IF EXISTS WORK_ORDER_SHELL_SIZE;

DROP TABLE IF EXISTS PACKING_LIST;
DROP TABLE IF EXISTS PR_INTERNAL;
DROP TABLE IF EXISTS REKONSILIASI_MATERIAL;
DROP TABLE IF EXISTS MATERIAL_LIST;
DROP TABLE IF EXISTS WORK_ORDER_TRIM;
DROP TABLE IF EXISTS WORK_ORDER_SHELL;
DROP TABLE IF EXISTS WORK_ORDER;
DROP TABLE IF EXISTS PENANGGUNG_JAWAB;

DROP TABLE IF EXISTS PACKING_LIST_ITEM_SIZE;
DROP TABLE IF EXISTS BARANG;
DROP TABLE IF EXISTS PO_CLIENT;
DROP TABLE IF EXISTS USER_AKSES;
DROP TABLE IF EXISTS LOG_AKTIVITAS_DETAIL;
DROP TABLE IF EXISTS DEPARTEMEN;

DROP TABLE IF EXISTS PACKING_LIST_ITEM;
DROP TABLE IF EXISTS SURAT_JALAN_INTERNAL;
DROP TABLE IF EXISTS PO_CLIENT_ITEM;
DROP TABLE IF EXISTS JENIS_BARANG;
DROP TABLE IF EXISTS MITRA;
DROP TABLE IF EXISTS HAK_AKSES;
DROP TABLE IF EXISTS LOG_AKTIVITAS;
DROP TABLE IF EXISTS "USER";
DROP TABLE IF EXISTS COMPANY;
