ALTER TABLE WORK_ORDER_TRIM DROP COLUMN IF EXISTS PROVIDED_BY CASCADE;

ALTER TABLE WORK_ORDER_SHELL DROP COLUMN IF EXISTS MATERIAL_TYPE CASCADE;
ALTER TABLE WORK_ORDER_SHELL DROP COLUMN IF EXISTS PROVIDED_BY CASCADE;
