CREATE TABLE IF NOT EXISTS MASTER_SIZE (
    ID_SIZE SERIAL PRIMARY KEY,
    NAMA_SIZE VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_master_size_nama_size_not_blank CHECK (LENGTH(BTRIM(NAMA_SIZE)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_master_size_nama_size_lower
ON MASTER_SIZE (LOWER(BTRIM(NAMA_SIZE)));

CREATE INDEX IF NOT EXISTS idx_master_size_created_at
ON MASTER_SIZE (created_at);

INSERT INTO MASTER_SIZE (NAMA_SIZE)
SELECT canonical_name
FROM (
    SELECT MIN(BTRIM(SIZE)) AS canonical_name
    FROM WORK_ORDER_SHELL_SIZE
    WHERE BTRIM(COALESCE(SIZE, '')) <> ''
    GROUP BY LOWER(BTRIM(SIZE))
) AS deduped_sizes
ON CONFLICT DO NOTHING;

ALTER TABLE WORK_ORDER_SHELL_SIZE
ADD COLUMN IF NOT EXISTS ID_SIZE INT NULL;

UPDATE WORK_ORDER_SHELL_SIZE woss
SET ID_SIZE = ms.ID_SIZE
FROM MASTER_SIZE ms
WHERE woss.ID_SIZE IS NULL
  AND BTRIM(COALESCE(woss.SIZE, '')) <> ''
  AND LOWER(BTRIM(woss.SIZE)) = LOWER(BTRIM(ms.NAMA_SIZE));

CREATE INDEX IF NOT EXISTS idx_work_order_shell_size_id_size
ON WORK_ORDER_SHELL_SIZE (ID_SIZE);

ALTER TABLE WORK_ORDER_SHELL_SIZE
DROP CONSTRAINT IF EXISTS fk_work_order_shell_size_master_size;

ALTER TABLE WORK_ORDER_SHELL_SIZE
ADD CONSTRAINT fk_work_order_shell_size_master_size
FOREIGN KEY (ID_SIZE) REFERENCES MASTER_SIZE(ID_SIZE) ON DELETE RESTRICT;
