--po client item kurang foreign key ke po client
ALTER TABLE PO_CLIENT_ITEM 
    ADD COLUMN ID_PO_CLIENT INT,
    ADD CONSTRAINT fk_po_client 
        FOREIGN KEY (ID_PO_CLIENT) 
        REFERENCES PO_CLIENT(ID_PO_CLIENT) 
        ON DELETE CASCADE;

--packing list item kurang foreign key ke packing list
ALTER TABLE PACKING_LIST_ITEM 
    ADD COLUMN ID_PACKING_LIST INT,
    ADD CONSTRAINT fk_packing_list 
        FOREIGN KEY (ID_PACKING_LIST) 
        REFERENCES PACKING_LIST(ID_PACKING_LIST) 
        ON DELETE CASCADE;

--hubungan departemen dan user yang konflik
ALTER TABLE DEPARTEMEN
DROP COLUMN ID_USER;

ALTER TABLE "USER"
DROP COLUMN DEPARTEMEN,
ADD COLUMN IS_MANAGER BOOLEAN DEFAULT FALSE,
ADD COLUMN ID_DEPARTEMEN INT,
ADD COLUMN ID_MITRA INT;

ALTER TABLE "USER"
ADD CONSTRAINT fk_user_departemen 
    FOREIGN KEY (ID_DEPARTEMEN) 
    REFERENCES DEPARTEMEN(ID_DEPARTEMEN)
    ON DELETE SET NULL,
ADD CONSTRAINT fk_user_mitra 
    FOREIGN KEY (ID_MITRA) 
    REFERENCES MITRA(ID_MITRA)
    ON DELETE SET NULL;

ALTER TABLE "USER"
ALTER COLUMN USERNAME SET NOT NULL,
ADD CONSTRAINT unique_username UNIQUE (USERNAME),
ALTER COLUMN PASSWORD SET NOT NULL;