ALTER TABLE PROFIL_PERUSAHAAN DROP COLUMN IF EXISTS BACKGROUND_LOGIN;
ALTER TABLE PROFIL_PERUSAHAAN DROP COLUMN IF EXISTS TEXT_FOOTER;
ALTER TABLE PROFIL_PERUSAHAAN DROP COLUMN IF EXISTS LINK_WEBSITE;
ALTER TABLE PROFIL_PERUSAHAAN DROP COLUMN IF EXISTS MEDSOS;
