-- Add no_dokumen and deskripsi fields to SURAT_JALAN_INTERNAL
ALTER TABLE SURAT_JALAN_INTERNAL
    ADD COLUMN IF NOT EXISTS no_dokumen VARCHAR(100) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS deskripsi TEXT NOT NULL DEFAULT '';
