-- 1. Alter ratio_marker to drop roll_qty and sambungan_roll
ALTER TABLE RATIO_MARKER DROP COLUMN IF EXISTS ROLL_QTY;
ALTER TABLE RATIO_MARKER DROP COLUMN IF EXISTS SAMBUNGAN_ROLL;

-- 2. Create spreading_cutting_plan
CREATE TABLE IF NOT EXISTS SPREADING_CUTTING_PLAN (
    ID_SPREADING_CUTTING_PLAN SERIAL PRIMARY KEY,
    NO_DOKUMEN VARCHAR(100) NOT NULL,
    TANGGAL_EFEKTIF DATE NOT NULL,
    ID_WO INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO) REFERENCES WORK_ORDER(ID_WO) ON DELETE CASCADE
);

-- 3. Create komponen_spreading_cutting_plan
CREATE TABLE IF NOT EXISTS KOMPONEN_SPREADING_CUTTING_PLAN (
    ID_KOMPONEN_SPREADING SERIAL PRIMARY KEY,
    ID_SPREADING_CUTTING_PLAN INT NOT NULL,
    NAMA_KOMPONEN VARCHAR(150) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_SPREADING_CUTTING_PLAN) REFERENCES SPREADING_CUTTING_PLAN(ID_SPREADING_CUTTING_PLAN) ON DELETE CASCADE
);

-- 4. Create ratio_spreading
CREATE TABLE IF NOT EXISTS RATIO_SPREADING (
    ID_RATIO_SPREADING SERIAL PRIMARY KEY,
    ID_KOMPONEN_SPREADING INT NOT NULL,
    ID_WO_SHELL INT NOT NULL,
    CONS DECIMAL(15,3) NOT NULL DEFAULT 0,
    PLAN_SPREADING_GELARAN DECIMAL(15,3) NOT NULL DEFAULT 0,
    ALLOWANCE DECIMAL(15,3) NOT NULL DEFAULT 0,
    ROLL_QTY INT NOT NULL DEFAULT 0,
    SAMBUNGAN_ROLL INT NOT NULL DEFAULT 0,
    REJECT DECIMAL(15,3) NOT NULL DEFAULT 0,
    LEBAR_KAIN DECIMAL(15,3) NOT NULL DEFAULT 0,
    KET TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_KOMPONEN_SPREADING) REFERENCES KOMPONEN_SPREADING_CUTTING_PLAN(ID_KOMPONEN_SPREADING) ON DELETE CASCADE,
    FOREIGN KEY (ID_WO_SHELL) REFERENCES WORK_ORDER_SHELL(ID_WO_SHELL) ON DELETE CASCADE
);

-- 5. Create ratio_size_spreading
CREATE TABLE IF NOT EXISTS RATIO_SIZE_SPREADING (
    ID_RATIO_SIZE_SPREADING SERIAL PRIMARY KEY,
    ID_RATIO_SPREADING INT NOT NULL,
    ID_WO_SHELL_SIZE INT NOT NULL,
    RATIO_PLAN INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_RATIO_SPREADING) REFERENCES RATIO_SPREADING(ID_RATIO_SPREADING) ON DELETE CASCADE,
    FOREIGN KEY (ID_WO_SHELL_SIZE) REFERENCES WORK_ORDER_SHELL_SIZE(ID_WO_SHELL_SIZE) ON DELETE CASCADE
);
