DROP TABLE IF EXISTS OTORITAS_DOKUMEN_DETAIL;
DROP TABLE IF EXISTS OTORITAS_DOKUMEN;
DROP TABLE IF EXISTS ARSIP_DOKUMEN_GABUNGAN;

ALTER TABLE USERS DROP CONSTRAINT IF EXISTS fk_users_role;
ALTER TABLE USERS DROP COLUMN IF EXISTS ID_ROLE;

DROP TABLE IF EXISTS ROLE_HAK_AKSES;
DROP TABLE IF EXISTS ROLES;
