-- Rollback schema changes introduced in 000002_init.up.sql

-- 1) Revert auth constraints on USER
ALTER TABLE "USER"
    DROP CONSTRAINT IF EXISTS unique_username,
    ALTER COLUMN USERNAME DROP NOT NULL,
    ALTER COLUMN PASSWORD DROP NOT NULL;

-- 2) Revert USER relation changes
ALTER TABLE "USER"
    DROP CONSTRAINT IF EXISTS fk_user_departemen,
    DROP CONSTRAINT IF EXISTS fk_user_mitra;

ALTER TABLE "USER"
    DROP COLUMN IF EXISTS ID_DEPARTEMEN,
    DROP COLUMN IF EXISTS ID_MITRA,
    DROP COLUMN IF EXISTS IS_MANAGER,
    ADD COLUMN IF NOT EXISTS DEPARTEMEN VARCHAR(100);

-- 3) Revert DEPARTEMEN relation changes
ALTER TABLE DEPARTEMEN
    ADD COLUMN IF NOT EXISTS ID_USER INT;

ALTER TABLE DEPARTEMEN
    DROP CONSTRAINT IF EXISTS departemen_id_user_fkey,
    ADD CONSTRAINT departemen_id_user_fkey
        FOREIGN KEY (ID_USER) REFERENCES "USER"(ID_USER);

-- 4) Revert missing relation fixes
ALTER TABLE PO_CLIENT_ITEM
    DROP CONSTRAINT IF EXISTS fk_po_client,
    DROP COLUMN IF EXISTS ID_PO_CLIENT;

ALTER TABLE PACKING_LIST_ITEM
    DROP CONSTRAINT IF EXISTS fk_packing_list,
    DROP COLUMN IF EXISTS ID_PACKING_LIST;
