-- Remove role assignments first (FK constraint)
DELETE FROM ROLE_HAK_AKSES
WHERE ID_HAK_AKSES IN (
    SELECT ID_HAK_AKSES FROM HAK_AKSES
    WHERE KODE_PERMISSION IN ('DATA_APPROVE_CUTTING_PLAN_READ', 'DATA_APPROVE_CUTTING_PLAN_CREATE')
);

-- Remove permissions from catalog
DELETE FROM HAK_AKSES
WHERE KODE_PERMISSION IN ('DATA_APPROVE_CUTTING_PLAN_READ', 'DATA_APPROVE_CUTTING_PLAN_CREATE');

DROP TABLE IF EXISTS DATA_APPROVE_CUTTING_PLAN;

