-- Revert MATERIAL_LIST grouping refactor back to 1:1 wrapper layout.
-- WARNING: collapses multiple MLI per ML down to a single one (data loss for additional items).

-- Step 1: re-add legacy columns.
ALTER TABLE MATERIAL_LIST ADD COLUMN IF NOT EXISTS ID_MATERIAL_LIST_ITEM INT;
ALTER TABLE MATERIAL_LIST_ITEM ADD COLUMN IF NOT EXISTS ID_WO INT;

-- Step 2: backfill MATERIAL_LIST.id_material_list_item with first MLI per ML.
UPDATE MATERIAL_LIST ml
SET ID_MATERIAL_LIST_ITEM = (
    SELECT MIN(mli.ID_MATERIAL_LIST_ITEM)
    FROM MATERIAL_LIST_ITEM mli
    WHERE mli.ID_MATERIAL_LIST = ml.ID_MATERIAL_LIST
)
WHERE ml.ID_MATERIAL_LIST_ITEM IS NULL;

-- Step 3: backfill MATERIAL_LIST_ITEM.id_wo from its parent ML.
UPDATE MATERIAL_LIST_ITEM mli
SET ID_WO = ml.ID_WO
FROM MATERIAL_LIST ml
WHERE mli.ID_MATERIAL_LIST = ml.ID_MATERIAL_LIST
  AND mli.ID_WO IS NULL;

-- Step 4: verify before tightening.
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM MATERIAL_LIST WHERE ID_MATERIAL_LIST_ITEM IS NULL) THEN
        RAISE EXCEPTION 'material_list down-backfill failed: id_material_list_item missing';
    END IF;
    IF EXISTS (SELECT 1 FROM MATERIAL_LIST_ITEM WHERE ID_WO IS NULL) THEN
        RAISE EXCEPTION 'material_list_item down-backfill failed: id_wo missing';
    END IF;
END $$;

-- Step 5: drop new constraints, indexes, columns.
DROP INDEX IF EXISTS idx_material_list_id_wo;
DROP INDEX IF EXISTS idx_material_list_item_id_ml;

ALTER TABLE MATERIAL_LIST_ITEM DROP CONSTRAINT IF EXISTS fk_mli_ml;
ALTER TABLE MATERIAL_LIST_ITEM DROP COLUMN IF EXISTS ID_MATERIAL_LIST;
ALTER TABLE MATERIAL_LIST_ITEM DROP COLUMN IF EXISTS ITEM;
ALTER TABLE MATERIAL_LIST_ITEM DROP COLUMN IF EXISTS QTY;
ALTER TABLE MATERIAL_LIST_ITEM DROP COLUMN IF EXISTS UNIT;
ALTER TABLE MATERIAL_LIST_ITEM DROP COLUMN IF EXISTS EST_PRICE;
ALTER TABLE MATERIAL_LIST_ITEM ALTER COLUMN ID_WO SET NOT NULL;
ALTER TABLE MATERIAL_LIST_ITEM ADD CONSTRAINT material_list_item_id_wo_fkey FOREIGN KEY (ID_WO) REFERENCES WORK_ORDER(ID_WO) ON DELETE CASCADE;

ALTER TABLE MATERIAL_LIST DROP CONSTRAINT IF EXISTS fk_ml_wo;
ALTER TABLE MATERIAL_LIST DROP COLUMN IF EXISTS ID_WO;
ALTER TABLE MATERIAL_LIST DROP COLUMN IF EXISTS NAME;
ALTER TABLE MATERIAL_LIST DROP COLUMN IF EXISTS IS_LOCKED;
ALTER TABLE MATERIAL_LIST ALTER COLUMN ID_MATERIAL_LIST_ITEM SET NOT NULL;
ALTER TABLE MATERIAL_LIST ADD CONSTRAINT fk_ml_mli FOREIGN KEY (ID_MATERIAL_LIST_ITEM) REFERENCES MATERIAL_LIST_ITEM(ID_MATERIAL_LIST_ITEM) ON DELETE CASCADE;
