CREATE TABLE IF NOT EXISTS RETUR_CLIENT (
    ID_RETUR_CLIENT SERIAL PRIMARY KEY,
    ID_WO INT NOT NULL,
    FILE TEXT NOT NULL DEFAULT '',
    DESKRIPSI TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO) REFERENCES WORK_ORDER(ID_WO) ON DELETE CASCADE
);
