-- 1. Remove PO_CLIENT_CREATE and PO_CLIENT_UPDATE from ADMIN_KEUANGAN
DELETE FROM ROLE_HAK_AKSES
WHERE ID_ROLE IN (SELECT ID_ROLE FROM ROLES WHERE NAMA_ROLE = 'ADMIN_KEUANGAN')
AND ID_HAK_AKSES IN (
    SELECT ID_HAK_AKSES FROM HAK_AKSES 
    WHERE KODE_PERMISSION IN ('PO_CLIENT_CREATE', 'PO_CLIENT_UPDATE')
);

-- 2. Grant PO_CLIENT_CREATE and PO_CLIENT_UPDATE back to ADMIN_PRODUKSI
INSERT INTO ROLE_HAK_AKSES (ID_ROLE, ID_HAK_AKSES)
SELECT r.ID_ROLE, h.ID_HAK_AKSES
FROM ROLES r, HAK_AKSES h
WHERE r.NAMA_ROLE = 'ADMIN_PRODUKSI'
AND h.KODE_PERMISSION IN ('PO_CLIENT_CREATE', 'PO_CLIENT_UPDATE')
ON CONFLICT DO NOTHING;
