CREATE TABLE IF NOT EXISTS AUDIT_LOGS (
    ID BIGSERIAL PRIMARY KEY,
    ACTOR_USER_ID INT,
    ACTOR_USERNAME VARCHAR(100) NOT NULL DEFAULT '',
    ACTOR_ROLE VARCHAR(100) NOT NULL DEFAULT '',
    ACTION VARCHAR(20) NOT NULL,
    MODULE VARCHAR(100) NOT NULL,
    ENTITY_TYPE VARCHAR(100) NOT NULL,
    ENTITY_ID VARCHAR(100) NOT NULL DEFAULT '',
    ENTITY_LABEL VARCHAR(255) NOT NULL DEFAULT '',
    METHOD VARCHAR(10) NOT NULL DEFAULT '',
    ROUTE VARCHAR(255) NOT NULL DEFAULT '',
    BEFORE_DATA JSONB,
    AFTER_DATA JSONB,
    CHANGED_FIELDS JSONB NOT NULL DEFAULT '[]'::jsonb,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_audit_logs_actor_user
        FOREIGN KEY (ACTOR_USER_ID) REFERENCES USERS(ID_USER) ON DELETE SET NULL,
    CONSTRAINT chk_audit_logs_action
        CHECK (ACTION IN ('CREATE', 'UPDATE', 'DELETE'))
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at
    ON AUDIT_LOGS (CREATED_AT DESC);

CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_user_id
    ON AUDIT_LOGS (ACTOR_USER_ID);

CREATE INDEX IF NOT EXISTS idx_audit_logs_module
    ON AUDIT_LOGS (MODULE);

CREATE INDEX IF NOT EXISTS idx_audit_logs_entity_type
    ON AUDIT_LOGS (ENTITY_TYPE);

CREATE INDEX IF NOT EXISTS idx_audit_logs_action
    ON AUDIT_LOGS (ACTION);
