ALTER TABLE RECEIVED DROP CONSTRAINT IF EXISTS fk_recv_mli;
ALTER TABLE RECEIVED ADD COLUMN ID_MATERIAL_LIST INT;
UPDATE RECEIVED r
SET ID_MATERIAL_LIST = ml.ID_MATERIAL_LIST
FROM MATERIAL_LIST ml
WHERE r.ID_MATERIAL_LIST_ITEM = ml.ID_MATERIAL_LIST_ITEM;
ALTER TABLE RECEIVED ALTER COLUMN ID_MATERIAL_LIST SET NOT NULL;
ALTER TABLE RECEIVED ADD CONSTRAINT received_id_material_list_fkey FOREIGN KEY (ID_MATERIAL_LIST) REFERENCES MATERIAL_LIST(ID_MATERIAL_LIST);
DROP INDEX IF EXISTS idx_received_id_material_list_item;
ALTER TABLE RECEIVED DROP COLUMN IF EXISTS ID_MATERIAL_LIST_ITEM;

ALTER TABLE SURAT_JALAN_CLIENT DROP CONSTRAINT IF EXISTS fk_sjc_mli;
ALTER TABLE SURAT_JALAN_CLIENT ADD COLUMN ID_MATERIAL_LIST INT;
UPDATE SURAT_JALAN_CLIENT sjc
SET ID_MATERIAL_LIST = ml.ID_MATERIAL_LIST
FROM MATERIAL_LIST ml
WHERE sjc.ID_MATERIAL_LIST_ITEM = ml.ID_MATERIAL_LIST_ITEM;
ALTER TABLE SURAT_JALAN_CLIENT ALTER COLUMN ID_MATERIAL_LIST SET NOT NULL;
ALTER TABLE SURAT_JALAN_CLIENT ADD CONSTRAINT surat_jalan_client_id_material_list_fkey FOREIGN KEY (ID_MATERIAL_LIST) REFERENCES MATERIAL_LIST(ID_MATERIAL_LIST);
DROP INDEX IF EXISTS idx_surat_jalan_client_id_material_list_item;
ALTER TABLE SURAT_JALAN_CLIENT DROP COLUMN IF EXISTS ID_MATERIAL_LIST_ITEM;

ALTER TABLE MATERIAL_LIST DROP CONSTRAINT IF EXISTS fk_ml_mli;
ALTER TABLE MATERIAL_LIST ADD COLUMN DESCRIPTION TEXT NOT NULL DEFAULT '';
ALTER TABLE MATERIAL_LIST ADD COLUMN SIZE VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE MATERIAL_LIST ADD COLUMN COLOR VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE MATERIAL_LIST ADD COLUMN UOM VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE MATERIAL_LIST ADD COLUMN ID_WO INT NOT NULL DEFAULT 0;

UPDATE MATERIAL_LIST ml
SET
    DESCRIPTION = mli.DESCRIPTION,
    COLOR = COALESCE(wos.COLOR, wot.COLOR, ''),
    UOM = COALESCE(wot.UOM, ''),
    ID_WO = COALESCE(wos.ID_WO, wot.ID_WO, mli.ID_WO, 0)
FROM MATERIAL_LIST_ITEM mli
LEFT JOIN WORK_ORDER_SHELL wos ON wos.ID_WO_SHELL = mli.ID_WO_SHELL
LEFT JOIN WORK_ORDER_TRIM wot ON wot.ID_WO_TRIM = mli.ID_WO_TRIM
WHERE ml.ID_MATERIAL_LIST_ITEM = mli.ID_MATERIAL_LIST_ITEM;

ALTER TABLE MATERIAL_LIST DROP COLUMN IF EXISTS ID_MATERIAL_LIST_ITEM;

DROP TABLE IF EXISTS MATERIAL_LIST_ITEM CASCADE;
