-- 1. Rename nama role OPERATOR menjadi ADMIN_SISTEM
UPDATE ROLES 
SET NAMA_ROLE = 'ADMIN_SISTEM' 
WHERE NAMA_ROLE = 'OPERATOR';

-- Pastikan role ADMIN_SISTEM ada (jika fresh setup belum ada)
INSERT INTO ROLES (NAMA_ROLE)
VALUES ('ADMIN_SISTEM')
ON CONFLICT DO NOTHING;

-- 2. Tambah permission baru ke tabel HAK_AKSES
INSERT INTO HAK_AKSES (KODE_PERMISSION, NAMA_HALAMAN, DESKRIPSI, DOMAIN_PERMISSION, AKSI_PERMISSION)
VALUES
    ('SURAT_JALAN_CLIENT_CREATE', 'Surat Jalan Client Create', 'Allows creating client delivery notes', 'surat_jalan_client', 'create'),
    ('SURAT_JALAN_CLIENT_UPDATE', 'Surat Jalan Client Update', 'Allows updating client delivery notes', 'surat_jalan_client', 'update'),
    ('SURAT_JALAN_CLIENT_DELETE', 'Surat Jalan Client Delete', 'Allows deleting client delivery notes', 'surat_jalan_client', 'delete'),
    ('SURAT_JALAN_INTERNAL_CREATE', 'Surat Jalan Internal Create', 'Allows creating internal delivery notes', 'surat_jalan_internal', 'create'),
    ('SURAT_JALAN_INTERNAL_UPDATE', 'Surat Jalan Internal Update', 'Allows updating internal delivery notes', 'surat_jalan_internal', 'update'),
    ('SURAT_JALAN_INTERNAL_DELETE', 'Surat Jalan Internal Delete', 'Allows deleting internal delivery notes', 'surat_jalan_internal', 'delete')
ON CONFLICT (KODE_PERMISSION) DO NOTHING;

-- 3. Bersihkan seluruh data MASTER_* dan SURAT_JALAN_* serta WO_CLOSE lama untuk role yang terdampak agar tidak terjadi tumpang tindih
DELETE FROM ROLE_HAK_AKSES
WHERE ID_ROLE IN (
    SELECT ID_ROLE FROM ROLES WHERE NAMA_ROLE IN ('ADMIN_SISTEM', 'ADMIN_KEUANGAN', 'ADMIN_PRODUKSI', 'ADMIN_GUDANG', 'MANAGER')
)
AND ID_HAK_AKSES IN (
    SELECT ID_HAK_AKSES FROM HAK_AKSES 
    WHERE KODE_PERMISSION LIKE 'MASTER_%' 
       OR KODE_PERMISSION LIKE 'SURAT_JALAN_%'
       OR KODE_PERMISSION = 'SURAT_JALAN_CREATE'
       OR KODE_PERMISSION = 'SURAT_JALAN_UPDATE'
       OR KODE_PERMISSION = 'WO_CLOSE'
);

-- 4. Hubungkan Hak Akses Baru ke masing-masing Role

-- ==========================================
-- ADMIN_SISTEM (Sebelumnya OPERATOR)
-- ==========================================
-- CRUD Departemen & Profil Perusahaan
INSERT INTO ROLE_HAK_AKSES (ID_ROLE, ID_HAK_AKSES)
SELECT r.ID_ROLE, h.ID_HAK_AKSES
FROM ROLES r, HAK_AKSES h
WHERE r.NAMA_ROLE = 'ADMIN_SISTEM'
AND h.KODE_PERMISSION IN (
    'MASTER_DEPARTEMEN_READ', 'MASTER_DEPARTEMEN_CREATE', 'MASTER_DEPARTEMEN_UPDATE', 'MASTER_DEPARTEMEN_DELETE',
    'MASTER_PROFIL_PERUSAHAAN_READ', 'MASTER_PROFIL_PERUSAHAAN_CREATE', 'MASTER_PROFIL_PERUSAHAAN_UPDATE', 'MASTER_PROFIL_PERUSAHAAN_DELETE'
)
ON CONFLICT DO NOTHING;

-- ==========================================
-- ADMIN_KEUANGAN
-- ==========================================
-- CRUD Mitra & Profil Perusahaan
-- READ Barang, Jenis Barang, Warna, Size, Departemen
-- WO_CLOSE
INSERT INTO ROLE_HAK_AKSES (ID_ROLE, ID_HAK_AKSES)
SELECT r.ID_ROLE, h.ID_HAK_AKSES
FROM ROLES r, HAK_AKSES h
WHERE r.NAMA_ROLE = 'ADMIN_KEUANGAN'
AND h.KODE_PERMISSION IN (
    'MASTER_MITRA_READ', 'MASTER_MITRA_CREATE', 'MASTER_MITRA_UPDATE', 'MASTER_MITRA_DELETE',
    'MASTER_PROFIL_PERUSAHAAN_READ', 'MASTER_PROFIL_PERUSAHAAN_CREATE', 'MASTER_PROFIL_PERUSAHAAN_UPDATE', 'MASTER_PROFIL_PERUSAHAAN_DELETE',
    'MASTER_BARANG_READ', 'MASTER_JENIS_BARANG_READ', 'MASTER_WARNA_READ', 'MASTER_SIZE_READ', 'MASTER_DEPARTEMEN_READ',
    'WO_CLOSE'
)
ON CONFLICT DO NOTHING;

-- ==========================================
-- ADMIN_PRODUKSI
-- ==========================================
-- CRUD Barang, Jenis Barang, Warna, Size
-- READ Mitra, Profil Perusahaan, Departemen
-- CRUD Surat Jalan Internal
INSERT INTO ROLE_HAK_AKSES (ID_ROLE, ID_HAK_AKSES)
SELECT r.ID_ROLE, h.ID_HAK_AKSES
FROM ROLES r, HAK_AKSES h
WHERE r.NAMA_ROLE = 'ADMIN_PRODUKSI'
AND h.KODE_PERMISSION IN (
    'MASTER_BARANG_READ', 'MASTER_BARANG_CREATE', 'MASTER_BARANG_UPDATE', 'MASTER_BARANG_DELETE',
    'MASTER_JENIS_BARANG_READ', 'MASTER_JENIS_BARANG_CREATE', 'MASTER_JENIS_BARANG_UPDATE', 'MASTER_JENIS_BARANG_DELETE',
    'MASTER_WARNA_READ', 'MASTER_WARNA_CREATE', 'MASTER_WARNA_UPDATE', 'MASTER_WARNA_DELETE',
    'MASTER_SIZE_READ', 'MASTER_SIZE_CREATE', 'MASTER_SIZE_UPDATE', 'MASTER_SIZE_DELETE',
    'MASTER_MITRA_READ', 'MASTER_PROFIL_PERUSAHAAN_READ', 'MASTER_DEPARTEMEN_READ',
    'SURAT_JALAN_INTERNAL_READ', 'SURAT_JALAN_INTERNAL_CREATE', 'SURAT_JALAN_INTERNAL_UPDATE', 'SURAT_JALAN_INTERNAL_DELETE'
)
ON CONFLICT DO NOTHING;

-- ==========================================
-- ADMIN_GUDANG
-- ==========================================
-- READ semua Master Data
-- CRUD Surat Jalan Client
INSERT INTO ROLE_HAK_AKSES (ID_ROLE, ID_HAK_AKSES)
SELECT r.ID_ROLE, h.ID_HAK_AKSES
FROM ROLES r, HAK_AKSES h
WHERE r.NAMA_ROLE = 'ADMIN_GUDANG'
AND h.KODE_PERMISSION IN (
    'MASTER_MITRA_READ', 'MASTER_BARANG_READ', 'MASTER_JENIS_BARANG_READ', 'MASTER_WARNA_READ', 'MASTER_SIZE_READ', 'MASTER_DEPARTEMEN_READ', 'MASTER_PROFIL_PERUSAHAAN_READ',
    'SURAT_JALAN_CLIENT_READ', 'SURAT_JALAN_CLIENT_CREATE', 'SURAT_JALAN_CLIENT_UPDATE', 'SURAT_JALAN_CLIENT_DELETE'
)
ON CONFLICT DO NOTHING;

-- ==========================================
-- MANAGER
-- ==========================================
-- CRUD Departemen
-- READ semua Master Data lainnya
-- READ Surat Jalan Client & Internal
INSERT INTO ROLE_HAK_AKSES (ID_ROLE, ID_HAK_AKSES)
SELECT r.ID_ROLE, h.ID_HAK_AKSES
FROM ROLES r, HAK_AKSES h
WHERE r.NAMA_ROLE = 'MANAGER'
AND h.KODE_PERMISSION IN (
    'MASTER_DEPARTEMEN_READ', 'MASTER_DEPARTEMEN_CREATE', 'MASTER_DEPARTEMEN_UPDATE', 'MASTER_DEPARTEMEN_DELETE',
    'MASTER_MITRA_READ', 'MASTER_BARANG_READ', 'MASTER_JENIS_BARANG_READ', 'MASTER_WARNA_READ', 'MASTER_SIZE_READ', 'MASTER_PROFIL_PERUSAHAAN_READ',
    'SURAT_JALAN_CLIENT_READ', 'SURAT_JALAN_INTERNAL_READ'
)
ON CONFLICT DO NOTHING;
