DELETE FROM ROLE_HAK_AKSES
WHERE ID_HAK_AKSES IN (
    SELECT ID_HAK_AKSES
    FROM HAK_AKSES
    WHERE KODE_PERMISSION IN (
        'REKONSILIASI_READ',
        'REKONSILIASI_CREATE',
        'REKONSILIASI_UPDATE'
    )
);

DELETE FROM HAK_AKSES
WHERE KODE_PERMISSION IN (
    'REKONSILIASI_READ',
    'REKONSILIASI_CREATE',
    'REKONSILIASI_UPDATE'
);

DROP TABLE IF EXISTS REKONSILIASI_TERIMA_ENTRY;
DROP TABLE IF EXISTS REKONSILIASI_MATERIAL_ROW;
DROP TABLE IF EXISTS REKONSILIASI;
