-- Refactor MATERIAL_LIST as grouping container for MATERIAL_LIST_ITEM.
-- Before: MATERIAL_LIST has FK to a single MATERIAL_LIST_ITEM (1:1 wrapper).
-- After:  MATERIAL_LIST belongs to a WO and groups multiple MATERIAL_LIST_ITEM rows (1:N).

-- Step 1: add new columns (nullable / defaulted for backfill).
ALTER TABLE MATERIAL_LIST ADD COLUMN IF NOT EXISTS ID_WO INT;
ALTER TABLE MATERIAL_LIST ADD COLUMN IF NOT EXISTS NAME VARCHAR(150) NOT NULL DEFAULT 'Material List Utama';
ALTER TABLE MATERIAL_LIST ADD COLUMN IF NOT EXISTS IS_LOCKED BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE MATERIAL_LIST_ITEM ADD COLUMN IF NOT EXISTS ID_MATERIAL_LIST INT;
ALTER TABLE MATERIAL_LIST_ITEM ADD COLUMN IF NOT EXISTS ITEM VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE MATERIAL_LIST_ITEM ADD COLUMN IF NOT EXISTS QTY INT NOT NULL DEFAULT 0;
ALTER TABLE MATERIAL_LIST_ITEM ADD COLUMN IF NOT EXISTS UNIT VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE MATERIAL_LIST_ITEM ADD COLUMN IF NOT EXISTS EST_PRICE DECIMAL(15,2) NOT NULL DEFAULT 0;

-- Step 2: backfill MATERIAL_LIST.id_wo from its current item link.
UPDATE MATERIAL_LIST ml
SET ID_WO = COALESCE(wos.ID_WO, wot.ID_WO)
FROM MATERIAL_LIST_ITEM mli
LEFT JOIN WORK_ORDER_SHELL wos ON wos.ID_WO_SHELL = mli.ID_WO_SHELL
LEFT JOIN WORK_ORDER_TRIM wot ON wot.ID_WO_TRIM = mli.ID_WO_TRIM
WHERE ml.ID_MATERIAL_LIST_ITEM = mli.ID_MATERIAL_LIST_ITEM
  AND ml.ID_WO IS NULL;

-- Step 3: backfill MATERIAL_LIST_ITEM.id_material_list from its parent ML.
UPDATE MATERIAL_LIST_ITEM mli
SET ID_MATERIAL_LIST = ml.ID_MATERIAL_LIST
FROM MATERIAL_LIST ml
WHERE ml.ID_MATERIAL_LIST_ITEM = mli.ID_MATERIAL_LIST_ITEM
  AND mli.ID_MATERIAL_LIST IS NULL;

-- Step 4: best-effort backfill of MATERIAL_LIST_ITEM.item from shell/trim spec.
UPDATE MATERIAL_LIST_ITEM mli
SET ITEM = COALESCE(
    (SELECT 'Fabric - ' || COALESCE(wos.color, '') FROM WORK_ORDER_SHELL wos WHERE wos.id_wo_shell = mli.id_wo_shell),
    (SELECT wot.item FROM WORK_ORDER_TRIM wot WHERE wot.id_wo_trim = mli.id_wo_trim),
    ''
)
WHERE mli.ITEM = '';

UPDATE MATERIAL_LIST_ITEM mli
SET UNIT = COALESCE(
    (SELECT wot.uom FROM WORK_ORDER_TRIM wot WHERE wot.id_wo_trim = mli.id_wo_trim),
    ''
)
WHERE mli.UNIT = '';

-- Step 5: verify backfill before applying NOT NULL.
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM MATERIAL_LIST WHERE ID_WO IS NULL) THEN
        RAISE EXCEPTION 'material_list backfill failed: id_wo missing';
    END IF;
    IF EXISTS (SELECT 1 FROM MATERIAL_LIST_ITEM WHERE ID_MATERIAL_LIST IS NULL) THEN
        RAISE EXCEPTION 'material_list_item backfill failed: id_material_list missing';
    END IF;
END $$;

-- Step 6: drop old links (now redundant).
ALTER TABLE MATERIAL_LIST DROP CONSTRAINT IF EXISTS fk_ml_mli;
ALTER TABLE MATERIAL_LIST DROP COLUMN IF EXISTS ID_MATERIAL_LIST_ITEM;

ALTER TABLE MATERIAL_LIST_ITEM DROP COLUMN IF EXISTS ID_WO;

-- Step 7: tighten new columns and add FKs.
ALTER TABLE MATERIAL_LIST ALTER COLUMN ID_WO SET NOT NULL;
ALTER TABLE MATERIAL_LIST ADD CONSTRAINT fk_ml_wo FOREIGN KEY (ID_WO) REFERENCES WORK_ORDER(ID_WO) ON DELETE CASCADE;

ALTER TABLE MATERIAL_LIST_ITEM ALTER COLUMN ID_MATERIAL_LIST SET NOT NULL;
ALTER TABLE MATERIAL_LIST_ITEM ADD CONSTRAINT fk_mli_ml FOREIGN KEY (ID_MATERIAL_LIST) REFERENCES MATERIAL_LIST(ID_MATERIAL_LIST) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_material_list_id_wo ON MATERIAL_LIST(ID_WO);
CREATE INDEX IF NOT EXISTS idx_material_list_item_id_ml ON MATERIAL_LIST_ITEM(ID_MATERIAL_LIST);
