-- 1. Remove WO_READ from ADMIN_KEUANGAN
DELETE FROM ROLE_HAK_AKSES
WHERE ID_ROLE IN (SELECT ID_ROLE FROM ROLES WHERE NAMA_ROLE = 'ADMIN_KEUANGAN')
AND ID_HAK_AKSES IN (SELECT ID_HAK_AKSES FROM HAK_AKSES WHERE KODE_PERMISSION = 'WO_READ');

-- 2. Restore PO_INTERNAL_APPROVE to ADMIN_KEUANGAN
INSERT INTO ROLE_HAK_AKSES (ID_ROLE, ID_HAK_AKSES)
SELECT r.ID_ROLE, h.ID_HAK_AKSES
FROM ROLES r, HAK_AKSES h
WHERE r.NAMA_ROLE = 'ADMIN_KEUANGAN'
AND h.KODE_PERMISSION = 'PO_INTERNAL_APPROVE'
ON CONFLICT DO NOTHING;

-- 3. Remove SURAT_JALAN_INTERNAL_READ from ADMIN_GUDANG
DELETE FROM ROLE_HAK_AKSES
WHERE ID_ROLE IN (SELECT ID_ROLE FROM ROLES WHERE NAMA_ROLE = 'ADMIN_GUDANG')
AND ID_HAK_AKSES IN (SELECT ID_HAK_AKSES FROM HAK_AKSES WHERE KODE_PERMISSION = 'SURAT_JALAN_INTERNAL_READ');
