ALTER TABLE MATERIAL_LIST_ITEM
    ADD COLUMN IF NOT EXISTS CATEGORY VARCHAR(16),
    ADD COLUMN IF NOT EXISTS CONS_PER_PC DECIMAL(15,3),
    ADD COLUMN IF NOT EXISTS QTY_WO_SCOPE VARCHAR(16),
    ADD COLUMN IF NOT EXISTS ID_QTY_WO_SHELL INT,
    ADD COLUMN IF NOT EXISTS ID_QTY_WO_SIZE INT;

ALTER TABLE MATERIAL_LIST_ITEM
    ADD CONSTRAINT chk_material_list_item_category
        CHECK (CATEGORY IS NULL OR CATEGORY IN ('FABRIC', 'SEWING', 'PACKING')),
    ADD CONSTRAINT chk_material_list_item_cons_per_pc
        CHECK (CONS_PER_PC IS NULL OR CONS_PER_PC >= 0),
    ADD CONSTRAINT chk_material_list_item_qty_wo_scope
        CHECK (QTY_WO_SCOPE IS NULL OR QTY_WO_SCOPE IN ('WHOLE_WO', 'SIZE', 'COLOR', 'COLOR_SIZE')),
    ADD CONSTRAINT chk_material_list_item_qty_wo_scope_references
        CHECK ((
            (QTY_WO_SCOPE IS NULL AND ID_QTY_WO_SHELL IS NULL AND ID_QTY_WO_SIZE IS NULL)
            OR (QTY_WO_SCOPE = 'WHOLE_WO' AND ID_QTY_WO_SHELL IS NULL AND ID_QTY_WO_SIZE IS NULL)
            OR (QTY_WO_SCOPE = 'SIZE' AND ID_QTY_WO_SHELL IS NULL AND ID_QTY_WO_SIZE IS NOT NULL)
            OR (QTY_WO_SCOPE = 'COLOR' AND ID_QTY_WO_SHELL IS NOT NULL AND ID_QTY_WO_SIZE IS NULL)
            OR (QTY_WO_SCOPE = 'COLOR_SIZE' AND ID_QTY_WO_SHELL IS NOT NULL AND ID_QTY_WO_SIZE IS NOT NULL)
        ) IS TRUE),
    ADD CONSTRAINT fk_material_list_item_qty_wo_shell
        FOREIGN KEY (ID_QTY_WO_SHELL) REFERENCES WORK_ORDER_SHELL(ID_WO_SHELL) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_material_list_item_qty_wo_size
        FOREIGN KEY (ID_QTY_WO_SIZE) REFERENCES MASTER_SIZE(ID_SIZE) ON DELETE RESTRICT;
