CREATE TABLE IF NOT EXISTS PACKING_LIST_REJECT_SIZE (
    ID_PACKING_LIST_REJECT_SIZE SERIAL PRIMARY KEY,
    QTY INT NOT NULL DEFAULT 0,
    ID_PACKING_LIST INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_PACKING_LIST) REFERENCES PACKING_LIST(ID_PACKING_LIST) ON DELETE CASCADE
);
