ALTER TABLE PROFIL_PERUSAHAAN ADD COLUMN BACKGROUND_LOGIN TEXT NOT NULL DEFAULT '';
ALTER TABLE PROFIL_PERUSAHAAN ADD COLUMN TEXT_FOOTER TEXT NOT NULL DEFAULT '';
ALTER TABLE PROFIL_PERUSAHAAN ADD COLUMN LINK_WEBSITE VARCHAR(150) NOT NULL DEFAULT '';
ALTER TABLE PROFIL_PERUSAHAAN ADD COLUMN MEDSOS JSONB NOT NULL DEFAULT '{}';
