CREATE TABLE IF NOT EXISTS REKONSILIASI (
    ID_REKONSILIASI SERIAL PRIMARY KEY,
    ID_WO INT NOT NULL UNIQUE,
    JASA VARCHAR(100) NOT NULL DEFAULT '',
    NO_PO VARCHAR(100) NOT NULL DEFAULT '',
    DELIVERY DATE,
    BUYER VARCHAR(150) NOT NULL DEFAULT '',
    BRAND VARCHAR(150) NOT NULL DEFAULT '',
    STYLE VARCHAR(150) NOT NULL DEFAULT '',
    QTY_PO INT NOT NULL DEFAULT 0,
    PLAN_CUT_TOTAL BIGINT NOT NULL DEFAULT 0,
    CONS_BAJU_SUMMARY VARCHAR(100) NOT NULL DEFAULT '',
    NAMA_BAHAN VARCHAR(255) NOT NULL DEFAULT '',
    WARNA_KAIN_SUMMARY JSONB NOT NULL DEFAULT '[]'::jsonb,
    CREATED_BY INT,
    UPDATED_BY INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO) REFERENCES WORK_ORDER(ID_WO) ON DELETE CASCADE,
    FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID_USER) ON DELETE SET NULL,
    FOREIGN KEY (UPDATED_BY) REFERENCES USERS(ID_USER) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS IDX_REKONSILIASI_ID_WO ON REKONSILIASI(ID_WO);
CREATE INDEX IF NOT EXISTS IDX_REKONSILIASI_CREATED_AT ON REKONSILIASI(created_at DESC);

CREATE TABLE IF NOT EXISTS REKONSILIASI_MATERIAL_ROW (
    ID_REKONSILIASI_MATERIAL_ROW SERIAL PRIMARY KEY,
    ID_REKONSILIASI INT NOT NULL,
    ROW_NO INT NOT NULL,
    KATEGORI VARCHAR(50) NOT NULL DEFAULT '',
    DESCRIPTION VARCHAR(255) NOT NULL DEFAULT '',
    SIZE_LABEL VARCHAR(255) NOT NULL DEFAULT '',
    RATIO_SOURCE DECIMAL(15,3) NOT NULL DEFAULT 0,
    RATIO_INPUT DECIMAL(15,3) NOT NULL DEFAULT 0,
    QTY_PER_PCS_INPUT DECIMAL(15,3) NOT NULL DEFAULT 0,
    QTY_WO INT NOT NULL DEFAULT 0,
    TOLERANSI INT NOT NULL DEFAULT 0,
    SATUAN VARCHAR(30) NOT NULL DEFAULT '',
    QTY_ACTUAL_KIRIM_SOURCE INT NOT NULL DEFAULT 0,
    QTY_ACTUAL_KIRIM_MANUAL INT NOT NULL DEFAULT 0,
    REJECT_QTY INT NOT NULL DEFAULT 0,
    RETUR_QTY INT NOT NULL DEFAULT 0,
    KETERANGAN TEXT NOT NULL DEFAULT '',
    ID_MATERIAL_LIST_ITEM INT,
    ID_WO_SHELL INT,
    ID_WO_TRIM INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_REKONSILIASI) REFERENCES REKONSILIASI(ID_REKONSILIASI) ON DELETE CASCADE,
    FOREIGN KEY (ID_MATERIAL_LIST_ITEM) REFERENCES MATERIAL_LIST_ITEM(ID_MATERIAL_LIST_ITEM) ON DELETE SET NULL,
    FOREIGN KEY (ID_WO_SHELL) REFERENCES WORK_ORDER_SHELL(ID_WO_SHELL) ON DELETE SET NULL,
    FOREIGN KEY (ID_WO_TRIM) REFERENCES WORK_ORDER_TRIM(ID_WO_TRIM) ON DELETE SET NULL,
    CONSTRAINT UQ_REKONSILIASI_ROW_NO UNIQUE (ID_REKONSILIASI, ROW_NO)
);

CREATE INDEX IF NOT EXISTS IDX_REKONSILIASI_MATERIAL_ROW_REKON ON REKONSILIASI_MATERIAL_ROW(ID_REKONSILIASI);
CREATE INDEX IF NOT EXISTS IDX_REKONSILIASI_MATERIAL_ROW_MLI ON REKONSILIASI_MATERIAL_ROW(ID_MATERIAL_LIST_ITEM);

CREATE TABLE IF NOT EXISTS REKONSILIASI_TERIMA_ENTRY (
    ID_REKONSILIASI_TERIMA_ENTRY SERIAL PRIMARY KEY,
    ID_REKONSILIASI_MATERIAL_ROW INT NOT NULL,
    ENTRY_TYPE VARCHAR(20) NOT NULL,
    ENTRY_LABEL VARCHAR(100) NOT NULL DEFAULT '',
    QTY INT NOT NULL DEFAULT 0,
    NOTE TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_REKONSILIASI_MATERIAL_ROW) REFERENCES REKONSILIASI_MATERIAL_ROW(ID_REKONSILIASI_MATERIAL_ROW) ON DELETE CASCADE,
    CONSTRAINT CHK_REKONSILIASI_TERIMA_ENTRY_TYPE CHECK (ENTRY_TYPE IN ('awal', 'untuk', 'ambil'))
);

CREATE INDEX IF NOT EXISTS IDX_REKONSILIASI_TERIMA_ROW ON REKONSILIASI_TERIMA_ENTRY(ID_REKONSILIASI_MATERIAL_ROW);

INSERT INTO HAK_AKSES (KODE_PERMISSION, NAMA_HALAMAN, DESKRIPSI, DOMAIN_PERMISSION, AKSI_PERMISSION)
VALUES
    ('REKONSILIASI_READ', 'Rekonsiliasi Read', 'Allows reading material reconciliation documents', 'rekonsiliasi', 'read'),
    ('REKONSILIASI_CREATE', 'Rekonsiliasi Create', 'Allows creating material reconciliation documents', 'rekonsiliasi', 'create'),
    ('REKONSILIASI_UPDATE', 'Rekonsiliasi Update', 'Allows updating material reconciliation documents', 'rekonsiliasi', 'update')
ON CONFLICT (KODE_PERMISSION) DO UPDATE
SET NAMA_HALAMAN = EXCLUDED.NAMA_HALAMAN,
    DESKRIPSI = EXCLUDED.DESKRIPSI,
    DOMAIN_PERMISSION = EXCLUDED.DOMAIN_PERMISSION,
    AKSI_PERMISSION = EXCLUDED.AKSI_PERMISSION;

INSERT INTO ROLE_HAK_AKSES (ID_ROLE, ID_HAK_AKSES)
SELECT r.ID_ROLE, h.ID_HAK_AKSES
FROM ROLES r
JOIN HAK_AKSES h ON h.KODE_PERMISSION = 'REKONSILIASI_READ'
WHERE r.NAMA_ROLE IN ('SUPER_ADMIN', 'ADMIN_PRODUKSI', 'ADMIN_KEUANGAN', 'ADMIN_GUDANG')
ON CONFLICT (ID_ROLE, ID_HAK_AKSES) DO NOTHING;

INSERT INTO ROLE_HAK_AKSES (ID_ROLE, ID_HAK_AKSES)
SELECT r.ID_ROLE, h.ID_HAK_AKSES
FROM ROLES r
JOIN HAK_AKSES h ON h.KODE_PERMISSION IN ('REKONSILIASI_CREATE', 'REKONSILIASI_UPDATE')
WHERE r.NAMA_ROLE IN ('SUPER_ADMIN', 'ADMIN_PRODUKSI')
ON CONFLICT (ID_ROLE, ID_HAK_AKSES) DO NOTHING;
