-- Add id_wo, no_dokumen and deskripsi fields to SURAT_JALAN_INTERNAL
ALTER TABLE SURAT_JALAN_INTERNAL
    ADD COLUMN IF NOT EXISTS id_wo INTEGER REFERENCES WORK_ORDER(id_wo),
    ADD COLUMN IF NOT EXISTS no_dokumen VARCHAR(100) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS deskripsi TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS SURAT_JALAN_INTERNAL_ITEM (
    id_surat_jalan_internal_item SERIAL PRIMARY KEY,
    id_surat_jalan_internal INTEGER NOT NULL REFERENCES SURAT_JALAN_INTERNAL(id_surat_jalan_internal) ON DELETE CASCADE,
    no_urut INTEGER NOT NULL DEFAULT 1,
    deskripsi TEXT NOT NULL DEFAULT '',
    qty INTEGER NOT NULL DEFAULT 0,
    note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
