ALTER TABLE USERS
ADD COLUMN IF NOT EXISTS MUST_CHANGE_PASSWORD BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS PASSWORD_CHANGED_AT TIMESTAMPTZ NULL,
ADD COLUMN IF NOT EXISTS CREATED_BY INT NULL,
ADD COLUMN IF NOT EXISTS UPDATED_BY INT NULL;

UPDATE USERS
SET MUST_CHANGE_PASSWORD = FALSE
WHERE PASSWORD IS NOT NULL;

ALTER TABLE USERS
DROP CONSTRAINT IF EXISTS fk_users_created_by;

ALTER TABLE USERS
ADD CONSTRAINT fk_users_created_by
FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID_USER) ON DELETE SET NULL;

ALTER TABLE USERS
DROP CONSTRAINT IF EXISTS fk_users_updated_by;

ALTER TABLE USERS
ADD CONSTRAINT fk_users_updated_by
FOREIGN KEY (UPDATED_BY) REFERENCES USERS(ID_USER) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_users_must_change_password ON USERS (MUST_CHANGE_PASSWORD);

CREATE TABLE IF NOT EXISTS PASSWORD_RESET_REQUESTS (
    ID_PASSWORD_RESET_REQUEST SERIAL PRIMARY KEY,
    ID_USER INT NOT NULL,
    REASON TEXT NOT NULL DEFAULT '',
    STATUS VARCHAR(30) NOT NULL DEFAULT 'pending',
    APPROVED_BY INT NULL,
    APPROVED_AT TIMESTAMPTZ NULL,
    REJECTED_BY INT NULL,
    REJECTED_AT TIMESTAMPTZ NULL,
    COMPLETED_AT TIMESTAMPTZ NULL,
    REJECTED_REASON TEXT NOT NULL DEFAULT '',
    REQUESTED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_password_reset_requests_user FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER) ON DELETE CASCADE,
    CONSTRAINT fk_password_reset_requests_approved_by FOREIGN KEY (APPROVED_BY) REFERENCES USERS(ID_USER) ON DELETE SET NULL,
    CONSTRAINT fk_password_reset_requests_rejected_by FOREIGN KEY (REJECTED_BY) REFERENCES USERS(ID_USER) ON DELETE SET NULL,
    CONSTRAINT chk_password_reset_requests_status CHECK (STATUS IN ('pending', 'approved', 'rejected', 'completed'))
);

CREATE INDEX IF NOT EXISTS idx_password_reset_requests_id_user ON PASSWORD_RESET_REQUESTS (ID_USER);
CREATE INDEX IF NOT EXISTS idx_password_reset_requests_status ON PASSWORD_RESET_REQUESTS (STATUS);
CREATE UNIQUE INDEX IF NOT EXISTS idx_password_reset_requests_user_pending
ON PASSWORD_RESET_REQUESTS (ID_USER)
WHERE STATUS = 'pending';

INSERT INTO HAK_AKSES (KODE_PERMISSION, NAMA_HALAMAN, DESKRIPSI, DOMAIN_PERMISSION, AKSI_PERMISSION)
VALUES
    ('PASSWORD_RESET_REQUEST_READ', 'Password Reset Request Read', 'Allows viewing password reset requests', 'password_reset_request', 'read'),
    ('PASSWORD_RESET_REQUEST_APPROVE', 'Password Reset Request Approve', 'Allows approving password reset requests', 'password_reset_request', 'approve'),
    ('PASSWORD_RESET_REQUEST_REJECT', 'Password Reset Request Reject', 'Allows rejecting password reset requests', 'password_reset_request', 'reject')
ON CONFLICT (KODE_PERMISSION) DO UPDATE SET
    NAMA_HALAMAN = EXCLUDED.NAMA_HALAMAN,
    DESKRIPSI = EXCLUDED.DESKRIPSI,
    DOMAIN_PERMISSION = EXCLUDED.DOMAIN_PERMISSION,
    AKSI_PERMISSION = EXCLUDED.AKSI_PERMISSION;

INSERT INTO ROLE_HAK_AKSES (ID_ROLE, ID_HAK_AKSES)
SELECT r.ID_ROLE, h.ID_HAK_AKSES
FROM ROLES r
JOIN HAK_AKSES h ON h.KODE_PERMISSION IN (
    'PASSWORD_RESET_REQUEST_READ',
    'PASSWORD_RESET_REQUEST_APPROVE',
    'PASSWORD_RESET_REQUEST_REJECT'
)
WHERE r.NAMA_ROLE = 'OPERATOR'
ON CONFLICT (ID_ROLE, ID_HAK_AKSES) DO NOTHING;
