ALTER TABLE RECEIVED DROP CONSTRAINT IF EXISTS fk_recv_mli;
ALTER TABLE RECEIVED DROP COLUMN IF EXISTS ID_MATERIAL_LIST_ITEM;
ALTER TABLE RECEIVED ADD COLUMN ID_MATERIAL_LIST INT NOT NULL DEFAULT 0;

ALTER TABLE SURAT_JALAN_CLIENT DROP CONSTRAINT IF EXISTS fk_sjc_mli;
ALTER TABLE SURAT_JALAN_CLIENT DROP COLUMN IF EXISTS ID_MATERIAL_LIST_ITEM;
ALTER TABLE SURAT_JALAN_CLIENT ADD COLUMN ID_MATERIAL_LIST INT NOT NULL DEFAULT 0;

ALTER TABLE MATERIAL_LIST DROP CONSTRAINT IF EXISTS fk_ml_mli;
ALTER TABLE MATERIAL_LIST DROP COLUMN IF EXISTS ID_MATERIAL_LIST_ITEM;
ALTER TABLE MATERIAL_LIST ADD COLUMN DESCRIPTION TEXT NOT NULL DEFAULT '';
ALTER TABLE MATERIAL_LIST ADD COLUMN SIZE VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE MATERIAL_LIST ADD COLUMN COLOR VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE MATERIAL_LIST ADD COLUMN UOM VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE MATERIAL_LIST ADD COLUMN ID_WO INT NOT NULL DEFAULT 0;

DROP TABLE IF EXISTS MATERIAL_LIST_ITEM CASCADE;
