-- 1. DROP LEVEL 7 (Report Tables)
DROP TABLE IF EXISTS REPORT_PENGIRIMAN CASCADE;
DROP TABLE IF EXISTS REPORT_PACKING CASCADE;
DROP TABLE IF EXISTS REPORT_QC_FINISH CASCADE;
DROP TABLE IF EXISTS REPORT_SEWING CASCADE;
DROP TABLE IF EXISTS REPORT_CUTTING CASCADE;

-- 2. DROP LEVEL 6 (Varian Size & Detail Eksekusi Terendah)
DROP TABLE IF EXISTS PACKING_LIST_ITEM_SIZE CASCADE;
DROP TABLE IF EXISTS PACKING_LIST_ITEM CASCADE;
DROP TABLE IF EXISTS REKONSILIASI_MATERIAL_TERIMA CASCADE;
DROP TABLE IF EXISTS RECEIVED CASCADE;
DROP TABLE IF EXISTS SURAT_JALAN_CLIENT CASCADE;
DROP TABLE IF EXISTS PO_INTERNAL_ITEM CASCADE;
DROP TABLE IF EXISTS WORK_ORDER_SHELL_SIZE CASCADE;

-- 3. DROP LEVEL 5 (Detail Work Order & Relasi Lanjutan)
DROP TABLE IF EXISTS PACKING_LIST CASCADE;
DROP TABLE IF EXISTS PO_INTERNAL CASCADE;
DROP TABLE IF EXISTS PR_INTERNAL_ITEM CASCADE;
DROP TABLE IF EXISTS REKONSILIASI_MATERIAL CASCADE;
DROP TABLE IF EXISTS MATERIAL_LIST CASCADE;
DROP TABLE IF EXISTS WORK_ORDER_TRIM CASCADE;
DROP TABLE IF EXISTS WORK_ORDER_SHELL CASCADE;

-- 4. DROP LEVEL 4 (Work Order Produksi & PR Internal)
DROP TABLE IF EXISTS PR_INTERNAL CASCADE;
DROP TABLE IF EXISTS WORK_ORDER CASCADE;

-- 5. DROP LEVEL 3 (Transaksi PO & Penanggung Jawab)
DROP TABLE IF EXISTS PENANGGUNG_JAWAB CASCADE;
DROP TABLE IF EXISTS PO_CLIENT_ITEM CASCADE;

-- 6. DROP LEVEL 2 (User & Master Lanjutan)
DROP TABLE IF EXISTS PO_CLIENT CASCADE;
DROP TABLE IF EXISTS BARANG CASCADE;
DROP TABLE IF EXISTS USER_AKSES CASCADE;
DROP TABLE IF EXISTS LOG_AKTIVITAS_DETAIL CASCADE;
DROP TABLE IF EXISTS USERS CASCADE; -- Menggunakan USERS, bukan "USER"

-- 7. DROP LEVEL 1 (Tabel Master Utama)
DROP TABLE IF EXISTS SURAT_JALAN_INTERNAL CASCADE;
DROP TABLE IF EXISTS DEPARTEMEN CASCADE;
DROP TABLE IF EXISTS JENIS_BARANG CASCADE;
DROP TABLE IF EXISTS MITRA CASCADE;
DROP TABLE IF EXISTS HAK_AKSES CASCADE;
DROP TABLE IF EXISTS LOG_AKTIVITAS CASCADE;
DROP TABLE IF EXISTS COMPANY CASCADE;