DELETE FROM ROLE_HAK_AKSES
WHERE ID_HAK_AKSES IN (
    SELECT ID_HAK_AKSES
    FROM HAK_AKSES
    WHERE KODE_PERMISSION IN (
        'PASSWORD_RESET_REQUEST_READ',
        'PASSWORD_RESET_REQUEST_APPROVE',
        'PASSWORD_RESET_REQUEST_REJECT'
    )
);

DELETE FROM HAK_AKSES
WHERE KODE_PERMISSION IN (
    'PASSWORD_RESET_REQUEST_READ',
    'PASSWORD_RESET_REQUEST_APPROVE',
    'PASSWORD_RESET_REQUEST_REJECT'
);

DROP INDEX IF EXISTS idx_password_reset_requests_user_pending;
DROP INDEX IF EXISTS idx_password_reset_requests_status;
DROP INDEX IF EXISTS idx_password_reset_requests_id_user;
DROP TABLE IF EXISTS PASSWORD_RESET_REQUESTS;

DROP INDEX IF EXISTS idx_users_must_change_password;

ALTER TABLE USERS
DROP CONSTRAINT IF EXISTS fk_users_updated_by;

ALTER TABLE USERS
DROP CONSTRAINT IF EXISTS fk_users_created_by;

ALTER TABLE USERS
DROP COLUMN IF EXISTS UPDATED_BY,
DROP COLUMN IF EXISTS CREATED_BY,
DROP COLUMN IF EXISTS PASSWORD_CHANGED_AT,
DROP COLUMN IF EXISTS MUST_CHANGE_PASSWORD;
