-- =================================================================================
-- 1. HAK AKSES METADATA
-- =================================================================================
ALTER TABLE HAK_AKSES
ADD COLUMN IF NOT EXISTS KODE_PERMISSION VARCHAR(150),
ADD COLUMN IF NOT EXISTS DESKRIPSI TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS DOMAIN_PERMISSION VARCHAR(100) NOT NULL DEFAULT 'general',
ADD COLUMN IF NOT EXISTS AKSI_PERMISSION VARCHAR(50) NOT NULL DEFAULT 'manage';

UPDATE HAK_AKSES
SET KODE_PERMISSION = UPPER(REGEXP_REPLACE(TRIM(NAMA_HALAMAN), '\s+', '_', 'g'))
WHERE KODE_PERMISSION IS NULL OR BTRIM(KODE_PERMISSION) = '';

UPDATE HAK_AKSES
SET DESKRIPSI = NAMA_HALAMAN
WHERE BTRIM(DESKRIPSI) = '';

UPDATE HAK_AKSES
SET DOMAIN_PERMISSION = CASE
        WHEN KODE_PERMISSION = 'ALL_ACCESS' THEN 'system'
        WHEN POSITION('_' IN KODE_PERMISSION) > 0 THEN LOWER(REGEXP_REPLACE(KODE_PERMISSION, '_[^_]+$', ''))
        ELSE 'general'
    END,
    AKSI_PERMISSION = CASE
        WHEN KODE_PERMISSION = 'ALL_ACCESS' THEN 'access'
        WHEN POSITION('_' IN KODE_PERMISSION) > 0 THEN LOWER((string_to_array(KODE_PERMISSION, '_'))[array_length(string_to_array(KODE_PERMISSION, '_'), 1)])
        ELSE 'manage'
    END
WHERE DOMAIN_PERMISSION = 'general' OR AKSI_PERMISSION = 'manage';

ALTER TABLE HAK_AKSES
ALTER COLUMN KODE_PERMISSION SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_hak_akses_kode_permission ON HAK_AKSES (KODE_PERMISSION);

-- =================================================================================
-- 2. SEED ROLE DASAR
-- =================================================================================
INSERT INTO ROLES (NAMA_ROLE) VALUES
    ('SUPER_ADMIN'),
    ('OPERATOR'),
    ('ADMIN_KEUANGAN'),
    ('ADMIN_PRODUKSI'),
    ('ADMIN_GUDANG'),
    ('MANAGER'),
    ('CLIENT')
ON CONFLICT (NAMA_ROLE) DO NOTHING;

-- =================================================================================
-- 3. USERS ROLE-FIRST MIGRATION
-- =================================================================================
ALTER TABLE USERS DROP CONSTRAINT IF EXISTS fk_users_role;
ALTER TABLE USERS
ADD CONSTRAINT fk_users_role FOREIGN KEY (ID_ROLE) REFERENCES ROLES(ID_ROLE) ON DELETE RESTRICT;

UPDATE USERS u
SET ID_ROLE = r.ID_ROLE
FROM ROLES r
WHERE r.NAMA_ROLE = 'SUPER_ADMIN'
  AND u.USERNAME = 'super-admin'
  AND (u.ID_ROLE IS NULL OR u.ID_ROLE <> r.ID_ROLE);

UPDATE USERS u
SET ID_ROLE = r.ID_ROLE
FROM ROLES r
WHERE r.NAMA_ROLE = 'CLIENT'
  AND u.ID_MITRA IS NOT NULL
  AND u.USERNAME <> 'super-admin'
  AND (u.ID_ROLE IS NULL OR u.ID_ROLE <> r.ID_ROLE);

UPDATE USERS u
SET ID_ROLE = r.ID_ROLE
FROM ROLES r
WHERE r.NAMA_ROLE = 'MANAGER'
  AND u.ID_MITRA IS NULL
  AND u.IS_MANAGER = TRUE
  AND u.USERNAME <> 'super-admin'
  AND (u.ID_ROLE IS NULL OR u.ID_ROLE <> r.ID_ROLE);

UPDATE USERS u
SET ID_ROLE = r.ID_ROLE
FROM ROLES r
WHERE r.NAMA_ROLE = 'OPERATOR'
  AND u.ID_ROLE IS NULL;

ALTER TABLE USERS
ALTER COLUMN ID_ROLE SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_users_id_role ON USERS (ID_ROLE);

ALTER TABLE USERS DROP COLUMN IF EXISTS IS_MANAGER;
