CREATE TABLE IF NOT EXISTS WARNA (
    id_warna SERIAL PRIMARY KEY,
    nama_warna VARCHAR(100) NOT NULL UNIQUE,
    kode_hex VARCHAR(7) DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
