DROP TABLE IF EXISTS MASTER_PLAN_TARGET_PROSES;
DROP TABLE IF EXISTS MASTER_PLAN_OUTPUT_HARIAN;
DROP TABLE IF EXISTS MASTER_PLAN_TARGET_HARIAN;
DROP TABLE IF EXISTS MASTER_PLAN_ITEM;
DROP TABLE IF EXISTS MASTER_PLAN;
