ALTER TABLE WORK_ORDER_SHELL ADD COLUMN PROVIDED_BY VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE WORK_ORDER_SHELL ADD COLUMN MATERIAL_TYPE VARCHAR(100) NOT NULL DEFAULT '';

ALTER TABLE WORK_ORDER_TRIM ADD COLUMN PROVIDED_BY VARCHAR(100) NOT NULL DEFAULT '';
