-- 1. Grant WO_READ to ADMIN_KEUANGAN (needed so they can read work orders to close them)
INSERT INTO ROLE_HAK_AKSES (ID_ROLE, ID_HAK_AKSES)
SELECT r.ID_ROLE, h.ID_HAK_AKSES
FROM ROLES r, HAK_AKSES h
WHERE r.NAMA_ROLE = 'ADMIN_KEUANGAN'
AND h.KODE_PERMISSION = 'WO_READ'
ON CONFLICT DO NOTHING;

-- 2. Remove PO_INTERNAL_APPROVE from ADMIN_KEUANGAN (only Manager approves PO Internal)
DELETE FROM ROLE_HAK_AKSES
WHERE ID_ROLE IN (SELECT ID_ROLE FROM ROLES WHERE NAMA_ROLE = 'ADMIN_KEUANGAN')
AND ID_HAK_AKSES IN (SELECT ID_HAK_AKSES FROM HAK_AKSES WHERE KODE_PERMISSION = 'PO_INTERNAL_APPROVE');

-- 3. Grant SURAT_JALAN_INTERNAL_READ to ADMIN_GUDANG (needed so they can read internal delivery notes)
INSERT INTO ROLE_HAK_AKSES (ID_ROLE, ID_HAK_AKSES)
SELECT r.ID_ROLE, h.ID_HAK_AKSES
FROM ROLES r, HAK_AKSES h
WHERE r.NAMA_ROLE = 'ADMIN_GUDANG'
AND h.KODE_PERMISSION = 'SURAT_JALAN_INTERNAL_READ'
ON CONFLICT DO NOTHING;
