ALTER TABLE PO_CLIENT ADD COLUMN PAYMENT_TERM VARCHAR(100) NOT NULL DEFAULT '';

UPDATE PO_CLIENT pc
SET PAYMENT_TERM = mpt.KODE
FROM MASTER_PAYMENT_TERM mpt
WHERE pc.ID_PAYMENT_TERM = mpt.ID_PAYMENT_TERM;

ALTER TABLE PO_CLIENT DROP CONSTRAINT fk_po_client_payment_term;
ALTER TABLE PO_CLIENT DROP COLUMN ID_PAYMENT_TERM;

DROP TABLE IF EXISTS MASTER_PAYMENT_TERM;
