-- =================================================================================
-- 1. TABEL MASTER (Tanpa Dependencies)
-- =================================================================================

CREATE TABLE IF NOT EXISTS COMPANY (
    ID_COMPANY SERIAL PRIMARY KEY,
    NAMA VARCHAR(100) NOT NULL,
    ALAMAT TEXT NOT NULL DEFAULT '',
    EMAIL VARCHAR(100) NOT NULL DEFAULT '',
    NO_TELP VARCHAR(50) NOT NULL DEFAULT '',
    ABOUT TEXT NOT NULL DEFAULT '',
    LOGO TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS LOG_AKTIVITAS (
    ID_LOG SERIAL PRIMARY KEY,
    AKSI VARCHAR(255) NOT NULL,
    WAKTU TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS HAK_AKSES (
    ID_HAK_AKSES SERIAL PRIMARY KEY,
    NAMA_HALAMAN VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS MITRA (
    ID_MITRA SERIAL PRIMARY KEY,
    NAMA_PERUSAHAAN VARCHAR(150) NOT NULL,
    TIPE_PERUSAHAAN VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL DEFAULT '',
    NO_TELP VARCHAR(50) NOT NULL DEFAULT '',
    ALAMAT TEXT NOT NULL DEFAULT '',
    KOTA VARCHAR(100) NOT NULL DEFAULT '',
    KODE_POS VARCHAR(20) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS JENIS_BARANG (
    ID_JENIS_BARANG SERIAL PRIMARY KEY,
    NAMA_JENIS_BARANG VARCHAR(100) NOT NULL,
    KODE VARCHAR(100) NOT NULL UNIQUE, -- Tambahan UNIQUE
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS DEPARTEMEN (
    ID_DEPARTEMEN SERIAL PRIMARY KEY,
    NAMA_DEPARTEMEN VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS SURAT_JALAN_INTERNAL (
    ID_SURAT_JALAN_INTERNAL SERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =================================================================================
-- 2. TABEL LEVEL 2 (User & Master Lanjutan)
-- =================================================================================

-- Penamaan tabel USER diganti menjadi USERS untuk menghindari Reserved Keyword SQL
CREATE TABLE IF NOT EXISTS USERS (
    ID_USER SERIAL PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    IS_MANAGER BOOLEAN NOT NULL DEFAULT FALSE,
    ID_DEPARTEMEN INT,
    ID_MITRA INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_DEPARTEMEN) REFERENCES DEPARTEMEN(ID_DEPARTEMEN) ON DELETE SET NULL,
    FOREIGN KEY (ID_MITRA) REFERENCES MITRA(ID_MITRA) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS LOG_AKTIVITAS_DETAIL (
    ID_LOG_DETAIL SERIAL PRIMARY KEY,
    NAMA VARCHAR(100) NOT NULL,
    TABLE_NAME VARCHAR(100) NOT NULL DEFAULT '', -- Mengganti keyword "TABLE"
    DESKRIPSI TEXT NOT NULL DEFAULT '',
    ID_LOG INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_LOG) REFERENCES LOG_AKTIVITAS(ID_LOG) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USER_AKSES (
    ID_USER INT NOT NULL,
    ID_HAK_AKSES INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID_USER, ID_HAK_AKSES),
    FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER) ON DELETE CASCADE,
    FOREIGN KEY (ID_HAK_AKSES) REFERENCES HAK_AKSES(ID_HAK_AKSES) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BARANG (
    ID_BARANG SERIAL PRIMARY KEY,
    NAMA_BARANG VARCHAR(150) NOT NULL,
    KODE VARCHAR(100) NOT NULL UNIQUE, -- Tambahan UNIQUE
    ID_JENIS_BARANG INT NOT NULL,
    ID_MITRA INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_JENIS_BARANG) REFERENCES JENIS_BARANG(ID_JENIS_BARANG),
    FOREIGN KEY (ID_MITRA) REFERENCES MITRA(ID_MITRA)
);

CREATE TABLE IF NOT EXISTS PO_CLIENT (
    ID_PO_CLIENT SERIAL PRIMARY KEY,
    PO_NUMBER VARCHAR(100) NOT NULL UNIQUE, -- Tambahan UNIQUE
    TANGGAL DATE NOT NULL,
    SEASON VARCHAR(100) NOT NULL DEFAULT '',
    DELIVERY DATE NOT NULL,
    PAYMENT_TERM VARCHAR(100) NOT NULL DEFAULT '',
    FILE TEXT NOT NULL DEFAULT '',
    ID_MITRA INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_MITRA) REFERENCES MITRA(ID_MITRA)
);

-- =================================================================================
-- 3. TABEL LEVEL 3 (Transaksi PO & Penanggung Jawab)
-- =================================================================================

CREATE TABLE IF NOT EXISTS PO_CLIENT_ITEM (
    ID_PO_CLIENT_ITEM SERIAL PRIMARY KEY,
    ID_PO_CLIENT INT NOT NULL,
    STYLE VARCHAR(100) NOT NULL,
    COLOUR VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT NOT NULL DEFAULT '', -- Mengganti keyword "DESC"
    QTY INT NOT NULL DEFAULT 0,
    PRICE DECIMAL(15,2) NOT NULL DEFAULT 0.00, -- Mencegah Overflow harga
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_PO_CLIENT) REFERENCES PO_CLIENT(ID_PO_CLIENT) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PENANGGUNG_JAWAB (
    ID_PENANGGUNG_JAWAB SERIAL PRIMARY KEY,
    NAMA VARCHAR(100) NOT NULL,
    NO_TELP VARCHAR(50) NOT NULL DEFAULT '',
    EMAIL VARCHAR(100) NOT NULL DEFAULT '',
    ID_PO_CLIENT INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_PO_CLIENT) REFERENCES PO_CLIENT(ID_PO_CLIENT) ON DELETE CASCADE
);

-- =================================================================================
-- 4. TABEL LEVEL 4 (Work Order Produksi & PR Internal)
-- =================================================================================

-- Perbaikan konsistensi snake_case pada kolom ID_PO_CLIENT_ITEM
CREATE TABLE IF NOT EXISTS WORK_ORDER (
    ID_WO SERIAL PRIMARY KEY,
    BUYER VARCHAR(100) NOT NULL,
    MODEL VARCHAR(100) NOT NULL,
    QTY INT NOT NULL DEFAULT 0,
    FOB_CMT BOOLEAN NOT NULL DEFAULT FALSE,
    DELIVERY DATE NOT NULL,
    ID_PO_CLIENT_ITEM INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_PO_CLIENT_ITEM) REFERENCES PO_CLIENT_ITEM(ID_PO_CLIENT_ITEM)
);

CREATE TABLE IF NOT EXISTS PR_INTERNAL (
    ID_PR_INTERNAL SERIAL PRIMARY KEY,
    TANGGAL DATE NOT NULL,
    NAMA VARCHAR(100) NOT NULL,
    DEPARTEMEN VARCHAR(100) NOT NULL,
    VENDOR_NAME VARCHAR(150) NOT NULL,
    VENDOR_ADDRESS TEXT NOT NULL DEFAULT '',
    VENDOR_TELP VARCHAR(50) NOT NULL DEFAULT '',
    PROJEK VARCHAR(100) NOT NULL,
    ID_WO INT NOT NULL,
    ID_USER INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO) REFERENCES WORK_ORDER(ID_WO),
    FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER)
);

-- =================================================================================
-- 5. TABEL LEVEL 5 (Detail Work Order & Relasi Lanjutan)
-- =================================================================================

CREATE TABLE IF NOT EXISTS WORK_ORDER_SHELL (
    ID_WO_SHELL SERIAL PRIMARY KEY,
    FABRIC VARCHAR(100) NOT NULL,
    CONS DECIMAL(15,3) NOT NULL DEFAULT 0,
    COLOR VARCHAR(100) NOT NULL,
    ALLOW INT NOT NULL DEFAULT 0,
    BERAT_1_YD DECIMAL(15,3) NOT NULL DEFAULT 0,
    ID_WO INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO) REFERENCES WORK_ORDER(ID_WO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS WORK_ORDER_TRIM (
    ID_WO_TRIM SERIAL PRIMARY KEY,
    ITEM VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT NOT NULL DEFAULT '', -- Mengganti keyword "DESC"
    COLOR VARCHAR(100) NOT NULL,
    CODE VARCHAR(100) NOT NULL,
    CONS DECIMAL(15,3) NOT NULL DEFAULT 0,
    QTY INT NOT NULL DEFAULT 0,
    UOM VARCHAR(20) NOT NULL,
    POSITION VARCHAR(100) NOT NULL DEFAULT '',
    CREATED_BY VARCHAR(100) NOT NULL DEFAULT '', -- Mengganti keyword "BY"
    ALLOW INT NOT NULL DEFAULT 0,
    ID_WO INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO) REFERENCES WORK_ORDER(ID_WO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MATERIAL_LIST (
    ID_MATERIAL_LIST SERIAL PRIMARY KEY,
    DESCRIPTION TEXT NOT NULL DEFAULT '', -- Mengganti keyword "DESC"
    SIZE VARCHAR(20) NOT NULL,
    COLOR VARCHAR(100) NOT NULL,
    UOM VARCHAR(20) NOT NULL,
    ID_WO INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO) REFERENCES WORK_ORDER(ID_WO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS REKONSILIASI_MATERIAL (
    ID_REKONSILIASI_MATERIAL SERIAL PRIMARY KEY,
    DESCRIPTION TEXT NOT NULL DEFAULT '',
    SIZE VARCHAR(100) NOT NULL,
    RATIO INT NOT NULL DEFAULT 0,
    QTY_PER_PCS DECIMAL(15,3) NOT NULL DEFAULT 0,
    QTY_WO INT NOT NULL DEFAULT 0,
    TOLERANSI INT NOT NULL DEFAULT 0,
    SATUAN VARCHAR(20) NOT NULL,
    ACTUAL_KIRIM INT NOT NULL DEFAULT 0,
    CONS_ACTUAL DECIMAL(15,3) NOT NULL DEFAULT 0,
    BALANCE INT NOT NULL DEFAULT 0,
    REJECT INT NOT NULL DEFAULT 0,
    RETUR INT NOT NULL DEFAULT 0,
    LAST_BALANCE INT NOT NULL DEFAULT 0,
    KETERANGAN TEXT NOT NULL DEFAULT '',
    ID_WO INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO) REFERENCES WORK_ORDER(ID_WO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PR_INTERNAL_ITEM (
    ID_PR_INTERNAL_ITEM SERIAL PRIMARY KEY,
    ID_PR_INTERNAL INT NOT NULL,
    ITEM VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT NOT NULL DEFAULT '', -- Mengganti keyword "DESC"
    QTY INT NOT NULL DEFAULT 0,
    UNIT VARCHAR(20) NOT NULL,
    EST_PRICE DECIMAL(15,2) NOT NULL DEFAULT 0.00, -- Mencegah Overflow harga
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_PR_INTERNAL) REFERENCES PR_INTERNAL(ID_PR_INTERNAL) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PO_INTERNAL (
    ID_PO_INTERNAL SERIAL PRIMARY KEY,
    TANGGAL DATE NOT NULL,
    NAMA_PO VARCHAR(100) NOT NULL,
    SUPPLIER_NAME VARCHAR(150) NOT NULL,
    SUPPLIER_ADDR TEXT NOT NULL DEFAULT '',
    SUPPLIER_CONTACT VARCHAR(100) NOT NULL DEFAULT '',
    SUPPLIER_EMAIL VARCHAR(100) NOT NULL DEFAULT '',
    SUPPLIER_TELP VARCHAR(50) NOT NULL DEFAULT '',
    SUPPLIER_FAX VARCHAR(50) NOT NULL DEFAULT '',
    CURRENCY VARCHAR(10) NOT NULL DEFAULT 'IDR',
    CPO VARCHAR(255) NOT NULL DEFAULT '',
    TERM VARCHAR(255) NOT NULL DEFAULT '',
    SHIP_DATE DATE NOT NULL,
    ID_PR_INTERNAL INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_PR_INTERNAL) REFERENCES PR_INTERNAL(ID_PR_INTERNAL)
);

CREATE TABLE IF NOT EXISTS PACKING_LIST (
    ID_PACKING_LIST SERIAL PRIMARY KEY,
    TOTAL_GARMENT_PER_BOX INT NOT NULL DEFAULT 0,
    TOTAL_REJECT INT NOT NULL DEFAULT 0,
    ID_WO INT NOT NULL,
    ID_SURAT_JALAN_INTERNAL INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO) REFERENCES WORK_ORDER(ID_WO),
    FOREIGN KEY (ID_SURAT_JALAN_INTERNAL) REFERENCES SURAT_JALAN_INTERNAL(ID_SURAT_JALAN_INTERNAL)
);

-- =================================================================================
-- 6. TABEL LEVEL 6 (Varian Size & Detail Eksekusi)
-- =================================================================================

CREATE TABLE IF NOT EXISTS WORK_ORDER_SHELL_SIZE (
    ID_WO_SHELL_SIZE SERIAL PRIMARY KEY,
    SIZE VARCHAR(20) NOT NULL,
    QTY INT NOT NULL DEFAULT 0,
    RATIO INT NOT NULL DEFAULT 0,
    ID_WO_SHELL INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO_SHELL) REFERENCES WORK_ORDER_SHELL(ID_WO_SHELL) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PO_INTERNAL_ITEM (
    ID_PO_INTERNAL_ITEM SERIAL PRIMARY KEY,
    ID_PO_INTERNAL INT NOT NULL,
    ITEM VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT NOT NULL DEFAULT '', -- Mengganti keyword "DESC"
    QTY INT NOT NULL DEFAULT 0,
    UNIT VARCHAR(20) NOT NULL,
    UNIT_PRICE DECIMAL(15,2) NOT NULL DEFAULT 0.00, -- Mencegah Overflow harga
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_PO_INTERNAL) REFERENCES PO_INTERNAL(ID_PO_INTERNAL) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SURAT_JALAN_CLIENT (
    ID_SURAT_JALAN_CLIENT SERIAL PRIMARY KEY,
    TANGGAL DATE NOT NULL,
    QTY INT NOT NULL DEFAULT 0,
    KETERANGAN TEXT NOT NULL DEFAULT '',
    ID_MATERIAL_LIST INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_MATERIAL_LIST) REFERENCES MATERIAL_LIST(ID_MATERIAL_LIST)
);

CREATE TABLE IF NOT EXISTS RECEIVED (
    ID_RECEIVED SERIAL PRIMARY KEY,
    TANGGAL DATE NOT NULL,
    QTY INT NOT NULL DEFAULT 0,
    KETERANGAN TEXT NOT NULL DEFAULT '',
    ID_MATERIAL_LIST INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_MATERIAL_LIST) REFERENCES MATERIAL_LIST(ID_MATERIAL_LIST)
);

CREATE TABLE IF NOT EXISTS REKONSILIASI_MATERIAL_TERIMA (
    ID_REKONSILIASI_MATERIAL_TERIMA SERIAL PRIMARY KEY,
    KETERANGAN TEXT NOT NULL DEFAULT '',
    QTY INT NOT NULL DEFAULT 0,
    ID_REKONSILIASI_MATERIAL INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_REKONSILIASI_MATERIAL) REFERENCES REKONSILIASI_MATERIAL(ID_REKONSILIASI_MATERIAL) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PACKING_LIST_ITEM (
    ID_PACKING_LIST_ITEM SERIAL PRIMARY KEY,
    ID_PACKING_LIST INT NOT NULL,
    COLOR VARCHAR(100) NOT NULL,
    QTY_BOX INT NOT NULL DEFAULT 0,
    QTY_PER_BOX INT NOT NULL DEFAULT 0,
    BOX_NO_START INT NOT NULL DEFAULT 0,
    BOX_NO_END INT NOT NULL DEFAULT 0,
    NOTE TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_PACKING_LIST) REFERENCES PACKING_LIST(ID_PACKING_LIST) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PACKING_LIST_ITEM_SIZE (
    ID_PACKING_LIST_ITEM_SIZE SERIAL PRIMARY KEY,
    QTY INT NOT NULL DEFAULT 0,
    ID_PACKING_LIST_ITEM INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_PACKING_LIST_ITEM) REFERENCES PACKING_LIST_ITEM(ID_PACKING_LIST_ITEM) ON DELETE CASCADE
);

-- =================================================================================
-- 7. TABEL REPORT (Tergantung pada WORK_ORDER_SHELL_SIZE)
-- =================================================================================

CREATE TABLE IF NOT EXISTS REPORT_CUTTING (
    ID_REPORT_CUTTING SERIAL PRIMARY KEY,
    TANGGAL DATE NOT NULL,
    QTY INT NOT NULL DEFAULT 0,
    ID_WO_SHELL_SIZE INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO_SHELL_SIZE) REFERENCES WORK_ORDER_SHELL_SIZE(ID_WO_SHELL_SIZE) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS REPORT_SEWING (
    ID_REPORT_SEWING SERIAL PRIMARY KEY,
    TANGGAL DATE NOT NULL,
    QTY INT NOT NULL DEFAULT 0,
    ID_WO_SHELL_SIZE INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO_SHELL_SIZE) REFERENCES WORK_ORDER_SHELL_SIZE(ID_WO_SHELL_SIZE) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS REPORT_QC_FINISH (
    ID_REPORT_QC_FINISHING SERIAL PRIMARY KEY,
    TANGGAL DATE NOT NULL,
    QTY INT NOT NULL DEFAULT 0,
    ID_WO_SHELL_SIZE INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO_SHELL_SIZE) REFERENCES WORK_ORDER_SHELL_SIZE(ID_WO_SHELL_SIZE) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS REPORT_PACKING (
    ID_REPORT_PACKING SERIAL PRIMARY KEY,
    TANGGAL DATE NOT NULL,
    QTY INT NOT NULL DEFAULT 0,
    ID_WO_SHELL_SIZE INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO_SHELL_SIZE) REFERENCES WORK_ORDER_SHELL_SIZE(ID_WO_SHELL_SIZE) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS REPORT_PENGIRIMAN (
    ID_REPORT_PENGIRIMAN SERIAL PRIMARY KEY,
    REPORT_DATE DATE NOT NULL, -- Mengganti keyword "DATE"
    QTY INT NOT NULL DEFAULT 0,
    ID_WO_SHELL_SIZE INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_WO_SHELL_SIZE) REFERENCES WORK_ORDER_SHELL_SIZE(ID_WO_SHELL_SIZE) ON DELETE CASCADE
);