-- Hapus assignment WO permissions dari semua role
DELETE FROM ROLE_HAK_AKSES
WHERE ID_HAK_AKSES IN (
    SELECT ID_HAK_AKSES FROM HAK_AKSES
    WHERE KODE_PERMISSION IN ('WO_READ', 'WO_CREATE', 'WO_UPDATE', 'WO_CLOSE')
);

-- Hapus WO permissions dari HAK_AKSES
DELETE FROM HAK_AKSES
WHERE KODE_PERMISSION IN ('WO_READ', 'WO_CREATE', 'WO_UPDATE', 'WO_CLOSE');
