-- =================================================================================
-- 1. TIMELINE PLAN PRODUKSI (Header)
-- =================================================================================
CREATE TABLE IF NOT EXISTS TIMELINE_PLAN_PRODUKSI (
    ID_TIMELINE SERIAL PRIMARY KEY,
    ID_PO_CLIENT INT NOT NULL,
    TANGGAL_DISUSUN DATE NOT NULL,
    NOTES TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_PO_CLIENT) REFERENCES PO_CLIENT(ID_PO_CLIENT)
);

-- =================================================================================
-- 2. WO SHELL PLAN (Detail)
-- =================================================================================
CREATE TABLE IF NOT EXISTS WO_SHELL_PLAN (
    ID_WO_SHELL_PLAN SERIAL PRIMARY KEY,
    ID_TIMELINE INT NOT NULL,
    ID_WO_SHELL INT NOT NULL,
    
    IN_LINE VARCHAR(100) NOT NULL DEFAULT '',
    
    TGL_GELAR_CUTTING DATE,
    STATUS_GELAR_CUTTING VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    
    TGL_EMBROO DATE,
    STATUS_EMBROO VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    
    TGL_LOADING_SEWING DATE,
    STATUS_LOADING_SEWING VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    
    TGL_FINISHING_PACKING DATE,
    STATUS_FINISHING_PACKING VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ID_TIMELINE) REFERENCES TIMELINE_PLAN_PRODUKSI(ID_TIMELINE) ON DELETE CASCADE,
    FOREIGN KEY (ID_WO_SHELL) REFERENCES WORK_ORDER_SHELL(ID_WO_SHELL)
);
