root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/web"
  bin = "tmp/main.exe"
  include_ext = ["go", "env"]
  exclude_dir = ["tmp", "vendor", "docs"]
  delay = 1000
  stop_on_error = true
  send_interrupt = true

[log]
  time = true

[color]
  main = "cyan"
  watcher = "yellow"
  build = "green"
  runner = "magenta"

[misc]
  clean_on_exit = true
