run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive
    - gofmt
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
