INSERT INTO ROLES (NAMA_ROLE) VALUES ('Operator') ON CONFLICT (NAMA_ROLE) DO NOTHING;
UPDATE USERS SET ID_ROLE = (SELECT ID_ROLE FROM ROLES WHERE NAMA_ROLE = 'Operator') WHERE USERNAME = 'operator';

INSERT INTO ROLE_HAK_AKSES (ID_ROLE, ID_HAK_AKSES)
SELECT r.ID_ROLE, h.ID_HAK_AKSES
FROM ROLES r, HAK_AKSES h
WHERE r.NAMA_ROLE = 'Operator' 
AND h.NAMA_HALAMAN IN (
    'MASTER_BARANG_READ', 'MASTER_JENIS_BARANG_READ', 'MASTER_DEPARTEMEN_READ', 
    'MASTER_MITRA_READ', 'MASTER_WARNA_READ', 'MASTER_COMPANY_READ', 
    'USER_READ', 'PASSWORD_RESET_REQUEST_READ', 
    'ROLE_READ', 'PERMISSION_READ', 
    'PO_CLIENT_READ', 'WO_READ', 'PO_INTERNAL_READ', 'REPORT_READ', 'PRODUCTION_SUMMARY_READ', 
    'PRODUCTION_REPORT_CREATE', 'DASHBOARD_READ'
)
ON CONFLICT DO NOTHING;
