// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*)
FROM AUDIT_LOGS
WHERE (
    $1::text = '' OR
    actor_username ILIKE '%' || $1::text || '%' OR
    actor_role ILIKE '%' || $1::text || '%' OR
    module ILIKE '%' || $1::text || '%' OR
    entity_type ILIKE '%' || $1::text || '%' OR
    entity_label ILIKE '%' || $1::text || '%' OR
    route ILIKE '%' || $1::text || '%'
)
AND (
    $2::text = '' OR
    action = $2::text
)
AND (
    $3::text = '' OR
    module = $3::text
)
AND (
    $4::text = '' OR
    entity_type = $4::text
)
AND (
    $5::int = 0 OR
    actor_user_id = $5::int
)
AND (
    $6::timestamptz IS NULL OR
    created_at >= $6::timestamptz
)
AND (
    $7::timestamptz IS NULL OR
    created_at <= $7::timestamptz
)
`

type CountAuditLogsParams struct {
	SearchTerm        string             `json:"search_term"`
	ActionFilter      string             `json:"action_filter"`
	ModuleFilter      string             `json:"module_filter"`
	EntityTypeFilter  string             `json:"entity_type_filter"`
	ActorUserIDFilter int32              `json:"actor_user_id_filter"`
	DateFrom          pgtype.Timestamptz `json:"date_from"`
	DateTo            pgtype.Timestamptz `json:"date_to"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.SearchTerm,
		arg.ActionFilter,
		arg.ModuleFilter,
		arg.EntityTypeFilter,
		arg.ActorUserIDFilter,
		arg.DateFrom,
		arg.DateTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO AUDIT_LOGS (
    actor_user_id,
    actor_username,
    actor_role,
    action,
    module,
    entity_type,
    entity_id,
    entity_label,
    method,
    route,
    before_data,
    after_data,
    changed_fields
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
RETURNING id, actor_user_id, actor_username, actor_role, action, module, entity_type, entity_id, entity_label, method, route, before_data, after_data, changed_fields, created_at
`

type CreateAuditLogParams struct {
	ActorUserID   pgtype.Int4 `json:"actor_user_id"`
	ActorUsername string      `json:"actor_username"`
	ActorRole     string      `json:"actor_role"`
	Action        string      `json:"action"`
	Module        string      `json:"module"`
	EntityType    string      `json:"entity_type"`
	EntityID      string      `json:"entity_id"`
	EntityLabel   string      `json:"entity_label"`
	Method        string      `json:"method"`
	Route         string      `json:"route"`
	BeforeData    []byte      `json:"before_data"`
	AfterData     []byte      `json:"after_data"`
	ChangedFields []byte      `json:"changed_fields"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ActorUserID,
		arg.ActorUsername,
		arg.ActorRole,
		arg.Action,
		arg.Module,
		arg.EntityType,
		arg.EntityID,
		arg.EntityLabel,
		arg.Method,
		arg.Route,
		arg.BeforeData,
		arg.AfterData,
		arg.ChangedFields,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.ActorUsername,
		&i.ActorRole,
		&i.Action,
		&i.Module,
		&i.EntityType,
		&i.EntityID,
		&i.EntityLabel,
		&i.Method,
		&i.Route,
		&i.BeforeData,
		&i.AfterData,
		&i.ChangedFields,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLogByID = `-- name: GetAuditLogByID :one
SELECT id, actor_user_id, actor_username, actor_role, action, module, entity_type, entity_id, entity_label, method, route, before_data, after_data, changed_fields, created_at
FROM AUDIT_LOGS
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAuditLogByID(ctx context.Context, id int64) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLogByID, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.ActorUsername,
		&i.ActorRole,
		&i.Action,
		&i.Module,
		&i.EntityType,
		&i.EntityID,
		&i.EntityLabel,
		&i.Method,
		&i.Route,
		&i.BeforeData,
		&i.AfterData,
		&i.ChangedFields,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_user_id, actor_username, actor_role, action, module, entity_type, entity_id, entity_label, method, route, before_data, after_data, changed_fields, created_at
FROM AUDIT_LOGS
WHERE (
    $1::text = '' OR
    actor_username ILIKE '%' || $1::text || '%' OR
    actor_role ILIKE '%' || $1::text || '%' OR
    module ILIKE '%' || $1::text || '%' OR
    entity_type ILIKE '%' || $1::text || '%' OR
    entity_label ILIKE '%' || $1::text || '%' OR
    route ILIKE '%' || $1::text || '%'
)
AND (
    $2::text = '' OR
    action = $2::text
)
AND (
    $3::text = '' OR
    module = $3::text
)
AND (
    $4::text = '' OR
    entity_type = $4::text
)
AND (
    $5::int = 0 OR
    actor_user_id = $5::int
)
AND (
    $6::timestamptz IS NULL OR
    created_at >= $6::timestamptz
)
AND (
    $7::timestamptz IS NULL OR
    created_at <= $7::timestamptz
)
ORDER BY
    CASE WHEN $8::text = 'created_at' AND NOT $9::bool THEN created_at END ASC,
    CASE WHEN $8::text = 'created_at' AND $9::bool THEN created_at END DESC,
    CASE WHEN $8::text = 'actor_username' AND NOT $9::bool THEN actor_username END ASC,
    CASE WHEN $8::text = 'actor_username' AND $9::bool THEN actor_username END DESC,
    CASE WHEN $8::text = 'action' AND NOT $9::bool THEN action END ASC,
    CASE WHEN $8::text = 'action' AND $9::bool THEN action END DESC,
    CASE WHEN $8::text = 'module' AND NOT $9::bool THEN module END ASC,
    CASE WHEN $8::text = 'module' AND $9::bool THEN module END DESC,
    CASE WHEN $8::text = 'entity_type' AND NOT $9::bool THEN entity_type END ASC,
    CASE WHEN $8::text = 'entity_type' AND $9::bool THEN entity_type END DESC,
    created_at DESC,
    id DESC
LIMIT $11 OFFSET $10
`

type ListAuditLogsParams struct {
	SearchTerm        string             `json:"search_term"`
	ActionFilter      string             `json:"action_filter"`
	ModuleFilter      string             `json:"module_filter"`
	EntityTypeFilter  string             `json:"entity_type_filter"`
	ActorUserIDFilter int32              `json:"actor_user_id_filter"`
	DateFrom          pgtype.Timestamptz `json:"date_from"`
	DateTo            pgtype.Timestamptz `json:"date_to"`
	SortBy            string             `json:"sort_by"`
	SortDesc          bool               `json:"sort_desc"`
	PageOffset        int32              `json:"page_offset"`
	PageLimit         int32              `json:"page_limit"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.SearchTerm,
		arg.ActionFilter,
		arg.ModuleFilter,
		arg.EntityTypeFilter,
		arg.ActorUserIDFilter,
		arg.DateFrom,
		arg.DateTo,
		arg.SortBy,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorUsername,
			&i.ActorRole,
			&i.Action,
			&i.Module,
			&i.EntityType,
			&i.EntityID,
			&i.EntityLabel,
			&i.Method,
			&i.Route,
			&i.BeforeData,
			&i.AfterData,
			&i.ChangedFields,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
