// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: barang.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBarang = `-- name: CreateBarang :one
INSERT INTO BARANG (
    nama_barang, kode, id_jenis_barang, id_mitra
) VALUES (
    $1, $2, $3, $4
) RETURNING id_barang, nama_barang, kode, id_jenis_barang, id_mitra, created_at
`

type CreateBarangParams struct {
	NamaBarang    string `json:"nama_barang"`
	Kode          string `json:"kode"`
	IDJenisBarang int32  `json:"id_jenis_barang"`
	IDMitra       int32  `json:"id_mitra"`
}

func (q *Queries) CreateBarang(ctx context.Context, arg CreateBarangParams) (Barang, error) {
	row := q.db.QueryRow(ctx, createBarang,
		arg.NamaBarang,
		arg.Kode,
		arg.IDJenisBarang,
		arg.IDMitra,
	)
	var i Barang
	err := row.Scan(
		&i.IDBarang,
		&i.NamaBarang,
		&i.Kode,
		&i.IDJenisBarang,
		&i.IDMitra,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBarang = `-- name: DeleteBarang :execrows
DELETE FROM BARANG
WHERE id_barang = $1
`

func (q *Queries) DeleteBarang(ctx context.Context, idBarang int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBarang, idBarang)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBarangByID = `-- name: GetBarangByID :one
SELECT b.id_barang, b.nama_barang, b.kode, b.id_jenis_barang, b.id_mitra, b.created_at, m.nama_perusahaan, j.nama_jenis_barang
FROM BARANG b
JOIN MITRA m ON b.id_mitra = m.id_mitra
JOIN JENIS_BARANG j ON b.id_jenis_barang = j.id_jenis_barang
WHERE b.id_barang = $1 LIMIT 1
`

type GetBarangByIDRow struct {
	IDBarang        int32              `json:"id_barang"`
	NamaBarang      string             `json:"nama_barang"`
	Kode            string             `json:"kode"`
	IDJenisBarang   int32              `json:"id_jenis_barang"`
	IDMitra         int32              `json:"id_mitra"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	NamaPerusahaan  string             `json:"nama_perusahaan"`
	NamaJenisBarang string             `json:"nama_jenis_barang"`
}

func (q *Queries) GetBarangByID(ctx context.Context, idBarang int32) (GetBarangByIDRow, error) {
	row := q.db.QueryRow(ctx, getBarangByID, idBarang)
	var i GetBarangByIDRow
	err := row.Scan(
		&i.IDBarang,
		&i.NamaBarang,
		&i.Kode,
		&i.IDJenisBarang,
		&i.IDMitra,
		&i.CreatedAt,
		&i.NamaPerusahaan,
		&i.NamaJenisBarang,
	)
	return i, err
}

const listBarang = `-- name: ListBarang :many
SELECT b.id_barang, b.nama_barang, b.kode, b.id_jenis_barang, b.id_mitra, b.created_at, m.nama_perusahaan, j.nama_jenis_barang
FROM BARANG b
JOIN MITRA m ON b.id_mitra = m.id_mitra
JOIN JENIS_BARANG j ON b.id_jenis_barang = j.id_jenis_barang
ORDER BY b.created_at DESC
LIMIT $1 OFFSET $2
`

type ListBarangParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListBarangRow struct {
	IDBarang        int32              `json:"id_barang"`
	NamaBarang      string             `json:"nama_barang"`
	Kode            string             `json:"kode"`
	IDJenisBarang   int32              `json:"id_jenis_barang"`
	IDMitra         int32              `json:"id_mitra"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	NamaPerusahaan  string             `json:"nama_perusahaan"`
	NamaJenisBarang string             `json:"nama_jenis_barang"`
}

func (q *Queries) ListBarang(ctx context.Context, arg ListBarangParams) ([]ListBarangRow, error) {
	rows, err := q.db.Query(ctx, listBarang, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBarangRow
	for rows.Next() {
		var i ListBarangRow
		if err := rows.Scan(
			&i.IDBarang,
			&i.NamaBarang,
			&i.Kode,
			&i.IDJenisBarang,
			&i.IDMitra,
			&i.CreatedAt,
			&i.NamaPerusahaan,
			&i.NamaJenisBarang,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBarang = `-- name: UpdateBarang :one
UPDATE BARANG
SET nama_barang = $2, kode = $3, id_jenis_barang = $4, id_mitra = $5
WHERE id_barang = $1
RETURNING id_barang, nama_barang, kode, id_jenis_barang, id_mitra, created_at
`

type UpdateBarangParams struct {
	IDBarang      int32  `json:"id_barang"`
	NamaBarang    string `json:"nama_barang"`
	Kode          string `json:"kode"`
	IDJenisBarang int32  `json:"id_jenis_barang"`
	IDMitra       int32  `json:"id_mitra"`
}

func (q *Queries) UpdateBarang(ctx context.Context, arg UpdateBarangParams) (Barang, error) {
	row := q.db.QueryRow(ctx, updateBarang,
		arg.IDBarang,
		arg.NamaBarang,
		arg.Kode,
		arg.IDJenisBarang,
		arg.IDMitra,
	)
	var i Barang
	err := row.Scan(
		&i.IDBarang,
		&i.NamaBarang,
		&i.Kode,
		&i.IDJenisBarang,
		&i.IDMitra,
		&i.CreatedAt,
	)
	return i, err
}
