// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: barang.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBarang = `-- name: CountBarang :one
SELECT COUNT(*)
FROM BARANG b
JOIN MITRA m ON b.id_mitra = m.id_mitra
JOIN JENIS_BARANG j ON b.id_jenis_barang = j.id_jenis_barang
WHERE (
    $1::text = '' OR
    b.nama_barang ILIKE '%' || $1::text || '%' OR
    b.kode ILIKE '%' || $1::text || '%' OR
    j.nama_jenis_barang ILIKE '%' || $1::text || '%' OR
    m.nama_perusahaan ILIKE '%' || $1::text || '%' OR
    b.satuan ILIKE '%' || $1::text || '%' OR
    b.lokasi_rak ILIKE '%' || $1::text || '%'
)
`

func (q *Queries) CountBarang(ctx context.Context, searchTerm string) (int64, error) {
	row := q.db.QueryRow(ctx, countBarang, searchTerm)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBarang = `-- name: CreateBarang :one
INSERT INTO BARANG (
    nama_barang, kode, id_jenis_barang, id_mitra, satuan, lokasi_rak, stok_minimum
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id_barang, nama_barang, kode, id_jenis_barang, id_mitra, created_at, satuan, lokasi_rak, stok_minimum
`

type CreateBarangParams struct {
	NamaBarang    string `json:"nama_barang"`
	Kode          string `json:"kode"`
	IDJenisBarang int32  `json:"id_jenis_barang"`
	IDMitra       int32  `json:"id_mitra"`
	Satuan        string `json:"satuan"`
	LokasiRak     string `json:"lokasi_rak"`
	StokMinimum   int32  `json:"stok_minimum"`
}

func (q *Queries) CreateBarang(ctx context.Context, arg CreateBarangParams) (Barang, error) {
	row := q.db.QueryRow(ctx, createBarang,
		arg.NamaBarang,
		arg.Kode,
		arg.IDJenisBarang,
		arg.IDMitra,
		arg.Satuan,
		arg.LokasiRak,
		arg.StokMinimum,
	)
	var i Barang
	err := row.Scan(
		&i.IDBarang,
		&i.NamaBarang,
		&i.Kode,
		&i.IDJenisBarang,
		&i.IDMitra,
		&i.CreatedAt,
		&i.Satuan,
		&i.LokasiRak,
		&i.StokMinimum,
	)
	return i, err
}

const deleteBarang = `-- name: DeleteBarang :execrows
DELETE FROM BARANG
WHERE id_barang = $1
`

func (q *Queries) DeleteBarang(ctx context.Context, idBarang int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBarang, idBarang)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBarangByID = `-- name: GetBarangByID :one
SELECT b.id_barang, b.nama_barang, b.kode, b.id_jenis_barang, b.id_mitra, b.created_at, b.satuan, b.lokasi_rak, b.stok_minimum, m.nama_perusahaan, j.nama_jenis_barang
FROM BARANG b
JOIN MITRA m ON b.id_mitra = m.id_mitra
JOIN JENIS_BARANG j ON b.id_jenis_barang = j.id_jenis_barang
WHERE b.id_barang = $1 LIMIT 1
`

type GetBarangByIDRow struct {
	IDBarang        int32              `json:"id_barang"`
	NamaBarang      string             `json:"nama_barang"`
	Kode            string             `json:"kode"`
	IDJenisBarang   int32              `json:"id_jenis_barang"`
	IDMitra         int32              `json:"id_mitra"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Satuan          string             `json:"satuan"`
	LokasiRak       string             `json:"lokasi_rak"`
	StokMinimum     int32              `json:"stok_minimum"`
	NamaPerusahaan  string             `json:"nama_perusahaan"`
	NamaJenisBarang string             `json:"nama_jenis_barang"`
}

func (q *Queries) GetBarangByID(ctx context.Context, idBarang int32) (GetBarangByIDRow, error) {
	row := q.db.QueryRow(ctx, getBarangByID, idBarang)
	var i GetBarangByIDRow
	err := row.Scan(
		&i.IDBarang,
		&i.NamaBarang,
		&i.Kode,
		&i.IDJenisBarang,
		&i.IDMitra,
		&i.CreatedAt,
		&i.Satuan,
		&i.LokasiRak,
		&i.StokMinimum,
		&i.NamaPerusahaan,
		&i.NamaJenisBarang,
	)
	return i, err
}

const listBarang = `-- name: ListBarang :many
SELECT b.id_barang, b.nama_barang, b.kode, b.id_jenis_barang, b.id_mitra, b.created_at, b.satuan, b.lokasi_rak, b.stok_minimum, m.nama_perusahaan, j.nama_jenis_barang
FROM BARANG b
JOIN MITRA m ON b.id_mitra = m.id_mitra
JOIN JENIS_BARANG j ON b.id_jenis_barang = j.id_jenis_barang
WHERE (
    $1::text = '' OR
    b.nama_barang ILIKE '%' || $1::text || '%' OR
    b.kode ILIKE '%' || $1::text || '%' OR
    j.nama_jenis_barang ILIKE '%' || $1::text || '%' OR
    m.nama_perusahaan ILIKE '%' || $1::text || '%' OR
    b.satuan ILIKE '%' || $1::text || '%' OR
    b.lokasi_rak ILIKE '%' || $1::text || '%'
)
ORDER BY
    CASE WHEN $2::text = 'created_at' AND NOT $3::bool THEN b.created_at END ASC,
    CASE WHEN $2::text = 'created_at' AND $3::bool THEN b.created_at END DESC,
    CASE WHEN $2::text = 'id_barang' AND NOT $3::bool THEN b.id_barang END ASC,
    CASE WHEN $2::text = 'id_barang' AND $3::bool THEN b.id_barang END DESC,
    CASE WHEN $2::text = 'kode' AND NOT $3::bool THEN b.kode END ASC,
    CASE WHEN $2::text = 'kode' AND $3::bool THEN b.kode END DESC,
    CASE WHEN $2::text = 'nama_barang' AND NOT $3::bool THEN b.nama_barang END ASC,
    CASE WHEN $2::text = 'nama_barang' AND $3::bool THEN b.nama_barang END DESC,
    CASE WHEN $2::text = 'nama_jenis_barang' AND NOT $3::bool THEN j.nama_jenis_barang END ASC,
    CASE WHEN $2::text = 'nama_jenis_barang' AND $3::bool THEN j.nama_jenis_barang END DESC,
    CASE WHEN $2::text = 'nama_perusahaan' AND NOT $3::bool THEN m.nama_perusahaan END ASC,
    CASE WHEN $2::text = 'nama_perusahaan' AND $3::bool THEN m.nama_perusahaan END DESC,
    b.created_at DESC,
    b.id_barang DESC
LIMIT $5 OFFSET $4
`

type ListBarangParams struct {
	SearchTerm string `json:"search_term"`
	SortBy     string `json:"sort_by"`
	SortDesc   bool   `json:"sort_desc"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type ListBarangRow struct {
	IDBarang        int32              `json:"id_barang"`
	NamaBarang      string             `json:"nama_barang"`
	Kode            string             `json:"kode"`
	IDJenisBarang   int32              `json:"id_jenis_barang"`
	IDMitra         int32              `json:"id_mitra"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Satuan          string             `json:"satuan"`
	LokasiRak       string             `json:"lokasi_rak"`
	StokMinimum     int32              `json:"stok_minimum"`
	NamaPerusahaan  string             `json:"nama_perusahaan"`
	NamaJenisBarang string             `json:"nama_jenis_barang"`
}

func (q *Queries) ListBarang(ctx context.Context, arg ListBarangParams) ([]ListBarangRow, error) {
	rows, err := q.db.Query(ctx, listBarang,
		arg.SearchTerm,
		arg.SortBy,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBarangRow
	for rows.Next() {
		var i ListBarangRow
		if err := rows.Scan(
			&i.IDBarang,
			&i.NamaBarang,
			&i.Kode,
			&i.IDJenisBarang,
			&i.IDMitra,
			&i.CreatedAt,
			&i.Satuan,
			&i.LokasiRak,
			&i.StokMinimum,
			&i.NamaPerusahaan,
			&i.NamaJenisBarang,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBarang = `-- name: UpdateBarang :one
UPDATE BARANG
SET nama_barang = $2, kode = $3, id_jenis_barang = $4, id_mitra = $5, satuan = $6, lokasi_rak = $7, stok_minimum = $8
WHERE id_barang = $1
RETURNING id_barang, nama_barang, kode, id_jenis_barang, id_mitra, created_at, satuan, lokasi_rak, stok_minimum
`

type UpdateBarangParams struct {
	IDBarang      int32  `json:"id_barang"`
	NamaBarang    string `json:"nama_barang"`
	Kode          string `json:"kode"`
	IDJenisBarang int32  `json:"id_jenis_barang"`
	IDMitra       int32  `json:"id_mitra"`
	Satuan        string `json:"satuan"`
	LokasiRak     string `json:"lokasi_rak"`
	StokMinimum   int32  `json:"stok_minimum"`
}

func (q *Queries) UpdateBarang(ctx context.Context, arg UpdateBarangParams) (Barang, error) {
	row := q.db.QueryRow(ctx, updateBarang,
		arg.IDBarang,
		arg.NamaBarang,
		arg.Kode,
		arg.IDJenisBarang,
		arg.IDMitra,
		arg.Satuan,
		arg.LokasiRak,
		arg.StokMinimum,
	)
	var i Barang
	err := row.Scan(
		&i.IDBarang,
		&i.NamaBarang,
		&i.Kode,
		&i.IDJenisBarang,
		&i.IDMitra,
		&i.CreatedAt,
		&i.Satuan,
		&i.LokasiRak,
		&i.StokMinimum,
	)
	return i, err
}
