// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company.sql

package entity

import (
	"context"
)

const getCompany = `-- name: GetCompany :one
SELECT id_company, nama, alamat, email, no_telp, about, logo, created_at FROM COMPANY
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetCompany(ctx context.Context) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany)
	var i Company
	err := row.Scan(
		&i.IDCompany,
		&i.Nama,
		&i.Alamat,
		&i.Email,
		&i.NoTelp,
		&i.About,
		&i.Logo,
		&i.CreatedAt,
	)
	return i, err
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE COMPANY
SET nama = $2, alamat = $3, email = $4, no_telp = $5, about = $6, logo = $7
WHERE id_company = $1
RETURNING id_company, nama, alamat, email, no_telp, about, logo, created_at
`

type UpdateCompanyParams struct {
	IDCompany int32  `json:"id_company"`
	Nama      string `json:"nama"`
	Alamat    string `json:"alamat"`
	Email     string `json:"email"`
	NoTelp    string `json:"no_telp"`
	About     string `json:"about"`
	Logo      string `json:"logo"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.IDCompany,
		arg.Nama,
		arg.Alamat,
		arg.Email,
		arg.NoTelp,
		arg.About,
		arg.Logo,
	)
	var i Company
	err := row.Scan(
		&i.IDCompany,
		&i.Nama,
		&i.Alamat,
		&i.Email,
		&i.NoTelp,
		&i.About,
		&i.Logo,
		&i.CreatedAt,
	)
	return i, err
}
