// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard_production.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProductionRecentMarkerPlans = `-- name: GetProductionRecentMarkerPlans :many
SELECT 
    mp.id_marker_plan,
    mp.no_dokumen,
    mp.tanggal_efektif,
    wos.color,
    wo.model
FROM MARKER_PLAN mp
JOIN WORK_ORDER_SHELL wos ON mp.id_wo_shell = wos.id_wo_shell
JOIN WORK_ORDER wo ON wos.id_wo = wo.id_wo
ORDER BY mp.created_at DESC
LIMIT 5
`

type GetProductionRecentMarkerPlansRow struct {
	IDMarkerPlan   int32       `json:"id_marker_plan"`
	NoDokumen      string      `json:"no_dokumen"`
	TanggalEfektif pgtype.Date `json:"tanggal_efektif"`
	Color          string      `json:"color"`
	Model          string      `json:"model"`
}

func (q *Queries) GetProductionRecentMarkerPlans(ctx context.Context) ([]GetProductionRecentMarkerPlansRow, error) {
	rows, err := q.db.Query(ctx, getProductionRecentMarkerPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductionRecentMarkerPlansRow
	for rows.Next() {
		var i GetProductionRecentMarkerPlansRow
		if err := rows.Scan(
			&i.IDMarkerPlan,
			&i.NoDokumen,
			&i.TanggalEfektif,
			&i.Color,
			&i.Model,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductionRecentSpreadingCuttingPlans = `-- name: GetProductionRecentSpreadingCuttingPlans :many
SELECT 
    scp.id_spreading_cutting_plan,
    scp.no_dokumen,
    scp.tanggal_efektif,
    wo.model
FROM SPREADING_CUTTING_PLAN scp
JOIN WORK_ORDER wo ON scp.id_wo = wo.id_wo
ORDER BY scp.created_at DESC
LIMIT 5
`

type GetProductionRecentSpreadingCuttingPlansRow struct {
	IDSpreadingCuttingPlan int32       `json:"id_spreading_cutting_plan"`
	NoDokumen              string      `json:"no_dokumen"`
	TanggalEfektif         pgtype.Date `json:"tanggal_efektif"`
	Model                  string      `json:"model"`
}

func (q *Queries) GetProductionRecentSpreadingCuttingPlans(ctx context.Context) ([]GetProductionRecentSpreadingCuttingPlansRow, error) {
	rows, err := q.db.Query(ctx, getProductionRecentSpreadingCuttingPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductionRecentSpreadingCuttingPlansRow
	for rows.Next() {
		var i GetProductionRecentSpreadingCuttingPlansRow
		if err := rows.Scan(
			&i.IDSpreadingCuttingPlan,
			&i.NoDokumen,
			&i.TanggalEfektif,
			&i.Model,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductionRecentTimelines = `-- name: GetProductionRecentTimelines :many
SELECT 
    tl.id_timeline,
    tl.tanggal_disusun,
    tl.notes,
    pc.po_number
FROM TIMELINE_PLAN_PRODUKSI tl
JOIN PO_CLIENT pc ON tl.id_po_client = pc.id_po_client
ORDER BY tl.created_at DESC
LIMIT 5
`

type GetProductionRecentTimelinesRow struct {
	IDTimeline     int32       `json:"id_timeline"`
	TanggalDisusun pgtype.Date `json:"tanggal_disusun"`
	Notes          string      `json:"notes"`
	PoNumber       string      `json:"po_number"`
}

func (q *Queries) GetProductionRecentTimelines(ctx context.Context) ([]GetProductionRecentTimelinesRow, error) {
	rows, err := q.db.Query(ctx, getProductionRecentTimelines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductionRecentTimelinesRow
	for rows.Next() {
		var i GetProductionRecentTimelinesRow
		if err := rows.Scan(
			&i.IDTimeline,
			&i.TanggalDisusun,
			&i.Notes,
			&i.PoNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductionTotalMarkerPlanThisMonth = `-- name: GetProductionTotalMarkerPlanThisMonth :one
SELECT COUNT(*) FROM MARKER_PLAN 
WHERE EXTRACT(MONTH FROM tanggal_efektif) = EXTRACT(MONTH FROM CURRENT_DATE) 
  AND EXTRACT(YEAR FROM tanggal_efektif) = EXTRACT(YEAR FROM CURRENT_DATE)
`

func (q *Queries) GetProductionTotalMarkerPlanThisMonth(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getProductionTotalMarkerPlanThisMonth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProductionTotalSpreadingCuttingPlanThisMonth = `-- name: GetProductionTotalSpreadingCuttingPlanThisMonth :one
SELECT COUNT(*) FROM SPREADING_CUTTING_PLAN 
WHERE EXTRACT(MONTH FROM tanggal_efektif) = EXTRACT(MONTH FROM CURRENT_DATE) 
  AND EXTRACT(YEAR FROM tanggal_efektif) = EXTRACT(YEAR FROM CURRENT_DATE)
`

func (q *Queries) GetProductionTotalSpreadingCuttingPlanThisMonth(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getProductionTotalSpreadingCuttingPlanThisMonth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProductionTotalTimelineThisMonth = `-- name: GetProductionTotalTimelineThisMonth :one
SELECT COUNT(*) FROM TIMELINE_PLAN_PRODUKSI 
WHERE EXTRACT(MONTH FROM created_at) = EXTRACT(MONTH FROM CURRENT_DATE) 
  AND EXTRACT(YEAR FROM created_at) = EXTRACT(YEAR FROM CURRENT_DATE)
`

func (q *Queries) GetProductionTotalTimelineThisMonth(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getProductionTotalTimelineThisMonth)
	var count int64
	err := row.Scan(&count)
	return count, err
}
