// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard_warehouse.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWarehouseRecentBarang = `-- name: GetWarehouseRecentBarang :many
SELECT 
    id_barang,
    nama_barang,
    kode,
    stok_minimum,
    created_at
FROM BARANG
ORDER BY created_at DESC 
LIMIT 5
`

type GetWarehouseRecentBarangRow struct {
	IDBarang    int32              `json:"id_barang"`
	NamaBarang  string             `json:"nama_barang"`
	Kode        string             `json:"kode"`
	StokMinimum int32              `json:"stok_minimum"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetWarehouseRecentBarang(ctx context.Context) ([]GetWarehouseRecentBarangRow, error) {
	rows, err := q.db.Query(ctx, getWarehouseRecentBarang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWarehouseRecentBarangRow
	for rows.Next() {
		var i GetWarehouseRecentBarangRow
		if err := rows.Scan(
			&i.IDBarang,
			&i.NamaBarang,
			&i.Kode,
			&i.StokMinimum,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWarehouseRecentSuratJalanClient = `-- name: GetWarehouseRecentSuratJalanClient :many
SELECT 
    sjc.id_surat_jalan_client,
    sjc.tanggal,
    sjc.keterangan,
    mli.description AS material_description
FROM SURAT_JALAN_CLIENT sjc
JOIN MATERIAL_LIST_ITEM mli ON sjc.id_material_list_item = mli.id_material_list_item
ORDER BY sjc.created_at DESC 
LIMIT 5
`

type GetWarehouseRecentSuratJalanClientRow struct {
	IDSuratJalanClient  int32       `json:"id_surat_jalan_client"`
	Tanggal             pgtype.Date `json:"tanggal"`
	Keterangan          string      `json:"keterangan"`
	MaterialDescription string      `json:"material_description"`
}

func (q *Queries) GetWarehouseRecentSuratJalanClient(ctx context.Context) ([]GetWarehouseRecentSuratJalanClientRow, error) {
	rows, err := q.db.Query(ctx, getWarehouseRecentSuratJalanClient)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWarehouseRecentSuratJalanClientRow
	for rows.Next() {
		var i GetWarehouseRecentSuratJalanClientRow
		if err := rows.Scan(
			&i.IDSuratJalanClient,
			&i.Tanggal,
			&i.Keterangan,
			&i.MaterialDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWarehouseRecentSuratJalanInternal = `-- name: GetWarehouseRecentSuratJalanInternal :many
SELECT 
    sji.id_surat_jalan_internal,
    sji.created_at
FROM SURAT_JALAN_INTERNAL sji
ORDER BY sji.created_at DESC 
LIMIT 5
`

func (q *Queries) GetWarehouseRecentSuratJalanInternal(ctx context.Context) ([]SuratJalanInternal, error) {
	rows, err := q.db.Query(ctx, getWarehouseRecentSuratJalanInternal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuratJalanInternal
	for rows.Next() {
		var i SuratJalanInternal
		if err := rows.Scan(&i.IDSuratJalanInternal, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWarehouseTotalItems = `-- name: GetWarehouseTotalItems :one
SELECT COUNT(*) FROM BARANG
`

func (q *Queries) GetWarehouseTotalItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getWarehouseTotalItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWarehouseTotalSuratJalanClientThisMonth = `-- name: GetWarehouseTotalSuratJalanClientThisMonth :one
SELECT COUNT(*) 
FROM SURAT_JALAN_CLIENT 
WHERE date_trunc('month', created_at) = date_trunc('month', CURRENT_DATE)
`

func (q *Queries) GetWarehouseTotalSuratJalanClientThisMonth(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getWarehouseTotalSuratJalanClientThisMonth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWarehouseTotalSuratJalanInternalThisMonth = `-- name: GetWarehouseTotalSuratJalanInternalThisMonth :one
SELECT COUNT(*) 
FROM SURAT_JALAN_INTERNAL 
WHERE date_trunc('month', created_at) = date_trunc('month', CURRENT_DATE)
`

func (q *Queries) GetWarehouseTotalSuratJalanInternalThisMonth(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getWarehouseTotalSuratJalanInternalThisMonth)
	var count int64
	err := row.Scan(&count)
	return count, err
}
