// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard_manager.sql

package entity

import (
	"context"
)

const getTotalUsersCount = `-- name: GetTotalUsersCount :one
SELECT COUNT(*) FROM USERS
`

func (q *Queries) GetTotalUsersCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalUsersCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
