// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: departemen.sql

package entity

import (
	"context"
)

const createDepartemen = `-- name: CreateDepartemen :one
INSERT INTO DEPARTEMEN (nama_departemen)
VALUES ($1)
RETURNING id_departemen, nama_departemen, created_at
`

func (q *Queries) CreateDepartemen(ctx context.Context, namaDepartemen string) (Departeman, error) {
	row := q.db.QueryRow(ctx, createDepartemen, namaDepartemen)
	var i Departeman
	err := row.Scan(&i.IDDepartemen, &i.NamaDepartemen, &i.CreatedAt)
	return i, err
}

const deleteDepartemen = `-- name: DeleteDepartemen :execrows
DELETE FROM DEPARTEMEN
WHERE id_departemen = $1
`

func (q *Queries) DeleteDepartemen(ctx context.Context, idDepartemen int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDepartemen, idDepartemen)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDepartemenByID = `-- name: GetDepartemenByID :one
SELECT id_departemen, nama_departemen, created_at FROM DEPARTEMEN
WHERE id_departemen = $1 LIMIT 1
`

func (q *Queries) GetDepartemenByID(ctx context.Context, idDepartemen int32) (Departeman, error) {
	row := q.db.QueryRow(ctx, getDepartemenByID, idDepartemen)
	var i Departeman
	err := row.Scan(&i.IDDepartemen, &i.NamaDepartemen, &i.CreatedAt)
	return i, err
}

const listDepartemen = `-- name: ListDepartemen :many
SELECT id_departemen, nama_departemen, created_at FROM DEPARTEMEN
ORDER BY nama_departemen ASC
`

func (q *Queries) ListDepartemen(ctx context.Context) ([]Departeman, error) {
	rows, err := q.db.Query(ctx, listDepartemen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Departeman
	for rows.Next() {
		var i Departeman
		if err := rows.Scan(&i.IDDepartemen, &i.NamaDepartemen, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartemen = `-- name: UpdateDepartemen :one
UPDATE DEPARTEMEN
SET nama_departemen = $2
WHERE id_departemen = $1
RETURNING id_departemen, nama_departemen, created_at
`

type UpdateDepartemenParams struct {
	IDDepartemen   int32  `json:"id_departemen"`
	NamaDepartemen string `json:"nama_departemen"`
}

func (q *Queries) UpdateDepartemen(ctx context.Context, arg UpdateDepartemenParams) (Departeman, error) {
	row := q.db.QueryRow(ctx, updateDepartemen, arg.IDDepartemen, arg.NamaDepartemen)
	var i Departeman
	err := row.Scan(&i.IDDepartemen, &i.NamaDepartemen, &i.CreatedAt)
	return i, err
}
