// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_status.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvePRInternal = `-- name: ApprovePRInternal :one
UPDATE PR_INTERNAL
SET
    status = 'approved',
    approved_by_user_id = $1,
    approved_at = NOW()
WHERE id_pr_internal = $2
RETURNING id_pr_internal, status, approved_by_user_id, approved_at
`

type ApprovePRInternalParams struct {
	ApprovedByUserID pgtype.Int4 `json:"approved_by_user_id"`
	IDPrInternal     int32       `json:"id_pr_internal"`
}

type ApprovePRInternalRow struct {
	IDPrInternal     int32              `json:"id_pr_internal"`
	Status           string             `json:"status"`
	ApprovedByUserID pgtype.Int4        `json:"approved_by_user_id"`
	ApprovedAt       pgtype.Timestamptz `json:"approved_at"`
}

func (q *Queries) ApprovePRInternal(ctx context.Context, arg ApprovePRInternalParams) (ApprovePRInternalRow, error) {
	row := q.db.QueryRow(ctx, approvePRInternal, arg.ApprovedByUserID, arg.IDPrInternal)
	var i ApprovePRInternalRow
	err := row.Scan(
		&i.IDPrInternal,
		&i.Status,
		&i.ApprovedByUserID,
		&i.ApprovedAt,
	)
	return i, err
}

const closeWorkOrder = `-- name: CloseWorkOrder :one
UPDATE WORK_ORDER
SET
    status = 'closed',
    closed_by_user_id = $1,
    closed_at = NOW()
WHERE id_wo = $2
RETURNING id_wo, status, closed_by_user_id, closed_at
`

type CloseWorkOrderParams struct {
	ClosedByUserID pgtype.Int4 `json:"closed_by_user_id"`
	IDWo           int32       `json:"id_wo"`
}

type CloseWorkOrderRow struct {
	IDWo           int32              `json:"id_wo"`
	Status         string             `json:"status"`
	ClosedByUserID pgtype.Int4        `json:"closed_by_user_id"`
	ClosedAt       pgtype.Timestamptz `json:"closed_at"`
}

func (q *Queries) CloseWorkOrder(ctx context.Context, arg CloseWorkOrderParams) (CloseWorkOrderRow, error) {
	row := q.db.QueryRow(ctx, closeWorkOrder, arg.ClosedByUserID, arg.IDWo)
	var i CloseWorkOrderRow
	err := row.Scan(
		&i.IDWo,
		&i.Status,
		&i.ClosedByUserID,
		&i.ClosedAt,
	)
	return i, err
}
