// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: document_status.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvePRInternal = `-- name: ApprovePRInternal :one
INSERT INTO OTORITAS_DOKUMEN (NAMA_TABEL_DOKUMEN, ID_DOKUMEN, STATUS_GLOBAL)
VALUES ('PR_INTERNAL', $1, 'approved')
ON CONFLICT (NAMA_TABEL_DOKUMEN, ID_DOKUMEN)
DO UPDATE SET STATUS_GLOBAL = 'approved'
WHERE ($2 IS NULL OR TRUE)
RETURNING ID_DOKUMEN AS id_pr_internal, STATUS_GLOBAL AS status, NULL::integer AS approved_by_user_id, NULL::timestamptz AS approved_at
`

type ApprovePRInternalParams struct {
	IDPrInternal     int32       `json:"id_pr_internal"`
	ApprovedByUserID interface{} `json:"approved_by_user_id"`
}

type ApprovePRInternalRow struct {
	IDPrInternal     int32              `json:"id_pr_internal"`
	Status           string             `json:"status"`
	ApprovedByUserID pgtype.Int4        `json:"approved_by_user_id"`
	ApprovedAt       pgtype.Timestamptz `json:"approved_at"`
}

func (q *Queries) ApprovePRInternal(ctx context.Context, arg ApprovePRInternalParams) (ApprovePRInternalRow, error) {
	row := q.db.QueryRow(ctx, approvePRInternal, arg.IDPrInternal, arg.ApprovedByUserID)
	var i ApprovePRInternalRow
	err := row.Scan(
		&i.IDPrInternal,
		&i.Status,
		&i.ApprovedByUserID,
		&i.ApprovedAt,
	)
	return i, err
}

const closeWorkOrder = `-- name: CloseWorkOrder :one
INSERT INTO OTORITAS_DOKUMEN (NAMA_TABEL_DOKUMEN, ID_DOKUMEN, STATUS_GLOBAL)
VALUES ('WORK_ORDER', $1, 'closed')
ON CONFLICT (NAMA_TABEL_DOKUMEN, ID_DOKUMEN)
DO UPDATE SET STATUS_GLOBAL = 'closed'
WHERE ($2 IS NULL OR TRUE)
RETURNING ID_DOKUMEN AS id_wo, STATUS_GLOBAL AS status, NULL::integer AS closed_by_user_id, NULL::timestamptz AS closed_at
`

type CloseWorkOrderParams struct {
	IDWo           int32       `json:"id_wo"`
	ClosedByUserID interface{} `json:"closed_by_user_id"`
}

type CloseWorkOrderRow struct {
	IDWo           int32              `json:"id_wo"`
	Status         string             `json:"status"`
	ClosedByUserID pgtype.Int4        `json:"closed_by_user_id"`
	ClosedAt       pgtype.Timestamptz `json:"closed_at"`
}

func (q *Queries) CloseWorkOrder(ctx context.Context, arg CloseWorkOrderParams) (CloseWorkOrderRow, error) {
	row := q.db.QueryRow(ctx, closeWorkOrder, arg.IDWo, arg.ClosedByUserID)
	var i CloseWorkOrderRow
	err := row.Scan(
		&i.IDWo,
		&i.Status,
		&i.ClosedByUserID,
		&i.ClosedAt,
	)
	return i, err
}
