// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hak_akses.sql

package entity

import (
	"context"
)

const listHakAkses = `-- name: ListHakAkses :many
SELECT id_hak_akses, nama_halaman, created_at FROM HAK_AKSES
ORDER BY nama_halaman ASC
`

func (q *Queries) ListHakAkses(ctx context.Context) ([]HakAkse, error) {
	rows, err := q.db.Query(ctx, listHakAkses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HakAkse
	for rows.Next() {
		var i HakAkse
		if err := rows.Scan(&i.IDHakAkses, &i.NamaHalaman, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
