// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: jenis_barang.sql

package entity

import (
	"context"
)

const countJenisBarang = `-- name: CountJenisBarang :one
SELECT COUNT(*)
FROM JENIS_BARANG
WHERE (
    $1::text = '' OR
    nama_jenis_barang ILIKE '%' || $1::text || '%' OR
    kode ILIKE '%' || $1::text || '%'
)
`

func (q *Queries) CountJenisBarang(ctx context.Context, searchTerm string) (int64, error) {
	row := q.db.QueryRow(ctx, countJenisBarang, searchTerm)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJenisBarang = `-- name: CreateJenisBarang :one
INSERT INTO JENIS_BARANG (nama_jenis_barang, kode)
VALUES ($1, $2)
RETURNING id_jenis_barang, nama_jenis_barang, kode, created_at
`

type CreateJenisBarangParams struct {
	NamaJenisBarang string `json:"nama_jenis_barang"`
	Kode            string `json:"kode"`
}

func (q *Queries) CreateJenisBarang(ctx context.Context, arg CreateJenisBarangParams) (JenisBarang, error) {
	row := q.db.QueryRow(ctx, createJenisBarang, arg.NamaJenisBarang, arg.Kode)
	var i JenisBarang
	err := row.Scan(
		&i.IDJenisBarang,
		&i.NamaJenisBarang,
		&i.Kode,
		&i.CreatedAt,
	)
	return i, err
}

const deleteJenisBarang = `-- name: DeleteJenisBarang :execrows
DELETE FROM JENIS_BARANG
WHERE id_jenis_barang = $1
`

func (q *Queries) DeleteJenisBarang(ctx context.Context, idJenisBarang int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteJenisBarang, idJenisBarang)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJenisBarangByID = `-- name: GetJenisBarangByID :one
SELECT id_jenis_barang, nama_jenis_barang, kode, created_at FROM JENIS_BARANG
WHERE id_jenis_barang = $1 LIMIT 1
`

func (q *Queries) GetJenisBarangByID(ctx context.Context, idJenisBarang int32) (JenisBarang, error) {
	row := q.db.QueryRow(ctx, getJenisBarangByID, idJenisBarang)
	var i JenisBarang
	err := row.Scan(
		&i.IDJenisBarang,
		&i.NamaJenisBarang,
		&i.Kode,
		&i.CreatedAt,
	)
	return i, err
}

const listJenisBarang = `-- name: ListJenisBarang :many
SELECT id_jenis_barang, nama_jenis_barang, kode, created_at
FROM JENIS_BARANG
WHERE (
    $1::text = '' OR
    nama_jenis_barang ILIKE '%' || $1::text || '%' OR
    kode ILIKE '%' || $1::text || '%'
)
ORDER BY
    CASE WHEN $2::text = 'created_at' AND NOT $3::bool THEN created_at END ASC,
    CASE WHEN $2::text = 'created_at' AND $3::bool THEN created_at END DESC,
    CASE WHEN $2::text = 'id_jenis_barang' AND NOT $3::bool THEN id_jenis_barang END ASC,
    CASE WHEN $2::text = 'id_jenis_barang' AND $3::bool THEN id_jenis_barang END DESC,
    CASE WHEN $2::text = 'kode' AND NOT $3::bool THEN kode END ASC,
    CASE WHEN $2::text = 'kode' AND $3::bool THEN kode END DESC,
    CASE WHEN $2::text = 'nama_jenis_barang' AND NOT $3::bool THEN nama_jenis_barang END ASC,
    CASE WHEN $2::text = 'nama_jenis_barang' AND $3::bool THEN nama_jenis_barang END DESC,
    nama_jenis_barang ASC,
    id_jenis_barang ASC
LIMIT $5 OFFSET $4
`

type ListJenisBarangParams struct {
	SearchTerm string `json:"search_term"`
	SortBy     string `json:"sort_by"`
	SortDesc   bool   `json:"sort_desc"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

func (q *Queries) ListJenisBarang(ctx context.Context, arg ListJenisBarangParams) ([]JenisBarang, error) {
	rows, err := q.db.Query(ctx, listJenisBarang,
		arg.SearchTerm,
		arg.SortBy,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JenisBarang
	for rows.Next() {
		var i JenisBarang
		if err := rows.Scan(
			&i.IDJenisBarang,
			&i.NamaJenisBarang,
			&i.Kode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJenisBarang = `-- name: UpdateJenisBarang :one
UPDATE JENIS_BARANG
SET nama_jenis_barang = $2, kode = $3
WHERE id_jenis_barang = $1
RETURNING id_jenis_barang, nama_jenis_barang, kode, created_at
`

type UpdateJenisBarangParams struct {
	IDJenisBarang   int32  `json:"id_jenis_barang"`
	NamaJenisBarang string `json:"nama_jenis_barang"`
	Kode            string `json:"kode"`
}

func (q *Queries) UpdateJenisBarang(ctx context.Context, arg UpdateJenisBarangParams) (JenisBarang, error) {
	row := q.db.QueryRow(ctx, updateJenisBarang, arg.IDJenisBarang, arg.NamaJenisBarang, arg.Kode)
	var i JenisBarang
	err := row.Scan(
		&i.IDJenisBarang,
		&i.NamaJenisBarang,
		&i.Kode,
		&i.CreatedAt,
	)
	return i, err
}
