// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: marker_plan.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKomponenMarkerPlan = `-- name: CreateKomponenMarkerPlan :one
INSERT INTO KOMPONEN_MARKER_PLAN (
    ID_MARKER_PLAN, NAMA_KOMPONEN
) VALUES (
    $1, $2
) RETURNING ID_KOMPONEN_MARKER, ID_MARKER_PLAN, NAMA_KOMPONEN, created_at
`

type CreateKomponenMarkerPlanParams struct {
	IDMarkerPlan int32  `json:"id_marker_plan"`
	NamaKomponen string `json:"nama_komponen"`
}

func (q *Queries) CreateKomponenMarkerPlan(ctx context.Context, arg CreateKomponenMarkerPlanParams) (KomponenMarkerPlan, error) {
	row := q.db.QueryRow(ctx, createKomponenMarkerPlan, arg.IDMarkerPlan, arg.NamaKomponen)
	var i KomponenMarkerPlan
	err := row.Scan(
		&i.IDKomponenMarker,
		&i.IDMarkerPlan,
		&i.NamaKomponen,
		&i.CreatedAt,
	)
	return i, err
}

const createMarkerPlan = `-- name: CreateMarkerPlan :one
INSERT INTO MARKER_PLAN (
    NO_DOKUMEN, TANGGAL_EFEKTIF, ID_WO_SHELL
) VALUES (
    $1, $2, $3
) RETURNING ID_MARKER_PLAN, NO_DOKUMEN, TANGGAL_EFEKTIF, ID_WO_SHELL, created_at
`

type CreateMarkerPlanParams struct {
	NoDokumen      string      `json:"no_dokumen"`
	TanggalEfektif pgtype.Date `json:"tanggal_efektif"`
	IDWoShell      int32       `json:"id_wo_shell"`
}

func (q *Queries) CreateMarkerPlan(ctx context.Context, arg CreateMarkerPlanParams) (MarkerPlan, error) {
	row := q.db.QueryRow(ctx, createMarkerPlan, arg.NoDokumen, arg.TanggalEfektif, arg.IDWoShell)
	var i MarkerPlan
	err := row.Scan(
		&i.IDMarkerPlan,
		&i.NoDokumen,
		&i.TanggalEfektif,
		&i.IDWoShell,
		&i.CreatedAt,
	)
	return i, err
}

const createRatioMarker = `-- name: CreateRatioMarker :one
INSERT INTO RATIO_MARKER (
    ID_KOMPONEN_MARKER, ID_WO_SHELL, CONS, PLAN_SPREADING_GELARAN,
    PANJANG_MARKER, EFFICIENCY_MARKER, ALLOWANCE, CONS_BUYER,
    ROLL_QTY, SAMBUNGAN_ROLL, PLOT, LEBAR_KAIN, PANJANG_MARKER_UNIT, KET
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING ID_RATIO_MARKER, ID_KOMPONEN_MARKER, ID_WO_SHELL, CONS, PLAN_SPREADING_GELARAN, PANJANG_MARKER, EFFICIENCY_MARKER, ALLOWANCE, CONS_BUYER, ROLL_QTY, SAMBUNGAN_ROLL, PLOT, LEBAR_KAIN, PANJANG_MARKER_UNIT, KET, created_at
`

type CreateRatioMarkerParams struct {
	IDKomponenMarker     int32          `json:"id_komponen_marker"`
	IDWoShell            int32          `json:"id_wo_shell"`
	Cons                 pgtype.Numeric `json:"cons"`
	PlanSpreadingGelaran pgtype.Numeric `json:"plan_spreading_gelaran"`
	PanjangMarker        pgtype.Numeric `json:"panjang_marker"`
	EfficiencyMarker     pgtype.Numeric `json:"efficiency_marker"`
	Allowance            pgtype.Numeric `json:"allowance"`
	ConsBuyer            pgtype.Numeric `json:"cons_buyer"`
	RollQty              int32          `json:"roll_qty"`
	SambunganRoll        int32          `json:"sambungan_roll"`
	Plot                 int32          `json:"plot"`
	LebarKain            pgtype.Numeric `json:"lebar_kain"`
	PanjangMarkerUnit    string         `json:"panjang_marker_unit"`
	Ket                  string         `json:"ket"`
}

type CreateRatioMarkerRow struct {
	IDRatioMarker        int32              `json:"id_ratio_marker"`
	IDKomponenMarker     int32              `json:"id_komponen_marker"`
	IDWoShell            int32              `json:"id_wo_shell"`
	Cons                 pgtype.Numeric     `json:"cons"`
	PlanSpreadingGelaran pgtype.Numeric     `json:"plan_spreading_gelaran"`
	PanjangMarker        pgtype.Numeric     `json:"panjang_marker"`
	EfficiencyMarker     pgtype.Numeric     `json:"efficiency_marker"`
	Allowance            pgtype.Numeric     `json:"allowance"`
	ConsBuyer            pgtype.Numeric     `json:"cons_buyer"`
	RollQty              int32              `json:"roll_qty"`
	SambunganRoll        int32              `json:"sambungan_roll"`
	Plot                 int32              `json:"plot"`
	LebarKain            pgtype.Numeric     `json:"lebar_kain"`
	PanjangMarkerUnit    string             `json:"panjang_marker_unit"`
	Ket                  string             `json:"ket"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateRatioMarker(ctx context.Context, arg CreateRatioMarkerParams) (CreateRatioMarkerRow, error) {
	row := q.db.QueryRow(ctx, createRatioMarker,
		arg.IDKomponenMarker,
		arg.IDWoShell,
		arg.Cons,
		arg.PlanSpreadingGelaran,
		arg.PanjangMarker,
		arg.EfficiencyMarker,
		arg.Allowance,
		arg.ConsBuyer,
		arg.RollQty,
		arg.SambunganRoll,
		arg.Plot,
		arg.LebarKain,
		arg.PanjangMarkerUnit,
		arg.Ket,
	)
	var i CreateRatioMarkerRow
	err := row.Scan(
		&i.IDRatioMarker,
		&i.IDKomponenMarker,
		&i.IDWoShell,
		&i.Cons,
		&i.PlanSpreadingGelaran,
		&i.PanjangMarker,
		&i.EfficiencyMarker,
		&i.Allowance,
		&i.ConsBuyer,
		&i.RollQty,
		&i.SambunganRoll,
		&i.Plot,
		&i.LebarKain,
		&i.PanjangMarkerUnit,
		&i.Ket,
		&i.CreatedAt,
	)
	return i, err
}

type CreateRatioSizeMarkerParams struct {
	IDRatioMarker int32 `json:"id_ratio_marker"`
	IDWoShellSize int32 `json:"id_wo_shell_size"`
	RatioPlan     int32 `json:"ratio_plan"`
}

const getMarkerPlanByID = `-- name: GetMarkerPlanByID :one
SELECT ID_MARKER_PLAN, NO_DOKUMEN, TANGGAL_EFEKTIF, ID_WO_SHELL, created_at
FROM MARKER_PLAN
WHERE ID_MARKER_PLAN = $1 LIMIT 1
`

func (q *Queries) GetMarkerPlanByID(ctx context.Context, idMarkerPlan int32) (MarkerPlan, error) {
	row := q.db.QueryRow(ctx, getMarkerPlanByID, idMarkerPlan)
	var i MarkerPlan
	err := row.Scan(
		&i.IDMarkerPlan,
		&i.NoDokumen,
		&i.TanggalEfektif,
		&i.IDWoShell,
		&i.CreatedAt,
	)
	return i, err
}

const listKomponenByMarkerPlanID = `-- name: ListKomponenByMarkerPlanID :many
SELECT ID_KOMPONEN_MARKER, ID_MARKER_PLAN, NAMA_KOMPONEN, created_at
FROM KOMPONEN_MARKER_PLAN
WHERE ID_MARKER_PLAN = $1
ORDER BY ID_KOMPONEN_MARKER ASC
`

func (q *Queries) ListKomponenByMarkerPlanID(ctx context.Context, idMarkerPlan int32) ([]KomponenMarkerPlan, error) {
	rows, err := q.db.Query(ctx, listKomponenByMarkerPlanID, idMarkerPlan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KomponenMarkerPlan
	for rows.Next() {
		var i KomponenMarkerPlan
		if err := rows.Scan(
			&i.IDKomponenMarker,
			&i.IDMarkerPlan,
			&i.NamaKomponen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarkerPlans = `-- name: ListMarkerPlans :many
SELECT
    mp.id_marker_plan,
    mp.no_dokumen,
    mp.tanggal_efektif,
    mp.id_wo_shell,
    mp.created_at,
    wos.fabric,
    wos.color,
    wo.id_wo,
    wo.buyer,
    wo.model,
    COUNT(*) OVER() AS total_count
FROM MARKER_PLAN mp
JOIN WORK_ORDER_SHELL wos ON mp.id_wo_shell = wos.id_wo_shell
JOIN WORK_ORDER wo ON wos.id_wo = wo.id_wo
JOIN PO_CLIENT_ITEM pci ON pci.id_po_client_item = wo.id_po_client_item
JOIN PO_CLIENT pc ON pc.id_po_client = pci.id_po_client
WHERE (
    $1 = '' OR
    mp.no_dokumen ILIKE '%' || $1 || '%' OR
    wo.buyer ILIKE '%' || $1 || '%' OR
    wo.model ILIKE '%' || $1 || '%' OR
    wos.fabric ILIKE '%' || $1 || '%'
) AND (
    $2::integer IS NULL OR
    pc.id_mitra = $2::integer
)
ORDER BY
    CASE WHEN $3::text = 'created_at' AND NOT $4::bool THEN mp.created_at END ASC,
    CASE WHEN $3::text = 'created_at' AND $4::bool THEN mp.created_at END DESC,
    CASE WHEN $3::text = 'no_dokumen' AND NOT $4::bool THEN mp.no_dokumen END ASC,
    CASE WHEN $3::text = 'no_dokumen' AND $4::bool THEN mp.no_dokumen END DESC,
    CASE WHEN $3::text = 'tanggal_efektif' AND NOT $4::bool THEN mp.tanggal_efektif END ASC,
    CASE WHEN $3::text = 'tanggal_efektif' AND $4::bool THEN mp.tanggal_efektif END DESC,
    CASE WHEN $3::text = 'model' AND NOT $4::bool THEN wo.model END ASC,
    CASE WHEN $3::text = 'model' AND $4::bool THEN wo.model END DESC,
    CASE WHEN $3::text = 'buyer' AND NOT $4::bool THEN wo.buyer END ASC,
    CASE WHEN $3::text = 'buyer' AND $4::bool THEN wo.buyer END DESC,
    mp.id_marker_plan DESC
LIMIT $6 OFFSET $5
`

type ListMarkerPlansParams struct {
	SearchTerm interface{} `json:"search_term"`
	IDMitra    pgtype.Int4 `json:"id_mitra"`
	SortBy     string      `json:"sort_by"`
	SortDesc   bool        `json:"sort_desc"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type ListMarkerPlansRow struct {
	IDMarkerPlan   int32              `json:"id_marker_plan"`
	NoDokumen      string             `json:"no_dokumen"`
	TanggalEfektif pgtype.Date        `json:"tanggal_efektif"`
	IDWoShell      int32              `json:"id_wo_shell"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Fabric         string             `json:"fabric"`
	Color          string             `json:"color"`
	IDWo           int32              `json:"id_wo"`
	Buyer          string             `json:"buyer"`
	Model          string             `json:"model"`
	TotalCount     int64              `json:"total_count"`
}

func (q *Queries) ListMarkerPlans(ctx context.Context, arg ListMarkerPlansParams) ([]ListMarkerPlansRow, error) {
	rows, err := q.db.Query(ctx, listMarkerPlans,
		arg.SearchTerm,
		arg.IDMitra,
		arg.SortBy,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMarkerPlansRow
	for rows.Next() {
		var i ListMarkerPlansRow
		if err := rows.Scan(
			&i.IDMarkerPlan,
			&i.NoDokumen,
			&i.TanggalEfektif,
			&i.IDWoShell,
			&i.CreatedAt,
			&i.Fabric,
			&i.Color,
			&i.IDWo,
			&i.Buyer,
			&i.Model,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatioByKomponenID = `-- name: ListRatioByKomponenID :many
SELECT ID_RATIO_MARKER, ID_KOMPONEN_MARKER, ID_WO_SHELL, CONS, PLAN_SPREADING_GELARAN,
       PANJANG_MARKER, EFFICIENCY_MARKER, ALLOWANCE, CONS_BUYER, ROLL_QTY, SAMBUNGAN_ROLL,
       PLOT, LEBAR_KAIN, PANJANG_MARKER_UNIT, KET, created_at
FROM RATIO_MARKER
WHERE ID_KOMPONEN_MARKER = $1
ORDER BY ID_RATIO_MARKER ASC
`

type ListRatioByKomponenIDRow struct {
	IDRatioMarker        int32              `json:"id_ratio_marker"`
	IDKomponenMarker     int32              `json:"id_komponen_marker"`
	IDWoShell            int32              `json:"id_wo_shell"`
	Cons                 pgtype.Numeric     `json:"cons"`
	PlanSpreadingGelaran pgtype.Numeric     `json:"plan_spreading_gelaran"`
	PanjangMarker        pgtype.Numeric     `json:"panjang_marker"`
	EfficiencyMarker     pgtype.Numeric     `json:"efficiency_marker"`
	Allowance            pgtype.Numeric     `json:"allowance"`
	ConsBuyer            pgtype.Numeric     `json:"cons_buyer"`
	RollQty              int32              `json:"roll_qty"`
	SambunganRoll        int32              `json:"sambungan_roll"`
	Plot                 int32              `json:"plot"`
	LebarKain            pgtype.Numeric     `json:"lebar_kain"`
	PanjangMarkerUnit    string             `json:"panjang_marker_unit"`
	Ket                  string             `json:"ket"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListRatioByKomponenID(ctx context.Context, idKomponenMarker int32) ([]ListRatioByKomponenIDRow, error) {
	rows, err := q.db.Query(ctx, listRatioByKomponenID, idKomponenMarker)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRatioByKomponenIDRow
	for rows.Next() {
		var i ListRatioByKomponenIDRow
		if err := rows.Scan(
			&i.IDRatioMarker,
			&i.IDKomponenMarker,
			&i.IDWoShell,
			&i.Cons,
			&i.PlanSpreadingGelaran,
			&i.PanjangMarker,
			&i.EfficiencyMarker,
			&i.Allowance,
			&i.ConsBuyer,
			&i.RollQty,
			&i.SambunganRoll,
			&i.Plot,
			&i.LebarKain,
			&i.PanjangMarkerUnit,
			&i.Ket,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatioSizeByRatioID = `-- name: ListRatioSizeByRatioID :many
SELECT rsm.ID_RATIO_SIZE_MARKER, rsm.ID_RATIO_MARKER, rsm.ID_WO_SHELL_SIZE, rsm.RATIO_PLAN, wss.SIZE, wss.QTY AS size_qty
FROM RATIO_SIZE_MARKER rsm
JOIN WORK_ORDER_SHELL_SIZE wss ON rsm.ID_WO_SHELL_SIZE = wss.ID_WO_SHELL_SIZE
WHERE rsm.ID_RATIO_MARKER = $1
ORDER BY rsm.ID_RATIO_SIZE_MARKER ASC
`

type ListRatioSizeByRatioIDRow struct {
	IDRatioSizeMarker int32  `json:"id_ratio_size_marker"`
	IDRatioMarker     int32  `json:"id_ratio_marker"`
	IDWoShellSize     int32  `json:"id_wo_shell_size"`
	RatioPlan         int32  `json:"ratio_plan"`
	Size              string `json:"size"`
	SizeQty           int32  `json:"size_qty"`
}

func (q *Queries) ListRatioSizeByRatioID(ctx context.Context, idRatioMarker int32) ([]ListRatioSizeByRatioIDRow, error) {
	rows, err := q.db.Query(ctx, listRatioSizeByRatioID, idRatioMarker)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRatioSizeByRatioIDRow
	for rows.Next() {
		var i ListRatioSizeByRatioIDRow
		if err := rows.Scan(
			&i.IDRatioSizeMarker,
			&i.IDRatioMarker,
			&i.IDWoShellSize,
			&i.RatioPlan,
			&i.Size,
			&i.SizeQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
