// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: master_data_deleted.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const isMasterDataDeleted = `-- name: IsMasterDataDeleted :one
SELECT EXISTS(
    SELECT 1 FROM MASTER_DATA_DELETED
    WHERE nama_tabel = $1 AND id_record = $2
)::boolean
`

type IsMasterDataDeletedParams struct {
	NamaTabel string `json:"nama_tabel"`
	IDRecord  int32  `json:"id_record"`
}

func (q *Queries) IsMasterDataDeleted(ctx context.Context, arg IsMasterDataDeletedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMasterDataDeleted, arg.NamaTabel, arg.IDRecord)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const softDeleteMasterData = `-- name: SoftDeleteMasterData :exec
INSERT INTO MASTER_DATA_DELETED (nama_tabel, id_record, deleted_by)
VALUES ($1, $2, $3)
ON CONFLICT (nama_tabel, id_record) DO NOTHING
`

type SoftDeleteMasterDataParams struct {
	NamaTabel string      `json:"nama_tabel"`
	IDRecord  int32       `json:"id_record"`
	DeletedBy pgtype.Int4 `json:"deleted_by"`
}

func (q *Queries) SoftDeleteMasterData(ctx context.Context, arg SoftDeleteMasterDataParams) error {
	_, err := q.db.Exec(ctx, softDeleteMasterData, arg.NamaTabel, arg.IDRecord, arg.DeletedBy)
	return err
}
