// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: master_plan.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMasterPlanItem = `-- name: AddMasterPlanItem :one
INSERT INTO MASTER_PLAN_ITEM (id_master_plan, id_wo_shell, no_urut)
VALUES ($1, $2, $3)
RETURNING id_master_plan_item, id_master_plan, id_wo_shell, no_urut, created_at
`

type AddMasterPlanItemParams struct {
	IDMasterPlan int32 `json:"id_master_plan"`
	IDWoShell    int32 `json:"id_wo_shell"`
	NoUrut       int32 `json:"no_urut"`
}

func (q *Queries) AddMasterPlanItem(ctx context.Context, arg AddMasterPlanItemParams) (MasterPlanItem, error) {
	row := q.db.QueryRow(ctx, addMasterPlanItem, arg.IDMasterPlan, arg.IDWoShell, arg.NoUrut)
	var i MasterPlanItem
	err := row.Scan(
		&i.IDMasterPlanItem,
		&i.IDMasterPlan,
		&i.IDWoShell,
		&i.NoUrut,
		&i.CreatedAt,
	)
	return i, err
}

const createMasterPlan = `-- name: CreateMasterPlan :one
INSERT INTO MASTER_PLAN (id_departemen, id_production_line, nama, created_by)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id_master_plan, id_departemen, id_production_line, nama, created_by, created_at, updated_at
`

type CreateMasterPlanParams struct {
	IDDepartemen     int32       `json:"id_departemen"`
	IDProductionLine int32       `json:"id_production_line"`
	Nama             string      `json:"nama"`
	CreatedBy        pgtype.Int4 `json:"created_by"`
}

func (q *Queries) CreateMasterPlan(ctx context.Context, arg CreateMasterPlanParams) (MasterPlan, error) {
	row := q.db.QueryRow(ctx, createMasterPlan,
		arg.IDDepartemen,
		arg.IDProductionLine,
		arg.Nama,
		arg.CreatedBy,
	)
	var i MasterPlan
	err := row.Scan(
		&i.IDMasterPlan,
		&i.IDDepartemen,
		&i.IDProductionLine,
		&i.Nama,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMasterPlan = `-- name: DeleteMasterPlan :exec
DELETE FROM MASTER_PLAN WHERE id_master_plan = $1
`

func (q *Queries) DeleteMasterPlan(ctx context.Context, idMasterPlan int32) error {
	_, err := q.db.Exec(ctx, deleteMasterPlan, idMasterPlan)
	return err
}

const deleteTargetProses = `-- name: DeleteTargetProses :exec
DELETE FROM MASTER_PLAN_TARGET_PROSES
WHERE id_master_plan_item = $1 AND tanggal = $2::date
`

type DeleteTargetProsesParams struct {
	IDMasterPlanItem int32       `json:"id_master_plan_item"`
	Column2          pgtype.Date `json:"column_2"`
}

func (q *Queries) DeleteTargetProses(ctx context.Context, arg DeleteTargetProsesParams) error {
	_, err := q.db.Exec(ctx, deleteTargetProses, arg.IDMasterPlanItem, arg.Column2)
	return err
}

const getMasterPlanByID = `-- name: GetMasterPlanByID :one
SELECT
    mp.id_master_plan,
    mp.id_departemen,
    mp.id_production_line,
    mp.nama,
    mp.created_by,
    mp.created_at,
    mp.updated_at,
    d.nama_departemen,
    pl.name AS nama_line
FROM MASTER_PLAN mp
JOIN DEPARTEMEN d ON d.id_departemen = mp.id_departemen
JOIN PRODUCTION_LINE pl ON pl.id_production_line = mp.id_production_line
WHERE mp.id_master_plan = $1
`

type GetMasterPlanByIDRow struct {
	IDMasterPlan     int32              `json:"id_master_plan"`
	IDDepartemen     int32              `json:"id_departemen"`
	IDProductionLine int32              `json:"id_production_line"`
	Nama             string             `json:"nama"`
	CreatedBy        pgtype.Int4        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	NamaDepartemen   string             `json:"nama_departemen"`
	NamaLine         string             `json:"nama_line"`
}

func (q *Queries) GetMasterPlanByID(ctx context.Context, idMasterPlan int32) (GetMasterPlanByIDRow, error) {
	row := q.db.QueryRow(ctx, getMasterPlanByID, idMasterPlan)
	var i GetMasterPlanByIDRow
	err := row.Scan(
		&i.IDMasterPlan,
		&i.IDDepartemen,
		&i.IDProductionLine,
		&i.Nama,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NamaDepartemen,
		&i.NamaLine,
	)
	return i, err
}

const getMasterPlanItemByID = `-- name: GetMasterPlanItemByID :one
SELECT
    mpi.id_master_plan_item,
    mpi.id_master_plan,
    mpi.id_wo_shell,
    mpi.no_urut,
    mpi.created_at,
    wos.id_wo,
    wos.color,
    wos.deskripsi,
    wo.buyer,
    wo.model AS style,
    wo.qty
FROM MASTER_PLAN_ITEM mpi
JOIN WORK_ORDER_SHELL wos ON wos.id_wo_shell = mpi.id_wo_shell
JOIN WORK_ORDER wo ON wo.id_wo = wos.id_wo
WHERE mpi.id_master_plan_item = $1
`

type GetMasterPlanItemByIDRow struct {
	IDMasterPlanItem int32              `json:"id_master_plan_item"`
	IDMasterPlan     int32              `json:"id_master_plan"`
	IDWoShell        int32              `json:"id_wo_shell"`
	NoUrut           int32              `json:"no_urut"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	IDWo             int32              `json:"id_wo"`
	Color            string             `json:"color"`
	Deskripsi        string             `json:"deskripsi"`
	Buyer            string             `json:"buyer"`
	Style            string             `json:"style"`
	Qty              int32              `json:"qty"`
}

func (q *Queries) GetMasterPlanItemByID(ctx context.Context, idMasterPlanItem int32) (GetMasterPlanItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getMasterPlanItemByID, idMasterPlanItem)
	var i GetMasterPlanItemByIDRow
	err := row.Scan(
		&i.IDMasterPlanItem,
		&i.IDMasterPlan,
		&i.IDWoShell,
		&i.NoUrut,
		&i.CreatedAt,
		&i.IDWo,
		&i.Color,
		&i.Deskripsi,
		&i.Buyer,
		&i.Style,
		&i.Qty,
	)
	return i, err
}

const listMasterPlanItems = `-- name: ListMasterPlanItems :many
SELECT
    mpi.id_master_plan_item,
    mpi.id_master_plan,
    mpi.id_wo_shell,
    mpi.no_urut,
    mpi.created_at,
    wos.id_wo,
    wos.color,
    wos.deskripsi,
    wo.buyer,
    wo.model AS style,
    wo.qty
FROM MASTER_PLAN_ITEM mpi
JOIN WORK_ORDER_SHELL wos ON wos.id_wo_shell = mpi.id_wo_shell
JOIN WORK_ORDER wo ON wo.id_wo = wos.id_wo
WHERE mpi.id_master_plan = $1
ORDER BY mpi.no_urut ASC, mpi.created_at ASC
`

type ListMasterPlanItemsRow struct {
	IDMasterPlanItem int32              `json:"id_master_plan_item"`
	IDMasterPlan     int32              `json:"id_master_plan"`
	IDWoShell        int32              `json:"id_wo_shell"`
	NoUrut           int32              `json:"no_urut"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	IDWo             int32              `json:"id_wo"`
	Color            string             `json:"color"`
	Deskripsi        string             `json:"deskripsi"`
	Buyer            string             `json:"buyer"`
	Style            string             `json:"style"`
	Qty              int32              `json:"qty"`
}

func (q *Queries) ListMasterPlanItems(ctx context.Context, idMasterPlan int32) ([]ListMasterPlanItemsRow, error) {
	rows, err := q.db.Query(ctx, listMasterPlanItems, idMasterPlan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMasterPlanItemsRow
	for rows.Next() {
		var i ListMasterPlanItemsRow
		if err := rows.Scan(
			&i.IDMasterPlanItem,
			&i.IDMasterPlan,
			&i.IDWoShell,
			&i.NoUrut,
			&i.CreatedAt,
			&i.IDWo,
			&i.Color,
			&i.Deskripsi,
			&i.Buyer,
			&i.Style,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMasterPlans = `-- name: ListMasterPlans :many
SELECT
    mp.id_master_plan,
    mp.id_departemen,
    mp.id_production_line,
    mp.nama,
    mp.created_at,
    d.nama_departemen,
    pl.name AS nama_line,
    COUNT(*) OVER() AS total_count
FROM MASTER_PLAN mp
JOIN DEPARTEMEN d ON d.id_departemen = mp.id_departemen
JOIN PRODUCTION_LINE pl ON pl.id_production_line = mp.id_production_line
WHERE (
    $1::text = '' OR
    mp.nama ILIKE '%' || $1::text || '%' OR
    d.nama_departemen ILIKE '%' || $1::text || '%' OR
    pl.name ILIKE '%' || $1::text || '%'
)
ORDER BY mp.created_at DESC
LIMIT $3 OFFSET $2
`

type ListMasterPlansParams struct {
	SearchTerm string `json:"search_term"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type ListMasterPlansRow struct {
	IDMasterPlan     int32              `json:"id_master_plan"`
	IDDepartemen     int32              `json:"id_departemen"`
	IDProductionLine int32              `json:"id_production_line"`
	Nama             string             `json:"nama"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	NamaDepartemen   string             `json:"nama_departemen"`
	NamaLine         string             `json:"nama_line"`
	TotalCount       int64              `json:"total_count"`
}

func (q *Queries) ListMasterPlans(ctx context.Context, arg ListMasterPlansParams) ([]ListMasterPlansRow, error) {
	rows, err := q.db.Query(ctx, listMasterPlans, arg.SearchTerm, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMasterPlansRow
	for rows.Next() {
		var i ListMasterPlansRow
		if err := rows.Scan(
			&i.IDMasterPlan,
			&i.IDDepartemen,
			&i.IDProductionLine,
			&i.Nama,
			&i.CreatedAt,
			&i.NamaDepartemen,
			&i.NamaLine,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutputHarianByItem = `-- name: ListOutputHarianByItem :many
SELECT id_output_harian, id_master_plan_item, tanggal, output, created_at, updated_at FROM MASTER_PLAN_OUTPUT_HARIAN
WHERE id_master_plan_item = $1
ORDER BY tanggal ASC
`

func (q *Queries) ListOutputHarianByItem(ctx context.Context, idMasterPlanItem int32) ([]MasterPlanOutputHarian, error) {
	rows, err := q.db.Query(ctx, listOutputHarianByItem, idMasterPlanItem)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterPlanOutputHarian
	for rows.Next() {
		var i MasterPlanOutputHarian
		if err := rows.Scan(
			&i.IDOutputHarian,
			&i.IDMasterPlanItem,
			&i.Tanggal,
			&i.Output,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetHarianByItem = `-- name: ListTargetHarianByItem :many
SELECT id_target_harian, id_master_plan_item, tanggal, target, created_at, updated_at FROM MASTER_PLAN_TARGET_HARIAN
WHERE id_master_plan_item = $1
ORDER BY tanggal ASC
`

func (q *Queries) ListTargetHarianByItem(ctx context.Context, idMasterPlanItem int32) ([]MasterPlanTargetHarian, error) {
	rows, err := q.db.Query(ctx, listTargetHarianByItem, idMasterPlanItem)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterPlanTargetHarian
	for rows.Next() {
		var i MasterPlanTargetHarian
		if err := rows.Scan(
			&i.IDTargetHarian,
			&i.IDMasterPlanItem,
			&i.Tanggal,
			&i.Target,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetProsesByItem = `-- name: ListTargetProsesByItem :many
SELECT id_target_proses, id_master_plan_item, tanggal, nama_proses, created_at FROM MASTER_PLAN_TARGET_PROSES
WHERE id_master_plan_item = $1
ORDER BY tanggal ASC
`

func (q *Queries) ListTargetProsesByItem(ctx context.Context, idMasterPlanItem int32) ([]MasterPlanTargetProse, error) {
	rows, err := q.db.Query(ctx, listTargetProsesByItem, idMasterPlanItem)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterPlanTargetProse
	for rows.Next() {
		var i MasterPlanTargetProse
		if err := rows.Scan(
			&i.IDTargetProses,
			&i.IDMasterPlanItem,
			&i.Tanggal,
			&i.NamaProses,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMasterPlanItem = `-- name: RemoveMasterPlanItem :execrows
DELETE FROM MASTER_PLAN_ITEM
WHERE id_master_plan_item = $1 AND id_master_plan = $2
`

type RemoveMasterPlanItemParams struct {
	IDMasterPlanItem int32 `json:"id_master_plan_item"`
	IDMasterPlan     int32 `json:"id_master_plan"`
}

func (q *Queries) RemoveMasterPlanItem(ctx context.Context, arg RemoveMasterPlanItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMasterPlanItem, arg.IDMasterPlanItem, arg.IDMasterPlan)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMasterPlan = `-- name: UpdateMasterPlan :one
UPDATE MASTER_PLAN
SET nama = $2, updated_at = NOW()
WHERE id_master_plan = $1
RETURNING id_master_plan, id_departemen, id_production_line, nama, created_by, created_at, updated_at
`

type UpdateMasterPlanParams struct {
	IDMasterPlan int32  `json:"id_master_plan"`
	Nama         string `json:"nama"`
}

func (q *Queries) UpdateMasterPlan(ctx context.Context, arg UpdateMasterPlanParams) (MasterPlan, error) {
	row := q.db.QueryRow(ctx, updateMasterPlan, arg.IDMasterPlan, arg.Nama)
	var i MasterPlan
	err := row.Scan(
		&i.IDMasterPlan,
		&i.IDDepartemen,
		&i.IDProductionLine,
		&i.Nama,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOutputHarian = `-- name: UpsertOutputHarian :one
INSERT INTO MASTER_PLAN_OUTPUT_HARIAN (id_master_plan_item, tanggal, output)
VALUES ($1, $2::date, $3)
ON CONFLICT (id_master_plan_item, tanggal)
DO UPDATE SET output = EXCLUDED.output, updated_at = NOW()
RETURNING id_output_harian, id_master_plan_item, tanggal, output, created_at, updated_at
`

type UpsertOutputHarianParams struct {
	IDMasterPlanItem int32       `json:"id_master_plan_item"`
	Column2          pgtype.Date `json:"column_2"`
	Output           int32       `json:"output"`
}

func (q *Queries) UpsertOutputHarian(ctx context.Context, arg UpsertOutputHarianParams) (MasterPlanOutputHarian, error) {
	row := q.db.QueryRow(ctx, upsertOutputHarian, arg.IDMasterPlanItem, arg.Column2, arg.Output)
	var i MasterPlanOutputHarian
	err := row.Scan(
		&i.IDOutputHarian,
		&i.IDMasterPlanItem,
		&i.Tanggal,
		&i.Output,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTargetHarian = `-- name: UpsertTargetHarian :one
INSERT INTO MASTER_PLAN_TARGET_HARIAN (id_master_plan_item, tanggal, target)
VALUES ($1, $2::date, $3)
ON CONFLICT (id_master_plan_item, tanggal)
DO UPDATE SET target = EXCLUDED.target, updated_at = NOW()
RETURNING id_target_harian, id_master_plan_item, tanggal, target, created_at, updated_at
`

type UpsertTargetHarianParams struct {
	IDMasterPlanItem int32       `json:"id_master_plan_item"`
	Column2          pgtype.Date `json:"column_2"`
	Target           int32       `json:"target"`
}

func (q *Queries) UpsertTargetHarian(ctx context.Context, arg UpsertTargetHarianParams) (MasterPlanTargetHarian, error) {
	row := q.db.QueryRow(ctx, upsertTargetHarian, arg.IDMasterPlanItem, arg.Column2, arg.Target)
	var i MasterPlanTargetHarian
	err := row.Scan(
		&i.IDTargetHarian,
		&i.IDMasterPlanItem,
		&i.Tanggal,
		&i.Target,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTargetProses = `-- name: UpsertTargetProses :one
INSERT INTO MASTER_PLAN_TARGET_PROSES (id_master_plan_item, tanggal, nama_proses)
VALUES ($1, $2::date, $3)
ON CONFLICT (id_master_plan_item, tanggal)
DO UPDATE SET nama_proses = EXCLUDED.nama_proses
RETURNING id_target_proses, id_master_plan_item, tanggal, nama_proses, created_at
`

type UpsertTargetProsesParams struct {
	IDMasterPlanItem int32       `json:"id_master_plan_item"`
	Column2          pgtype.Date `json:"column_2"`
	NamaProses       string      `json:"nama_proses"`
}

func (q *Queries) UpsertTargetProses(ctx context.Context, arg UpsertTargetProsesParams) (MasterPlanTargetProse, error) {
	row := q.db.QueryRow(ctx, upsertTargetProses, arg.IDMasterPlanItem, arg.Column2, arg.NamaProses)
	var i MasterPlanTargetProse
	err := row.Scan(
		&i.IDTargetProses,
		&i.IDMasterPlanItem,
		&i.Tanggal,
		&i.NamaProses,
		&i.CreatedAt,
	)
	return i, err
}
