// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: material_list_export.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMaterialListExportHeader = `-- name: GetMaterialListExportHeader :one

SELECT
    ml.id_material_list,
    ml.name AS material_list_name,
    wo.id_wo,
    wo.buyer,
    wo.model,
    pci.style,
    wo.qty AS wo_qty,
    wo.fob_cmt,
    wo.delivery
FROM material_list ml
JOIN work_order wo ON wo.id_wo = ml.id_wo
JOIN po_client_item pci ON pci.id_po_client_item = wo.id_po_client_item
WHERE ml.id_material_list = $1
`

type GetMaterialListExportHeaderRow struct {
	IDMaterialList   int32       `json:"id_material_list"`
	MaterialListName string      `json:"material_list_name"`
	IDWo             int32       `json:"id_wo"`
	Buyer            string      `json:"buyer"`
	Model            string      `json:"model"`
	Style            string      `json:"style"`
	WoQty            int32       `json:"wo_qty"`
	FobCmt           bool        `json:"fob_cmt"`
	Delivery         pgtype.Date `json:"delivery"`
}

// Dedicated, batched reads for the Material List export composition.  These
// queries deliberately expose source and applicability separately.
func (q *Queries) GetMaterialListExportHeader(ctx context.Context, idMaterialList int32) (GetMaterialListExportHeaderRow, error) {
	row := q.db.QueryRow(ctx, getMaterialListExportHeader, idMaterialList)
	var i GetMaterialListExportHeaderRow
	err := row.Scan(
		&i.IDMaterialList,
		&i.MaterialListName,
		&i.IDWo,
		&i.Buyer,
		&i.Model,
		&i.Style,
		&i.WoQty,
		&i.FobCmt,
		&i.Delivery,
	)
	return i, err
}

const listMaterialListExportCutting = `-- name: ListMaterialListExportCutting :many
SELECT
    woss.id_wo_shell_size,
    COALESCE(SUM(rc.qty), 0)::bigint AS actual_cut_qty
FROM report_cutting rc
JOIN work_order_shell_size woss ON woss.id_wo_shell_size = rc.id_wo_shell_size
JOIN work_order_shell wos ON wos.id_wo_shell = woss.id_wo_shell
WHERE wos.id_wo = $1
GROUP BY woss.id_wo_shell_size
ORDER BY woss.id_wo_shell_size ASC
`

type ListMaterialListExportCuttingRow struct {
	IDWoShellSize int32 `json:"id_wo_shell_size"`
	ActualCutQty  int64 `json:"actual_cut_qty"`
}

func (q *Queries) ListMaterialListExportCutting(ctx context.Context, idWo int32) ([]ListMaterialListExportCuttingRow, error) {
	rows, err := q.db.Query(ctx, listMaterialListExportCutting, idWo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaterialListExportCuttingRow
	for rows.Next() {
		var i ListMaterialListExportCuttingRow
		if err := rows.Scan(&i.IDWoShellSize, &i.ActualCutQty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialListExportItems = `-- name: ListMaterialListExportItems :many
SELECT
    mli.id_material_list_item,
    mli.item,
    mli.description,
    mli.category,
    mli.unit,
    mli.cons_per_pc,
    mli.qty_wo_scope,
    mli.id_qty_wo_shell,
    mli.id_qty_wo_size,
    source_shell.id_wo_shell AS source_shell_id,
    source_shell.deskripsi AS source_shell_description,
    source_shell.color AS source_shell_color,
    source_shell.allow AS source_shell_allow,
    source_trim.id_wo_trim AS source_trim_id,
    source_trim.item AS source_trim_item,
    source_trim.description AS source_trim_description,
    source_trim.color AS source_trim_color,
    source_trim.allow AS source_trim_allow
FROM material_list_item mli
JOIN material_list ml ON ml.id_material_list = mli.id_material_list
LEFT JOIN work_order_shell source_shell ON source_shell.id_wo_shell = mli.id_wo_shell AND source_shell.id_wo = ml.id_wo
LEFT JOIN work_order_trim source_trim ON source_trim.id_wo_trim = mli.id_wo_trim AND source_trim.id_wo = ml.id_wo
WHERE mli.id_material_list = $1
ORDER BY mli.id_material_list_item ASC
`

type ListMaterialListExportItemsRow struct {
	IDMaterialListItem     int32          `json:"id_material_list_item"`
	Item                   string         `json:"item"`
	Description            string         `json:"description"`
	Category               pgtype.Text    `json:"category"`
	Unit                   string         `json:"unit"`
	ConsPerPc              pgtype.Numeric `json:"cons_per_pc"`
	QtyWoScope             pgtype.Text    `json:"qty_wo_scope"`
	IDQtyWoShell           pgtype.Int4    `json:"id_qty_wo_shell"`
	IDQtyWoSize            pgtype.Int4    `json:"id_qty_wo_size"`
	SourceShellID          pgtype.Int4    `json:"source_shell_id"`
	SourceShellDescription pgtype.Text    `json:"source_shell_description"`
	SourceShellColor       pgtype.Text    `json:"source_shell_color"`
	SourceShellAllow       pgtype.Int4    `json:"source_shell_allow"`
	SourceTrimID           pgtype.Int4    `json:"source_trim_id"`
	SourceTrimItem         pgtype.Text    `json:"source_trim_item"`
	SourceTrimDescription  pgtype.Text    `json:"source_trim_description"`
	SourceTrimColor        pgtype.Text    `json:"source_trim_color"`
	SourceTrimAllow        pgtype.Int4    `json:"source_trim_allow"`
}

func (q *Queries) ListMaterialListExportItems(ctx context.Context, idMaterialList int32) ([]ListMaterialListExportItemsRow, error) {
	rows, err := q.db.Query(ctx, listMaterialListExportItems, idMaterialList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaterialListExportItemsRow
	for rows.Next() {
		var i ListMaterialListExportItemsRow
		if err := rows.Scan(
			&i.IDMaterialListItem,
			&i.Item,
			&i.Description,
			&i.Category,
			&i.Unit,
			&i.ConsPerPc,
			&i.QtyWoScope,
			&i.IDQtyWoShell,
			&i.IDQtyWoSize,
			&i.SourceShellID,
			&i.SourceShellDescription,
			&i.SourceShellColor,
			&i.SourceShellAllow,
			&i.SourceTrimID,
			&i.SourceTrimItem,
			&i.SourceTrimDescription,
			&i.SourceTrimColor,
			&i.SourceTrimAllow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialListExportMarkerPlans = `-- name: ListMaterialListExportMarkerPlans :many
SELECT id_marker_plan, id_wo_shell
FROM marker_plan
WHERE id_wo_shell IN (
    SELECT id_wo_shell FROM work_order_shell WHERE id_wo = $1
)
ORDER BY id_wo_shell ASC, id_marker_plan ASC
`

type ListMaterialListExportMarkerPlansRow struct {
	IDMarkerPlan int32 `json:"id_marker_plan"`
	IDWoShell    int32 `json:"id_wo_shell"`
}

func (q *Queries) ListMaterialListExportMarkerPlans(ctx context.Context, idWo int32) ([]ListMaterialListExportMarkerPlansRow, error) {
	rows, err := q.db.Query(ctx, listMaterialListExportMarkerPlans, idWo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaterialListExportMarkerPlansRow
	for rows.Next() {
		var i ListMaterialListExportMarkerPlansRow
		if err := rows.Scan(&i.IDMarkerPlan, &i.IDWoShell); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialListExportMarkerRatios = `-- name: ListMaterialListExportMarkerRatios :many
SELECT
    mp.id_marker_plan,
    mp.id_wo_shell AS marker_plan_shell_id,
    rm.id_ratio_marker,
    rm.id_wo_shell AS ratio_shell_id,
    rm.plan_spreading_gelaran,
    rsm.id_ratio_size_marker,
    rsm.id_wo_shell_size,
    rsm.ratio_plan,
    woss.id_wo_shell AS ratio_size_shell_id,
    woss.id_size
FROM marker_plan mp
JOIN komponen_marker_plan kmp ON kmp.id_marker_plan = mp.id_marker_plan
JOIN ratio_marker rm ON rm.id_komponen_marker = kmp.id_komponen_marker
JOIN ratio_size_marker rsm ON rsm.id_ratio_marker = rm.id_ratio_marker
JOIN work_order_shell_size woss ON woss.id_wo_shell_size = rsm.id_wo_shell_size
JOIN work_order_shell shell ON shell.id_wo_shell = mp.id_wo_shell
WHERE shell.id_wo = $1
ORDER BY mp.id_marker_plan ASC, rm.id_ratio_marker ASC, rsm.id_ratio_size_marker ASC
`

type ListMaterialListExportMarkerRatiosRow struct {
	IDMarkerPlan         int32          `json:"id_marker_plan"`
	MarkerPlanShellID    int32          `json:"marker_plan_shell_id"`
	IDRatioMarker        int32          `json:"id_ratio_marker"`
	RatioShellID         int32          `json:"ratio_shell_id"`
	PlanSpreadingGelaran pgtype.Numeric `json:"plan_spreading_gelaran"`
	IDRatioSizeMarker    int32          `json:"id_ratio_size_marker"`
	IDWoShellSize        int32          `json:"id_wo_shell_size"`
	RatioPlan            int32          `json:"ratio_plan"`
	RatioSizeShellID     int32          `json:"ratio_size_shell_id"`
	IDSize               int32          `json:"id_size"`
}

func (q *Queries) ListMaterialListExportMarkerRatios(ctx context.Context, idWo int32) ([]ListMaterialListExportMarkerRatiosRow, error) {
	rows, err := q.db.Query(ctx, listMaterialListExportMarkerRatios, idWo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaterialListExportMarkerRatiosRow
	for rows.Next() {
		var i ListMaterialListExportMarkerRatiosRow
		if err := rows.Scan(
			&i.IDMarkerPlan,
			&i.MarkerPlanShellID,
			&i.IDRatioMarker,
			&i.RatioShellID,
			&i.PlanSpreadingGelaran,
			&i.IDRatioSizeMarker,
			&i.IDWoShellSize,
			&i.RatioPlan,
			&i.RatioSizeShellID,
			&i.IDSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialListExportReceivedByDate = `-- name: ListMaterialListExportReceivedByDate :many
SELECT
    r.id_material_list_item,
    r.tanggal,
    SUM(r.qty)::bigint AS qty
FROM received r
JOIN material_list_item mli ON mli.id_material_list_item = r.id_material_list_item
WHERE mli.id_material_list = $1
GROUP BY r.id_material_list_item, r.tanggal
ORDER BY r.tanggal ASC, r.id_material_list_item ASC
`

type ListMaterialListExportReceivedByDateRow struct {
	IDMaterialListItem int32       `json:"id_material_list_item"`
	Tanggal            pgtype.Date `json:"tanggal"`
	Qty                int64       `json:"qty"`
}

func (q *Queries) ListMaterialListExportReceivedByDate(ctx context.Context, idMaterialList int32) ([]ListMaterialListExportReceivedByDateRow, error) {
	rows, err := q.db.Query(ctx, listMaterialListExportReceivedByDate, idMaterialList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaterialListExportReceivedByDateRow
	for rows.Next() {
		var i ListMaterialListExportReceivedByDateRow
		if err := rows.Scan(&i.IDMaterialListItem, &i.Tanggal, &i.Qty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialListExportReconciliationRows = `-- name: ListMaterialListExportReconciliationRows :many
SELECT
    rmr.id_material_list_item,
    rmr.reject_qty,
    rmr.retur_qty,
    rmr.keterangan
FROM rekonsiliasi_material_row rmr
JOIN rekonsiliasi r ON r.id_rekonsiliasi = rmr.id_rekonsiliasi
JOIN material_list_item mli ON mli.id_material_list_item = rmr.id_material_list_item
WHERE r.id_wo = $1
  AND mli.id_material_list = $2
ORDER BY rmr.id_material_list_item ASC, rmr.id_rekonsiliasi_material_row ASC
`

type ListMaterialListExportReconciliationRowsParams struct {
	IDWo           int32 `json:"id_wo"`
	IDMaterialList int32 `json:"id_material_list"`
}

type ListMaterialListExportReconciliationRowsRow struct {
	IDMaterialListItem pgtype.Int4 `json:"id_material_list_item"`
	RejectQty          int32       `json:"reject_qty"`
	ReturQty           int32       `json:"retur_qty"`
	Keterangan         string      `json:"keterangan"`
}

func (q *Queries) ListMaterialListExportReconciliationRows(ctx context.Context, arg ListMaterialListExportReconciliationRowsParams) ([]ListMaterialListExportReconciliationRowsRow, error) {
	rows, err := q.db.Query(ctx, listMaterialListExportReconciliationRows, arg.IDWo, arg.IDMaterialList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaterialListExportReconciliationRowsRow
	for rows.Next() {
		var i ListMaterialListExportReconciliationRowsRow
		if err := rows.Scan(
			&i.IDMaterialListItem,
			&i.RejectQty,
			&i.ReturQty,
			&i.Keterangan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialListExportShellSizes = `-- name: ListMaterialListExportShellSizes :many
SELECT
    wos.id_wo_shell,
    wos.color,
    wos.deskripsi AS shell_description,
    woss.id_wo_shell_size,
    woss.id_size,
    ms.nama_size,
    woss.qty AS order_qty
FROM work_order_shell wos
LEFT JOIN work_order_shell_size woss ON woss.id_wo_shell = wos.id_wo_shell
LEFT JOIN master_size ms ON ms.id_size = woss.id_size
WHERE wos.id_wo = $1
ORDER BY wos.id_wo_shell ASC, ms.nama_size ASC NULLS LAST, woss.id_wo_shell_size ASC
`

type ListMaterialListExportShellSizesRow struct {
	IDWoShell        int32       `json:"id_wo_shell"`
	Color            string      `json:"color"`
	ShellDescription string      `json:"shell_description"`
	IDWoShellSize    pgtype.Int4 `json:"id_wo_shell_size"`
	IDSize           pgtype.Int4 `json:"id_size"`
	NamaSize         pgtype.Text `json:"nama_size"`
	OrderQty         pgtype.Int4 `json:"order_qty"`
}

func (q *Queries) ListMaterialListExportShellSizes(ctx context.Context, idWo int32) ([]ListMaterialListExportShellSizesRow, error) {
	rows, err := q.db.Query(ctx, listMaterialListExportShellSizes, idWo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaterialListExportShellSizesRow
	for rows.Next() {
		var i ListMaterialListExportShellSizesRow
		if err := rows.Scan(
			&i.IDWoShell,
			&i.Color,
			&i.ShellDescription,
			&i.IDWoShellSize,
			&i.IDSize,
			&i.NamaSize,
			&i.OrderQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialListExportSuratJalanByDate = `-- name: ListMaterialListExportSuratJalanByDate :many
SELECT
    sjc.id_material_list_item,
    sjc.tanggal,
    SUM(sjc.qty)::bigint AS qty
FROM surat_jalan_client sjc
JOIN material_list_item mli ON mli.id_material_list_item = sjc.id_material_list_item
WHERE mli.id_material_list = $1
GROUP BY sjc.id_material_list_item, sjc.tanggal
ORDER BY sjc.tanggal ASC, sjc.id_material_list_item ASC
`

type ListMaterialListExportSuratJalanByDateRow struct {
	IDMaterialListItem int32       `json:"id_material_list_item"`
	Tanggal            pgtype.Date `json:"tanggal"`
	Qty                int64       `json:"qty"`
}

func (q *Queries) ListMaterialListExportSuratJalanByDate(ctx context.Context, idMaterialList int32) ([]ListMaterialListExportSuratJalanByDateRow, error) {
	rows, err := q.db.Query(ctx, listMaterialListExportSuratJalanByDate, idMaterialList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaterialListExportSuratJalanByDateRow
	for rows.Next() {
		var i ListMaterialListExportSuratJalanByDateRow
		if err := rows.Scan(&i.IDMaterialListItem, &i.Tanggal, &i.Qty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
