// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: material_list.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkMaterialListBelongsToWO = `-- name: CheckMaterialListBelongsToWO :one
SELECT EXISTS (
    SELECT 1 FROM MATERIAL_LIST
    WHERE id_material_list = $1
      AND id_wo = $2
) AS exists
`

type CheckMaterialListBelongsToWOParams struct {
	IDMaterialList int32 `json:"id_material_list"`
	IDWo           int32 `json:"id_wo"`
}

func (q *Queries) CheckMaterialListBelongsToWO(ctx context.Context, arg CheckMaterialListBelongsToWOParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkMaterialListBelongsToWO, arg.IDMaterialList, arg.IDWo)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteMaterialList = `-- name: DeleteMaterialList :exec
DELETE FROM MATERIAL_LIST
WHERE id_material_list = $1
  AND is_locked = FALSE
`

func (q *Queries) DeleteMaterialList(ctx context.Context, idMaterialList int32) error {
	_, err := q.db.Exec(ctx, deleteMaterialList, idMaterialList)
	return err
}

const deleteMaterialListItem = `-- name: DeleteMaterialListItem :exec
DELETE FROM MATERIAL_LIST_ITEM
WHERE id_material_list_item = $1
  AND id_material_list IN (
      SELECT id_material_list FROM MATERIAL_LIST WHERE is_locked = FALSE
  )
`

func (q *Queries) DeleteMaterialListItem(ctx context.Context, idMaterialListItem int32) error {
	_, err := q.db.Exec(ctx, deleteMaterialListItem, idMaterialListItem)
	return err
}

const getMaterialList = `-- name: GetMaterialList :one
SELECT id_material_list, id_wo, name, is_locked, created_at
FROM MATERIAL_LIST
WHERE id_material_list = $1
`

type GetMaterialListRow struct {
	IDMaterialList int32              `json:"id_material_list"`
	IDWo           int32              `json:"id_wo"`
	Name           string             `json:"name"`
	IsLocked       bool               `json:"is_locked"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetMaterialList(ctx context.Context, idMaterialList int32) (GetMaterialListRow, error) {
	row := q.db.QueryRow(ctx, getMaterialList, idMaterialList)
	var i GetMaterialListRow
	err := row.Scan(
		&i.IDMaterialList,
		&i.IDWo,
		&i.Name,
		&i.IsLocked,
		&i.CreatedAt,
	)
	return i, err
}

const getMaterialListItem = `-- name: GetMaterialListItem :one
SELECT 
    mli.id_material_list_item, 
    mli.id_material_list, 
    mli.item, 
    mli.description, 
    mli.qty, 
    mli.unit, 
    mli.est_price, 
    mli.id_wo_shell, 
    mli.id_wo_trim, 
    mli.created_at,
    COALESCE((SELECT SUM(sjc.qty) FROM SURAT_JALAN_CLIENT sjc WHERE sjc.id_material_list_item = mli.id_material_list_item), 0)::integer AS qty_surat_jalan,
    COALESCE((SELECT SUM(r.qty) FROM RECEIVED r WHERE r.id_material_list_item = mli.id_material_list_item), 0)::integer AS qty_received
FROM MATERIAL_LIST_ITEM mli
WHERE mli.id_material_list_item = $1
`

type GetMaterialListItemRow struct {
	IDMaterialListItem int32              `json:"id_material_list_item"`
	IDMaterialList     int32              `json:"id_material_list"`
	Item               string             `json:"item"`
	Description        string             `json:"description"`
	Qty                int32              `json:"qty"`
	Unit               string             `json:"unit"`
	EstPrice           pgtype.Numeric     `json:"est_price"`
	IDWoShell          pgtype.Int4        `json:"id_wo_shell"`
	IDWoTrim           pgtype.Int4        `json:"id_wo_trim"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	QtySuratJalan      int32              `json:"qty_surat_jalan"`
	QtyReceived        int32              `json:"qty_received"`
}

func (q *Queries) GetMaterialListItem(ctx context.Context, idMaterialListItem int32) (GetMaterialListItemRow, error) {
	row := q.db.QueryRow(ctx, getMaterialListItem, idMaterialListItem)
	var i GetMaterialListItemRow
	err := row.Scan(
		&i.IDMaterialListItem,
		&i.IDMaterialList,
		&i.Item,
		&i.Description,
		&i.Qty,
		&i.Unit,
		&i.EstPrice,
		&i.IDWoShell,
		&i.IDWoTrim,
		&i.CreatedAt,
		&i.QtySuratJalan,
		&i.QtyReceived,
	)
	return i, err
}

const getMaterialListItemDetail = `-- name: GetMaterialListItemDetail :one
SELECT
    mli.id_material_list_item,
    mli.id_material_list,
    mli.item,
    mli.description,
    mli.qty,
    mli.unit,
    mli.est_price,
    mli.id_wo_shell,
    mli.id_wo_trim,
    mli.created_at,
    COALESCE((SELECT SUM(sjc.qty) FROM SURAT_JALAN_CLIENT sjc WHERE sjc.id_material_list_item = mli.id_material_list_item), 0)::integer AS qty_surat_jalan,
    COALESCE((SELECT SUM(r.qty) FROM RECEIVED r WHERE r.id_material_list_item = mli.id_material_list_item), 0)::integer AS qty_received,
    ml.name AS ml_name,
    ml.is_locked AS ml_is_locked,
    wo.id_wo,
    wo.buyer,
    wo.model
FROM MATERIAL_LIST_ITEM mli
JOIN MATERIAL_LIST ml ON ml.id_material_list = mli.id_material_list
JOIN WORK_ORDER wo ON wo.id_wo = ml.id_wo
WHERE mli.id_material_list_item = $1
`

type GetMaterialListItemDetailRow struct {
	IDMaterialListItem int32              `json:"id_material_list_item"`
	IDMaterialList     int32              `json:"id_material_list"`
	Item               string             `json:"item"`
	Description        string             `json:"description"`
	Qty                int32              `json:"qty"`
	Unit               string             `json:"unit"`
	EstPrice           pgtype.Numeric     `json:"est_price"`
	IDWoShell          pgtype.Int4        `json:"id_wo_shell"`
	IDWoTrim           pgtype.Int4        `json:"id_wo_trim"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	QtySuratJalan      int32              `json:"qty_surat_jalan"`
	QtyReceived        int32              `json:"qty_received"`
	MlName             string             `json:"ml_name"`
	MlIsLocked         bool               `json:"ml_is_locked"`
	IDWo               int32              `json:"id_wo"`
	Buyer              string             `json:"buyer"`
	Model              string             `json:"model"`
}

func (q *Queries) GetMaterialListItemDetail(ctx context.Context, idMaterialListItem int32) (GetMaterialListItemDetailRow, error) {
	row := q.db.QueryRow(ctx, getMaterialListItemDetail, idMaterialListItem)
	var i GetMaterialListItemDetailRow
	err := row.Scan(
		&i.IDMaterialListItem,
		&i.IDMaterialList,
		&i.Item,
		&i.Description,
		&i.Qty,
		&i.Unit,
		&i.EstPrice,
		&i.IDWoShell,
		&i.IDWoTrim,
		&i.CreatedAt,
		&i.QtySuratJalan,
		&i.QtyReceived,
		&i.MlName,
		&i.MlIsLocked,
		&i.IDWo,
		&i.Buyer,
		&i.Model,
	)
	return i, err
}

const listMaterialListItemsByML = `-- name: ListMaterialListItemsByML :many
SELECT 
    mli.id_material_list_item, 
    mli.id_material_list, 
    mli.item, 
    mli.description, 
    mli.qty, 
    mli.unit, 
    mli.est_price, 
    mli.id_wo_shell, 
    mli.id_wo_trim, 
    mli.created_at,
    COALESCE((SELECT SUM(sjc.qty) FROM SURAT_JALAN_CLIENT sjc WHERE sjc.id_material_list_item = mli.id_material_list_item), 0)::integer AS qty_surat_jalan,
    COALESCE((SELECT SUM(r.qty) FROM RECEIVED r WHERE r.id_material_list_item = mli.id_material_list_item), 0)::integer AS qty_received
FROM MATERIAL_LIST_ITEM mli
WHERE mli.id_material_list = $1
ORDER BY mli.id_material_list_item ASC
`

type ListMaterialListItemsByMLRow struct {
	IDMaterialListItem int32              `json:"id_material_list_item"`
	IDMaterialList     int32              `json:"id_material_list"`
	Item               string             `json:"item"`
	Description        string             `json:"description"`
	Qty                int32              `json:"qty"`
	Unit               string             `json:"unit"`
	EstPrice           pgtype.Numeric     `json:"est_price"`
	IDWoShell          pgtype.Int4        `json:"id_wo_shell"`
	IDWoTrim           pgtype.Int4        `json:"id_wo_trim"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	QtySuratJalan      int32              `json:"qty_surat_jalan"`
	QtyReceived        int32              `json:"qty_received"`
}

func (q *Queries) ListMaterialListItemsByML(ctx context.Context, idMaterialList int32) ([]ListMaterialListItemsByMLRow, error) {
	rows, err := q.db.Query(ctx, listMaterialListItemsByML, idMaterialList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaterialListItemsByMLRow
	for rows.Next() {
		var i ListMaterialListItemsByMLRow
		if err := rows.Scan(
			&i.IDMaterialListItem,
			&i.IDMaterialList,
			&i.Item,
			&i.Description,
			&i.Qty,
			&i.Unit,
			&i.EstPrice,
			&i.IDWoShell,
			&i.IDWoTrim,
			&i.CreatedAt,
			&i.QtySuratJalan,
			&i.QtyReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialListsPaginated = `-- name: ListMaterialListsPaginated :many
SELECT
    ml.id_material_list,
    ml.id_wo,
    ml.name,
    ml.is_locked,
    ml.created_at,
    wo.buyer,
    wo.model,
    wo.qty AS wo_qty,
    (SELECT COUNT(*) FROM MATERIAL_LIST_ITEM WHERE id_material_list = ml.id_material_list)::integer AS item_count,
    (SELECT COALESCE(SUM(sjc.qty), 0)
     FROM SURAT_JALAN_CLIENT sjc
     JOIN MATERIAL_LIST_ITEM mli2 ON mli2.id_material_list_item = sjc.id_material_list_item
     WHERE mli2.id_material_list = ml.id_material_list)::integer AS total_qty_sj,
    (SELECT COALESCE(SUM(r.qty), 0)
     FROM RECEIVED r
     JOIN MATERIAL_LIST_ITEM mli3 ON mli3.id_material_list_item = r.id_material_list_item
     WHERE mli3.id_material_list = ml.id_material_list)::integer AS total_qty_received,
    COUNT(*) OVER () AS total_count
FROM MATERIAL_LIST ml
JOIN WORK_ORDER wo ON wo.id_wo = ml.id_wo
WHERE (NOT $1::boolean OR ml.is_locked = TRUE)
  AND (
    $2::text = ''
    OR LOWER(wo.buyer) LIKE '%' || LOWER($2::text) || '%'
    OR LOWER(wo.model) LIKE '%' || LOWER($2::text) || '%'
    OR LOWER(ml.name) LIKE '%' || LOWER($2::text) || '%'
  )
ORDER BY ml.created_at DESC
LIMIT $4
OFFSET $3
`

type ListMaterialListsPaginatedParams struct {
	LockedOnly bool   `json:"locked_only"`
	Search     string `json:"search"`
	Off        int32  `json:"off"`
	Lim        int32  `json:"lim"`
}

type ListMaterialListsPaginatedRow struct {
	IDMaterialList   int32              `json:"id_material_list"`
	IDWo             int32              `json:"id_wo"`
	Name             string             `json:"name"`
	IsLocked         bool               `json:"is_locked"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Buyer            string             `json:"buyer"`
	Model            string             `json:"model"`
	WoQty            int32              `json:"wo_qty"`
	ItemCount        int32              `json:"item_count"`
	TotalQtySj       int32              `json:"total_qty_sj"`
	TotalQtyReceived int32              `json:"total_qty_received"`
	TotalCount       int64              `json:"total_count"`
}

func (q *Queries) ListMaterialListsPaginated(ctx context.Context, arg ListMaterialListsPaginatedParams) ([]ListMaterialListsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listMaterialListsPaginated,
		arg.LockedOnly,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaterialListsPaginatedRow
	for rows.Next() {
		var i ListMaterialListsPaginatedRow
		if err := rows.Scan(
			&i.IDMaterialList,
			&i.IDWo,
			&i.Name,
			&i.IsLocked,
			&i.CreatedAt,
			&i.Buyer,
			&i.Model,
			&i.WoQty,
			&i.ItemCount,
			&i.TotalQtySj,
			&i.TotalQtyReceived,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnlockedMaterialListsByWO = `-- name: ListUnlockedMaterialListsByWO :many
SELECT id_material_list, id_wo, name, is_locked, created_at
FROM MATERIAL_LIST
WHERE id_wo = $1 AND is_locked = FALSE
ORDER BY id_material_list ASC
`

type ListUnlockedMaterialListsByWORow struct {
	IDMaterialList int32              `json:"id_material_list"`
	IDWo           int32              `json:"id_wo"`
	Name           string             `json:"name"`
	IsLocked       bool               `json:"is_locked"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUnlockedMaterialListsByWO(ctx context.Context, idWo int32) ([]ListUnlockedMaterialListsByWORow, error) {
	rows, err := q.db.Query(ctx, listUnlockedMaterialListsByWO, idWo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnlockedMaterialListsByWORow
	for rows.Next() {
		var i ListUnlockedMaterialListsByWORow
		if err := rows.Scan(
			&i.IDMaterialList,
			&i.IDWo,
			&i.Name,
			&i.IsLocked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMaterialList = `-- name: LockMaterialList :one
UPDATE MATERIAL_LIST
SET is_locked = TRUE
WHERE id_material_list = $1
RETURNING id_material_list, id_wo, name, is_locked, created_at
`

type LockMaterialListRow struct {
	IDMaterialList int32              `json:"id_material_list"`
	IDWo           int32              `json:"id_wo"`
	Name           string             `json:"name"`
	IsLocked       bool               `json:"is_locked"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) LockMaterialList(ctx context.Context, idMaterialList int32) (LockMaterialListRow, error) {
	row := q.db.QueryRow(ctx, lockMaterialList, idMaterialList)
	var i LockMaterialListRow
	err := row.Scan(
		&i.IDMaterialList,
		&i.IDWo,
		&i.Name,
		&i.IsLocked,
		&i.CreatedAt,
	)
	return i, err
}

const updateMaterialList = `-- name: UpdateMaterialList :one
UPDATE MATERIAL_LIST
SET name = $1
WHERE id_material_list = $2
  AND is_locked = FALSE
RETURNING id_material_list, id_wo, name, is_locked, created_at
`

type UpdateMaterialListParams struct {
	Name           string `json:"name"`
	IDMaterialList int32  `json:"id_material_list"`
}

type UpdateMaterialListRow struct {
	IDMaterialList int32              `json:"id_material_list"`
	IDWo           int32              `json:"id_wo"`
	Name           string             `json:"name"`
	IsLocked       bool               `json:"is_locked"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateMaterialList(ctx context.Context, arg UpdateMaterialListParams) (UpdateMaterialListRow, error) {
	row := q.db.QueryRow(ctx, updateMaterialList, arg.Name, arg.IDMaterialList)
	var i UpdateMaterialListRow
	err := row.Scan(
		&i.IDMaterialList,
		&i.IDWo,
		&i.Name,
		&i.IsLocked,
		&i.CreatedAt,
	)
	return i, err
}

const updateMaterialListItem = `-- name: UpdateMaterialListItem :one
UPDATE MATERIAL_LIST_ITEM
SET
    item = $1,
    description = $2,
    qty = $3,
    unit = $4,
    est_price = $5::numeric,
    id_wo_shell = $6,
    id_wo_trim = $7
WHERE id_material_list_item = $8
  AND id_material_list IN (
      SELECT id_material_list FROM MATERIAL_LIST WHERE is_locked = FALSE
  )
RETURNING id_material_list_item, id_material_list, item, description, qty, unit, est_price, id_wo_shell, id_wo_trim, created_at
`

type UpdateMaterialListItemParams struct {
	Item               string         `json:"item"`
	Description        string         `json:"description"`
	Qty                int32          `json:"qty"`
	Unit               string         `json:"unit"`
	EstPrice           pgtype.Numeric `json:"est_price"`
	IDWoShell          pgtype.Int4    `json:"id_wo_shell"`
	IDWoTrim           pgtype.Int4    `json:"id_wo_trim"`
	IDMaterialListItem int32          `json:"id_material_list_item"`
}

type UpdateMaterialListItemRow struct {
	IDMaterialListItem int32              `json:"id_material_list_item"`
	IDMaterialList     int32              `json:"id_material_list"`
	Item               string             `json:"item"`
	Description        string             `json:"description"`
	Qty                int32              `json:"qty"`
	Unit               string             `json:"unit"`
	EstPrice           pgtype.Numeric     `json:"est_price"`
	IDWoShell          pgtype.Int4        `json:"id_wo_shell"`
	IDWoTrim           pgtype.Int4        `json:"id_wo_trim"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateMaterialListItem(ctx context.Context, arg UpdateMaterialListItemParams) (UpdateMaterialListItemRow, error) {
	row := q.db.QueryRow(ctx, updateMaterialListItem,
		arg.Item,
		arg.Description,
		arg.Qty,
		arg.Unit,
		arg.EstPrice,
		arg.IDWoShell,
		arg.IDWoTrim,
		arg.IDMaterialListItem,
	)
	var i UpdateMaterialListItemRow
	err := row.Scan(
		&i.IDMaterialListItem,
		&i.IDMaterialList,
		&i.Item,
		&i.Description,
		&i.Qty,
		&i.Unit,
		&i.EstPrice,
		&i.IDWoShell,
		&i.IDWoTrim,
		&i.CreatedAt,
	)
	return i, err
}
