// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: material_list.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkMaterialListBelongsToWO = `-- name: CheckMaterialListBelongsToWO :one
SELECT EXISTS (
    SELECT 1 FROM MATERIAL_LIST
    WHERE id_material_list = $1
      AND id_wo = $2
) AS exists
`

type CheckMaterialListBelongsToWOParams struct {
	IDMaterialList int32 `json:"id_material_list"`
	IDWo           int32 `json:"id_wo"`
}

func (q *Queries) CheckMaterialListBelongsToWO(ctx context.Context, arg CheckMaterialListBelongsToWOParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkMaterialListBelongsToWO, arg.IDMaterialList, arg.IDWo)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteMaterialList = `-- name: DeleteMaterialList :exec
DELETE FROM MATERIAL_LIST
WHERE id_material_list = $1
  AND is_locked = FALSE
`

func (q *Queries) DeleteMaterialList(ctx context.Context, idMaterialList int32) error {
	_, err := q.db.Exec(ctx, deleteMaterialList, idMaterialList)
	return err
}

const deleteMaterialListItem = `-- name: DeleteMaterialListItem :exec
DELETE FROM MATERIAL_LIST_ITEM
WHERE id_material_list_item = $1
  AND id_material_list IN (
      SELECT id_material_list FROM MATERIAL_LIST WHERE is_locked = FALSE
  )
`

func (q *Queries) DeleteMaterialListItem(ctx context.Context, idMaterialListItem int32) error {
	_, err := q.db.Exec(ctx, deleteMaterialListItem, idMaterialListItem)
	return err
}

const getMaterialList = `-- name: GetMaterialList :one
SELECT id_material_list, id_wo, name, is_locked, created_at
FROM MATERIAL_LIST
WHERE id_material_list = $1
`

type GetMaterialListRow struct {
	IDMaterialList int32              `json:"id_material_list"`
	IDWo           int32              `json:"id_wo"`
	Name           string             `json:"name"`
	IsLocked       bool               `json:"is_locked"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetMaterialList(ctx context.Context, idMaterialList int32) (GetMaterialListRow, error) {
	row := q.db.QueryRow(ctx, getMaterialList, idMaterialList)
	var i GetMaterialListRow
	err := row.Scan(
		&i.IDMaterialList,
		&i.IDWo,
		&i.Name,
		&i.IsLocked,
		&i.CreatedAt,
	)
	return i, err
}

const getMaterialListItem = `-- name: GetMaterialListItem :one
SELECT id_material_list_item, id_material_list, item, description, qty, unit, est_price, id_wo_shell, id_wo_trim, created_at
FROM MATERIAL_LIST_ITEM
WHERE id_material_list_item = $1
`

type GetMaterialListItemRow struct {
	IDMaterialListItem int32              `json:"id_material_list_item"`
	IDMaterialList     int32              `json:"id_material_list"`
	Item               string             `json:"item"`
	Description        string             `json:"description"`
	Qty                int32              `json:"qty"`
	Unit               string             `json:"unit"`
	EstPrice           pgtype.Numeric     `json:"est_price"`
	IDWoShell          pgtype.Int4        `json:"id_wo_shell"`
	IDWoTrim           pgtype.Int4        `json:"id_wo_trim"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetMaterialListItem(ctx context.Context, idMaterialListItem int32) (GetMaterialListItemRow, error) {
	row := q.db.QueryRow(ctx, getMaterialListItem, idMaterialListItem)
	var i GetMaterialListItemRow
	err := row.Scan(
		&i.IDMaterialListItem,
		&i.IDMaterialList,
		&i.Item,
		&i.Description,
		&i.Qty,
		&i.Unit,
		&i.EstPrice,
		&i.IDWoShell,
		&i.IDWoTrim,
		&i.CreatedAt,
	)
	return i, err
}

const listMaterialListItemsByML = `-- name: ListMaterialListItemsByML :many
SELECT id_material_list_item, id_material_list, item, description, qty, unit, est_price, id_wo_shell, id_wo_trim, created_at
FROM MATERIAL_LIST_ITEM
WHERE id_material_list = $1
ORDER BY id_material_list_item ASC
`

type ListMaterialListItemsByMLRow struct {
	IDMaterialListItem int32              `json:"id_material_list_item"`
	IDMaterialList     int32              `json:"id_material_list"`
	Item               string             `json:"item"`
	Description        string             `json:"description"`
	Qty                int32              `json:"qty"`
	Unit               string             `json:"unit"`
	EstPrice           pgtype.Numeric     `json:"est_price"`
	IDWoShell          pgtype.Int4        `json:"id_wo_shell"`
	IDWoTrim           pgtype.Int4        `json:"id_wo_trim"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMaterialListItemsByML(ctx context.Context, idMaterialList int32) ([]ListMaterialListItemsByMLRow, error) {
	rows, err := q.db.Query(ctx, listMaterialListItemsByML, idMaterialList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaterialListItemsByMLRow
	for rows.Next() {
		var i ListMaterialListItemsByMLRow
		if err := rows.Scan(
			&i.IDMaterialListItem,
			&i.IDMaterialList,
			&i.Item,
			&i.Description,
			&i.Qty,
			&i.Unit,
			&i.EstPrice,
			&i.IDWoShell,
			&i.IDWoTrim,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnlockedMaterialListsByWO = `-- name: ListUnlockedMaterialListsByWO :many
SELECT id_material_list, id_wo, name, is_locked, created_at
FROM MATERIAL_LIST
WHERE id_wo = $1 AND is_locked = FALSE
ORDER BY id_material_list ASC
`

type ListUnlockedMaterialListsByWORow struct {
	IDMaterialList int32              `json:"id_material_list"`
	IDWo           int32              `json:"id_wo"`
	Name           string             `json:"name"`
	IsLocked       bool               `json:"is_locked"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUnlockedMaterialListsByWO(ctx context.Context, idWo int32) ([]ListUnlockedMaterialListsByWORow, error) {
	rows, err := q.db.Query(ctx, listUnlockedMaterialListsByWO, idWo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnlockedMaterialListsByWORow
	for rows.Next() {
		var i ListUnlockedMaterialListsByWORow
		if err := rows.Scan(
			&i.IDMaterialList,
			&i.IDWo,
			&i.Name,
			&i.IsLocked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMaterialList = `-- name: LockMaterialList :one
UPDATE MATERIAL_LIST
SET is_locked = TRUE
WHERE id_material_list = $1
RETURNING id_material_list, id_wo, name, is_locked, created_at
`

type LockMaterialListRow struct {
	IDMaterialList int32              `json:"id_material_list"`
	IDWo           int32              `json:"id_wo"`
	Name           string             `json:"name"`
	IsLocked       bool               `json:"is_locked"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) LockMaterialList(ctx context.Context, idMaterialList int32) (LockMaterialListRow, error) {
	row := q.db.QueryRow(ctx, lockMaterialList, idMaterialList)
	var i LockMaterialListRow
	err := row.Scan(
		&i.IDMaterialList,
		&i.IDWo,
		&i.Name,
		&i.IsLocked,
		&i.CreatedAt,
	)
	return i, err
}

const updateMaterialList = `-- name: UpdateMaterialList :one
UPDATE MATERIAL_LIST
SET name = $1
WHERE id_material_list = $2
  AND is_locked = FALSE
RETURNING id_material_list, id_wo, name, is_locked, created_at
`

type UpdateMaterialListParams struct {
	Name           string `json:"name"`
	IDMaterialList int32  `json:"id_material_list"`
}

type UpdateMaterialListRow struct {
	IDMaterialList int32              `json:"id_material_list"`
	IDWo           int32              `json:"id_wo"`
	Name           string             `json:"name"`
	IsLocked       bool               `json:"is_locked"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateMaterialList(ctx context.Context, arg UpdateMaterialListParams) (UpdateMaterialListRow, error) {
	row := q.db.QueryRow(ctx, updateMaterialList, arg.Name, arg.IDMaterialList)
	var i UpdateMaterialListRow
	err := row.Scan(
		&i.IDMaterialList,
		&i.IDWo,
		&i.Name,
		&i.IsLocked,
		&i.CreatedAt,
	)
	return i, err
}

const updateMaterialListItem = `-- name: UpdateMaterialListItem :one
UPDATE MATERIAL_LIST_ITEM
SET
    item = $1,
    description = $2,
    qty = $3,
    unit = $4,
    est_price = $5::numeric,
    id_wo_shell = $6,
    id_wo_trim = $7
WHERE id_material_list_item = $8
  AND id_material_list IN (
      SELECT id_material_list FROM MATERIAL_LIST WHERE is_locked = FALSE
  )
RETURNING id_material_list_item, id_material_list, item, description, qty, unit, est_price, id_wo_shell, id_wo_trim, created_at
`

type UpdateMaterialListItemParams struct {
	Item               string         `json:"item"`
	Description        string         `json:"description"`
	Qty                int32          `json:"qty"`
	Unit               string         `json:"unit"`
	EstPrice           pgtype.Numeric `json:"est_price"`
	IDWoShell          pgtype.Int4    `json:"id_wo_shell"`
	IDWoTrim           pgtype.Int4    `json:"id_wo_trim"`
	IDMaterialListItem int32          `json:"id_material_list_item"`
}

type UpdateMaterialListItemRow struct {
	IDMaterialListItem int32              `json:"id_material_list_item"`
	IDMaterialList     int32              `json:"id_material_list"`
	Item               string             `json:"item"`
	Description        string             `json:"description"`
	Qty                int32              `json:"qty"`
	Unit               string             `json:"unit"`
	EstPrice           pgtype.Numeric     `json:"est_price"`
	IDWoShell          pgtype.Int4        `json:"id_wo_shell"`
	IDWoTrim           pgtype.Int4        `json:"id_wo_trim"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateMaterialListItem(ctx context.Context, arg UpdateMaterialListItemParams) (UpdateMaterialListItemRow, error) {
	row := q.db.QueryRow(ctx, updateMaterialListItem,
		arg.Item,
		arg.Description,
		arg.Qty,
		arg.Unit,
		arg.EstPrice,
		arg.IDWoShell,
		arg.IDWoTrim,
		arg.IDMaterialListItem,
	)
	var i UpdateMaterialListItemRow
	err := row.Scan(
		&i.IDMaterialListItem,
		&i.IDMaterialList,
		&i.Item,
		&i.Description,
		&i.Qty,
		&i.Unit,
		&i.EstPrice,
		&i.IDWoShell,
		&i.IDWoTrim,
		&i.CreatedAt,
	)
	return i, err
}
