// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mitra.sql

package entity

import (
	"context"
)

const createMitra = `-- name: CreateMitra :one
INSERT INTO MITRA (
    nama_perusahaan, tipe_perusahaan, email, no_telp, alamat, kota, kode_pos
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id_mitra, nama_perusahaan, tipe_perusahaan, email, no_telp, alamat, kota, kode_pos, created_at
`

type CreateMitraParams struct {
	NamaPerusahaan string `json:"nama_perusahaan"`
	TipePerusahaan string `json:"tipe_perusahaan"`
	Email          string `json:"email"`
	NoTelp         string `json:"no_telp"`
	Alamat         string `json:"alamat"`
	Kota           string `json:"kota"`
	KodePos        string `json:"kode_pos"`
}

func (q *Queries) CreateMitra(ctx context.Context, arg CreateMitraParams) (Mitra, error) {
	row := q.db.QueryRow(ctx, createMitra,
		arg.NamaPerusahaan,
		arg.TipePerusahaan,
		arg.Email,
		arg.NoTelp,
		arg.Alamat,
		arg.Kota,
		arg.KodePos,
	)
	var i Mitra
	err := row.Scan(
		&i.IDMitra,
		&i.NamaPerusahaan,
		&i.TipePerusahaan,
		&i.Email,
		&i.NoTelp,
		&i.Alamat,
		&i.Kota,
		&i.KodePos,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMitra = `-- name: DeleteMitra :execrows
DELETE FROM MITRA
WHERE id_mitra = $1
`

func (q *Queries) DeleteMitra(ctx context.Context, idMitra int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMitra, idMitra)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMitraByID = `-- name: GetMitraByID :one
SELECT id_mitra, nama_perusahaan, tipe_perusahaan, email, no_telp, alamat, kota, kode_pos, created_at FROM MITRA
WHERE id_mitra = $1 LIMIT 1
`

func (q *Queries) GetMitraByID(ctx context.Context, idMitra int32) (Mitra, error) {
	row := q.db.QueryRow(ctx, getMitraByID, idMitra)
	var i Mitra
	err := row.Scan(
		&i.IDMitra,
		&i.NamaPerusahaan,
		&i.TipePerusahaan,
		&i.Email,
		&i.NoTelp,
		&i.Alamat,
		&i.Kota,
		&i.KodePos,
		&i.CreatedAt,
	)
	return i, err
}

const listMitra = `-- name: ListMitra :many
SELECT id_mitra, nama_perusahaan, tipe_perusahaan, email, no_telp, alamat, kota, kode_pos, created_at FROM MITRA
ORDER BY nama_perusahaan ASC
`

func (q *Queries) ListMitra(ctx context.Context) ([]Mitra, error) {
	rows, err := q.db.Query(ctx, listMitra)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mitra
	for rows.Next() {
		var i Mitra
		if err := rows.Scan(
			&i.IDMitra,
			&i.NamaPerusahaan,
			&i.TipePerusahaan,
			&i.Email,
			&i.NoTelp,
			&i.Alamat,
			&i.Kota,
			&i.KodePos,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMitra = `-- name: UpdateMitra :one
UPDATE MITRA
SET nama_perusahaan = $2, tipe_perusahaan = $3, email = $4, no_telp = $5, alamat = $6, kota = $7, kode_pos = $8
WHERE id_mitra = $1
RETURNING id_mitra, nama_perusahaan, tipe_perusahaan, email, no_telp, alamat, kota, kode_pos, created_at
`

type UpdateMitraParams struct {
	IDMitra        int32  `json:"id_mitra"`
	NamaPerusahaan string `json:"nama_perusahaan"`
	TipePerusahaan string `json:"tipe_perusahaan"`
	Email          string `json:"email"`
	NoTelp         string `json:"no_telp"`
	Alamat         string `json:"alamat"`
	Kota           string `json:"kota"`
	KodePos        string `json:"kode_pos"`
}

func (q *Queries) UpdateMitra(ctx context.Context, arg UpdateMitraParams) (Mitra, error) {
	row := q.db.QueryRow(ctx, updateMitra,
		arg.IDMitra,
		arg.NamaPerusahaan,
		arg.TipePerusahaan,
		arg.Email,
		arg.NoTelp,
		arg.Alamat,
		arg.Kota,
		arg.KodePos,
	)
	var i Mitra
	err := row.Scan(
		&i.IDMitra,
		&i.NamaPerusahaan,
		&i.TipePerusahaan,
		&i.Email,
		&i.NoTelp,
		&i.Alamat,
		&i.Kota,
		&i.KodePos,
		&i.CreatedAt,
	)
	return i, err
}
