// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package entity

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Barang struct {
	IDBarang      int32              `json:"id_barang"`
	NamaBarang    string             `json:"nama_barang"`
	Kode          string             `json:"kode"`
	IDJenisBarang int32              `json:"id_jenis_barang"`
	IDMitra       int32              `json:"id_mitra"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Company struct {
	IDCompany int32              `json:"id_company"`
	Nama      string             `json:"nama"`
	Alamat    string             `json:"alamat"`
	Email     string             `json:"email"`
	NoTelp    string             `json:"no_telp"`
	About     string             `json:"about"`
	Logo      string             `json:"logo"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Departeman struct {
	IDDepartemen   int32              `json:"id_departemen"`
	NamaDepartemen string             `json:"nama_departemen"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type HakAkse struct {
	IDHakAkses  int32              `json:"id_hak_akses"`
	NamaHalaman string             `json:"nama_halaman"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type JenisBarang struct {
	IDJenisBarang   int32              `json:"id_jenis_barang"`
	NamaJenisBarang string             `json:"nama_jenis_barang"`
	Kode            string             `json:"kode"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type LogAktivita struct {
	IDLog     int32              `json:"id_log"`
	Aksi      string             `json:"aksi"`
	Waktu     pgtype.Timestamptz `json:"waktu"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LogAktivitasDetail struct {
	IDLogDetail int32              `json:"id_log_detail"`
	Nama        string             `json:"nama"`
	TableName   string             `json:"table_name"`
	Deskripsi   string             `json:"deskripsi"`
	IDLog       int32              `json:"id_log"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MaterialList struct {
	IDMaterialList int32              `json:"id_material_list"`
	Description    string             `json:"description"`
	Size           string             `json:"size"`
	Color          string             `json:"color"`
	Uom            string             `json:"uom"`
	IDWo           int32              `json:"id_wo"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Mitra struct {
	IDMitra        int32              `json:"id_mitra"`
	NamaPerusahaan string             `json:"nama_perusahaan"`
	TipePerusahaan string             `json:"tipe_perusahaan"`
	Email          string             `json:"email"`
	NoTelp         string             `json:"no_telp"`
	Alamat         string             `json:"alamat"`
	Kota           string             `json:"kota"`
	KodePos        string             `json:"kode_pos"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PackingList struct {
	IDPackingList        int32              `json:"id_packing_list"`
	TotalGarmentPerBox   int32              `json:"total_garment_per_box"`
	TotalReject          int32              `json:"total_reject"`
	IDWo                 int32              `json:"id_wo"`
	IDSuratJalanInternal pgtype.Int4        `json:"id_surat_jalan_internal"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type PackingListItem struct {
	IDPackingListItem int32              `json:"id_packing_list_item"`
	IDPackingList     int32              `json:"id_packing_list"`
	Color             string             `json:"color"`
	QtyBox            int32              `json:"qty_box"`
	QtyPerBox         int32              `json:"qty_per_box"`
	BoxNoStart        int32              `json:"box_no_start"`
	BoxNoEnd          int32              `json:"box_no_end"`
	Note              string             `json:"note"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type PackingListItemSize struct {
	IDPackingListItemSize int32              `json:"id_packing_list_item_size"`
	Qty                   int32              `json:"qty"`
	IDPackingListItem     int32              `json:"id_packing_list_item"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type PenanggungJawab struct {
	IDPenanggungJawab int32              `json:"id_penanggung_jawab"`
	Nama              string             `json:"nama"`
	NoTelp            string             `json:"no_telp"`
	Email             string             `json:"email"`
	IDPoClient        int32              `json:"id_po_client"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type PoClient struct {
	IDPoClient  int32              `json:"id_po_client"`
	PoNumber    string             `json:"po_number"`
	Tanggal     pgtype.Date        `json:"tanggal"`
	Season      string             `json:"season"`
	Delivery    pgtype.Date        `json:"delivery"`
	PaymentTerm string             `json:"payment_term"`
	File        string             `json:"file"`
	IDMitra     int32              `json:"id_mitra"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PoClientItem struct {
	IDPoClientItem int32              `json:"id_po_client_item"`
	IDPoClient     int32              `json:"id_po_client"`
	Style          string             `json:"style"`
	Colour         string             `json:"colour"`
	Description    string             `json:"description"`
	Qty            int32              `json:"qty"`
	Price          pgtype.Numeric     `json:"price"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PoInternal struct {
	IDPoInternal    int32              `json:"id_po_internal"`
	Tanggal         pgtype.Date        `json:"tanggal"`
	NamaPo          string             `json:"nama_po"`
	SupplierName    string             `json:"supplier_name"`
	SupplierAddr    string             `json:"supplier_addr"`
	SupplierContact string             `json:"supplier_contact"`
	SupplierEmail   string             `json:"supplier_email"`
	SupplierTelp    string             `json:"supplier_telp"`
	SupplierFax     string             `json:"supplier_fax"`
	Currency        string             `json:"currency"`
	Cpo             string             `json:"cpo"`
	Term            string             `json:"term"`
	ShipDate        pgtype.Date        `json:"ship_date"`
	IDPrInternal    int32              `json:"id_pr_internal"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PoInternalItem struct {
	IDPoInternalItem int32              `json:"id_po_internal_item"`
	IDPoInternal     int32              `json:"id_po_internal"`
	Item             string             `json:"item"`
	Description      string             `json:"description"`
	Qty              int32              `json:"qty"`
	Unit             string             `json:"unit"`
	UnitPrice        pgtype.Numeric     `json:"unit_price"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type PrInternal struct {
	IDPrInternal     int32              `json:"id_pr_internal"`
	Tanggal          pgtype.Date        `json:"tanggal"`
	Nama             string             `json:"nama"`
	Departemen       string             `json:"departemen"`
	VendorName       string             `json:"vendor_name"`
	VendorAddress    string             `json:"vendor_address"`
	VendorTelp       string             `json:"vendor_telp"`
	Projek           string             `json:"projek"`
	IDWo             int32              `json:"id_wo"`
	IDUser           int32              `json:"id_user"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Status           string             `json:"status"`
	ApprovedByUserID pgtype.Int4        `json:"approved_by_user_id"`
	ApprovedAt       pgtype.Timestamptz `json:"approved_at"`
}

type PrInternalItem struct {
	IDPrInternalItem int32              `json:"id_pr_internal_item"`
	IDPrInternal     int32              `json:"id_pr_internal"`
	Item             string             `json:"item"`
	Description      string             `json:"description"`
	Qty              int32              `json:"qty"`
	Unit             string             `json:"unit"`
	EstPrice         pgtype.Numeric     `json:"est_price"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Received struct {
	IDReceived     int32              `json:"id_received"`
	Tanggal        pgtype.Date        `json:"tanggal"`
	Qty            int32              `json:"qty"`
	Keterangan     string             `json:"keterangan"`
	IDMaterialList int32              `json:"id_material_list"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RekonsiliasiMaterial struct {
	IDRekonsiliasiMaterial int32              `json:"id_rekonsiliasi_material"`
	Description            string             `json:"description"`
	Size                   string             `json:"size"`
	Ratio                  int32              `json:"ratio"`
	QtyPerPcs              pgtype.Numeric     `json:"qty_per_pcs"`
	QtyWo                  int32              `json:"qty_wo"`
	Toleransi              int32              `json:"toleransi"`
	Satuan                 string             `json:"satuan"`
	ActualKirim            int32              `json:"actual_kirim"`
	ConsActual             pgtype.Numeric     `json:"cons_actual"`
	Balance                int32              `json:"balance"`
	Reject                 int32              `json:"reject"`
	Retur                  int32              `json:"retur"`
	LastBalance            int32              `json:"last_balance"`
	Keterangan             string             `json:"keterangan"`
	IDWo                   int32              `json:"id_wo"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type RekonsiliasiMaterialTerima struct {
	IDRekonsiliasiMaterialTerima int32              `json:"id_rekonsiliasi_material_terima"`
	Keterangan                   string             `json:"keterangan"`
	Qty                          int32              `json:"qty"`
	IDRekonsiliasiMaterial       int32              `json:"id_rekonsiliasi_material"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
}

type ReportCutting struct {
	IDReportCutting int32              `json:"id_report_cutting"`
	Tanggal         pgtype.Date        `json:"tanggal"`
	Qty             int32              `json:"qty"`
	IDWoShellSize   int32              `json:"id_wo_shell_size"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ReportPacking struct {
	IDReportPacking int32              `json:"id_report_packing"`
	Tanggal         pgtype.Date        `json:"tanggal"`
	Qty             int32              `json:"qty"`
	IDWoShellSize   int32              `json:"id_wo_shell_size"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ReportPengiriman struct {
	IDReportPengiriman int32              `json:"id_report_pengiriman"`
	ReportDate         pgtype.Date        `json:"report_date"`
	Qty                int32              `json:"qty"`
	IDWoShellSize      int32              `json:"id_wo_shell_size"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ReportQcFinish struct {
	IDReportQcFinishing int32              `json:"id_report_qc_finishing"`
	Tanggal             pgtype.Date        `json:"tanggal"`
	Qty                 int32              `json:"qty"`
	IDWoShellSize       int32              `json:"id_wo_shell_size"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type ReportSewing struct {
	IDReportSewing int32              `json:"id_report_sewing"`
	Tanggal        pgtype.Date        `json:"tanggal"`
	Qty            int32              `json:"qty"`
	IDWoShellSize  int32              `json:"id_wo_shell_size"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SuratJalanClient struct {
	IDSuratJalanClient int32              `json:"id_surat_jalan_client"`
	Tanggal            pgtype.Date        `json:"tanggal"`
	Qty                int32              `json:"qty"`
	Keterangan         string             `json:"keterangan"`
	IDMaterialList     int32              `json:"id_material_list"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type SuratJalanInternal struct {
	IDSuratJalanInternal int32              `json:"id_surat_jalan_internal"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	IDUser       int32              `json:"id_user"`
	Username     string             `json:"username"`
	Password     string             `json:"password"`
	IsManager    bool               `json:"is_manager"`
	IDDepartemen pgtype.Int4        `json:"id_departemen"`
	IDMitra      pgtype.Int4        `json:"id_mitra"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type UserAkse struct {
	IDUser     int32              `json:"id_user"`
	IDHakAkses int32              `json:"id_hak_akses"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type WorkOrder struct {
	IDWo           int32              `json:"id_wo"`
	Buyer          string             `json:"buyer"`
	Model          string             `json:"model"`
	Qty            int32              `json:"qty"`
	FobCmt         bool               `json:"fob_cmt"`
	Delivery       pgtype.Date        `json:"delivery"`
	IDPoClientItem int32              `json:"id_po_client_item"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Status         string             `json:"status"`
	ClosedByUserID pgtype.Int4        `json:"closed_by_user_id"`
	ClosedAt       pgtype.Timestamptz `json:"closed_at"`
}

type WorkOrderShell struct {
	IDWoShell int32              `json:"id_wo_shell"`
	Fabric    string             `json:"fabric"`
	Cons      pgtype.Numeric     `json:"cons"`
	Color     string             `json:"color"`
	Allow     int32              `json:"allow"`
	Berat1Yd  pgtype.Numeric     `json:"berat_1_yd"`
	IDWo      int32              `json:"id_wo"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WorkOrderShellSize struct {
	IDWoShellSize int32              `json:"id_wo_shell_size"`
	Size          string             `json:"size"`
	Qty           int32              `json:"qty"`
	Ratio         int32              `json:"ratio"`
	IDWoShell     int32              `json:"id_wo_shell"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type WorkOrderTrim struct {
	IDWoTrim    int32              `json:"id_wo_trim"`
	Item        string             `json:"item"`
	Description string             `json:"description"`
	Color       string             `json:"color"`
	Code        string             `json:"code"`
	Cons        pgtype.Numeric     `json:"cons"`
	Qty         int32              `json:"qty"`
	Uom         string             `json:"uom"`
	Position    string             `json:"position"`
	CreatedBy   string             `json:"created_by"`
	Allow       int32              `json:"allow"`
	IDWo        int32              `json:"id_wo"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
