// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package entity

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ArsipDokumenGabungan struct {
	IDArsip        int32              `json:"id_arsip"`
	NamaDokumen    string             `json:"nama_dokumen"`
	TipeDokumen    string             `json:"tipe_dokumen"`
	ParameterQuery string             `json:"parameter_query"`
	FileUrl        string             `json:"file_url"`
	IDPembuat      int32              `json:"id_pembuat"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID            int64              `json:"id"`
	ActorUserID   pgtype.Int4        `json:"actor_user_id"`
	ActorUsername string             `json:"actor_username"`
	ActorRole     string             `json:"actor_role"`
	Action        string             `json:"action"`
	Module        string             `json:"module"`
	EntityType    string             `json:"entity_type"`
	EntityID      string             `json:"entity_id"`
	EntityLabel   string             `json:"entity_label"`
	Method        string             `json:"method"`
	Route         string             `json:"route"`
	BeforeData    []byte             `json:"before_data"`
	AfterData     []byte             `json:"after_data"`
	ChangedFields []byte             `json:"changed_fields"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Barang struct {
	IDBarang      int32              `json:"id_barang"`
	NamaBarang    string             `json:"nama_barang"`
	Kode          string             `json:"kode"`
	IDJenisBarang int32              `json:"id_jenis_barang"`
	IDMitra       int32              `json:"id_mitra"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Satuan        string             `json:"satuan"`
	LokasiRak     string             `json:"lokasi_rak"`
	StokMinimum   int32              `json:"stok_minimum"`
}

type Departeman struct {
	IDDepartemen   int32              `json:"id_departemen"`
	NamaDepartemen string             `json:"nama_departemen"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type HakAkse struct {
	IDHakAkses       int32              `json:"id_hak_akses"`
	NamaHalaman      string             `json:"nama_halaman"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	KodePermission   string             `json:"kode_permission"`
	Deskripsi        string             `json:"deskripsi"`
	DomainPermission string             `json:"domain_permission"`
	AksiPermission   string             `json:"aksi_permission"`
}

type JenisBarang struct {
	IDJenisBarang   int32              `json:"id_jenis_barang"`
	NamaJenisBarang string             `json:"nama_jenis_barang"`
	Kode            string             `json:"kode"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type KomponenMarkerPlan struct {
	IDKomponenMarker int32              `json:"id_komponen_marker"`
	IDMarkerPlan     int32              `json:"id_marker_plan"`
	NamaKomponen     string             `json:"nama_komponen"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type KomponenSpreadingCuttingPlan struct {
	IDKomponenSpreading    int32              `json:"id_komponen_spreading"`
	IDSpreadingCuttingPlan int32              `json:"id_spreading_cutting_plan"`
	NamaKomponen           string             `json:"nama_komponen"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type LogAktivita struct {
	IDLog     int32              `json:"id_log"`
	Aksi      string             `json:"aksi"`
	Waktu     pgtype.Timestamptz `json:"waktu"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LogAktivitasDetail struct {
	IDLogDetail int32              `json:"id_log_detail"`
	Nama        string             `json:"nama"`
	TableName   string             `json:"table_name"`
	Deskripsi   string             `json:"deskripsi"`
	IDLog       int32              `json:"id_log"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MarkerPlan struct {
	IDMarkerPlan   int32              `json:"id_marker_plan"`
	NoDokumen      string             `json:"no_dokumen"`
	TanggalEfektif pgtype.Date        `json:"tanggal_efektif"`
	IDWoShell      int32              `json:"id_wo_shell"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type MasterSize struct {
	IDSize    int32              `json:"id_size"`
	NamaSize  string             `json:"nama_size"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MaterialList struct {
	IDMaterialList int32              `json:"id_material_list"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	IDWo           int32              `json:"id_wo"`
	Name           string             `json:"name"`
	IsLocked       bool               `json:"is_locked"`
}

type MaterialListItem struct {
	IDMaterialListItem int32              `json:"id_material_list_item"`
	Description        string             `json:"description"`
	IDWoShell          pgtype.Int4        `json:"id_wo_shell"`
	IDWoTrim           pgtype.Int4        `json:"id_wo_trim"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	IDMaterialList     int32              `json:"id_material_list"`
	Item               string             `json:"item"`
	Qty                int32              `json:"qty"`
	Unit               string             `json:"unit"`
	EstPrice           pgtype.Numeric     `json:"est_price"`
}

type Mitra struct {
	IDMitra        int32              `json:"id_mitra"`
	NamaPerusahaan string             `json:"nama_perusahaan"`
	TipePerusahaan string             `json:"tipe_perusahaan"`
	Email          string             `json:"email"`
	NoTelp         string             `json:"no_telp"`
	Alamat         string             `json:"alamat"`
	Kota           string             `json:"kota"`
	KodePos        string             `json:"kode_pos"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type OtoritasDokuman struct {
	IDOtoritas       int32              `json:"id_otoritas"`
	NamaTabelDokumen string             `json:"nama_tabel_dokumen"`
	IDDokumen        int32              `json:"id_dokumen"`
	StatusGlobal     string             `json:"status_global"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type OtoritasDokumenDetail struct {
	IDOtoritasDetail int32              `json:"id_otoritas_detail"`
	IDOtoritas       int32              `json:"id_otoritas"`
	IDUser           int32              `json:"id_user"`
	TipePeran        string             `json:"tipe_peran"`
	IsActionDone     bool               `json:"is_action_done"`
	WaktuAksi        pgtype.Timestamptz `json:"waktu_aksi"`
	Catatan          string             `json:"catatan"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type PackingList struct {
	IDPackingList        int32              `json:"id_packing_list"`
	TotalGarmentPerBox   int32              `json:"total_garment_per_box"`
	TotalReject          int32              `json:"total_reject"`
	IDWo                 int32              `json:"id_wo"`
	IDSuratJalanInternal pgtype.Int4        `json:"id_surat_jalan_internal"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type PackingListItem struct {
	IDPackingListItem int32              `json:"id_packing_list_item"`
	IDPackingList     int32              `json:"id_packing_list"`
	Color             string             `json:"color"`
	QtyBox            int32              `json:"qty_box"`
	QtyPerBox         int32              `json:"qty_per_box"`
	BoxNoStart        int32              `json:"box_no_start"`
	BoxNoEnd          int32              `json:"box_no_end"`
	Note              string             `json:"note"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type PackingListItemSize struct {
	IDPackingListItemSize int32              `json:"id_packing_list_item_size"`
	Qty                   int32              `json:"qty"`
	IDPackingListItem     int32              `json:"id_packing_list_item"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	IDWoShellSize         int32              `json:"id_wo_shell_size"`
}

type PackingListRejectSize struct {
	IDPackingListRejectSize int32              `json:"id_packing_list_reject_size"`
	Qty                     int32              `json:"qty"`
	IDPackingList           int32              `json:"id_packing_list"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	IDWoShellSize           int32              `json:"id_wo_shell_size"`
}

type PasswordResetRequest struct {
	IDPasswordResetRequest int32              `json:"id_password_reset_request"`
	IDUser                 int32              `json:"id_user"`
	Reason                 string             `json:"reason"`
	Status                 string             `json:"status"`
	ApprovedBy             pgtype.Int4        `json:"approved_by"`
	ApprovedAt             pgtype.Timestamptz `json:"approved_at"`
	RejectedBy             pgtype.Int4        `json:"rejected_by"`
	RejectedAt             pgtype.Timestamptz `json:"rejected_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	RejectedReason         string             `json:"rejected_reason"`
	RequestedAt            pgtype.Timestamptz `json:"requested_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type PenanggungJawab struct {
	IDPenanggungJawab int32              `json:"id_penanggung_jawab"`
	Nama              string             `json:"nama"`
	NoTelp            string             `json:"no_telp"`
	Email             string             `json:"email"`
	IDPoClient        int32              `json:"id_po_client"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type PoClient struct {
	IDPoClient  int32              `json:"id_po_client"`
	PoNumber    string             `json:"po_number"`
	Tanggal     pgtype.Date        `json:"tanggal"`
	Season      string             `json:"season"`
	Delivery    pgtype.Date        `json:"delivery"`
	PaymentTerm string             `json:"payment_term"`
	File        string             `json:"file"`
	IDMitra     int32              `json:"id_mitra"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PoClientItem struct {
	IDPoClientItem int32              `json:"id_po_client_item"`
	IDPoClient     int32              `json:"id_po_client"`
	Style          string             `json:"style"`
	Colour         string             `json:"colour"`
	Description    string             `json:"description"`
	Qty            int32              `json:"qty"`
	Price          pgtype.Numeric     `json:"price"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PoInternal struct {
	IDPoInternal    int32              `json:"id_po_internal"`
	Tanggal         pgtype.Date        `json:"tanggal"`
	NamaPo          string             `json:"nama_po"`
	SupplierName    string             `json:"supplier_name"`
	SupplierAddr    string             `json:"supplier_addr"`
	SupplierContact string             `json:"supplier_contact"`
	SupplierEmail   string             `json:"supplier_email"`
	SupplierTelp    string             `json:"supplier_telp"`
	SupplierFax     string             `json:"supplier_fax"`
	Currency        string             `json:"currency"`
	Cpo             string             `json:"cpo"`
	Term            string             `json:"term"`
	ShipDate        pgtype.Date        `json:"ship_date"`
	IDPrInternal    int32              `json:"id_pr_internal"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PoInternalItem struct {
	IDPoInternalItem int32              `json:"id_po_internal_item"`
	IDPoInternal     int32              `json:"id_po_internal"`
	Item             string             `json:"item"`
	Description      string             `json:"description"`
	Qty              int32              `json:"qty"`
	Unit             string             `json:"unit"`
	UnitPrice        pgtype.Numeric     `json:"unit_price"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type PrInternal struct {
	IDPrInternal  int32              `json:"id_pr_internal"`
	Tanggal       pgtype.Date        `json:"tanggal"`
	Nama          string             `json:"nama"`
	Departemen    string             `json:"departemen"`
	VendorName    string             `json:"vendor_name"`
	VendorAddress string             `json:"vendor_address"`
	VendorTelp    string             `json:"vendor_telp"`
	Projek        string             `json:"projek"`
	IDWo          int32              `json:"id_wo"`
	IDUser        int32              `json:"id_user"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PrInternalItem struct {
	IDPrInternalItem int32              `json:"id_pr_internal_item"`
	IDPrInternal     int32              `json:"id_pr_internal"`
	Item             string             `json:"item"`
	Description      string             `json:"description"`
	Qty              int32              `json:"qty"`
	Unit             string             `json:"unit"`
	EstPrice         pgtype.Numeric     `json:"est_price"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type ProductionLine struct {
	IDProductionLine int32              `json:"id_production_line"`
	Name             string             `json:"name"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type ProductionStatusPlan struct {
	IDProductionStatusPlan int32              `json:"id_production_status_plan"`
	Name                   string             `json:"name"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type ProfilPerusahaan struct {
	IDProfilPerusahaan int32              `json:"id_profil_perusahaan"`
	Nama               string             `json:"nama"`
	Alamat             string             `json:"alamat"`
	Email              string             `json:"email"`
	NoTelp             string             `json:"no_telp"`
	About              string             `json:"about"`
	Logo               string             `json:"logo"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	BackgroundLogin    string             `json:"background_login"`
	TextFooter         string             `json:"text_footer"`
	LinkWebsite        string             `json:"link_website"`
	Medsos             []byte             `json:"medsos"`
}

type RatioMarker struct {
	IDRatioMarker        int32              `json:"id_ratio_marker"`
	IDKomponenMarker     int32              `json:"id_komponen_marker"`
	IDWoShell            int32              `json:"id_wo_shell"`
	Cons                 pgtype.Numeric     `json:"cons"`
	PlanSpreadingGelaran pgtype.Numeric     `json:"plan_spreading_gelaran"`
	PanjangMarker        pgtype.Numeric     `json:"panjang_marker"`
	EfficiencyMarker     pgtype.Numeric     `json:"efficiency_marker"`
	Allowance            pgtype.Numeric     `json:"allowance"`
	ConsBuyer            pgtype.Numeric     `json:"cons_buyer"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	Plot                 int32              `json:"plot"`
	LebarKain            pgtype.Numeric     `json:"lebar_kain"`
	PanjangMarkerUnit    string             `json:"panjang_marker_unit"`
	Ket                  string             `json:"ket"`
}

type RatioSizeMarker struct {
	IDRatioSizeMarker int32              `json:"id_ratio_size_marker"`
	IDRatioMarker     int32              `json:"id_ratio_marker"`
	IDWoShellSize     int32              `json:"id_wo_shell_size"`
	RatioPlan         int32              `json:"ratio_plan"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type RatioSizeSpreading struct {
	IDRatioSizeSpreading int32              `json:"id_ratio_size_spreading"`
	IDRatioSpreading     int32              `json:"id_ratio_spreading"`
	IDWoShellSize        int32              `json:"id_wo_shell_size"`
	RatioPlan            int32              `json:"ratio_plan"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type RatioSpreading struct {
	IDRatioSpreading     int32              `json:"id_ratio_spreading"`
	IDKomponenSpreading  int32              `json:"id_komponen_spreading"`
	IDWoShell            int32              `json:"id_wo_shell"`
	Cons                 pgtype.Numeric     `json:"cons"`
	PlanSpreadingGelaran pgtype.Numeric     `json:"plan_spreading_gelaran"`
	Allowance            pgtype.Numeric     `json:"allowance"`
	RollQty              int32              `json:"roll_qty"`
	SambunganRoll        int32              `json:"sambungan_roll"`
	Reject               pgtype.Numeric     `json:"reject"`
	LebarKain            pgtype.Numeric     `json:"lebar_kain"`
	Ket                  string             `json:"ket"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type Received struct {
	IDReceived         int32              `json:"id_received"`
	Tanggal            pgtype.Date        `json:"tanggal"`
	Qty                int32              `json:"qty"`
	Keterangan         string             `json:"keterangan"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	IDMaterialListItem int32              `json:"id_material_list_item"`
}

type Rekonsiliasi struct {
	IDRekonsiliasi   int32              `json:"id_rekonsiliasi"`
	IDWo             int32              `json:"id_wo"`
	Jasa             string             `json:"jasa"`
	NoPo             string             `json:"no_po"`
	Delivery         pgtype.Date        `json:"delivery"`
	Buyer            string             `json:"buyer"`
	Brand            string             `json:"brand"`
	Style            string             `json:"style"`
	QtyPo            int32              `json:"qty_po"`
	PlanCutTotal     int64              `json:"plan_cut_total"`
	ConsBajuSummary  string             `json:"cons_baju_summary"`
	NamaBahan        string             `json:"nama_bahan"`
	WarnaKainSummary []byte             `json:"warna_kain_summary"`
	CreatedBy        pgtype.Int4        `json:"created_by"`
	UpdatedBy        pgtype.Int4        `json:"updated_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type RekonsiliasiMaterial struct {
	IDRekonsiliasiMaterial int32              `json:"id_rekonsiliasi_material"`
	Description            string             `json:"description"`
	Size                   string             `json:"size"`
	Ratio                  int32              `json:"ratio"`
	QtyPerPcs              pgtype.Numeric     `json:"qty_per_pcs"`
	QtyWo                  int32              `json:"qty_wo"`
	Toleransi              int32              `json:"toleransi"`
	Satuan                 string             `json:"satuan"`
	ActualKirim            int32              `json:"actual_kirim"`
	ConsActual             pgtype.Numeric     `json:"cons_actual"`
	Balance                int32              `json:"balance"`
	Reject                 int32              `json:"reject"`
	Retur                  int32              `json:"retur"`
	LastBalance            int32              `json:"last_balance"`
	Keterangan             string             `json:"keterangan"`
	IDWo                   int32              `json:"id_wo"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type RekonsiliasiMaterialRow struct {
	IDRekonsiliasiMaterialRow int32              `json:"id_rekonsiliasi_material_row"`
	IDRekonsiliasi            int32              `json:"id_rekonsiliasi"`
	RowNo                     int32              `json:"row_no"`
	Kategori                  string             `json:"kategori"`
	Description               string             `json:"description"`
	SizeLabel                 string             `json:"size_label"`
	RatioSource               pgtype.Numeric     `json:"ratio_source"`
	RatioInput                pgtype.Numeric     `json:"ratio_input"`
	QtyPerPcsInput            pgtype.Numeric     `json:"qty_per_pcs_input"`
	QtyWo                     int32              `json:"qty_wo"`
	Toleransi                 int32              `json:"toleransi"`
	Satuan                    string             `json:"satuan"`
	QtyActualKirimSource      int32              `json:"qty_actual_kirim_source"`
	QtyActualKirimManual      int32              `json:"qty_actual_kirim_manual"`
	RejectQty                 int32              `json:"reject_qty"`
	ReturQty                  int32              `json:"retur_qty"`
	Keterangan                string             `json:"keterangan"`
	IDMaterialListItem        pgtype.Int4        `json:"id_material_list_item"`
	IDWoShell                 pgtype.Int4        `json:"id_wo_shell"`
	IDWoTrim                  pgtype.Int4        `json:"id_wo_trim"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

type RekonsiliasiMaterialTerima struct {
	IDRekonsiliasiMaterialTerima int32              `json:"id_rekonsiliasi_material_terima"`
	Keterangan                   string             `json:"keterangan"`
	Qty                          int32              `json:"qty"`
	IDRekonsiliasiMaterial       int32              `json:"id_rekonsiliasi_material"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
}

type RekonsiliasiTerimaEntry struct {
	IDRekonsiliasiTerimaEntry int32              `json:"id_rekonsiliasi_terima_entry"`
	IDRekonsiliasiMaterialRow int32              `json:"id_rekonsiliasi_material_row"`
	EntryType                 string             `json:"entry_type"`
	EntryLabel                string             `json:"entry_label"`
	Qty                       int32              `json:"qty"`
	Note                      string             `json:"note"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

type ReportCutting struct {
	IDReportCutting int32              `json:"id_report_cutting"`
	Tanggal         pgtype.Date        `json:"tanggal"`
	Qty             int32              `json:"qty"`
	IDWoShellSize   int32              `json:"id_wo_shell_size"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ReportPacking struct {
	IDReportPacking int32              `json:"id_report_packing"`
	Tanggal         pgtype.Date        `json:"tanggal"`
	Qty             int32              `json:"qty"`
	IDWoShellSize   int32              `json:"id_wo_shell_size"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ReportPengiriman struct {
	IDReportPengiriman int32              `json:"id_report_pengiriman"`
	ReportDate         pgtype.Date        `json:"report_date"`
	Qty                int32              `json:"qty"`
	IDWoShellSize      int32              `json:"id_wo_shell_size"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ReportQcFinish struct {
	IDReportQcFinishing int32              `json:"id_report_qc_finishing"`
	Tanggal             pgtype.Date        `json:"tanggal"`
	Qty                 int32              `json:"qty"`
	IDWoShellSize       int32              `json:"id_wo_shell_size"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type ReportSewing struct {
	IDReportSewing int32              `json:"id_report_sewing"`
	Tanggal        pgtype.Date        `json:"tanggal"`
	Qty            int32              `json:"qty"`
	IDWoShellSize  int32              `json:"id_wo_shell_size"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ReturClient struct {
	IDReturClient int32              `json:"id_retur_client"`
	IDWo          int32              `json:"id_wo"`
	File          string             `json:"file"`
	Deskripsi     string             `json:"deskripsi"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	IDRole    int32              `json:"id_role"`
	NamaRole  string             `json:"nama_role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RoleHakAkse struct {
	IDRole     int32 `json:"id_role"`
	IDHakAkses int32 `json:"id_hak_akses"`
}

type SpreadingCuttingPlan struct {
	IDSpreadingCuttingPlan int32              `json:"id_spreading_cutting_plan"`
	NoDokumen              string             `json:"no_dokumen"`
	TanggalEfektif         pgtype.Date        `json:"tanggal_efektif"`
	IDWo                   int32              `json:"id_wo"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type SuratJalanClient struct {
	IDSuratJalanClient int32              `json:"id_surat_jalan_client"`
	Tanggal            pgtype.Date        `json:"tanggal"`
	Qty                int32              `json:"qty"`
	Keterangan         string             `json:"keterangan"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	IDMaterialListItem int32              `json:"id_material_list_item"`
}

type SuratJalanInternal struct {
	IDSuratJalanInternal int32              `json:"id_surat_jalan_internal"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type TimelinePlanProduksi struct {
	IDTimeline     int32              `json:"id_timeline"`
	IDPoClient     int32              `json:"id_po_client"`
	TanggalDisusun pgtype.Date        `json:"tanggal_disusun"`
	Notes          string             `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	IDUser             int32              `json:"id_user"`
	Username           string             `json:"username"`
	Password           string             `json:"password"`
	IDDepartemen       pgtype.Int4        `json:"id_departemen"`
	IDMitra            pgtype.Int4        `json:"id_mitra"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	Status             string             `json:"status"`
	IDRole             int32              `json:"id_role"`
	MustChangePassword bool               `json:"must_change_password"`
	PasswordChangedAt  pgtype.Timestamptz `json:"password_changed_at"`
	CreatedBy          pgtype.Int4        `json:"created_by"`
	UpdatedBy          pgtype.Int4        `json:"updated_by"`
}

type UserAkse struct {
	IDUser     int32              `json:"id_user"`
	IDHakAkses int32              `json:"id_hak_akses"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type VPrInternal struct {
	IDPrInternal     int32              `json:"id_pr_internal"`
	Tanggal          pgtype.Date        `json:"tanggal"`
	Nama             string             `json:"nama"`
	Departemen       string             `json:"departemen"`
	VendorName       string             `json:"vendor_name"`
	VendorAddress    string             `json:"vendor_address"`
	VendorTelp       string             `json:"vendor_telp"`
	Projek           string             `json:"projek"`
	IDWo             int32              `json:"id_wo"`
	IDUser           int32              `json:"id_user"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Status           string             `json:"status"`
	ApprovedByUserID pgtype.Int4        `json:"approved_by_user_id"`
	ApprovedAt       pgtype.Timestamptz `json:"approved_at"`
}

type VWorkOrder struct {
	IDWo           int32              `json:"id_wo"`
	Buyer          string             `json:"buyer"`
	Model          string             `json:"model"`
	Qty            int32              `json:"qty"`
	FobCmt         bool               `json:"fob_cmt"`
	Delivery       pgtype.Date        `json:"delivery"`
	IDPoClientItem int32              `json:"id_po_client_item"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Status         string             `json:"status"`
	ClosedByUserID pgtype.Int4        `json:"closed_by_user_id"`
	ClosedAt       pgtype.Timestamptz `json:"closed_at"`
}

type Warna struct {
	IDWarna   int32              `json:"id_warna"`
	NamaWarna string             `json:"nama_warna"`
	KodeHex   pgtype.Text        `json:"kode_hex"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WoShellPlan struct {
	IDWoShellPlan          int32              `json:"id_wo_shell_plan"`
	IDTimeline             int32              `json:"id_timeline"`
	IDWoShell              int32              `json:"id_wo_shell"`
	InLine                 string             `json:"in_line"`
	TglGelarCutting        pgtype.Date        `json:"tgl_gelar_cutting"`
	StatusGelarCutting     string             `json:"status_gelar_cutting"`
	TglEmbroo              pgtype.Date        `json:"tgl_embroo"`
	StatusEmbroo           string             `json:"status_embroo"`
	TglLoadingSewing       pgtype.Date        `json:"tgl_loading_sewing"`
	StatusLoadingSewing    string             `json:"status_loading_sewing"`
	TglFinishingPacking    pgtype.Date        `json:"tgl_finishing_packing"`
	StatusFinishingPacking string             `json:"status_finishing_packing"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type WorkOrder struct {
	IDWo           int32              `json:"id_wo"`
	Buyer          string             `json:"buyer"`
	Model          string             `json:"model"`
	Qty            int32              `json:"qty"`
	FobCmt         bool               `json:"fob_cmt"`
	Delivery       pgtype.Date        `json:"delivery"`
	IDPoClientItem int32              `json:"id_po_client_item"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type WorkOrderShell struct {
	IDWoShell    int32              `json:"id_wo_shell"`
	Deskripsi    string             `json:"deskripsi"`
	Cons         pgtype.Numeric     `json:"cons"`
	Color        string             `json:"color"`
	Allow        int32              `json:"allow"`
	Berat1Yd     pgtype.Numeric     `json:"berat_1_yd"`
	IDWo         int32              `json:"id_wo"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ProvidedBy   string             `json:"provided_by"`
	MaterialType string             `json:"material_type"`
}

type WorkOrderShellSize struct {
	IDWoShellSize int32              `json:"id_wo_shell_size"`
	Qty           int32              `json:"qty"`
	Ratio         int32              `json:"ratio"`
	IDWoShell     int32              `json:"id_wo_shell"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	IDSize        int32              `json:"id_size"`
}

type WorkOrderTrim struct {
	IDWoTrim    int32              `json:"id_wo_trim"`
	Item        string             `json:"item"`
	Description string             `json:"description"`
	Color       string             `json:"color"`
	Code        string             `json:"code"`
	Cons        pgtype.Numeric     `json:"cons"`
	Qty         int32              `json:"qty"`
	Uom         string             `json:"uom"`
	Position    string             `json:"position"`
	CreatedBy   string             `json:"created_by"`
	Allow       int32              `json:"allow"`
	IDWo        int32              `json:"id_wo"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProvidedBy  string             `json:"provided_by"`
}
