// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvePasswordResetRequest = `-- name: ApprovePasswordResetRequest :one
UPDATE PASSWORD_RESET_REQUESTS
SET STATUS = 'completed',
    APPROVED_BY = $2,
    APPROVED_AT = NOW(),
    COMPLETED_AT = NOW(),
    REJECTED_REASON = ''
WHERE ID_PASSWORD_RESET_REQUEST = $1
  AND STATUS = 'pending'
RETURNING
    ID_PASSWORD_RESET_REQUEST,
    ID_USER,
    REASON,
    STATUS,
    REQUESTED_AT,
    APPROVED_AT,
    REJECTED_AT,
    COMPLETED_AT,
    REJECTED_REASON,
    APPROVED_BY,
    REJECTED_BY,
    created_at
`

type ApprovePasswordResetRequestParams struct {
	IDPasswordResetRequest int32       `json:"id_password_reset_request"`
	ApprovedBy             pgtype.Int4 `json:"approved_by"`
}

type ApprovePasswordResetRequestRow struct {
	IDPasswordResetRequest int32              `json:"id_password_reset_request"`
	IDUser                 int32              `json:"id_user"`
	Reason                 string             `json:"reason"`
	Status                 string             `json:"status"`
	RequestedAt            pgtype.Timestamptz `json:"requested_at"`
	ApprovedAt             pgtype.Timestamptz `json:"approved_at"`
	RejectedAt             pgtype.Timestamptz `json:"rejected_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	RejectedReason         string             `json:"rejected_reason"`
	ApprovedBy             pgtype.Int4        `json:"approved_by"`
	RejectedBy             pgtype.Int4        `json:"rejected_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ApprovePasswordResetRequest(ctx context.Context, arg ApprovePasswordResetRequestParams) (ApprovePasswordResetRequestRow, error) {
	row := q.db.QueryRow(ctx, approvePasswordResetRequest, arg.IDPasswordResetRequest, arg.ApprovedBy)
	var i ApprovePasswordResetRequestRow
	err := row.Scan(
		&i.IDPasswordResetRequest,
		&i.IDUser,
		&i.Reason,
		&i.Status,
		&i.RequestedAt,
		&i.ApprovedAt,
		&i.RejectedAt,
		&i.CompletedAt,
		&i.RejectedReason,
		&i.ApprovedBy,
		&i.RejectedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createPasswordResetRequest = `-- name: CreatePasswordResetRequest :one
INSERT INTO PASSWORD_RESET_REQUESTS (
    ID_USER,
    REASON,
    STATUS
) VALUES (
    $1,
    $2,
    'pending'
)
RETURNING
    ID_PASSWORD_RESET_REQUEST,
    ID_USER,
    REASON,
    STATUS,
    REQUESTED_AT,
    APPROVED_AT,
    REJECTED_AT,
    COMPLETED_AT,
    REJECTED_REASON,
    APPROVED_BY,
    REJECTED_BY,
    created_at
`

type CreatePasswordResetRequestParams struct {
	IDUser int32  `json:"id_user"`
	Reason string `json:"reason"`
}

type CreatePasswordResetRequestRow struct {
	IDPasswordResetRequest int32              `json:"id_password_reset_request"`
	IDUser                 int32              `json:"id_user"`
	Reason                 string             `json:"reason"`
	Status                 string             `json:"status"`
	RequestedAt            pgtype.Timestamptz `json:"requested_at"`
	ApprovedAt             pgtype.Timestamptz `json:"approved_at"`
	RejectedAt             pgtype.Timestamptz `json:"rejected_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	RejectedReason         string             `json:"rejected_reason"`
	ApprovedBy             pgtype.Int4        `json:"approved_by"`
	RejectedBy             pgtype.Int4        `json:"rejected_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePasswordResetRequest(ctx context.Context, arg CreatePasswordResetRequestParams) (CreatePasswordResetRequestRow, error) {
	row := q.db.QueryRow(ctx, createPasswordResetRequest, arg.IDUser, arg.Reason)
	var i CreatePasswordResetRequestRow
	err := row.Scan(
		&i.IDPasswordResetRequest,
		&i.IDUser,
		&i.Reason,
		&i.Status,
		&i.RequestedAt,
		&i.ApprovedAt,
		&i.RejectedAt,
		&i.CompletedAt,
		&i.RejectedReason,
		&i.ApprovedBy,
		&i.RejectedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordResetRequestByID = `-- name: GetPasswordResetRequestByID :one
SELECT
    pr.ID_PASSWORD_RESET_REQUEST,
    pr.ID_USER,
    u.USERNAME,
    u.ID_ROLE,
    r.NAMA_ROLE,
    pr.REASON,
    pr.STATUS,
    pr.REQUESTED_AT,
    pr.APPROVED_AT,
    pr.REJECTED_AT,
    pr.COMPLETED_AT,
    pr.REJECTED_REASON,
    pr.APPROVED_BY,
    approver.USERNAME AS APPROVED_BY_USERNAME,
    pr.REJECTED_BY,
    rejector.USERNAME AS REJECTED_BY_USERNAME,
    pr.created_at
FROM PASSWORD_RESET_REQUESTS pr
JOIN USERS u ON u.ID_USER = pr.ID_USER
JOIN ROLES r ON r.ID_ROLE = u.ID_ROLE
LEFT JOIN USERS approver ON approver.ID_USER = pr.APPROVED_BY
LEFT JOIN USERS rejector ON rejector.ID_USER = pr.REJECTED_BY
WHERE pr.ID_PASSWORD_RESET_REQUEST = $1
LIMIT 1
`

type GetPasswordResetRequestByIDRow struct {
	IDPasswordResetRequest int32              `json:"id_password_reset_request"`
	IDUser                 int32              `json:"id_user"`
	Username               string             `json:"username"`
	IDRole                 int32              `json:"id_role"`
	NamaRole               string             `json:"nama_role"`
	Reason                 string             `json:"reason"`
	Status                 string             `json:"status"`
	RequestedAt            pgtype.Timestamptz `json:"requested_at"`
	ApprovedAt             pgtype.Timestamptz `json:"approved_at"`
	RejectedAt             pgtype.Timestamptz `json:"rejected_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	RejectedReason         string             `json:"rejected_reason"`
	ApprovedBy             pgtype.Int4        `json:"approved_by"`
	ApprovedByUsername     pgtype.Text        `json:"approved_by_username"`
	RejectedBy             pgtype.Int4        `json:"rejected_by"`
	RejectedByUsername     pgtype.Text        `json:"rejected_by_username"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetPasswordResetRequestByID(ctx context.Context, idPasswordResetRequest int32) (GetPasswordResetRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getPasswordResetRequestByID, idPasswordResetRequest)
	var i GetPasswordResetRequestByIDRow
	err := row.Scan(
		&i.IDPasswordResetRequest,
		&i.IDUser,
		&i.Username,
		&i.IDRole,
		&i.NamaRole,
		&i.Reason,
		&i.Status,
		&i.RequestedAt,
		&i.ApprovedAt,
		&i.RejectedAt,
		&i.CompletedAt,
		&i.RejectedReason,
		&i.ApprovedBy,
		&i.ApprovedByUsername,
		&i.RejectedBy,
		&i.RejectedByUsername,
		&i.CreatedAt,
	)
	return i, err
}

const hasPendingPasswordResetRequest = `-- name: HasPendingPasswordResetRequest :one
SELECT EXISTS (
    SELECT 1
    FROM PASSWORD_RESET_REQUESTS
    WHERE ID_USER = $1
      AND STATUS = 'pending'
)
`

func (q *Queries) HasPendingPasswordResetRequest(ctx context.Context, idUser int32) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingPasswordResetRequest, idUser)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listPasswordResetRequests = `-- name: ListPasswordResetRequests :many
SELECT
    pr.ID_PASSWORD_RESET_REQUEST,
    pr.ID_USER,
    u.USERNAME,
    u.ID_ROLE,
    r.NAMA_ROLE,
    pr.REASON,
    pr.STATUS,
    pr.REQUESTED_AT,
    pr.APPROVED_AT,
    pr.REJECTED_AT,
    pr.COMPLETED_AT,
    pr.REJECTED_REASON,
    pr.APPROVED_BY,
    approver.USERNAME AS APPROVED_BY_USERNAME,
    pr.REJECTED_BY,
    rejector.USERNAME AS REJECTED_BY_USERNAME,
    pr.created_at
FROM PASSWORD_RESET_REQUESTS pr
JOIN USERS u ON u.ID_USER = pr.ID_USER
JOIN ROLES r ON r.ID_ROLE = u.ID_ROLE
LEFT JOIN USERS approver ON approver.ID_USER = pr.APPROVED_BY
LEFT JOIN USERS rejector ON rejector.ID_USER = pr.REJECTED_BY
ORDER BY pr.REQUESTED_AT DESC, pr.ID_PASSWORD_RESET_REQUEST DESC
`

type ListPasswordResetRequestsRow struct {
	IDPasswordResetRequest int32              `json:"id_password_reset_request"`
	IDUser                 int32              `json:"id_user"`
	Username               string             `json:"username"`
	IDRole                 int32              `json:"id_role"`
	NamaRole               string             `json:"nama_role"`
	Reason                 string             `json:"reason"`
	Status                 string             `json:"status"`
	RequestedAt            pgtype.Timestamptz `json:"requested_at"`
	ApprovedAt             pgtype.Timestamptz `json:"approved_at"`
	RejectedAt             pgtype.Timestamptz `json:"rejected_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	RejectedReason         string             `json:"rejected_reason"`
	ApprovedBy             pgtype.Int4        `json:"approved_by"`
	ApprovedByUsername     pgtype.Text        `json:"approved_by_username"`
	RejectedBy             pgtype.Int4        `json:"rejected_by"`
	RejectedByUsername     pgtype.Text        `json:"rejected_by_username"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPasswordResetRequests(ctx context.Context) ([]ListPasswordResetRequestsRow, error) {
	rows, err := q.db.Query(ctx, listPasswordResetRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPasswordResetRequestsRow
	for rows.Next() {
		var i ListPasswordResetRequestsRow
		if err := rows.Scan(
			&i.IDPasswordResetRequest,
			&i.IDUser,
			&i.Username,
			&i.IDRole,
			&i.NamaRole,
			&i.Reason,
			&i.Status,
			&i.RequestedAt,
			&i.ApprovedAt,
			&i.RejectedAt,
			&i.CompletedAt,
			&i.RejectedReason,
			&i.ApprovedBy,
			&i.ApprovedByUsername,
			&i.RejectedBy,
			&i.RejectedByUsername,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectPasswordResetRequest = `-- name: RejectPasswordResetRequest :one
UPDATE PASSWORD_RESET_REQUESTS
SET STATUS = 'rejected',
    REJECTED_BY = $2,
    REJECTED_AT = NOW(),
    REJECTED_REASON = $3
WHERE ID_PASSWORD_RESET_REQUEST = $1
  AND STATUS = 'pending'
RETURNING
    ID_PASSWORD_RESET_REQUEST,
    ID_USER,
    REASON,
    STATUS,
    REQUESTED_AT,
    APPROVED_AT,
    REJECTED_AT,
    COMPLETED_AT,
    REJECTED_REASON,
    APPROVED_BY,
    REJECTED_BY,
    created_at
`

type RejectPasswordResetRequestParams struct {
	IDPasswordResetRequest int32       `json:"id_password_reset_request"`
	RejectedBy             pgtype.Int4 `json:"rejected_by"`
	RejectedReason         string      `json:"rejected_reason"`
}

type RejectPasswordResetRequestRow struct {
	IDPasswordResetRequest int32              `json:"id_password_reset_request"`
	IDUser                 int32              `json:"id_user"`
	Reason                 string             `json:"reason"`
	Status                 string             `json:"status"`
	RequestedAt            pgtype.Timestamptz `json:"requested_at"`
	ApprovedAt             pgtype.Timestamptz `json:"approved_at"`
	RejectedAt             pgtype.Timestamptz `json:"rejected_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	RejectedReason         string             `json:"rejected_reason"`
	ApprovedBy             pgtype.Int4        `json:"approved_by"`
	RejectedBy             pgtype.Int4        `json:"rejected_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) RejectPasswordResetRequest(ctx context.Context, arg RejectPasswordResetRequestParams) (RejectPasswordResetRequestRow, error) {
	row := q.db.QueryRow(ctx, rejectPasswordResetRequest, arg.IDPasswordResetRequest, arg.RejectedBy, arg.RejectedReason)
	var i RejectPasswordResetRequestRow
	err := row.Scan(
		&i.IDPasswordResetRequest,
		&i.IDUser,
		&i.Reason,
		&i.Status,
		&i.RequestedAt,
		&i.ApprovedAt,
		&i.RejectedAt,
		&i.CompletedAt,
		&i.RejectedReason,
		&i.ApprovedBy,
		&i.RejectedBy,
		&i.CreatedAt,
	)
	return i, err
}
