// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: production_line.sql

package entity

import (
	"context"
)

const countProductionLines = `-- name: CountProductionLines :one
SELECT COUNT(*) FROM PRODUCTION_LINE
WHERE (
    $1::text = '' OR
    name ILIKE '%' || $1::text || '%'
)
`

func (q *Queries) CountProductionLines(ctx context.Context, searchTerm string) (int64, error) {
	row := q.db.QueryRow(ctx, countProductionLines, searchTerm)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProductionLine = `-- name: CreateProductionLine :one
INSERT INTO PRODUCTION_LINE (name)
VALUES ($1) RETURNING id_production_line, name, created_at
`

func (q *Queries) CreateProductionLine(ctx context.Context, name string) (ProductionLine, error) {
	row := q.db.QueryRow(ctx, createProductionLine, name)
	var i ProductionLine
	err := row.Scan(&i.IDProductionLine, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteProductionLine = `-- name: DeleteProductionLine :execrows
DELETE FROM PRODUCTION_LINE
WHERE id_production_line = $1
`

func (q *Queries) DeleteProductionLine(ctx context.Context, idProductionLine int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProductionLine, idProductionLine)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProductionLineByID = `-- name: GetProductionLineByID :one
SELECT id_production_line, name, created_at FROM PRODUCTION_LINE WHERE id_production_line = $1 LIMIT 1
`

func (q *Queries) GetProductionLineByID(ctx context.Context, idProductionLine int32) (ProductionLine, error) {
	row := q.db.QueryRow(ctx, getProductionLineByID, idProductionLine)
	var i ProductionLine
	err := row.Scan(&i.IDProductionLine, &i.Name, &i.CreatedAt)
	return i, err
}

const listProductionLines = `-- name: ListProductionLines :many
SELECT id_production_line, name, created_at FROM PRODUCTION_LINE
WHERE (
    $1::text = '' OR
    name ILIKE '%' || $1::text || '%'
)
ORDER BY
    CASE WHEN $2::text = 'created_at' AND NOT $3::bool THEN created_at END ASC,
    CASE WHEN $2::text = 'created_at' AND $3::bool THEN created_at END DESC,
    CASE WHEN $2::text = 'name' AND NOT $3::bool THEN name END ASC,
    CASE WHEN $2::text = 'name' AND $3::bool THEN name END DESC,
    created_at DESC
LIMIT $5 OFFSET $4
`

type ListProductionLinesParams struct {
	SearchTerm string `json:"search_term"`
	SortBy     string `json:"sort_by"`
	SortDesc   bool   `json:"sort_desc"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

func (q *Queries) ListProductionLines(ctx context.Context, arg ListProductionLinesParams) ([]ProductionLine, error) {
	rows, err := q.db.Query(ctx, listProductionLines,
		arg.SearchTerm,
		arg.SortBy,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductionLine
	for rows.Next() {
		var i ProductionLine
		if err := rows.Scan(&i.IDProductionLine, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductionLine = `-- name: UpdateProductionLine :one
UPDATE PRODUCTION_LINE
SET name = $2
WHERE id_production_line = $1
RETURNING id_production_line, name, created_at
`

type UpdateProductionLineParams struct {
	IDProductionLine int32  `json:"id_production_line"`
	Name             string `json:"name"`
}

func (q *Queries) UpdateProductionLine(ctx context.Context, arg UpdateProductionLineParams) (ProductionLine, error) {
	row := q.db.QueryRow(ctx, updateProductionLine, arg.IDProductionLine, arg.Name)
	var i ProductionLine
	err := row.Scan(&i.IDProductionLine, &i.Name, &i.CreatedAt)
	return i, err
}
