// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: production_summary.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listProductionSummary = `-- name: ListProductionSummary :many
WITH cutting_agg AS (
    SELECT
        id_wo_shell_size,
        SUM(qty)::bigint AS cutting_qty,
        MAX(created_at) AS last_created_at
    FROM REPORT_CUTTING
    GROUP BY id_wo_shell_size
),
sewing_agg AS (
    SELECT
        id_wo_shell_size,
        SUM(qty)::bigint AS sewing_qty,
        MAX(created_at) AS last_created_at
    FROM REPORT_SEWING
    GROUP BY id_wo_shell_size
),
qc_agg AS (
    SELECT
        id_wo_shell_size,
        SUM(qty)::bigint AS qc_pass_qty,
        MAX(created_at) AS last_created_at
    FROM REPORT_QC_FINISH
    GROUP BY id_wo_shell_size
),
packing_agg AS (
    SELECT
        id_wo_shell_size,
        SUM(qty)::bigint AS packing_qty,
        MAX(created_at) AS last_created_at
    FROM REPORT_PACKING
    GROUP BY id_wo_shell_size
),
shipping_agg AS (
    SELECT
        id_wo_shell_size,
        SUM(qty)::bigint AS shipped_qty,
        MAX(created_at) AS last_created_at
    FROM REPORT_PENGIRIMAN
    GROUP BY id_wo_shell_size
)
SELECT
    woss.id_wo_shell_size,
    woss.id_size,
    wo.id_wo,
    wo.model AS model_name,
    ms.nama_size AS size,
    woss.qty AS target_qty,
    COALESCE(ca.cutting_qty, 0)::int AS cutting_qty,
    COALESCE(sa.sewing_qty, 0)::int AS sewing_qty,
    COALESCE(qa.qc_pass_qty, 0)::int AS qc_pass_qty,
    COALESCE(pa.packing_qty, 0)::int AS packing_qty,
    COALESCE(sha.shipped_qty, 0)::int AS shipped_qty,
    GREATEST(
        woss.created_at,
        COALESCE(ca.last_created_at, woss.created_at),
        COALESCE(sa.last_created_at, woss.created_at),
        COALESCE(qa.last_created_at, woss.created_at),
        COALESCE(pa.last_created_at, woss.created_at),
        COALESCE(sha.last_created_at, woss.created_at)
    )::timestamptz AS last_updated,
    COUNT(*) OVER() AS total_count
FROM WORK_ORDER_SHELL_SIZE woss
JOIN WORK_ORDER_SHELL wos ON wos.id_wo_shell = woss.id_wo_shell
JOIN WORK_ORDER wo ON wo.id_wo = wos.id_wo
JOIN PO_CLIENT_ITEM pci ON pci.id_po_client_item = wo.id_po_client_item
JOIN PO_CLIENT pc ON pc.id_po_client = pci.id_po_client
JOIN MASTER_SIZE ms ON ms.id_size = woss.id_size
LEFT JOIN cutting_agg ca ON ca.id_wo_shell_size = woss.id_wo_shell_size
LEFT JOIN sewing_agg sa ON sa.id_wo_shell_size = woss.id_wo_shell_size
LEFT JOIN qc_agg qa ON qa.id_wo_shell_size = woss.id_wo_shell_size
LEFT JOIN packing_agg pa ON pa.id_wo_shell_size = woss.id_wo_shell_size
LEFT JOIN shipping_agg sha ON sha.id_wo_shell_size = woss.id_wo_shell_size
WHERE (
    $1::int = 0 OR
    wo.id_wo = $1::int
) AND (
    $2::int = 0 OR
    woss.id_wo_shell_size = $2::int
) AND (
    $3::text = '' OR
    wo.model ILIKE '%' || $3::text || '%' OR
    ms.nama_size ILIKE '%' || $3::text || '%'
 ) AND (
    $4::integer IS NULL OR
    pc.id_mitra = $4::integer
)
ORDER BY
    CASE WHEN $5::text = 'last_updated' AND NOT $6::bool THEN GREATEST(
        woss.created_at,
        COALESCE(ca.last_created_at, woss.created_at),
        COALESCE(sa.last_created_at, woss.created_at),
        COALESCE(qa.last_created_at, woss.created_at),
        COALESCE(pa.last_created_at, woss.created_at),
        COALESCE(sha.last_created_at, woss.created_at)
    ) END ASC,
    CASE WHEN $5::text = 'last_updated' AND $6::bool THEN GREATEST(
        woss.created_at,
        COALESCE(ca.last_created_at, woss.created_at),
        COALESCE(sa.last_created_at, woss.created_at),
        COALESCE(qa.last_created_at, woss.created_at),
        COALESCE(pa.last_created_at, woss.created_at),
        COALESCE(sha.last_created_at, woss.created_at)
    ) END DESC,
    CASE WHEN $5::text = 'id_wo_shell_size' AND NOT $6::bool THEN woss.id_wo_shell_size END ASC,
    CASE WHEN $5::text = 'id_wo_shell_size' AND $6::bool THEN woss.id_wo_shell_size END DESC,
    CASE WHEN $5::text = 'model_name' AND NOT $6::bool THEN wo.model END ASC,
    CASE WHEN $5::text = 'model_name' AND $6::bool THEN wo.model END DESC,
    CASE WHEN $5::text = 'size' AND NOT $6::bool THEN ms.nama_size END ASC,
    CASE WHEN $5::text = 'size' AND $6::bool THEN ms.nama_size END DESC,
    CASE WHEN $5::text = 'target_qty' AND NOT $6::bool THEN woss.qty END ASC,
    CASE WHEN $5::text = 'target_qty' AND $6::bool THEN woss.qty END DESC,
    CASE WHEN $5::text = 'cutting_qty' AND NOT $6::bool THEN COALESCE(ca.cutting_qty, 0)::int END ASC,
    CASE WHEN $5::text = 'cutting_qty' AND $6::bool THEN COALESCE(ca.cutting_qty, 0)::int END DESC,
    CASE WHEN $5::text = 'sewing_qty' AND NOT $6::bool THEN COALESCE(sa.sewing_qty, 0)::int END ASC,
    CASE WHEN $5::text = 'sewing_qty' AND $6::bool THEN COALESCE(sa.sewing_qty, 0)::int END DESC,
    CASE WHEN $5::text = 'qc_pass_qty' AND NOT $6::bool THEN COALESCE(qa.qc_pass_qty, 0)::int END ASC,
    CASE WHEN $5::text = 'qc_pass_qty' AND $6::bool THEN COALESCE(qa.qc_pass_qty, 0)::int END DESC,
    CASE WHEN $5::text = 'packing_qty' AND NOT $6::bool THEN COALESCE(pa.packing_qty, 0)::int END ASC,
    CASE WHEN $5::text = 'packing_qty' AND $6::bool THEN COALESCE(pa.packing_qty, 0)::int END DESC,
    CASE WHEN $5::text = 'shipped_qty' AND NOT $6::bool THEN COALESCE(sha.shipped_qty, 0)::int END ASC,
    CASE WHEN $5::text = 'shipped_qty' AND $6::bool THEN COALESCE(sha.shipped_qty, 0)::int END DESC,
    last_updated DESC,
    woss.id_wo_shell_size DESC
LIMIT $8 OFFSET $7
`

type ListProductionSummaryParams struct {
	IDWo          int32       `json:"id_wo"`
	IDWoShellSize int32       `json:"id_wo_shell_size"`
	SearchTerm    string      `json:"search_term"`
	IDMitra       pgtype.Int4 `json:"id_mitra"`
	SortBy        string      `json:"sort_by"`
	SortDesc      bool        `json:"sort_desc"`
	PageOffset    int32       `json:"page_offset"`
	PageLimit     int32       `json:"page_limit"`
}

type ListProductionSummaryRow struct {
	IDWoShellSize int32              `json:"id_wo_shell_size"`
	IDSize        int32              `json:"id_size"`
	IDWo          int32              `json:"id_wo"`
	ModelName     string             `json:"model_name"`
	Size          string             `json:"size"`
	TargetQty     int32              `json:"target_qty"`
	CuttingQty    int32              `json:"cutting_qty"`
	SewingQty     int32              `json:"sewing_qty"`
	QcPassQty     int32              `json:"qc_pass_qty"`
	PackingQty    int32              `json:"packing_qty"`
	ShippedQty    int32              `json:"shipped_qty"`
	LastUpdated   pgtype.Timestamptz `json:"last_updated"`
	TotalCount    int64              `json:"total_count"`
}

func (q *Queries) ListProductionSummary(ctx context.Context, arg ListProductionSummaryParams) ([]ListProductionSummaryRow, error) {
	rows, err := q.db.Query(ctx, listProductionSummary,
		arg.IDWo,
		arg.IDWoShellSize,
		arg.SearchTerm,
		arg.IDMitra,
		arg.SortBy,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductionSummaryRow
	for rows.Next() {
		var i ListProductionSummaryRow
		if err := rows.Scan(
			&i.IDWoShellSize,
			&i.IDSize,
			&i.IDWo,
			&i.ModelName,
			&i.Size,
			&i.TargetQty,
			&i.CuttingQty,
			&i.SewingQty,
			&i.QcPassQty,
			&i.PackingQty,
			&i.ShippedQty,
			&i.LastUpdated,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
