// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: production_status_plan.sql

package entity

import (
	"context"
)

const countProductionStatusPlans = `-- name: CountProductionStatusPlans :one
SELECT COUNT(*) FROM PRODUCTION_STATUS_PLAN
WHERE (
    $1::text = '' OR
    name ILIKE '%' || $1::text || '%'
)
`

func (q *Queries) CountProductionStatusPlans(ctx context.Context, searchTerm string) (int64, error) {
	row := q.db.QueryRow(ctx, countProductionStatusPlans, searchTerm)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProductionStatusPlan = `-- name: CreateProductionStatusPlan :one
INSERT INTO PRODUCTION_STATUS_PLAN (name)
VALUES ($1) RETURNING id_production_status_plan, name, created_at
`

func (q *Queries) CreateProductionStatusPlan(ctx context.Context, name string) (ProductionStatusPlan, error) {
	row := q.db.QueryRow(ctx, createProductionStatusPlan, name)
	var i ProductionStatusPlan
	err := row.Scan(&i.IDProductionStatusPlan, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteProductionStatusPlan = `-- name: DeleteProductionStatusPlan :execrows
DELETE FROM PRODUCTION_STATUS_PLAN
WHERE id_production_status_plan = $1
`

func (q *Queries) DeleteProductionStatusPlan(ctx context.Context, idProductionStatusPlan int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProductionStatusPlan, idProductionStatusPlan)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProductionStatusPlanByID = `-- name: GetProductionStatusPlanByID :one
SELECT id_production_status_plan, name, created_at FROM PRODUCTION_STATUS_PLAN WHERE id_production_status_plan = $1 LIMIT 1
`

func (q *Queries) GetProductionStatusPlanByID(ctx context.Context, idProductionStatusPlan int32) (ProductionStatusPlan, error) {
	row := q.db.QueryRow(ctx, getProductionStatusPlanByID, idProductionStatusPlan)
	var i ProductionStatusPlan
	err := row.Scan(&i.IDProductionStatusPlan, &i.Name, &i.CreatedAt)
	return i, err
}

const listProductionStatusPlans = `-- name: ListProductionStatusPlans :many
SELECT id_production_status_plan, name, created_at FROM PRODUCTION_STATUS_PLAN
WHERE (
    $1::text = '' OR
    name ILIKE '%' || $1::text || '%'
)
ORDER BY
    CASE WHEN $2::text = 'created_at' AND NOT $3::bool THEN created_at END ASC,
    CASE WHEN $2::text = 'created_at' AND $3::bool THEN created_at END DESC,
    CASE WHEN $2::text = 'name' AND NOT $3::bool THEN name END ASC,
    CASE WHEN $2::text = 'name' AND $3::bool THEN name END DESC,
    created_at DESC
LIMIT $5 OFFSET $4
`

type ListProductionStatusPlansParams struct {
	SearchTerm string `json:"search_term"`
	SortBy     string `json:"sort_by"`
	SortDesc   bool   `json:"sort_desc"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

func (q *Queries) ListProductionStatusPlans(ctx context.Context, arg ListProductionStatusPlansParams) ([]ProductionStatusPlan, error) {
	rows, err := q.db.Query(ctx, listProductionStatusPlans,
		arg.SearchTerm,
		arg.SortBy,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductionStatusPlan
	for rows.Next() {
		var i ProductionStatusPlan
		if err := rows.Scan(&i.IDProductionStatusPlan, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductionStatusPlan = `-- name: UpdateProductionStatusPlan :one
UPDATE PRODUCTION_STATUS_PLAN
SET name = $2
WHERE id_production_status_plan = $1
RETURNING id_production_status_plan, name, created_at
`

type UpdateProductionStatusPlanParams struct {
	IDProductionStatusPlan int32  `json:"id_production_status_plan"`
	Name                   string `json:"name"`
}

func (q *Queries) UpdateProductionStatusPlan(ctx context.Context, arg UpdateProductionStatusPlanParams) (ProductionStatusPlan, error) {
	row := q.db.QueryRow(ctx, updateProductionStatusPlan, arg.IDProductionStatusPlan, arg.Name)
	var i ProductionStatusPlan
	err := row.Scan(&i.IDProductionStatusPlan, &i.Name, &i.CreatedAt)
	return i, err
}
