// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: production_report.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReportCutting = `-- name: CreateReportCutting :one
INSERT INTO REPORT_CUTTING (
    tanggal,
    qty,
    id_wo_shell_size
) VALUES (
    $1::date,
    $2,
    $3
)
RETURNING id_report_cutting, tanggal, qty, id_wo_shell_size, created_at
`

type CreateReportCuttingParams struct {
	Tanggal       pgtype.Date `json:"tanggal"`
	Qty           int32       `json:"qty"`
	IDWoShellSize int32       `json:"id_wo_shell_size"`
}

func (q *Queries) CreateReportCutting(ctx context.Context, arg CreateReportCuttingParams) (ReportCutting, error) {
	row := q.db.QueryRow(ctx, createReportCutting, arg.Tanggal, arg.Qty, arg.IDWoShellSize)
	var i ReportCutting
	err := row.Scan(
		&i.IDReportCutting,
		&i.Tanggal,
		&i.Qty,
		&i.IDWoShellSize,
		&i.CreatedAt,
	)
	return i, err
}

const createReportPacking = `-- name: CreateReportPacking :one
INSERT INTO REPORT_PACKING (
    tanggal,
    qty,
    id_wo_shell_size
) VALUES (
    $1::date,
    $2,
    $3
)
RETURNING id_report_packing, tanggal, qty, id_wo_shell_size, created_at
`

type CreateReportPackingParams struct {
	Tanggal       pgtype.Date `json:"tanggal"`
	Qty           int32       `json:"qty"`
	IDWoShellSize int32       `json:"id_wo_shell_size"`
}

func (q *Queries) CreateReportPacking(ctx context.Context, arg CreateReportPackingParams) (ReportPacking, error) {
	row := q.db.QueryRow(ctx, createReportPacking, arg.Tanggal, arg.Qty, arg.IDWoShellSize)
	var i ReportPacking
	err := row.Scan(
		&i.IDReportPacking,
		&i.Tanggal,
		&i.Qty,
		&i.IDWoShellSize,
		&i.CreatedAt,
	)
	return i, err
}

const createReportPengiriman = `-- name: CreateReportPengiriman :one
INSERT INTO REPORT_PENGIRIMAN (
    report_date,
    qty,
    id_wo_shell_size
) VALUES (
    $1::date,
    $2,
    $3
)
RETURNING id_report_pengiriman, report_date, qty, id_wo_shell_size, created_at
`

type CreateReportPengirimanParams struct {
	ReportDate    pgtype.Date `json:"report_date"`
	Qty           int32       `json:"qty"`
	IDWoShellSize int32       `json:"id_wo_shell_size"`
}

func (q *Queries) CreateReportPengiriman(ctx context.Context, arg CreateReportPengirimanParams) (ReportPengiriman, error) {
	row := q.db.QueryRow(ctx, createReportPengiriman, arg.ReportDate, arg.Qty, arg.IDWoShellSize)
	var i ReportPengiriman
	err := row.Scan(
		&i.IDReportPengiriman,
		&i.ReportDate,
		&i.Qty,
		&i.IDWoShellSize,
		&i.CreatedAt,
	)
	return i, err
}

const createReportQCFinish = `-- name: CreateReportQCFinish :one
INSERT INTO REPORT_QC_FINISH (
    tanggal,
    qty,
    id_wo_shell_size
) VALUES (
    $1::date,
    $2,
    $3
)
RETURNING id_report_qc_finishing, tanggal, qty, id_wo_shell_size, created_at
`

type CreateReportQCFinishParams struct {
	Tanggal       pgtype.Date `json:"tanggal"`
	Qty           int32       `json:"qty"`
	IDWoShellSize int32       `json:"id_wo_shell_size"`
}

func (q *Queries) CreateReportQCFinish(ctx context.Context, arg CreateReportQCFinishParams) (ReportQcFinish, error) {
	row := q.db.QueryRow(ctx, createReportQCFinish, arg.Tanggal, arg.Qty, arg.IDWoShellSize)
	var i ReportQcFinish
	err := row.Scan(
		&i.IDReportQcFinishing,
		&i.Tanggal,
		&i.Qty,
		&i.IDWoShellSize,
		&i.CreatedAt,
	)
	return i, err
}

const createReportSewing = `-- name: CreateReportSewing :one
INSERT INTO REPORT_SEWING (
    tanggal,
    qty,
    id_wo_shell_size
) VALUES (
    $1::date,
    $2,
    $3
)
RETURNING id_report_sewing, tanggal, qty, id_wo_shell_size, created_at
`

type CreateReportSewingParams struct {
	Tanggal       pgtype.Date `json:"tanggal"`
	Qty           int32       `json:"qty"`
	IDWoShellSize int32       `json:"id_wo_shell_size"`
}

func (q *Queries) CreateReportSewing(ctx context.Context, arg CreateReportSewingParams) (ReportSewing, error) {
	row := q.db.QueryRow(ctx, createReportSewing, arg.Tanggal, arg.Qty, arg.IDWoShellSize)
	var i ReportSewing
	err := row.Scan(
		&i.IDReportSewing,
		&i.Tanggal,
		&i.Qty,
		&i.IDWoShellSize,
		&i.CreatedAt,
	)
	return i, err
}

const getDailyReportsByWorkOrder = `-- name: GetDailyReportsByWorkOrder :many
SELECT 'cutting'::varchar(20) AS division, rc.tanggal, rc.qty, rc.id_wo_shell_size
FROM REPORT_CUTTING rc
JOIN WORK_ORDER_SHELL_SIZE woss ON woss.id_wo_shell_size = rc.id_wo_shell_size
JOIN WORK_ORDER_SHELL wos ON wos.id_wo_shell = woss.id_wo_shell
WHERE wos.id_wo = $1

UNION ALL

SELECT 'sewing'::varchar(20) AS division, rs.tanggal, rs.qty, rs.id_wo_shell_size
FROM REPORT_SEWING rs
JOIN WORK_ORDER_SHELL_SIZE woss ON woss.id_wo_shell_size = rs.id_wo_shell_size
JOIN WORK_ORDER_SHELL wos ON wos.id_wo_shell = woss.id_wo_shell
WHERE wos.id_wo = $1

UNION ALL

SELECT 'qc-finish'::varchar(20) AS division, rq.tanggal, rq.qty, rq.id_wo_shell_size
FROM REPORT_QC_FINISH rq
JOIN WORK_ORDER_SHELL_SIZE woss ON woss.id_wo_shell_size = rq.id_wo_shell_size
JOIN WORK_ORDER_SHELL wos ON wos.id_wo_shell = woss.id_wo_shell
WHERE wos.id_wo = $1

UNION ALL

SELECT 'packing'::varchar(20) AS division, rp.tanggal, rp.qty, rp.id_wo_shell_size
FROM REPORT_PACKING rp
JOIN WORK_ORDER_SHELL_SIZE woss ON woss.id_wo_shell_size = rp.id_wo_shell_size
JOIN WORK_ORDER_SHELL wos ON wos.id_wo_shell = woss.id_wo_shell
WHERE wos.id_wo = $1

UNION ALL

SELECT 'pengiriman'::varchar(20) AS division, rpe.report_date AS tanggal, rpe.qty, rpe.id_wo_shell_size
FROM REPORT_PENGIRIMAN rpe
JOIN WORK_ORDER_SHELL_SIZE woss ON woss.id_wo_shell_size = rpe.id_wo_shell_size
JOIN WORK_ORDER_SHELL wos ON wos.id_wo_shell = woss.id_wo_shell
WHERE wos.id_wo = $1

ORDER BY tanggal DESC, id_wo_shell_size ASC
`

type GetDailyReportsByWorkOrderRow struct {
	Division      string      `json:"division"`
	Tanggal       pgtype.Date `json:"tanggal"`
	Qty           int32       `json:"qty"`
	IDWoShellSize int32       `json:"id_wo_shell_size"`
}

func (q *Queries) GetDailyReportsByWorkOrder(ctx context.Context, idWo int32) ([]GetDailyReportsByWorkOrderRow, error) {
	rows, err := q.db.Query(ctx, getDailyReportsByWorkOrder, idWo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyReportsByWorkOrderRow
	for rows.Next() {
		var i GetDailyReportsByWorkOrderRow
		if err := rows.Scan(
			&i.Division,
			&i.Tanggal,
			&i.Qty,
			&i.IDWoShellSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
