// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profil_perusahaan.sql

package entity

import (
	"context"
)

const createProfilPerusahaan = `-- name: CreateProfilPerusahaan :one
INSERT INTO PROFIL_PERUSAHAAN (
    nama, alamat, email, no_telp, about, logo
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id_profil_perusahaan, nama, alamat, email, no_telp, about, logo, created_at
`

type CreateProfilPerusahaanParams struct {
	Nama   string `json:"nama"`
	Alamat string `json:"alamat"`
	Email  string `json:"email"`
	NoTelp string `json:"no_telp"`
	About  string `json:"about"`
	Logo   string `json:"logo"`
}

func (q *Queries) CreateProfilPerusahaan(ctx context.Context, arg CreateProfilPerusahaanParams) (ProfilPerusahaan, error) {
	row := q.db.QueryRow(ctx, createProfilPerusahaan,
		arg.Nama,
		arg.Alamat,
		arg.Email,
		arg.NoTelp,
		arg.About,
		arg.Logo,
	)
	var i ProfilPerusahaan
	err := row.Scan(
		&i.IDProfilPerusahaan,
		&i.Nama,
		&i.Alamat,
		&i.Email,
		&i.NoTelp,
		&i.About,
		&i.Logo,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProfilPerusahaan = `-- name: DeleteProfilPerusahaan :execrows
DELETE FROM PROFIL_PERUSAHAAN
WHERE id_profil_perusahaan = $1
`

func (q *Queries) DeleteProfilPerusahaan(ctx context.Context, idProfilPerusahaan int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProfilPerusahaan, idProfilPerusahaan)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProfilPerusahaan = `-- name: GetProfilPerusahaan :one
SELECT id_profil_perusahaan, nama, alamat, email, no_telp, about, logo, created_at FROM PROFIL_PERUSAHAAN
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetProfilPerusahaan(ctx context.Context) (ProfilPerusahaan, error) {
	row := q.db.QueryRow(ctx, getProfilPerusahaan)
	var i ProfilPerusahaan
	err := row.Scan(
		&i.IDProfilPerusahaan,
		&i.Nama,
		&i.Alamat,
		&i.Email,
		&i.NoTelp,
		&i.About,
		&i.Logo,
		&i.CreatedAt,
	)
	return i, err
}

const getProfilPerusahaanByID = `-- name: GetProfilPerusahaanByID :one
SELECT id_profil_perusahaan, nama, alamat, email, no_telp, about, logo, created_at FROM PROFIL_PERUSAHAAN
WHERE id_profil_perusahaan = $1 LIMIT 1
`

func (q *Queries) GetProfilPerusahaanByID(ctx context.Context, idProfilPerusahaan int32) (ProfilPerusahaan, error) {
	row := q.db.QueryRow(ctx, getProfilPerusahaanByID, idProfilPerusahaan)
	var i ProfilPerusahaan
	err := row.Scan(
		&i.IDProfilPerusahaan,
		&i.Nama,
		&i.Alamat,
		&i.Email,
		&i.NoTelp,
		&i.About,
		&i.Logo,
		&i.CreatedAt,
	)
	return i, err
}

const updateProfilPerusahaan = `-- name: UpdateProfilPerusahaan :one
UPDATE PROFIL_PERUSAHAAN
SET nama = $2, alamat = $3, email = $4, no_telp = $5, about = $6, logo = $7
WHERE id_profil_perusahaan = $1
RETURNING id_profil_perusahaan, nama, alamat, email, no_telp, about, logo, created_at
`

type UpdateProfilPerusahaanParams struct {
	IDProfilPerusahaan int32  `json:"id_profil_perusahaan"`
	Nama               string `json:"nama"`
	Alamat             string `json:"alamat"`
	Email              string `json:"email"`
	NoTelp             string `json:"no_telp"`
	About              string `json:"about"`
	Logo               string `json:"logo"`
}

func (q *Queries) UpdateProfilPerusahaan(ctx context.Context, arg UpdateProfilPerusahaanParams) (ProfilPerusahaan, error) {
	row := q.db.QueryRow(ctx, updateProfilPerusahaan,
		arg.IDProfilPerusahaan,
		arg.Nama,
		arg.Alamat,
		arg.Email,
		arg.NoTelp,
		arg.About,
		arg.Logo,
	)
	var i ProfilPerusahaan
	err := row.Scan(
		&i.IDProfilPerusahaan,
		&i.Nama,
		&i.Alamat,
		&i.Email,
		&i.NoTelp,
		&i.About,
		&i.Logo,
		&i.CreatedAt,
	)
	return i, err
}
