// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package entity

import (
	"context"
)

type Querier interface {
	CreateBarang(ctx context.Context, arg CreateBarangParams) (Barang, error)
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	CreateDepartemen(ctx context.Context, namaDepartemen string) (Departeman, error)
	CreateHakAkses(ctx context.Context, namaHalaman string) (HakAkse, error)
	CreateJenisBarang(ctx context.Context, arg CreateJenisBarangParams) (JenisBarang, error)
	CreateMaterialList(ctx context.Context, arg CreateMaterialListParams) (MaterialList, error)
	CreateMitra(ctx context.Context, arg CreateMitraParams) (Mitra, error)
	CreatePOClient(ctx context.Context, arg CreatePOClientParams) (PoClient, error)
	CreatePOClientItem(ctx context.Context, arg CreatePOClientItemParams) (PoClientItem, error)
	CreatePOInternal(ctx context.Context, arg CreatePOInternalParams) (PoInternal, error)
	CreatePOInternalItem(ctx context.Context, arg CreatePOInternalItemParams) (PoInternalItem, error)
	CreatePRInternal(ctx context.Context, arg CreatePRInternalParams) (PrInternal, error)
	CreatePRInternalItem(ctx context.Context, arg CreatePRInternalItemParams) (PrInternalItem, error)
	CreatePenanggungJawab(ctx context.Context, arg CreatePenanggungJawabParams) (PenanggungJawab, error)
	CreateReportCutting(ctx context.Context, arg CreateReportCuttingParams) (ReportCutting, error)
	CreateReportPacking(ctx context.Context, arg CreateReportPackingParams) (ReportPacking, error)
	CreateReportQCFinish(ctx context.Context, arg CreateReportQCFinishParams) (ReportQcFinish, error)
	CreateReportSewing(ctx context.Context, arg CreateReportSewingParams) (ReportSewing, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateUserAkses(ctx context.Context, arg CreateUserAksesParams) error
	CreateWorkOrder(ctx context.Context, arg CreateWorkOrderParams) (WorkOrder, error)
	CreateWorkOrderShell(ctx context.Context, arg CreateWorkOrderShellParams) (WorkOrderShell, error)
	CreateWorkOrderShellSize(ctx context.Context, arg CreateWorkOrderShellSizeParams) (WorkOrderShellSize, error)
	CreateWorkOrderTrim(ctx context.Context, arg CreateWorkOrderTrimParams) (WorkOrderTrim, error)
	DeleteBarang(ctx context.Context, idBarang int32) (int64, error)
	DeleteCompany(ctx context.Context, idCompany int32) (int64, error)
	DeleteDepartemen(ctx context.Context, idDepartemen int32) (int64, error)
	DeleteHakAkses(ctx context.Context, idHakAkses int32) (int64, error)
	DeleteJenisBarang(ctx context.Context, idJenisBarang int32) (int64, error)
	DeleteMitra(ctx context.Context, idMitra int32) (int64, error)
	DeleteUser(ctx context.Context, idUser int32) (int64, error)
	GetBarangByID(ctx context.Context, idBarang int32) (GetBarangByIDRow, error)
	GetCompany(ctx context.Context) (Company, error)
	GetCompanyByID(ctx context.Context, idCompany int32) (Company, error)
	GetDepartemenByID(ctx context.Context, idDepartemen int32) (Departeman, error)
	GetHakAksesByID(ctx context.Context, idHakAkses int32) (HakAkse, error)
	GetJenisBarangByID(ctx context.Context, idJenisBarang int32) (JenisBarang, error)
	GetMitraByID(ctx context.Context, idMitra int32) (Mitra, error)
	GetUserByID(ctx context.Context, idUser int32) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserPermissions(ctx context.Context, idUser int32) ([]string, error)
	ListBarang(ctx context.Context, arg ListBarangParams) ([]ListBarangRow, error)
	ListDepartemen(ctx context.Context) ([]Departeman, error)
	ListHakAkses(ctx context.Context) ([]HakAkse, error)
	ListJenisBarang(ctx context.Context) ([]JenisBarang, error)
	ListMitra(ctx context.Context) ([]Mitra, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	UpdateBarang(ctx context.Context, arg UpdateBarangParams) (Barang, error)
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error)
	UpdateDepartemen(ctx context.Context, arg UpdateDepartemenParams) (Departeman, error)
	UpdateHakAkses(ctx context.Context, arg UpdateHakAksesParams) (HakAkse, error)
	UpdateJenisBarang(ctx context.Context, arg UpdateJenisBarangParams) (JenisBarang, error)
	UpdateMitra(ctx context.Context, arg UpdateMitraParams) (Mitra, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
