// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package entity

import (
	"context"
)

type Querier interface {
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserPermissions(ctx context.Context, idUser int32) ([]string, error)
}

var _ Querier = (*Queries)(nil)
