// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rekonsiliasi.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRekonsiliasi = `-- name: CreateRekonsiliasi :one
INSERT INTO REKONSILIASI (
    id_wo,
    jasa,
    no_po,
    delivery,
    buyer,
    brand,
    style,
    qty_po,
    plan_cut_total,
    cons_baju_summary,
    nama_bahan,
    warna_kain_summary,
    created_by,
    updated_by
) VALUES (
    $1,
    $2,
    $3,
    $4::date,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    to_jsonb($12::text[]),
    $13,
    $14
)
RETURNING
    id_rekonsiliasi,
    id_wo,
    jasa,
    no_po,
    delivery,
    buyer,
    brand,
    style,
    qty_po,
    plan_cut_total,
    cons_baju_summary,
    nama_bahan,
    warna_kain_summary,
    created_by,
    updated_by,
    created_at,
    updated_at
`

type CreateRekonsiliasiParams struct {
	IDWo             int32       `json:"id_wo"`
	Jasa             string      `json:"jasa"`
	NoPo             string      `json:"no_po"`
	Delivery         pgtype.Date `json:"delivery"`
	Buyer            string      `json:"buyer"`
	Brand            string      `json:"brand"`
	Style            string      `json:"style"`
	QtyPo            int32       `json:"qty_po"`
	PlanCutTotal     int64       `json:"plan_cut_total"`
	ConsBajuSummary  string      `json:"cons_baju_summary"`
	NamaBahan        string      `json:"nama_bahan"`
	WarnaKainSummary []string    `json:"warna_kain_summary"`
	CreatedBy        pgtype.Int4 `json:"created_by"`
	UpdatedBy        pgtype.Int4 `json:"updated_by"`
}

func (q *Queries) CreateRekonsiliasi(ctx context.Context, arg CreateRekonsiliasiParams) (Rekonsiliasi, error) {
	row := q.db.QueryRow(ctx, createRekonsiliasi,
		arg.IDWo,
		arg.Jasa,
		arg.NoPo,
		arg.Delivery,
		arg.Buyer,
		arg.Brand,
		arg.Style,
		arg.QtyPo,
		arg.PlanCutTotal,
		arg.ConsBajuSummary,
		arg.NamaBahan,
		arg.WarnaKainSummary,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Rekonsiliasi
	err := row.Scan(
		&i.IDRekonsiliasi,
		&i.IDWo,
		&i.Jasa,
		&i.NoPo,
		&i.Delivery,
		&i.Buyer,
		&i.Brand,
		&i.Style,
		&i.QtyPo,
		&i.PlanCutTotal,
		&i.ConsBajuSummary,
		&i.NamaBahan,
		&i.WarnaKainSummary,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRekonsiliasiMaterialRow = `-- name: CreateRekonsiliasiMaterialRow :one
INSERT INTO REKONSILIASI_MATERIAL_ROW (
    id_rekonsiliasi,
    row_no,
    kategori,
    description,
    size_label,
    ratio_source,
    ratio_input,
    qty_per_pcs_input,
    qty_wo,
    toleransi,
    satuan,
    qty_actual_kirim_source,
    qty_actual_kirim_manual,
    reject_qty,
    retur_qty,
    keterangan,
    id_material_list_item,
    id_wo_shell,
    id_wo_trim
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6::numeric,
    $7::numeric,
    $8::numeric,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19
)
RETURNING
    id_rekonsiliasi_material_row,
    id_rekonsiliasi,
    row_no,
    kategori,
    description,
    size_label,
    ratio_source,
    ratio_input,
    qty_per_pcs_input,
    qty_wo,
    toleransi,
    satuan,
    qty_actual_kirim_source,
    qty_actual_kirim_manual,
    reject_qty,
    retur_qty,
    keterangan,
    id_material_list_item,
    id_wo_shell,
    id_wo_trim,
    created_at,
    updated_at
`

type CreateRekonsiliasiMaterialRowParams struct {
	IDRekonsiliasi       int32          `json:"id_rekonsiliasi"`
	RowNo                int32          `json:"row_no"`
	Kategori             string         `json:"kategori"`
	Description          string         `json:"description"`
	SizeLabel            string         `json:"size_label"`
	RatioSource          pgtype.Numeric `json:"ratio_source"`
	RatioInput           pgtype.Numeric `json:"ratio_input"`
	QtyPerPcsInput       pgtype.Numeric `json:"qty_per_pcs_input"`
	QtyWo                int32          `json:"qty_wo"`
	Toleransi            int32          `json:"toleransi"`
	Satuan               string         `json:"satuan"`
	QtyActualKirimSource int32          `json:"qty_actual_kirim_source"`
	QtyActualKirimManual int32          `json:"qty_actual_kirim_manual"`
	RejectQty            int32          `json:"reject_qty"`
	ReturQty             int32          `json:"retur_qty"`
	Keterangan           string         `json:"keterangan"`
	IDMaterialListItem   pgtype.Int4    `json:"id_material_list_item"`
	IDWoShell            pgtype.Int4    `json:"id_wo_shell"`
	IDWoTrim             pgtype.Int4    `json:"id_wo_trim"`
}

func (q *Queries) CreateRekonsiliasiMaterialRow(ctx context.Context, arg CreateRekonsiliasiMaterialRowParams) (RekonsiliasiMaterialRow, error) {
	row := q.db.QueryRow(ctx, createRekonsiliasiMaterialRow,
		arg.IDRekonsiliasi,
		arg.RowNo,
		arg.Kategori,
		arg.Description,
		arg.SizeLabel,
		arg.RatioSource,
		arg.RatioInput,
		arg.QtyPerPcsInput,
		arg.QtyWo,
		arg.Toleransi,
		arg.Satuan,
		arg.QtyActualKirimSource,
		arg.QtyActualKirimManual,
		arg.RejectQty,
		arg.ReturQty,
		arg.Keterangan,
		arg.IDMaterialListItem,
		arg.IDWoShell,
		arg.IDWoTrim,
	)
	var i RekonsiliasiMaterialRow
	err := row.Scan(
		&i.IDRekonsiliasiMaterialRow,
		&i.IDRekonsiliasi,
		&i.RowNo,
		&i.Kategori,
		&i.Description,
		&i.SizeLabel,
		&i.RatioSource,
		&i.RatioInput,
		&i.QtyPerPcsInput,
		&i.QtyWo,
		&i.Toleransi,
		&i.Satuan,
		&i.QtyActualKirimSource,
		&i.QtyActualKirimManual,
		&i.RejectQty,
		&i.ReturQty,
		&i.Keterangan,
		&i.IDMaterialListItem,
		&i.IDWoShell,
		&i.IDWoTrim,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRekonsiliasiTerimaEntry = `-- name: CreateRekonsiliasiTerimaEntry :one
INSERT INTO REKONSILIASI_TERIMA_ENTRY (
    id_rekonsiliasi_material_row,
    entry_type,
    entry_label,
    qty,
    note
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id_rekonsiliasi_terima_entry,
    id_rekonsiliasi_material_row,
    entry_type,
    entry_label,
    qty,
    note,
    created_at,
    updated_at
`

type CreateRekonsiliasiTerimaEntryParams struct {
	IDRekonsiliasiMaterialRow int32  `json:"id_rekonsiliasi_material_row"`
	EntryType                 string `json:"entry_type"`
	EntryLabel                string `json:"entry_label"`
	Qty                       int32  `json:"qty"`
	Note                      string `json:"note"`
}

func (q *Queries) CreateRekonsiliasiTerimaEntry(ctx context.Context, arg CreateRekonsiliasiTerimaEntryParams) (RekonsiliasiTerimaEntry, error) {
	row := q.db.QueryRow(ctx, createRekonsiliasiTerimaEntry,
		arg.IDRekonsiliasiMaterialRow,
		arg.EntryType,
		arg.EntryLabel,
		arg.Qty,
		arg.Note,
	)
	var i RekonsiliasiTerimaEntry
	err := row.Scan(
		&i.IDRekonsiliasiTerimaEntry,
		&i.IDRekonsiliasiMaterialRow,
		&i.EntryType,
		&i.EntryLabel,
		&i.Qty,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRekonsiliasiMaterialRowsByRekonsiliasiID = `-- name: DeleteRekonsiliasiMaterialRowsByRekonsiliasiID :exec
DELETE FROM REKONSILIASI_MATERIAL_ROW
WHERE id_rekonsiliasi = $1
`

func (q *Queries) DeleteRekonsiliasiMaterialRowsByRekonsiliasiID(ctx context.Context, idRekonsiliasi int32) error {
	_, err := q.db.Exec(ctx, deleteRekonsiliasiMaterialRowsByRekonsiliasiID, idRekonsiliasi)
	return err
}

const deleteRekonsiliasiTerimaEntriesByRowID = `-- name: DeleteRekonsiliasiTerimaEntriesByRowID :exec
DELETE FROM REKONSILIASI_TERIMA_ENTRY
WHERE id_rekonsiliasi_material_row = $1
`

func (q *Queries) DeleteRekonsiliasiTerimaEntriesByRowID(ctx context.Context, idRekonsiliasiMaterialRow int32) error {
	_, err := q.db.Exec(ctx, deleteRekonsiliasiTerimaEntriesByRowID, idRekonsiliasiMaterialRow)
	return err
}

const getRekonsiliasiByID = `-- name: GetRekonsiliasiByID :one
SELECT
    r.id_rekonsiliasi,
    r.id_wo,
    r.jasa,
    r.no_po,
    r.delivery,
    r.buyer,
    r.brand,
    r.style,
    r.qty_po,
    r.plan_cut_total,
    r.cons_baju_summary,
    r.nama_bahan,
    r.warna_kain_summary,
    r.created_by,
    r.updated_by,
    r.created_at,
    r.updated_at,
    COALESCE(cu.username, '') AS created_by_username,
    COALESCE(uu.username, '') AS updated_by_username
FROM REKONSILIASI r
LEFT JOIN USERS cu ON cu.id_user = r.created_by
LEFT JOIN USERS uu ON uu.id_user = r.updated_by
WHERE r.id_rekonsiliasi = $1
LIMIT 1
`

type GetRekonsiliasiByIDRow struct {
	IDRekonsiliasi    int32              `json:"id_rekonsiliasi"`
	IDWo              int32              `json:"id_wo"`
	Jasa              string             `json:"jasa"`
	NoPo              string             `json:"no_po"`
	Delivery          pgtype.Date        `json:"delivery"`
	Buyer             string             `json:"buyer"`
	Brand             string             `json:"brand"`
	Style             string             `json:"style"`
	QtyPo             int32              `json:"qty_po"`
	PlanCutTotal      int64              `json:"plan_cut_total"`
	ConsBajuSummary   string             `json:"cons_baju_summary"`
	NamaBahan         string             `json:"nama_bahan"`
	WarnaKainSummary  []byte             `json:"warna_kain_summary"`
	CreatedBy         pgtype.Int4        `json:"created_by"`
	UpdatedBy         pgtype.Int4        `json:"updated_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedByUsername string             `json:"created_by_username"`
	UpdatedByUsername string             `json:"updated_by_username"`
}

func (q *Queries) GetRekonsiliasiByID(ctx context.Context, idRekonsiliasi int32) (GetRekonsiliasiByIDRow, error) {
	row := q.db.QueryRow(ctx, getRekonsiliasiByID, idRekonsiliasi)
	var i GetRekonsiliasiByIDRow
	err := row.Scan(
		&i.IDRekonsiliasi,
		&i.IDWo,
		&i.Jasa,
		&i.NoPo,
		&i.Delivery,
		&i.Buyer,
		&i.Brand,
		&i.Style,
		&i.QtyPo,
		&i.PlanCutTotal,
		&i.ConsBajuSummary,
		&i.NamaBahan,
		&i.WarnaKainSummary,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUsername,
		&i.UpdatedByUsername,
	)
	return i, err
}

const getRekonsiliasiByWOID = `-- name: GetRekonsiliasiByWOID :one
SELECT
    r.id_rekonsiliasi,
    r.id_wo,
    r.jasa,
    r.no_po,
    r.delivery,
    r.buyer,
    r.brand,
    r.style,
    r.qty_po,
    r.plan_cut_total,
    r.cons_baju_summary,
    r.nama_bahan,
    r.warna_kain_summary,
    r.created_by,
    r.updated_by,
    r.created_at,
    r.updated_at
FROM REKONSILIASI r
WHERE r.id_wo = $1
LIMIT 1
`

func (q *Queries) GetRekonsiliasiByWOID(ctx context.Context, idWo int32) (Rekonsiliasi, error) {
	row := q.db.QueryRow(ctx, getRekonsiliasiByWOID, idWo)
	var i Rekonsiliasi
	err := row.Scan(
		&i.IDRekonsiliasi,
		&i.IDWo,
		&i.Jasa,
		&i.NoPo,
		&i.Delivery,
		&i.Buyer,
		&i.Brand,
		&i.Style,
		&i.QtyPo,
		&i.PlanCutTotal,
		&i.ConsBajuSummary,
		&i.NamaBahan,
		&i.WarnaKainSummary,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRekonsiliasiSourceHeader = `-- name: GetRekonsiliasiSourceHeader :one
SELECT
    wo.id_wo,
    CASE
        WHEN wo.fob_cmt THEN 'FOB'
        ELSE 'CMT'
    END AS jasa,
    pc.po_number AS no_po,
    pc.delivery,
    wo.buyer,
    ''::text AS brand,
    pci.style,
    pci.qty AS qty_po,
    COALESCE((
        SELECT SUM(rss.ratio_plan)::bigint
        FROM RATIO_SIZE_SPREADING rss
        JOIN RATIO_SPREADING rs ON rs.id_ratio_spreading = rss.id_ratio_spreading
        JOIN WORK_ORDER_SHELL wos_plan ON wos_plan.id_wo_shell = rs.id_wo_shell
        WHERE wos_plan.id_wo = wo.id_wo
    ), 0)::bigint AS plan_cut_total
FROM WORK_ORDER wo
JOIN PO_CLIENT_ITEM pci ON pci.id_po_client_item = wo.id_po_client_item
JOIN PO_CLIENT pc ON pc.id_po_client = pci.id_po_client
WHERE wo.id_wo = $1
LIMIT 1
`

type GetRekonsiliasiSourceHeaderRow struct {
	IDWo         int32       `json:"id_wo"`
	Jasa         string      `json:"jasa"`
	NoPo         string      `json:"no_po"`
	Delivery     pgtype.Date `json:"delivery"`
	Buyer        string      `json:"buyer"`
	Brand        string      `json:"brand"`
	Style        string      `json:"style"`
	QtyPo        int32       `json:"qty_po"`
	PlanCutTotal int64       `json:"plan_cut_total"`
}

func (q *Queries) GetRekonsiliasiSourceHeader(ctx context.Context, idWo int32) (GetRekonsiliasiSourceHeaderRow, error) {
	row := q.db.QueryRow(ctx, getRekonsiliasiSourceHeader, idWo)
	var i GetRekonsiliasiSourceHeaderRow
	err := row.Scan(
		&i.IDWo,
		&i.Jasa,
		&i.NoPo,
		&i.Delivery,
		&i.Buyer,
		&i.Brand,
		&i.Style,
		&i.QtyPo,
		&i.PlanCutTotal,
	)
	return i, err
}

const listRekonsiliasiColorSourcesByWO = `-- name: ListRekonsiliasiColorSourcesByWO :many
SELECT
    wos.color,
    ms.nama_size AS size,
    wss.qty AS qty_order,
    COALESCE(ship.qty_kirim, 0)::integer AS qty_kirim
FROM WORK_ORDER_SHELL wos
JOIN WORK_ORDER_SHELL_SIZE wss ON wss.id_wo_shell = wos.id_wo_shell
JOIN MASTER_SIZE ms ON ms.id_size = wss.id_size
LEFT JOIN (
    SELECT
        rp.id_wo_shell_size,
        SUM(rp.qty) AS qty_kirim
    FROM REPORT_PENGIRIMAN rp
    GROUP BY rp.id_wo_shell_size
) ship ON ship.id_wo_shell_size = wss.id_wo_shell_size
WHERE wos.id_wo = $1
ORDER BY wos.color ASC, wss.id_wo_shell_size ASC
`

type ListRekonsiliasiColorSourcesByWORow struct {
	Color    string `json:"color"`
	Size     string `json:"size"`
	QtyOrder int32  `json:"qty_order"`
	QtyKirim int32  `json:"qty_kirim"`
}

func (q *Queries) ListRekonsiliasiColorSourcesByWO(ctx context.Context, idWo int32) ([]ListRekonsiliasiColorSourcesByWORow, error) {
	rows, err := q.db.Query(ctx, listRekonsiliasiColorSourcesByWO, idWo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRekonsiliasiColorSourcesByWORow
	for rows.Next() {
		var i ListRekonsiliasiColorSourcesByWORow
		if err := rows.Scan(
			&i.Color,
			&i.Size,
			&i.QtyOrder,
			&i.QtyKirim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRekonsiliasiMaterialRowsByRekonsiliasiID = `-- name: ListRekonsiliasiMaterialRowsByRekonsiliasiID :many
SELECT
    id_rekonsiliasi_material_row,
    id_rekonsiliasi,
    row_no,
    kategori,
    description,
    size_label,
    ratio_source,
    ratio_input,
    qty_per_pcs_input,
    qty_wo,
    toleransi,
    satuan,
    qty_actual_kirim_source,
    qty_actual_kirim_manual,
    reject_qty,
    retur_qty,
    keterangan,
    id_material_list_item,
    id_wo_shell,
    id_wo_trim,
    created_at,
    updated_at
FROM REKONSILIASI_MATERIAL_ROW
WHERE id_rekonsiliasi = $1
ORDER BY row_no ASC, id_rekonsiliasi_material_row ASC
`

func (q *Queries) ListRekonsiliasiMaterialRowsByRekonsiliasiID(ctx context.Context, idRekonsiliasi int32) ([]RekonsiliasiMaterialRow, error) {
	rows, err := q.db.Query(ctx, listRekonsiliasiMaterialRowsByRekonsiliasiID, idRekonsiliasi)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RekonsiliasiMaterialRow
	for rows.Next() {
		var i RekonsiliasiMaterialRow
		if err := rows.Scan(
			&i.IDRekonsiliasiMaterialRow,
			&i.IDRekonsiliasi,
			&i.RowNo,
			&i.Kategori,
			&i.Description,
			&i.SizeLabel,
			&i.RatioSource,
			&i.RatioInput,
			&i.QtyPerPcsInput,
			&i.QtyWo,
			&i.Toleransi,
			&i.Satuan,
			&i.QtyActualKirimSource,
			&i.QtyActualKirimManual,
			&i.RejectQty,
			&i.ReturQty,
			&i.Keterangan,
			&i.IDMaterialListItem,
			&i.IDWoShell,
			&i.IDWoTrim,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRekonsiliasiMaterialSourceRowsByWO = `-- name: ListRekonsiliasiMaterialSourceRowsByWO :many
SELECT
    mli.id_material_list_item,
    mli.id_material_list,
    CASE
        WHEN mli.id_wo_shell IS NOT NULL THEN 'shell'
        ELSE 'trim'
    END AS kategori,
    COALESCE(
        NULLIF(mli.item, ''),
        NULLIF(mli.description, ''),
        CASE
            WHEN mli.id_wo_shell IS NOT NULL THEN wos.deskripsi
            ELSE wot.item
        END,
        ''
    ) AS description,
    CASE
        WHEN mli.id_wo_shell IS NOT NULL THEN COALESCE(wos.color, 'ALL SIZE')
        WHEN COALESCE(wot.color, '') <> '' THEN wot.color
        ELSE 'ALL SIZE'
    END AS size_label,
    CASE
        WHEN mli.id_wo_shell IS NOT NULL THEN COALESCE(shell_qty.qty_order, 0)::numeric
        WHEN mli.id_wo_trim IS NOT NULL THEN COALESCE(wot.qty, mli.qty)::numeric
        ELSE mli.qty::numeric
    END AS ratio_source,
    CASE
        WHEN mli.id_wo_shell IS NOT NULL THEN COALESCE(ROUND(shell_qty.qty_order::numeric * wos.cons), 0)::integer
        WHEN mli.id_wo_trim IS NOT NULL THEN COALESCE(wot.qty, mli.qty)
        ELSE mli.qty
    END AS qty_wo,
    CASE
        WHEN mli.id_wo_shell IS NOT NULL THEN COALESCE(wos.allow, 0)
        WHEN mli.id_wo_trim IS NOT NULL THEN COALESCE(wot.allow, 0)
        ELSE 0
    END AS toleransi,
    CASE
        WHEN COALESCE(NULLIF(mli.unit, ''), '') <> '' THEN mli.unit
        WHEN mli.id_wo_shell IS NOT NULL THEN 'YDS'
        WHEN mli.id_wo_trim IS NOT NULL THEN COALESCE(wot.uom, '')
        ELSE ''
    END AS satuan,
    CASE
        WHEN mli.id_wo_shell IS NOT NULL THEN COALESCE(shell_ship.qty_shipped, 0)
        ELSE COALESCE(wo_ship.qty_shipped, 0)
    END AS qty_actual_kirim_source,
    mli.id_wo_shell,
    mli.id_wo_trim
FROM MATERIAL_LIST_ITEM mli
JOIN MATERIAL_LIST ml ON ml.id_material_list = mli.id_material_list
LEFT JOIN WORK_ORDER_SHELL wos ON wos.id_wo_shell = mli.id_wo_shell
LEFT JOIN WORK_ORDER_TRIM wot ON wot.id_wo_trim = mli.id_wo_trim
LEFT JOIN (
    SELECT
        wss.id_wo_shell,
        SUM(wss.qty) AS qty_order
    FROM WORK_ORDER_SHELL_SIZE wss
    GROUP BY wss.id_wo_shell
) shell_qty ON shell_qty.id_wo_shell = mli.id_wo_shell
LEFT JOIN (
    SELECT
        wss.id_wo_shell,
        SUM(rp.qty)::integer AS qty_shipped
    FROM REPORT_PENGIRIMAN rp
    JOIN WORK_ORDER_SHELL_SIZE wss ON wss.id_wo_shell_size = rp.id_wo_shell_size
    GROUP BY wss.id_wo_shell
) shell_ship ON shell_ship.id_wo_shell = mli.id_wo_shell
LEFT JOIN (
    SELECT
        wos2.id_wo,
        SUM(rp.qty)::integer AS qty_shipped
    FROM REPORT_PENGIRIMAN rp
    JOIN WORK_ORDER_SHELL_SIZE wss2 ON wss2.id_wo_shell_size = rp.id_wo_shell_size
    JOIN WORK_ORDER_SHELL wos2 ON wos2.id_wo_shell = wss2.id_wo_shell
    GROUP BY wos2.id_wo
) wo_ship ON wo_ship.id_wo = ml.id_wo
WHERE ml.id_wo = $1
ORDER BY mli.id_material_list_item ASC
`

type ListRekonsiliasiMaterialSourceRowsByWORow struct {
	IDMaterialListItem   int32          `json:"id_material_list_item"`
	IDMaterialList       int32          `json:"id_material_list"`
	Kategori             string         `json:"kategori"`
	Description          interface{}    `json:"description"`
	SizeLabel            string         `json:"size_label"`
	RatioSource          pgtype.Numeric `json:"ratio_source"`
	QtyWo                interface{}    `json:"qty_wo"`
	Toleransi            int32          `json:"toleransi"`
	Satuan               string         `json:"satuan"`
	QtyActualKirimSource interface{}    `json:"qty_actual_kirim_source"`
	IDWoShell            pgtype.Int4    `json:"id_wo_shell"`
	IDWoTrim             pgtype.Int4    `json:"id_wo_trim"`
}

func (q *Queries) ListRekonsiliasiMaterialSourceRowsByWO(ctx context.Context, idWo int32) ([]ListRekonsiliasiMaterialSourceRowsByWORow, error) {
	rows, err := q.db.Query(ctx, listRekonsiliasiMaterialSourceRowsByWO, idWo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRekonsiliasiMaterialSourceRowsByWORow
	for rows.Next() {
		var i ListRekonsiliasiMaterialSourceRowsByWORow
		if err := rows.Scan(
			&i.IDMaterialListItem,
			&i.IDMaterialList,
			&i.Kategori,
			&i.Description,
			&i.SizeLabel,
			&i.RatioSource,
			&i.QtyWo,
			&i.Toleransi,
			&i.Satuan,
			&i.QtyActualKirimSource,
			&i.IDWoShell,
			&i.IDWoTrim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRekonsiliasiShellSourcesByWO = `-- name: ListRekonsiliasiShellSourcesByWO :many
SELECT
    wos.id_wo_shell,
    wos.deskripsi,
    wos.color,
    wos.cons,
    wos.allow,
    wos.material_type,
    COALESCE(SUM(wss.qty), 0)::integer AS qty_order,
    COALESCE(shell_ship.qty_shipped, 0)::integer AS qty_actual_kirim_source
FROM WORK_ORDER_SHELL wos
LEFT JOIN WORK_ORDER_SHELL_SIZE wss ON wss.id_wo_shell = wos.id_wo_shell
LEFT JOIN (
    SELECT
        wss2.id_wo_shell,
        SUM(rp.qty) AS qty_shipped
    FROM REPORT_PENGIRIMAN rp
    JOIN WORK_ORDER_SHELL_SIZE wss2 ON wss2.id_wo_shell_size = rp.id_wo_shell_size
    GROUP BY wss2.id_wo_shell
) shell_ship ON shell_ship.id_wo_shell = wos.id_wo_shell
WHERE wos.id_wo = $1
GROUP BY
    wos.id_wo_shell,
    wos.deskripsi,
    wos.color,
    wos.cons,
    wos.allow,
    wos.material_type,
    shell_ship.qty_shipped
ORDER BY wos.id_wo_shell ASC
`

type ListRekonsiliasiShellSourcesByWORow struct {
	IDWoShell            int32          `json:"id_wo_shell"`
	Deskripsi            string         `json:"deskripsi"`
	Color                string         `json:"color"`
	Cons                 pgtype.Numeric `json:"cons"`
	Allow                int32          `json:"allow"`
	MaterialType         string         `json:"material_type"`
	QtyOrder             int32          `json:"qty_order"`
	QtyActualKirimSource int32          `json:"qty_actual_kirim_source"`
}

func (q *Queries) ListRekonsiliasiShellSourcesByWO(ctx context.Context, idWo int32) ([]ListRekonsiliasiShellSourcesByWORow, error) {
	rows, err := q.db.Query(ctx, listRekonsiliasiShellSourcesByWO, idWo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRekonsiliasiShellSourcesByWORow
	for rows.Next() {
		var i ListRekonsiliasiShellSourcesByWORow
		if err := rows.Scan(
			&i.IDWoShell,
			&i.Deskripsi,
			&i.Color,
			&i.Cons,
			&i.Allow,
			&i.MaterialType,
			&i.QtyOrder,
			&i.QtyActualKirimSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRekonsiliasiTerimaEntriesByRekonsiliasiID = `-- name: ListRekonsiliasiTerimaEntriesByRekonsiliasiID :many
SELECT
    rte.id_rekonsiliasi_terima_entry,
    rte.id_rekonsiliasi_material_row,
    rte.entry_type,
    rte.entry_label,
    rte.qty,
    rte.note,
    rte.created_at,
    rte.updated_at
FROM REKONSILIASI_TERIMA_ENTRY rte
JOIN REKONSILIASI_MATERIAL_ROW rmr ON rmr.id_rekonsiliasi_material_row = rte.id_rekonsiliasi_material_row
WHERE rmr.id_rekonsiliasi = $1
ORDER BY rmr.row_no ASC, rte.id_rekonsiliasi_terima_entry ASC
`

func (q *Queries) ListRekonsiliasiTerimaEntriesByRekonsiliasiID(ctx context.Context, idRekonsiliasi int32) ([]RekonsiliasiTerimaEntry, error) {
	rows, err := q.db.Query(ctx, listRekonsiliasiTerimaEntriesByRekonsiliasiID, idRekonsiliasi)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RekonsiliasiTerimaEntry
	for rows.Next() {
		var i RekonsiliasiTerimaEntry
		if err := rows.Scan(
			&i.IDRekonsiliasiTerimaEntry,
			&i.IDRekonsiliasiMaterialRow,
			&i.EntryType,
			&i.EntryLabel,
			&i.Qty,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRekonsiliasis = `-- name: ListRekonsiliasis :many
SELECT
    r.id_rekonsiliasi,
    r.id_wo,
    wo.model AS nama_wo,
    r.buyer,
    r.brand,
    r.style,
    r.qty_po,
    r.plan_cut_total,
    r.created_at,
    r.updated_at,
    COALESCE(cu.username, '') AS created_by_username,
    COALESCE(uu.username, '') AS updated_by_username,
    COUNT(*) OVER() AS total_count
FROM REKONSILIASI r
JOIN WORK_ORDER wo ON wo.id_wo = r.id_wo
LEFT JOIN USERS cu ON cu.id_user = r.created_by
LEFT JOIN USERS uu ON uu.id_user = r.updated_by
WHERE (
    $1::text = ''
    OR r.no_po ILIKE '%' || $1::text || '%'
    OR r.buyer ILIKE '%' || $1::text || '%'
    OR r.style ILIKE '%' || $1::text || '%'
    OR wo.model ILIKE '%' || $1::text || '%'
) AND (
    $2::integer IS NULL
    OR r.id_wo = $2::integer
)
ORDER BY
    CASE WHEN $3::text = 'created_at' AND NOT $4::bool THEN r.created_at END ASC,
    CASE WHEN $3::text = 'created_at' AND $4::bool THEN r.created_at END DESC,
    CASE WHEN $3::text = 'updated_at' AND NOT $4::bool THEN r.updated_at END ASC,
    CASE WHEN $3::text = 'updated_at' AND $4::bool THEN r.updated_at END DESC,
    CASE WHEN $3::text = 'id_rekonsiliasi' AND NOT $4::bool THEN r.id_rekonsiliasi END ASC,
    CASE WHEN $3::text = 'id_rekonsiliasi' AND $4::bool THEN r.id_rekonsiliasi END DESC,
    CASE WHEN $3::text = 'id_wo' AND NOT $4::bool THEN r.id_wo END ASC,
    CASE WHEN $3::text = 'id_wo' AND $4::bool THEN r.id_wo END DESC,
    CASE WHEN $3::text = 'buyer' AND NOT $4::bool THEN r.buyer END ASC,
    CASE WHEN $3::text = 'buyer' AND $4::bool THEN r.buyer END DESC,
    CASE WHEN $3::text = 'style' AND NOT $4::bool THEN r.style END ASC,
    CASE WHEN $3::text = 'style' AND $4::bool THEN r.style END DESC,
    r.id_rekonsiliasi DESC
LIMIT $6 OFFSET $5
`

type ListRekonsiliasisParams struct {
	SearchTerm string      `json:"search_term"`
	IDWo       pgtype.Int4 `json:"id_wo"`
	SortBy     string      `json:"sort_by"`
	SortDesc   bool        `json:"sort_desc"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type ListRekonsiliasisRow struct {
	IDRekonsiliasi    int32              `json:"id_rekonsiliasi"`
	IDWo              int32              `json:"id_wo"`
	NamaWo            string             `json:"nama_wo"`
	Buyer             string             `json:"buyer"`
	Brand             string             `json:"brand"`
	Style             string             `json:"style"`
	QtyPo             int32              `json:"qty_po"`
	PlanCutTotal      int64              `json:"plan_cut_total"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedByUsername string             `json:"created_by_username"`
	UpdatedByUsername string             `json:"updated_by_username"`
	TotalCount        int64              `json:"total_count"`
}

func (q *Queries) ListRekonsiliasis(ctx context.Context, arg ListRekonsiliasisParams) ([]ListRekonsiliasisRow, error) {
	rows, err := q.db.Query(ctx, listRekonsiliasis,
		arg.SearchTerm,
		arg.IDWo,
		arg.SortBy,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRekonsiliasisRow
	for rows.Next() {
		var i ListRekonsiliasisRow
		if err := rows.Scan(
			&i.IDRekonsiliasi,
			&i.IDWo,
			&i.NamaWo,
			&i.Buyer,
			&i.Brand,
			&i.Style,
			&i.QtyPo,
			&i.PlanCutTotal,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByUsername,
			&i.UpdatedByUsername,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchRekonsiliasi = `-- name: TouchRekonsiliasi :one
UPDATE REKONSILIASI
SET
    updated_by = $1,
    updated_at = NOW()
WHERE id_rekonsiliasi = $2
RETURNING
    id_rekonsiliasi,
    id_wo,
    jasa,
    no_po,
    delivery,
    buyer,
    brand,
    style,
    qty_po,
    plan_cut_total,
    cons_baju_summary,
    nama_bahan,
    warna_kain_summary,
    created_by,
    updated_by,
    created_at,
    updated_at
`

type TouchRekonsiliasiParams struct {
	UpdatedBy      pgtype.Int4 `json:"updated_by"`
	IDRekonsiliasi int32       `json:"id_rekonsiliasi"`
}

func (q *Queries) TouchRekonsiliasi(ctx context.Context, arg TouchRekonsiliasiParams) (Rekonsiliasi, error) {
	row := q.db.QueryRow(ctx, touchRekonsiliasi, arg.UpdatedBy, arg.IDRekonsiliasi)
	var i Rekonsiliasi
	err := row.Scan(
		&i.IDRekonsiliasi,
		&i.IDWo,
		&i.Jasa,
		&i.NoPo,
		&i.Delivery,
		&i.Buyer,
		&i.Brand,
		&i.Style,
		&i.QtyPo,
		&i.PlanCutTotal,
		&i.ConsBajuSummary,
		&i.NamaBahan,
		&i.WarnaKainSummary,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRekonsiliasiMaterialRowManualFields = `-- name: UpdateRekonsiliasiMaterialRowManualFields :one
UPDATE REKONSILIASI_MATERIAL_ROW
SET
    ratio_input = $1::numeric,
    qty_per_pcs_input = $2::numeric,
    qty_actual_kirim_manual = $3,
    reject_qty = $4,
    retur_qty = $5,
    keterangan = $6,
    updated_at = NOW()
WHERE id_rekonsiliasi_material_row = $7
RETURNING
    id_rekonsiliasi_material_row,
    id_rekonsiliasi,
    row_no,
    kategori,
    description,
    size_label,
    ratio_source,
    ratio_input,
    qty_per_pcs_input,
    qty_wo,
    toleransi,
    satuan,
    qty_actual_kirim_source,
    qty_actual_kirim_manual,
    reject_qty,
    retur_qty,
    keterangan,
    id_material_list_item,
    id_wo_shell,
    id_wo_trim,
    created_at,
    updated_at
`

type UpdateRekonsiliasiMaterialRowManualFieldsParams struct {
	RatioInput                pgtype.Numeric `json:"ratio_input"`
	QtyPerPcsInput            pgtype.Numeric `json:"qty_per_pcs_input"`
	QtyActualKirimManual      int32          `json:"qty_actual_kirim_manual"`
	RejectQty                 int32          `json:"reject_qty"`
	ReturQty                  int32          `json:"retur_qty"`
	Keterangan                string         `json:"keterangan"`
	IDRekonsiliasiMaterialRow int32          `json:"id_rekonsiliasi_material_row"`
}

func (q *Queries) UpdateRekonsiliasiMaterialRowManualFields(ctx context.Context, arg UpdateRekonsiliasiMaterialRowManualFieldsParams) (RekonsiliasiMaterialRow, error) {
	row := q.db.QueryRow(ctx, updateRekonsiliasiMaterialRowManualFields,
		arg.RatioInput,
		arg.QtyPerPcsInput,
		arg.QtyActualKirimManual,
		arg.RejectQty,
		arg.ReturQty,
		arg.Keterangan,
		arg.IDRekonsiliasiMaterialRow,
	)
	var i RekonsiliasiMaterialRow
	err := row.Scan(
		&i.IDRekonsiliasiMaterialRow,
		&i.IDRekonsiliasi,
		&i.RowNo,
		&i.Kategori,
		&i.Description,
		&i.SizeLabel,
		&i.RatioSource,
		&i.RatioInput,
		&i.QtyPerPcsInput,
		&i.QtyWo,
		&i.Toleransi,
		&i.Satuan,
		&i.QtyActualKirimSource,
		&i.QtyActualKirimManual,
		&i.RejectQty,
		&i.ReturQty,
		&i.Keterangan,
		&i.IDMaterialListItem,
		&i.IDWoShell,
		&i.IDWoTrim,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRekonsiliasiSnapshot = `-- name: UpdateRekonsiliasiSnapshot :one
UPDATE REKONSILIASI
SET
    jasa = $1,
    no_po = $2,
    delivery = $3::date,
    buyer = $4,
    brand = $5,
    style = $6,
    qty_po = $7,
    plan_cut_total = $8,
    cons_baju_summary = $9,
    nama_bahan = $10,
    warna_kain_summary = to_jsonb($11::text[]),
    updated_by = $12,
    updated_at = NOW()
WHERE id_rekonsiliasi = $13
RETURNING
    id_rekonsiliasi,
    id_wo,
    jasa,
    no_po,
    delivery,
    buyer,
    brand,
    style,
    qty_po,
    plan_cut_total,
    cons_baju_summary,
    nama_bahan,
    warna_kain_summary,
    created_by,
    updated_by,
    created_at,
    updated_at
`

type UpdateRekonsiliasiSnapshotParams struct {
	Jasa             string      `json:"jasa"`
	NoPo             string      `json:"no_po"`
	Delivery         pgtype.Date `json:"delivery"`
	Buyer            string      `json:"buyer"`
	Brand            string      `json:"brand"`
	Style            string      `json:"style"`
	QtyPo            int32       `json:"qty_po"`
	PlanCutTotal     int64       `json:"plan_cut_total"`
	ConsBajuSummary  string      `json:"cons_baju_summary"`
	NamaBahan        string      `json:"nama_bahan"`
	WarnaKainSummary []string    `json:"warna_kain_summary"`
	UpdatedBy        pgtype.Int4 `json:"updated_by"`
	IDRekonsiliasi   int32       `json:"id_rekonsiliasi"`
}

func (q *Queries) UpdateRekonsiliasiSnapshot(ctx context.Context, arg UpdateRekonsiliasiSnapshotParams) (Rekonsiliasi, error) {
	row := q.db.QueryRow(ctx, updateRekonsiliasiSnapshot,
		arg.Jasa,
		arg.NoPo,
		arg.Delivery,
		arg.Buyer,
		arg.Brand,
		arg.Style,
		arg.QtyPo,
		arg.PlanCutTotal,
		arg.ConsBajuSummary,
		arg.NamaBahan,
		arg.WarnaKainSummary,
		arg.UpdatedBy,
		arg.IDRekonsiliasi,
	)
	var i Rekonsiliasi
	err := row.Scan(
		&i.IDRekonsiliasi,
		&i.IDWo,
		&i.Jasa,
		&i.NoPo,
		&i.Delivery,
		&i.Buyer,
		&i.Brand,
		&i.Style,
		&i.QtyPo,
		&i.PlanCutTotal,
		&i.ConsBajuSummary,
		&i.NamaBahan,
		&i.WarnaKainSummary,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
