// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMovementReport = `-- name: GetMovementReport :many
SELECT 
    'IN'::text AS tipe,
    r.tanggal,
    r.qty::int AS qty,
    r.keterangan,
    ml.description::text AS nama_material,
    ml.size::text AS size,
    ml.uom::text AS uom,
    wo.model::text AS work_order_model
FROM 
    RECEIVED r
JOIN 
    MATERIAL_LIST ml ON r.id_material_list = ml.id_material_list
JOIN 
    WORK_ORDER wo ON ml.id_wo = wo.id_wo

UNION ALL

SELECT 
    'OUT'::text AS tipe,
    sjc.tanggal,
    sjc.qty::int AS qty,
    sjc.keterangan,
    ml.description::text AS nama_material,
    ml.size::text AS size,
    ml.uom::text AS uom,
    wo.model::text AS work_order_model
FROM 
    SURAT_JALAN_CLIENT sjc
JOIN 
    MATERIAL_LIST ml ON sjc.id_material_list = ml.id_material_list
JOIN 
    WORK_ORDER wo ON ml.id_wo = wo.id_wo

ORDER BY 
    tanggal DESC, nama_material ASC
`

type GetMovementReportRow struct {
	Tipe           string      `json:"tipe"`
	Tanggal        pgtype.Date `json:"tanggal"`
	Qty            int32       `json:"qty"`
	Keterangan     string      `json:"keterangan"`
	NamaMaterial   string      `json:"nama_material"`
	Size           string      `json:"size"`
	Uom            string      `json:"uom"`
	WorkOrderModel string      `json:"work_order_model"`
}

// Mengambil laporan riwayat pergerakan stok masuk (received) dan keluar (surat jalan) secara kronologis
func (q *Queries) GetMovementReport(ctx context.Context) ([]GetMovementReportRow, error) {
	rows, err := q.db.Query(ctx, getMovementReport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMovementReportRow
	for rows.Next() {
		var i GetMovementReportRow
		if err := rows.Scan(
			&i.Tipe,
			&i.Tanggal,
			&i.Qty,
			&i.Keterangan,
			&i.NamaMaterial,
			&i.Size,
			&i.Uom,
			&i.WorkOrderModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockReportPerKategori = `-- name: GetStockReportPerKategori :many
SELECT 
    COALESCE(jb.nama_jenis_barang, 'Lain-lain')::text AS kategori,
    rm.description::text AS nama_barang,
    rm.size::text AS size,
    SUM(rm.balance)::bigint AS total_stok,
    rm.satuan::text AS satuan
FROM 
    REKONSILIASI_MATERIAL rm
LEFT JOIN 
    BARANG b ON rm.description = b.nama_barang OR rm.description = b.kode
LEFT JOIN 
    JENIS_BARANG jb ON b.id_jenis_barang = jb.id_jenis_barang
GROUP BY 
    jb.nama_jenis_barang, rm.description, rm.size, rm.satuan
ORDER BY 
    kategori ASC, nama_barang ASC
`

type GetStockReportPerKategoriRow struct {
	Kategori   string `json:"kategori"`
	NamaBarang string `json:"nama_barang"`
	Size       string `json:"size"`
	TotalStok  int64  `json:"total_stok"`
	Satuan     string `json:"satuan"`
}

// Mengambil laporan stok material yang teragregasi per kategori barang garmen
func (q *Queries) GetStockReportPerKategori(ctx context.Context) ([]GetStockReportPerKategoriRow, error) {
	rows, err := q.db.Query(ctx, getStockReportPerKategori)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStockReportPerKategoriRow
	for rows.Next() {
		var i GetStockReportPerKategoriRow
		if err := rows.Scan(
			&i.Kategori,
			&i.NamaBarang,
			&i.Size,
			&i.TotalStok,
			&i.Satuan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockReportPerLokasi = `-- name: GetStockReportPerLokasi :many
SELECT 
    COALESCE(b.lokasi_rak, 'Belum Diatur')::text AS lokasi_rak,
    rm.description::text AS nama_barang,
    rm.size::text AS size,
    SUM(rm.balance)::bigint AS total_stok,
    rm.satuan::text AS satuan
FROM 
    REKONSILIASI_MATERIAL rm
LEFT JOIN 
    BARANG b ON rm.description = b.nama_barang OR rm.description = b.kode
GROUP BY 
    b.lokasi_rak, rm.description, rm.size, rm.satuan
ORDER BY 
    lokasi_rak ASC, nama_barang ASC
`

type GetStockReportPerLokasiRow struct {
	LokasiRak  string `json:"lokasi_rak"`
	NamaBarang string `json:"nama_barang"`
	Size       string `json:"size"`
	TotalStok  int64  `json:"total_stok"`
	Satuan     string `json:"satuan"`
}

// Mengambil laporan stok material yang teragregasi per lokasi penyimpanan rak
func (q *Queries) GetStockReportPerLokasi(ctx context.Context) ([]GetStockReportPerLokasiRow, error) {
	rows, err := q.db.Query(ctx, getStockReportPerLokasi)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStockReportPerLokasiRow
	for rows.Next() {
		var i GetStockReportPerLokasiRow
		if err := rows.Scan(
			&i.LokasiRak,
			&i.NamaBarang,
			&i.Size,
			&i.TotalStok,
			&i.Satuan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
