// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retur_client.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const autoCloseWorkOrders = `-- name: AutoCloseWorkOrders :exec
INSERT INTO OTORITAS_DOKUMEN (NAMA_TABEL_DOKUMEN, ID_DOKUMEN, STATUS_GLOBAL)
SELECT 'WORK_ORDER', wo.id_wo, 'client_closed'
FROM WORK_ORDER wo
JOIN (
    SELECT wos.id_wo, MAX(rp.REPORT_DATE) AS last_delivery
    FROM REPORT_PENGIRIMAN rp
    JOIN WORK_ORDER_SHELL_SIZE woss ON woss.id_wo_shell_size = rp.id_wo_shell_size
    JOIN WORK_ORDER_SHELL wos ON wos.id_wo_shell = woss.id_wo_shell
    GROUP BY wos.id_wo
) delivery ON delivery.id_wo = wo.id_wo
LEFT JOIN RETUR_CLIENT rc ON rc.id_wo = wo.id_wo
LEFT JOIN OTORITAS_DOKUMEN od ON od.NAMA_TABEL_DOKUMEN = 'WORK_ORDER' AND od.ID_DOKUMEN = wo.id_wo
WHERE COALESCE(od.STATUS_GLOBAL, 'open') = 'open'
  AND rc.id_retur_client IS NULL
  AND delivery.last_delivery < NOW() - INTERVAL '2 months'
ON CONFLICT (NAMA_TABEL_DOKUMEN, ID_DOKUMEN)
DO UPDATE SET STATUS_GLOBAL = 'client_closed'
`

func (q *Queries) AutoCloseWorkOrders(ctx context.Context) error {
	_, err := q.db.Exec(ctx, autoCloseWorkOrders)
	return err
}

const clientCloseWorkOrder = `-- name: ClientCloseWorkOrder :one
INSERT INTO OTORITAS_DOKUMEN (NAMA_TABEL_DOKUMEN, ID_DOKUMEN, STATUS_GLOBAL)
VALUES ('WORK_ORDER', $1, 'client_closed')
ON CONFLICT (NAMA_TABEL_DOKUMEN, ID_DOKUMEN)
DO UPDATE SET STATUS_GLOBAL = 'client_closed'
RETURNING ID_DOKUMEN AS id_wo, STATUS_GLOBAL AS status
`

type ClientCloseWorkOrderRow struct {
	IDWo   int32  `json:"id_wo"`
	Status string `json:"status"`
}

func (q *Queries) ClientCloseWorkOrder(ctx context.Context, idWo int32) (ClientCloseWorkOrderRow, error) {
	row := q.db.QueryRow(ctx, clientCloseWorkOrder, idWo)
	var i ClientCloseWorkOrderRow
	err := row.Scan(&i.IDWo, &i.Status)
	return i, err
}

const createReturClient = `-- name: CreateReturClient :one
INSERT INTO RETUR_CLIENT (
    id_wo,
    file,
    deskripsi
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id_retur_client, id_wo, file, deskripsi, created_at
`

type CreateReturClientParams struct {
	IDWo      int32  `json:"id_wo"`
	File      string `json:"file"`
	Deskripsi string `json:"deskripsi"`
}

func (q *Queries) CreateReturClient(ctx context.Context, arg CreateReturClientParams) (ReturClient, error) {
	row := q.db.QueryRow(ctx, createReturClient, arg.IDWo, arg.File, arg.Deskripsi)
	var i ReturClient
	err := row.Scan(
		&i.IDReturClient,
		&i.IDWo,
		&i.File,
		&i.Deskripsi,
		&i.CreatedAt,
	)
	return i, err
}

const getReturClientByWorkOrderID = `-- name: GetReturClientByWorkOrderID :one
SELECT id_retur_client, id_wo, file, deskripsi, created_at
FROM RETUR_CLIENT
WHERE id_wo = $1 LIMIT 1
`

func (q *Queries) GetReturClientByWorkOrderID(ctx context.Context, idWo int32) (ReturClient, error) {
	row := q.db.QueryRow(ctx, getReturClientByWorkOrderID, idWo)
	var i ReturClient
	err := row.Scan(
		&i.IDReturClient,
		&i.IDWo,
		&i.File,
		&i.Deskripsi,
		&i.CreatedAt,
	)
	return i, err
}

const listReturClients = `-- name: ListReturClients :many
SELECT rc.id_retur_client, rc.id_wo, rc.file, rc.deskripsi, rc.created_at,
       wo.buyer, wo.model, wo.qty AS wo_qty,
       pc.po_number, pc.id_mitra, m.nama_perusahaan as mitra_name,
       pc.id_po_client,
       COUNT(*) OVER() as total_count
FROM RETUR_CLIENT rc
JOIN WORK_ORDER wo ON wo.id_wo = rc.id_wo
JOIN PO_CLIENT_ITEM pci ON pci.id_po_client_item = wo.id_po_client_item
JOIN PO_CLIENT pc ON pc.id_po_client = pci.id_po_client
JOIN MITRA m ON m.id_mitra = pc.id_mitra
WHERE (
    $1::integer IS NULL OR
    pc.id_mitra = $1::integer
) AND (
    $2::text = '' OR
    pc.po_number ILIKE '%' || $2::text || '%' OR
    wo.model ILIKE '%' || $2::text || '%'
)
ORDER BY rc.created_at DESC
LIMIT $4::integer
OFFSET $3::integer
`

type ListReturClientsParams struct {
	IDMitra    pgtype.Int4 `json:"id_mitra"`
	Search     string      `json:"search"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type ListReturClientsRow struct {
	IDReturClient int32              `json:"id_retur_client"`
	IDWo          int32              `json:"id_wo"`
	File          string             `json:"file"`
	Deskripsi     string             `json:"deskripsi"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Buyer         string             `json:"buyer"`
	Model         string             `json:"model"`
	WoQty         int32              `json:"wo_qty"`
	PoNumber      string             `json:"po_number"`
	IDMitra       int32              `json:"id_mitra"`
	MitraName     string             `json:"mitra_name"`
	IDPoClient    int32              `json:"id_po_client"`
	TotalCount    int64              `json:"total_count"`
}

func (q *Queries) ListReturClients(ctx context.Context, arg ListReturClientsParams) ([]ListReturClientsRow, error) {
	rows, err := q.db.Query(ctx, listReturClients,
		arg.IDMitra,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReturClientsRow
	for rows.Next() {
		var i ListReturClientsRow
		if err := rows.Scan(
			&i.IDReturClient,
			&i.IDWo,
			&i.File,
			&i.Deskripsi,
			&i.CreatedAt,
			&i.Buyer,
			&i.Model,
			&i.WoQty,
			&i.PoNumber,
			&i.IDMitra,
			&i.MitraName,
			&i.IDPoClient,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
