// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: size.sql

package entity

import (
	"context"
)

const countSizes = `-- name: CountSizes :one
SELECT COUNT(*)
FROM MASTER_SIZE
WHERE (
    $1::text = '' OR
    nama_size ILIKE '%' || $1::text || '%'
)
  AND NOT EXISTS (
      SELECT 1 FROM MASTER_DATA_DELETED mdd
      WHERE mdd.nama_tabel = 'MASTER_SIZE' AND mdd.id_record = MASTER_SIZE.id_size
  )
`

func (q *Queries) CountSizes(ctx context.Context, searchTerm string) (int64, error) {
	row := q.db.QueryRow(ctx, countSizes, searchTerm)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSize = `-- name: CreateSize :one
INSERT INTO MASTER_SIZE (nama_size)
VALUES ($1)
RETURNING id_size, nama_size, created_at
`

func (q *Queries) CreateSize(ctx context.Context, namaSize string) (MasterSize, error) {
	row := q.db.QueryRow(ctx, createSize, namaSize)
	var i MasterSize
	err := row.Scan(&i.IDSize, &i.NamaSize, &i.CreatedAt)
	return i, err
}

const deleteSize = `-- name: DeleteSize :execrows
DELETE FROM MASTER_SIZE
WHERE id_size = $1
`

func (q *Queries) DeleteSize(ctx context.Context, idSize int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSize, idSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSizeByID = `-- name: GetSizeByID :one
SELECT id_size, nama_size, created_at
FROM MASTER_SIZE
WHERE id_size = $1
  AND NOT EXISTS (
      SELECT 1 FROM MASTER_DATA_DELETED mdd
      WHERE mdd.nama_tabel = 'MASTER_SIZE' AND mdd.id_record = MASTER_SIZE.id_size
  )
LIMIT 1
`

func (q *Queries) GetSizeByID(ctx context.Context, idSize int32) (MasterSize, error) {
	row := q.db.QueryRow(ctx, getSizeByID, idSize)
	var i MasterSize
	err := row.Scan(&i.IDSize, &i.NamaSize, &i.CreatedAt)
	return i, err
}

const getSizeByName = `-- name: GetSizeByName :one
SELECT id_size, nama_size, created_at
FROM MASTER_SIZE
WHERE LOWER(BTRIM(nama_size)) = LOWER(BTRIM($1))
  AND NOT EXISTS (
      SELECT 1 FROM MASTER_DATA_DELETED mdd
      WHERE mdd.nama_tabel = 'MASTER_SIZE' AND mdd.id_record = MASTER_SIZE.id_size
  )
LIMIT 1
`

func (q *Queries) GetSizeByName(ctx context.Context, btrim string) (MasterSize, error) {
	row := q.db.QueryRow(ctx, getSizeByName, btrim)
	var i MasterSize
	err := row.Scan(&i.IDSize, &i.NamaSize, &i.CreatedAt)
	return i, err
}

const listSizes = `-- name: ListSizes :many
SELECT id_size, nama_size, created_at
FROM MASTER_SIZE
WHERE (
    $1::text = '' OR
    nama_size ILIKE '%' || $1::text || '%'
)
  AND NOT EXISTS (
      SELECT 1 FROM MASTER_DATA_DELETED mdd
      WHERE mdd.nama_tabel = 'MASTER_SIZE' AND mdd.id_record = MASTER_SIZE.id_size
  )
ORDER BY
    CASE WHEN $2::text = 'created_at' AND NOT $3::bool THEN created_at END ASC,
    CASE WHEN $2::text = 'created_at' AND $3::bool THEN created_at END DESC,
    CASE WHEN $2::text = 'id_size' AND NOT $3::bool THEN id_size END ASC,
    CASE WHEN $2::text = 'id_size' AND $3::bool THEN id_size END DESC,
    CASE WHEN $2::text = 'nama_size' AND NOT $3::bool THEN nama_size END ASC,
    CASE WHEN $2::text = 'nama_size' AND $3::bool THEN nama_size END DESC,
    nama_size ASC,
    id_size ASC
LIMIT $5 OFFSET $4
`

type ListSizesParams struct {
	SearchTerm string `json:"search_term"`
	SortBy     string `json:"sort_by"`
	SortDesc   bool   `json:"sort_desc"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

func (q *Queries) ListSizes(ctx context.Context, arg ListSizesParams) ([]MasterSize, error) {
	rows, err := q.db.Query(ctx, listSizes,
		arg.SearchTerm,
		arg.SortBy,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterSize
	for rows.Next() {
		var i MasterSize
		if err := rows.Scan(&i.IDSize, &i.NamaSize, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSize = `-- name: UpdateSize :one
UPDATE MASTER_SIZE
SET nama_size = $2
WHERE id_size = $1
RETURNING id_size, nama_size, created_at
`

type UpdateSizeParams struct {
	IDSize   int32  `json:"id_size"`
	NamaSize string `json:"nama_size"`
}

func (q *Queries) UpdateSize(ctx context.Context, arg UpdateSizeParams) (MasterSize, error) {
	row := q.db.QueryRow(ctx, updateSize, arg.IDSize, arg.NamaSize)
	var i MasterSize
	err := row.Scan(&i.IDSize, &i.NamaSize, &i.CreatedAt)
	return i, err
}
