// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spreading_cutting_plan_export.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSpreadingCuttingPlanExportHeader = `-- name: GetSpreadingCuttingPlanExportHeader :one

SELECT
    scp.id_spreading_cutting_plan,
    scp.no_dokumen,
    scp.tanggal_efektif,
    wo.id_wo,
    wo.buyer,
    wo.model,
    pci.style
FROM spreading_cutting_plan scp
JOIN work_order wo ON wo.id_wo = scp.id_wo
JOIN po_client_item pci ON pci.id_po_client_item = wo.id_po_client_item
WHERE scp.id_spreading_cutting_plan = $1
`

type GetSpreadingCuttingPlanExportHeaderRow struct {
	IDSpreadingCuttingPlan int32       `json:"id_spreading_cutting_plan"`
	NoDokumen              string      `json:"no_dokumen"`
	TanggalEfektif         pgtype.Date `json:"tanggal_efektif"`
	IDWo                   int32       `json:"id_wo"`
	Buyer                  string      `json:"buyer"`
	Model                  string      `json:"model"`
	Style                  string      `json:"style"`
}

// Dedicated fixed reads for the renderer-neutral Spreading & Cutting Plan
// export. Marker Plan, Data Approve Cutting Plan, and REPORT_CUTTING are
// intentionally outside this document's source graph.
func (q *Queries) GetSpreadingCuttingPlanExportHeader(ctx context.Context, idSpreadingCuttingPlan int32) (GetSpreadingCuttingPlanExportHeaderRow, error) {
	row := q.db.QueryRow(ctx, getSpreadingCuttingPlanExportHeader, idSpreadingCuttingPlan)
	var i GetSpreadingCuttingPlanExportHeaderRow
	err := row.Scan(
		&i.IDSpreadingCuttingPlan,
		&i.NoDokumen,
		&i.TanggalEfektif,
		&i.IDWo,
		&i.Buyer,
		&i.Model,
		&i.Style,
	)
	return i, err
}

const listSpreadingCuttingPlanExportRatios = `-- name: ListSpreadingCuttingPlanExportRatios :many
SELECT
    kscp.id_komponen_spreading,
    kscp.nama_komponen,
    rs.id_ratio_spreading,
    rs.id_wo_shell AS ratio_shell_id,
    ratio_shell.id_wo AS ratio_shell_wo_id,
    rs.cons,
    rs.plan_spreading_gelaran,
    rs.allowance,
    rs.roll_qty,
    rs.sambungan_roll,
    rs.reject,
    rs.lebar_kain,
    rs.ket,
    rss.id_ratio_size_spreading,
    rss.id_wo_shell_size,
    rss.ratio_plan,
    ratio_size.id_wo_shell AS ratio_size_shell_id,
    ratio_size_shell.id_wo AS ratio_size_shell_wo_id,
    ratio_size.id_size
FROM komponen_spreading_cutting_plan kscp
JOIN ratio_spreading rs ON rs.id_komponen_spreading = kscp.id_komponen_spreading
JOIN work_order_shell ratio_shell ON ratio_shell.id_wo_shell = rs.id_wo_shell
LEFT JOIN ratio_size_spreading rss ON rss.id_ratio_spreading = rs.id_ratio_spreading
LEFT JOIN work_order_shell_size ratio_size ON ratio_size.id_wo_shell_size = rss.id_wo_shell_size
LEFT JOIN work_order_shell ratio_size_shell ON ratio_size_shell.id_wo_shell = ratio_size.id_wo_shell
WHERE kscp.id_spreading_cutting_plan = $1
ORDER BY kscp.id_komponen_spreading ASC, rs.id_ratio_spreading ASC,
         rss.id_ratio_size_spreading ASC NULLS LAST
`

type ListSpreadingCuttingPlanExportRatiosRow struct {
	IDKomponenSpreading  int32          `json:"id_komponen_spreading"`
	NamaKomponen         string         `json:"nama_komponen"`
	IDRatioSpreading     int32          `json:"id_ratio_spreading"`
	RatioShellID         int32          `json:"ratio_shell_id"`
	RatioShellWoID       int32          `json:"ratio_shell_wo_id"`
	Cons                 pgtype.Numeric `json:"cons"`
	PlanSpreadingGelaran pgtype.Numeric `json:"plan_spreading_gelaran"`
	Allowance            pgtype.Numeric `json:"allowance"`
	RollQty              int32          `json:"roll_qty"`
	SambunganRoll        int32          `json:"sambungan_roll"`
	Reject               pgtype.Numeric `json:"reject"`
	LebarKain            pgtype.Numeric `json:"lebar_kain"`
	Ket                  string         `json:"ket"`
	IDRatioSizeSpreading pgtype.Int4    `json:"id_ratio_size_spreading"`
	IDWoShellSize        pgtype.Int4    `json:"id_wo_shell_size"`
	RatioPlan            pgtype.Int4    `json:"ratio_plan"`
	RatioSizeShellID     pgtype.Int4    `json:"ratio_size_shell_id"`
	RatioSizeShellWoID   pgtype.Int4    `json:"ratio_size_shell_wo_id"`
	IDSize               pgtype.Int4    `json:"id_size"`
}

func (q *Queries) ListSpreadingCuttingPlanExportRatios(ctx context.Context, idSpreadingCuttingPlan int32) ([]ListSpreadingCuttingPlanExportRatiosRow, error) {
	rows, err := q.db.Query(ctx, listSpreadingCuttingPlanExportRatios, idSpreadingCuttingPlan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpreadingCuttingPlanExportRatiosRow
	for rows.Next() {
		var i ListSpreadingCuttingPlanExportRatiosRow
		if err := rows.Scan(
			&i.IDKomponenSpreading,
			&i.NamaKomponen,
			&i.IDRatioSpreading,
			&i.RatioShellID,
			&i.RatioShellWoID,
			&i.Cons,
			&i.PlanSpreadingGelaran,
			&i.Allowance,
			&i.RollQty,
			&i.SambunganRoll,
			&i.Reject,
			&i.LebarKain,
			&i.Ket,
			&i.IDRatioSizeSpreading,
			&i.IDWoShellSize,
			&i.RatioPlan,
			&i.RatioSizeShellID,
			&i.RatioSizeShellWoID,
			&i.IDSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpreadingCuttingPlanExportReceivedByShell = `-- name: ListSpreadingCuttingPlanExportReceivedByShell :many
SELECT
    mli.id_wo_shell,
    source_shell.id_wo AS source_shell_wo_id,
    SUM(received.qty)::bigint AS received_actual
FROM material_list ml
JOIN material_list_item mli ON mli.id_material_list = ml.id_material_list
JOIN received ON received.id_material_list_item = mli.id_material_list_item
JOIN work_order_shell source_shell ON source_shell.id_wo_shell = mli.id_wo_shell
WHERE ml.id_wo = $1
GROUP BY mli.id_wo_shell, source_shell.id_wo
ORDER BY mli.id_wo_shell ASC
`

type ListSpreadingCuttingPlanExportReceivedByShellRow struct {
	IDWoShell       pgtype.Int4 `json:"id_wo_shell"`
	SourceShellWoID int32       `json:"source_shell_wo_id"`
	ReceivedActual  int64       `json:"received_actual"`
}

func (q *Queries) ListSpreadingCuttingPlanExportReceivedByShell(ctx context.Context, idWo int32) ([]ListSpreadingCuttingPlanExportReceivedByShellRow, error) {
	rows, err := q.db.Query(ctx, listSpreadingCuttingPlanExportReceivedByShell, idWo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpreadingCuttingPlanExportReceivedByShellRow
	for rows.Next() {
		var i ListSpreadingCuttingPlanExportReceivedByShellRow
		if err := rows.Scan(&i.IDWoShell, &i.SourceShellWoID, &i.ReceivedActual); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpreadingCuttingPlanExportShellSizes = `-- name: ListSpreadingCuttingPlanExportShellSizes :many
SELECT
    wos.id_wo_shell,
    wos.color,
    woss.id_wo_shell_size,
    woss.id_size,
    ms.nama_size,
    woss.qty AS order_qty
FROM work_order_shell wos
LEFT JOIN work_order_shell_size woss ON woss.id_wo_shell = wos.id_wo_shell
LEFT JOIN master_size ms ON ms.id_size = woss.id_size
WHERE wos.id_wo = $1
ORDER BY wos.id_wo_shell ASC, woss.id_wo_shell_size ASC NULLS LAST
`

type ListSpreadingCuttingPlanExportShellSizesRow struct {
	IDWoShell     int32       `json:"id_wo_shell"`
	Color         string      `json:"color"`
	IDWoShellSize pgtype.Int4 `json:"id_wo_shell_size"`
	IDSize        pgtype.Int4 `json:"id_size"`
	NamaSize      pgtype.Text `json:"nama_size"`
	OrderQty      pgtype.Int4 `json:"order_qty"`
}

func (q *Queries) ListSpreadingCuttingPlanExportShellSizes(ctx context.Context, idWo int32) ([]ListSpreadingCuttingPlanExportShellSizesRow, error) {
	rows, err := q.db.Query(ctx, listSpreadingCuttingPlanExportShellSizes, idWo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpreadingCuttingPlanExportShellSizesRow
	for rows.Next() {
		var i ListSpreadingCuttingPlanExportShellSizesRow
		if err := rows.Scan(
			&i.IDWoShell,
			&i.Color,
			&i.IDWoShellSize,
			&i.IDSize,
			&i.NamaSize,
			&i.OrderQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
