// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spreading_cutting_plan.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKomponenSpreadingCuttingPlan = `-- name: CreateKomponenSpreadingCuttingPlan :one
INSERT INTO KOMPONEN_SPREADING_CUTTING_PLAN (
    ID_SPREADING_CUTTING_PLAN, NAMA_KOMPONEN
) VALUES (
    $1, $2
) RETURNING ID_KOMPONEN_SPREADING, ID_SPREADING_CUTTING_PLAN, NAMA_KOMPONEN, created_at
`

type CreateKomponenSpreadingCuttingPlanParams struct {
	IDSpreadingCuttingPlan int32  `json:"id_spreading_cutting_plan"`
	NamaKomponen           string `json:"nama_komponen"`
}

func (q *Queries) CreateKomponenSpreadingCuttingPlan(ctx context.Context, arg CreateKomponenSpreadingCuttingPlanParams) (KomponenSpreadingCuttingPlan, error) {
	row := q.db.QueryRow(ctx, createKomponenSpreadingCuttingPlan, arg.IDSpreadingCuttingPlan, arg.NamaKomponen)
	var i KomponenSpreadingCuttingPlan
	err := row.Scan(
		&i.IDKomponenSpreading,
		&i.IDSpreadingCuttingPlan,
		&i.NamaKomponen,
		&i.CreatedAt,
	)
	return i, err
}

type CreateRatioSizeSpreadingParams struct {
	IDRatioSpreading int32 `json:"id_ratio_spreading"`
	IDWoShellSize    int32 `json:"id_wo_shell_size"`
	RatioPlan        int32 `json:"ratio_plan"`
}

const createRatioSpreading = `-- name: CreateRatioSpreading :one
INSERT INTO RATIO_SPREADING (
    ID_KOMPONEN_SPREADING, ID_WO_SHELL, CONS, PLAN_SPREADING_GELARAN,
    ALLOWANCE, ROLL_QTY, SAMBUNGAN_ROLL, REJECT, LEBAR_KAIN, KET
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING ID_RATIO_SPREADING, ID_KOMPONEN_SPREADING, ID_WO_SHELL, CONS, PLAN_SPREADING_GELARAN, ALLOWANCE, ROLL_QTY, SAMBUNGAN_ROLL, REJECT, LEBAR_KAIN, KET, created_at
`

type CreateRatioSpreadingParams struct {
	IDKomponenSpreading  int32          `json:"id_komponen_spreading"`
	IDWoShell            int32          `json:"id_wo_shell"`
	Cons                 pgtype.Numeric `json:"cons"`
	PlanSpreadingGelaran pgtype.Numeric `json:"plan_spreading_gelaran"`
	Allowance            pgtype.Numeric `json:"allowance"`
	RollQty              int32          `json:"roll_qty"`
	SambunganRoll        int32          `json:"sambungan_roll"`
	Reject               pgtype.Numeric `json:"reject"`
	LebarKain            pgtype.Numeric `json:"lebar_kain"`
	Ket                  string         `json:"ket"`
}

func (q *Queries) CreateRatioSpreading(ctx context.Context, arg CreateRatioSpreadingParams) (RatioSpreading, error) {
	row := q.db.QueryRow(ctx, createRatioSpreading,
		arg.IDKomponenSpreading,
		arg.IDWoShell,
		arg.Cons,
		arg.PlanSpreadingGelaran,
		arg.Allowance,
		arg.RollQty,
		arg.SambunganRoll,
		arg.Reject,
		arg.LebarKain,
		arg.Ket,
	)
	var i RatioSpreading
	err := row.Scan(
		&i.IDRatioSpreading,
		&i.IDKomponenSpreading,
		&i.IDWoShell,
		&i.Cons,
		&i.PlanSpreadingGelaran,
		&i.Allowance,
		&i.RollQty,
		&i.SambunganRoll,
		&i.Reject,
		&i.LebarKain,
		&i.Ket,
		&i.CreatedAt,
	)
	return i, err
}

const createSpreadingCuttingPlan = `-- name: CreateSpreadingCuttingPlan :one
INSERT INTO SPREADING_CUTTING_PLAN (
    NO_DOKUMEN, TANGGAL_EFEKTIF, ID_WO
) VALUES (
    $1, $2, $3
) RETURNING ID_SPREADING_CUTTING_PLAN, NO_DOKUMEN, TANGGAL_EFEKTIF, ID_WO, created_at
`

type CreateSpreadingCuttingPlanParams struct {
	NoDokumen      string      `json:"no_dokumen"`
	TanggalEfektif pgtype.Date `json:"tanggal_efektif"`
	IDWo           int32       `json:"id_wo"`
}

func (q *Queries) CreateSpreadingCuttingPlan(ctx context.Context, arg CreateSpreadingCuttingPlanParams) (SpreadingCuttingPlan, error) {
	row := q.db.QueryRow(ctx, createSpreadingCuttingPlan, arg.NoDokumen, arg.TanggalEfektif, arg.IDWo)
	var i SpreadingCuttingPlan
	err := row.Scan(
		&i.IDSpreadingCuttingPlan,
		&i.NoDokumen,
		&i.TanggalEfektif,
		&i.IDWo,
		&i.CreatedAt,
	)
	return i, err
}

const getSpreadingCuttingPlanByID = `-- name: GetSpreadingCuttingPlanByID :one
SELECT 
    scp.id_spreading_cutting_plan, 
    scp.no_dokumen, 
    scp.tanggal_efektif, 
    scp.id_wo, 
    scp.created_at,
    pci.style,
    wo.model,
    wo.buyer
FROM SPREADING_CUTTING_PLAN scp
JOIN WORK_ORDER wo ON scp.id_wo = wo.id_wo
JOIN PO_CLIENT_ITEM pci ON pci.id_po_client_item = wo.id_po_client_item
WHERE scp.id_spreading_cutting_plan = $1 LIMIT 1
`

type GetSpreadingCuttingPlanByIDRow struct {
	IDSpreadingCuttingPlan int32              `json:"id_spreading_cutting_plan"`
	NoDokumen              string             `json:"no_dokumen"`
	TanggalEfektif         pgtype.Date        `json:"tanggal_efektif"`
	IDWo                   int32              `json:"id_wo"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	Style                  string             `json:"style"`
	Model                  string             `json:"model"`
	Buyer                  string             `json:"buyer"`
}

func (q *Queries) GetSpreadingCuttingPlanByID(ctx context.Context, idSpreadingCuttingPlan int32) (GetSpreadingCuttingPlanByIDRow, error) {
	row := q.db.QueryRow(ctx, getSpreadingCuttingPlanByID, idSpreadingCuttingPlan)
	var i GetSpreadingCuttingPlanByIDRow
	err := row.Scan(
		&i.IDSpreadingCuttingPlan,
		&i.NoDokumen,
		&i.TanggalEfektif,
		&i.IDWo,
		&i.CreatedAt,
		&i.Style,
		&i.Model,
		&i.Buyer,
	)
	return i, err
}

const listKomponenBySpreadingPlanID = `-- name: ListKomponenBySpreadingPlanID :many
SELECT ID_KOMPONEN_SPREADING, ID_SPREADING_CUTTING_PLAN, NAMA_KOMPONEN, created_at
FROM KOMPONEN_SPREADING_CUTTING_PLAN
WHERE ID_SPREADING_CUTTING_PLAN = $1
ORDER BY ID_KOMPONEN_SPREADING ASC
`

func (q *Queries) ListKomponenBySpreadingPlanID(ctx context.Context, idSpreadingCuttingPlan int32) ([]KomponenSpreadingCuttingPlan, error) {
	rows, err := q.db.Query(ctx, listKomponenBySpreadingPlanID, idSpreadingCuttingPlan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KomponenSpreadingCuttingPlan
	for rows.Next() {
		var i KomponenSpreadingCuttingPlan
		if err := rows.Scan(
			&i.IDKomponenSpreading,
			&i.IDSpreadingCuttingPlan,
			&i.NamaKomponen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatioByKomponenSpreadingID = `-- name: ListRatioByKomponenSpreadingID :many
SELECT ID_RATIO_SPREADING, ID_KOMPONEN_SPREADING, ID_WO_SHELL, CONS, PLAN_SPREADING_GELARAN,
       ALLOWANCE, ROLL_QTY, SAMBUNGAN_ROLL, REJECT, LEBAR_KAIN, KET, created_at
FROM RATIO_SPREADING
WHERE ID_KOMPONEN_SPREADING = $1
ORDER BY ID_RATIO_SPREADING ASC
`

func (q *Queries) ListRatioByKomponenSpreadingID(ctx context.Context, idKomponenSpreading int32) ([]RatioSpreading, error) {
	rows, err := q.db.Query(ctx, listRatioByKomponenSpreadingID, idKomponenSpreading)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RatioSpreading
	for rows.Next() {
		var i RatioSpreading
		if err := rows.Scan(
			&i.IDRatioSpreading,
			&i.IDKomponenSpreading,
			&i.IDWoShell,
			&i.Cons,
			&i.PlanSpreadingGelaran,
			&i.Allowance,
			&i.RollQty,
			&i.SambunganRoll,
			&i.Reject,
			&i.LebarKain,
			&i.Ket,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatioSizeByRatioSpreadingID = `-- name: ListRatioSizeByRatioSpreadingID :many
SELECT rss.ID_RATIO_SIZE_SPREADING, rss.ID_RATIO_SPREADING, rss.ID_WO_SHELL_SIZE, rss.RATIO_PLAN, ms.NAMA_SIZE AS SIZE, wss.QTY AS size_qty
FROM RATIO_SIZE_SPREADING rss
JOIN WORK_ORDER_SHELL_SIZE wss ON rss.ID_WO_SHELL_SIZE = wss.ID_WO_SHELL_SIZE
JOIN MASTER_SIZE ms ON ms.ID_SIZE = wss.ID_SIZE
WHERE rss.ID_RATIO_SPREADING = $1
ORDER BY rss.ID_RATIO_SIZE_SPREADING ASC
`

type ListRatioSizeByRatioSpreadingIDRow struct {
	IDRatioSizeSpreading int32  `json:"id_ratio_size_spreading"`
	IDRatioSpreading     int32  `json:"id_ratio_spreading"`
	IDWoShellSize        int32  `json:"id_wo_shell_size"`
	RatioPlan            int32  `json:"ratio_plan"`
	Size                 string `json:"size"`
	SizeQty              int32  `json:"size_qty"`
}

func (q *Queries) ListRatioSizeByRatioSpreadingID(ctx context.Context, idRatioSpreading int32) ([]ListRatioSizeByRatioSpreadingIDRow, error) {
	rows, err := q.db.Query(ctx, listRatioSizeByRatioSpreadingID, idRatioSpreading)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRatioSizeByRatioSpreadingIDRow
	for rows.Next() {
		var i ListRatioSizeByRatioSpreadingIDRow
		if err := rows.Scan(
			&i.IDRatioSizeSpreading,
			&i.IDRatioSpreading,
			&i.IDWoShellSize,
			&i.RatioPlan,
			&i.Size,
			&i.SizeQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpreadingCuttingPlans = `-- name: ListSpreadingCuttingPlans :many
SELECT
    scp.id_spreading_cutting_plan,
    scp.no_dokumen,
    scp.tanggal_efektif,
    scp.id_wo,
    scp.created_at,
    wo.buyer,
    wo.model,
    COUNT(*) OVER() AS total_count
FROM SPREADING_CUTTING_PLAN scp
JOIN WORK_ORDER wo ON scp.id_wo = wo.id_wo
JOIN PO_CLIENT_ITEM pci ON pci.id_po_client_item = wo.id_po_client_item
JOIN PO_CLIENT pc ON pc.id_po_client = pci.id_po_client
WHERE (
    $1 = '' OR
    scp.no_dokumen ILIKE '%' || $1 || '%' OR
    wo.buyer ILIKE '%' || $1 || '%' OR
    wo.model ILIKE '%' || $1 || '%'
) AND (
    $2::integer IS NULL OR
    pc.id_mitra = $2::integer
)
ORDER BY
    CASE WHEN $3::text = 'created_at' AND NOT $4::bool THEN scp.created_at END ASC,
    CASE WHEN $3::text = 'created_at' AND $4::bool THEN scp.created_at END DESC,
    CASE WHEN $3::text = 'no_dokumen' AND NOT $4::bool THEN scp.no_dokumen END ASC,
    CASE WHEN $3::text = 'no_dokumen' AND $4::bool THEN scp.no_dokumen END DESC,
    CASE WHEN $3::text = 'tanggal_efektif' AND NOT $4::bool THEN scp.tanggal_efektif END ASC,
    CASE WHEN $3::text = 'tanggal_efektif' AND $4::bool THEN scp.tanggal_efektif END DESC,
    CASE WHEN $3::text = 'model' AND NOT $4::bool THEN wo.model END ASC,
    CASE WHEN $3::text = 'model' AND $4::bool THEN wo.model END DESC,
    CASE WHEN $3::text = 'buyer' AND NOT $4::bool THEN wo.buyer END ASC,
    CASE WHEN $3::text = 'buyer' AND $4::bool THEN wo.buyer END DESC,
    scp.id_spreading_cutting_plan DESC
LIMIT $6 OFFSET $5
`

type ListSpreadingCuttingPlansParams struct {
	SearchTerm interface{} `json:"search_term"`
	IDMitra    pgtype.Int4 `json:"id_mitra"`
	SortBy     string      `json:"sort_by"`
	SortDesc   bool        `json:"sort_desc"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type ListSpreadingCuttingPlansRow struct {
	IDSpreadingCuttingPlan int32              `json:"id_spreading_cutting_plan"`
	NoDokumen              string             `json:"no_dokumen"`
	TanggalEfektif         pgtype.Date        `json:"tanggal_efektif"`
	IDWo                   int32              `json:"id_wo"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	Buyer                  string             `json:"buyer"`
	Model                  string             `json:"model"`
	TotalCount             int64              `json:"total_count"`
}

func (q *Queries) ListSpreadingCuttingPlans(ctx context.Context, arg ListSpreadingCuttingPlansParams) ([]ListSpreadingCuttingPlansRow, error) {
	rows, err := q.db.Query(ctx, listSpreadingCuttingPlans,
		arg.SearchTerm,
		arg.IDMitra,
		arg.SortBy,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpreadingCuttingPlansRow
	for rows.Next() {
		var i ListSpreadingCuttingPlansRow
		if err := rows.Scan(
			&i.IDSpreadingCuttingPlan,
			&i.NoDokumen,
			&i.TanggalEfektif,
			&i.IDWo,
			&i.CreatedAt,
			&i.Buyer,
			&i.Model,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
