// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package entity

import (
	"context"
)

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id_user, username, password, is_manager, id_departemen, id_mitra, created_at
FROM USERS
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.IDUser,
		&i.Username,
		&i.Password,
		&i.IsManager,
		&i.IDDepartemen,
		&i.IDMitra,
		&i.CreatedAt,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT h.NAMA_HALAMAN
FROM HAK_AKSES h
JOIN USER_AKSES ua ON h.ID_HAK_AKSES = ua.ID_HAK_AKSES
WHERE ua.ID_USER = $1
`

func (q *Queries) GetUserPermissions(ctx context.Context, idUser int32) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, idUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var nama_halaman string
		if err := rows.Scan(&nama_halaman); err != nil {
			return nil, err
		}
		items = append(items, nama_halaman)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
