// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)
FROM USERS u
LEFT JOIN DEPARTEMEN d ON u.id_departemen = d.id_departemen
LEFT JOIN MITRA m ON u.id_mitra = m.id_mitra
WHERE (
    $1::text = '' OR
    u.username ILIKE '%' || $1::text || '%' OR
    u.status ILIKE '%' || $1::text || '%' OR
    COALESCE(d.nama_departemen, '') ILIKE '%' || $1::text || '%' OR
    COALESCE(m.nama_perusahaan, '') ILIKE '%' || $1::text || '%'
)
`

func (q *Queries) CountUsers(ctx context.Context, searchTerm string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, searchTerm)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO USERS (
    username, password, is_manager, id_departemen, id_mitra, status
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id_user, username, is_manager, id_departemen, id_mitra, status, created_at
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	Password     string      `json:"password"`
	IsManager    bool        `json:"is_manager"`
	IDDepartemen pgtype.Int4 `json:"id_departemen"`
	IDMitra      pgtype.Int4 `json:"id_mitra"`
	Status       string      `json:"status"`
}

type CreateUserRow struct {
	IDUser       int32              `json:"id_user"`
	Username     string             `json:"username"`
	IsManager    bool               `json:"is_manager"`
	IDDepartemen pgtype.Int4        `json:"id_departemen"`
	IDMitra      pgtype.Int4        `json:"id_mitra"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.IsManager,
		arg.IDDepartemen,
		arg.IDMitra,
		arg.Status,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.IDUser,
		&i.Username,
		&i.IsManager,
		&i.IDDepartemen,
		&i.IDMitra,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createUserAkses = `-- name: CreateUserAkses :exec
INSERT INTO USER_AKSES (
    id_user, id_hak_akses
) VALUES (
    $1, $2
)
`

type CreateUserAksesParams struct {
	IDUser     int32 `json:"id_user"`
	IDHakAkses int32 `json:"id_hak_akses"`
}

func (q *Queries) CreateUserAkses(ctx context.Context, arg CreateUserAksesParams) error {
	_, err := q.db.Exec(ctx, createUserAkses, arg.IDUser, arg.IDHakAkses)
	return err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM USERS
WHERE id_user = $1
`

func (q *Queries) DeleteUser(ctx context.Context, idUser int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, idUser)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id_user, u.username, u.is_manager, u.status, u.id_departemen, u.id_mitra, d.nama_departemen, m.nama_perusahaan, u.created_at
FROM USERS u
LEFT JOIN DEPARTEMEN d ON u.id_departemen = d.id_departemen
LEFT JOIN MITRA m ON u.id_mitra = m.id_mitra
WHERE u.id_user = $1 LIMIT 1
`

type GetUserByIDRow struct {
	IDUser         int32              `json:"id_user"`
	Username       string             `json:"username"`
	IsManager      bool               `json:"is_manager"`
	Status         string             `json:"status"`
	IDDepartemen   pgtype.Int4        `json:"id_departemen"`
	IDMitra        pgtype.Int4        `json:"id_mitra"`
	NamaDepartemen pgtype.Text        `json:"nama_departemen"`
	NamaPerusahaan pgtype.Text        `json:"nama_perusahaan"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, idUser int32) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, idUser)
	var i GetUserByIDRow
	err := row.Scan(
		&i.IDUser,
		&i.Username,
		&i.IsManager,
		&i.Status,
		&i.IDDepartemen,
		&i.IDMitra,
		&i.NamaDepartemen,
		&i.NamaPerusahaan,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id_user, username, password, is_manager, id_departemen, id_mitra, status, created_at
FROM USERS
WHERE username = $1 LIMIT 1
`

type GetUserByUsernameRow struct {
	IDUser       int32              `json:"id_user"`
	Username     string             `json:"username"`
	Password     string             `json:"password"`
	IsManager    bool               `json:"is_manager"`
	IDDepartemen pgtype.Int4        `json:"id_departemen"`
	IDMitra      pgtype.Int4        `json:"id_mitra"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.IDUser,
		&i.Username,
		&i.Password,
		&i.IsManager,
		&i.IDDepartemen,
		&i.IDMitra,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserPermissionIDs = `-- name: GetUserPermissionIDs :many
SELECT id_hak_akses
FROM USER_AKSES
WHERE id_user = $1
`

func (q *Queries) GetUserPermissionIDs(ctx context.Context, idUser int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, getUserPermissionIDs, idUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id_hak_akses int32
		if err := rows.Scan(&id_hak_akses); err != nil {
			return nil, err
		}
		items = append(items, id_hak_akses)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT h.NAMA_HALAMAN 
FROM HAK_AKSES h
JOIN ROLE_HAK_AKSES rha ON h.ID_HAK_AKSES = rha.ID_HAK_AKSES
JOIN USERS u ON u.ID_ROLE = rha.ID_ROLE
WHERE u.ID_USER = $1
UNION
SELECT h.NAMA_HALAMAN 
FROM HAK_AKSES h
JOIN USER_AKSES ua ON h.ID_HAK_AKSES = ua.ID_HAK_AKSES
WHERE ua.ID_USER = $1
`

func (q *Queries) GetUserPermissions(ctx context.Context, idUser int32) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, idUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var nama_halaman string
		if err := rows.Scan(&nama_halaman); err != nil {
			return nil, err
		}
		items = append(items, nama_halaman)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT u.id_user, u.username, u.is_manager, u.status, u.id_departemen, u.id_mitra, d.nama_departemen, m.nama_perusahaan, u.created_at
FROM USERS u
LEFT JOIN DEPARTEMEN d ON u.id_departemen = d.id_departemen
LEFT JOIN MITRA m ON u.id_mitra = m.id_mitra
WHERE (
    $1::text = '' OR
    u.username ILIKE '%' || $1::text || '%' OR
    u.status ILIKE '%' || $1::text || '%' OR
    COALESCE(d.nama_departemen, '') ILIKE '%' || $1::text || '%' OR
    COALESCE(m.nama_perusahaan, '') ILIKE '%' || $1::text || '%'
)
ORDER BY
    CASE WHEN $2::text = 'created_at' AND NOT $3::bool THEN u.created_at END ASC,
    CASE WHEN $2::text = 'created_at' AND $3::bool THEN u.created_at END DESC,
    CASE WHEN $2::text = 'id_user' AND NOT $3::bool THEN u.id_user END ASC,
    CASE WHEN $2::text = 'id_user' AND $3::bool THEN u.id_user END DESC,
    CASE WHEN $2::text = 'username' AND NOT $3::bool THEN u.username END ASC,
    CASE WHEN $2::text = 'username' AND $3::bool THEN u.username END DESC,
    CASE WHEN $2::text = 'status' AND NOT $3::bool THEN u.status END ASC,
    CASE WHEN $2::text = 'status' AND $3::bool THEN u.status END DESC,
    CASE WHEN $2::text = 'is_manager' AND NOT $3::bool THEN u.is_manager END ASC,
    CASE WHEN $2::text = 'is_manager' AND $3::bool THEN u.is_manager END DESC,
    u.id_user ASC
LIMIT $5 OFFSET $4
`

type ListUsersParams struct {
	SearchTerm string `json:"search_term"`
	SortBy     string `json:"sort_by"`
	SortDesc   bool   `json:"sort_desc"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type ListUsersRow struct {
	IDUser         int32              `json:"id_user"`
	Username       string             `json:"username"`
	IsManager      bool               `json:"is_manager"`
	Status         string             `json:"status"`
	IDDepartemen   pgtype.Int4        `json:"id_departemen"`
	IDMitra        pgtype.Int4        `json:"id_mitra"`
	NamaDepartemen pgtype.Text        `json:"nama_departemen"`
	NamaPerusahaan pgtype.Text        `json:"nama_perusahaan"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.SearchTerm,
		arg.SortBy,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.IDUser,
			&i.Username,
			&i.IsManager,
			&i.Status,
			&i.IDDepartemen,
			&i.IDMitra,
			&i.NamaDepartemen,
			&i.NamaPerusahaan,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE USERS
SET username = $2,
    password = $3,
    is_manager = $4,
    id_departemen = $5,
    id_mitra = $6,
    status = $7
WHERE id_user = $1
RETURNING id_user, username, is_manager, id_departemen, id_mitra, status, created_at
`

type UpdateUserParams struct {
	IDUser       int32       `json:"id_user"`
	Username     string      `json:"username"`
	Password     string      `json:"password"`
	IsManager    bool        `json:"is_manager"`
	IDDepartemen pgtype.Int4 `json:"id_departemen"`
	IDMitra      pgtype.Int4 `json:"id_mitra"`
	Status       string      `json:"status"`
}

type UpdateUserRow struct {
	IDUser       int32              `json:"id_user"`
	Username     string             `json:"username"`
	IsManager    bool               `json:"is_manager"`
	IDDepartemen pgtype.Int4        `json:"id_departemen"`
	IDMitra      pgtype.Int4        `json:"id_mitra"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.IDUser,
		arg.Username,
		arg.Password,
		arg.IsManager,
		arg.IDDepartemen,
		arg.IDMitra,
		arg.Status,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.IDUser,
		&i.Username,
		&i.IsManager,
		&i.IDDepartemen,
		&i.IDMitra,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE USERS
SET status = $2
WHERE id_user = $1
RETURNING id_user, username, status
`

type UpdateUserStatusParams struct {
	IDUser int32  `json:"id_user"`
	Status string `json:"status"`
}

type UpdateUserStatusRow struct {
	IDUser   int32  `json:"id_user"`
	Username string `json:"username"`
	Status   string `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (UpdateUserStatusRow, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.IDUser, arg.Status)
	var i UpdateUserStatusRow
	err := row.Scan(&i.IDUser, &i.Username, &i.Status)
	return i, err
}
