// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: warehouse_delivery.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPackingList = `-- name: CreatePackingList :one
INSERT INTO PACKING_LIST (
    total_garment_per_box,
    total_reject,
    id_wo,
    id_surat_jalan_internal
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id_packing_list, total_garment_per_box, total_reject, id_wo, id_surat_jalan_internal, created_at
`

type CreatePackingListParams struct {
	TotalGarmentPerBox   int32       `json:"total_garment_per_box"`
	TotalReject          int32       `json:"total_reject"`
	IDWo                 int32       `json:"id_wo"`
	IDSuratJalanInternal pgtype.Int4 `json:"id_surat_jalan_internal"`
}

func (q *Queries) CreatePackingList(ctx context.Context, arg CreatePackingListParams) (PackingList, error) {
	row := q.db.QueryRow(ctx, createPackingList,
		arg.TotalGarmentPerBox,
		arg.TotalReject,
		arg.IDWo,
		arg.IDSuratJalanInternal,
	)
	var i PackingList
	err := row.Scan(
		&i.IDPackingList,
		&i.TotalGarmentPerBox,
		&i.TotalReject,
		&i.IDWo,
		&i.IDSuratJalanInternal,
		&i.CreatedAt,
	)
	return i, err
}

const createPackingListItem = `-- name: CreatePackingListItem :one
INSERT INTO PACKING_LIST_ITEM (
    id_packing_list,
    color,
    qty_box,
    qty_per_box,
    box_no_start,
    box_no_end,
    note
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id_packing_list_item, id_packing_list, color, qty_box, qty_per_box, box_no_start, box_no_end, note, created_at
`

type CreatePackingListItemParams struct {
	IDPackingList int32  `json:"id_packing_list"`
	Color         string `json:"color"`
	QtyBox        int32  `json:"qty_box"`
	QtyPerBox     int32  `json:"qty_per_box"`
	BoxNoStart    int32  `json:"box_no_start"`
	BoxNoEnd      int32  `json:"box_no_end"`
	Note          string `json:"note"`
}

func (q *Queries) CreatePackingListItem(ctx context.Context, arg CreatePackingListItemParams) (PackingListItem, error) {
	row := q.db.QueryRow(ctx, createPackingListItem,
		arg.IDPackingList,
		arg.Color,
		arg.QtyBox,
		arg.QtyPerBox,
		arg.BoxNoStart,
		arg.BoxNoEnd,
		arg.Note,
	)
	var i PackingListItem
	err := row.Scan(
		&i.IDPackingListItem,
		&i.IDPackingList,
		&i.Color,
		&i.QtyBox,
		&i.QtyPerBox,
		&i.BoxNoStart,
		&i.BoxNoEnd,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const createPackingListItemSize = `-- name: CreatePackingListItemSize :one
INSERT INTO PACKING_LIST_ITEM_SIZE (
    qty,
    id_packing_list_item,
    id_wo_shell_size
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id_packing_list_item_size, qty, id_packing_list_item, id_wo_shell_size, created_at
`

type CreatePackingListItemSizeParams struct {
	Qty               int32 `json:"qty"`
	IDPackingListItem int32 `json:"id_packing_list_item"`
	IDWoShellSize     int32 `json:"id_wo_shell_size"`
}

type CreatePackingListItemSizeRow struct {
	IDPackingListItemSize int32              `json:"id_packing_list_item_size"`
	Qty                   int32              `json:"qty"`
	IDPackingListItem     int32              `json:"id_packing_list_item"`
	IDWoShellSize         int32              `json:"id_wo_shell_size"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePackingListItemSize(ctx context.Context, arg CreatePackingListItemSizeParams) (CreatePackingListItemSizeRow, error) {
	row := q.db.QueryRow(ctx, createPackingListItemSize, arg.Qty, arg.IDPackingListItem, arg.IDWoShellSize)
	var i CreatePackingListItemSizeRow
	err := row.Scan(
		&i.IDPackingListItemSize,
		&i.Qty,
		&i.IDPackingListItem,
		&i.IDWoShellSize,
		&i.CreatedAt,
	)
	return i, err
}

const createPackingListRejectSize = `-- name: CreatePackingListRejectSize :one
INSERT INTO PACKING_LIST_REJECT_SIZE (
    qty,
    id_packing_list,
    id_wo_shell_size
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id_packing_list_reject_size, qty, id_packing_list, id_wo_shell_size, created_at
`

type CreatePackingListRejectSizeParams struct {
	Qty           int32 `json:"qty"`
	IDPackingList int32 `json:"id_packing_list"`
	IDWoShellSize int32 `json:"id_wo_shell_size"`
}

type CreatePackingListRejectSizeRow struct {
	IDPackingListRejectSize int32              `json:"id_packing_list_reject_size"`
	Qty                     int32              `json:"qty"`
	IDPackingList           int32              `json:"id_packing_list"`
	IDWoShellSize           int32              `json:"id_wo_shell_size"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePackingListRejectSize(ctx context.Context, arg CreatePackingListRejectSizeParams) (CreatePackingListRejectSizeRow, error) {
	row := q.db.QueryRow(ctx, createPackingListRejectSize, arg.Qty, arg.IDPackingList, arg.IDWoShellSize)
	var i CreatePackingListRejectSizeRow
	err := row.Scan(
		&i.IDPackingListRejectSize,
		&i.Qty,
		&i.IDPackingList,
		&i.IDWoShellSize,
		&i.CreatedAt,
	)
	return i, err
}

const createReceivedSimple = `-- name: CreateReceivedSimple :one
INSERT INTO RECEIVED (tanggal, qty, keterangan, id_material_list_item)
VALUES ($1::date, $2, $3, $4)
RETURNING id_received, tanggal, qty, keterangan, id_material_list_item, created_at
`

type CreateReceivedSimpleParams struct {
	Tanggal            pgtype.Date `json:"tanggal"`
	Qty                int32       `json:"qty"`
	Keterangan         string      `json:"keterangan"`
	IDMaterialListItem int32       `json:"id_material_list_item"`
}

type CreateReceivedSimpleRow struct {
	IDReceived         int32              `json:"id_received"`
	Tanggal            pgtype.Date        `json:"tanggal"`
	Qty                int32              `json:"qty"`
	Keterangan         string             `json:"keterangan"`
	IDMaterialListItem int32              `json:"id_material_list_item"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateReceivedSimple(ctx context.Context, arg CreateReceivedSimpleParams) (CreateReceivedSimpleRow, error) {
	row := q.db.QueryRow(ctx, createReceivedSimple,
		arg.Tanggal,
		arg.Qty,
		arg.Keterangan,
		arg.IDMaterialListItem,
	)
	var i CreateReceivedSimpleRow
	err := row.Scan(
		&i.IDReceived,
		&i.Tanggal,
		&i.Qty,
		&i.Keterangan,
		&i.IDMaterialListItem,
		&i.CreatedAt,
	)
	return i, err
}

const createSuratJalanClient = `-- name: CreateSuratJalanClient :one
INSERT INTO SURAT_JALAN_CLIENT (
    tanggal,
    qty,
    keterangan,
    id_material_list_item
) VALUES (
    $1::date,
    $2,
    $3,
    $4
)
RETURNING id_surat_jalan_client, tanggal, qty, keterangan, id_material_list_item AS id_material_list, created_at
`

type CreateSuratJalanClientParams struct {
	Tanggal            pgtype.Date `json:"tanggal"`
	Qty                int32       `json:"qty"`
	Keterangan         string      `json:"keterangan"`
	IDMaterialListItem int32       `json:"id_material_list_item"`
}

type CreateSuratJalanClientRow struct {
	IDSuratJalanClient int32              `json:"id_surat_jalan_client"`
	Tanggal            pgtype.Date        `json:"tanggal"`
	Qty                int32              `json:"qty"`
	Keterangan         string             `json:"keterangan"`
	IDMaterialList     int32              `json:"id_material_list"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSuratJalanClient(ctx context.Context, arg CreateSuratJalanClientParams) (CreateSuratJalanClientRow, error) {
	row := q.db.QueryRow(ctx, createSuratJalanClient,
		arg.Tanggal,
		arg.Qty,
		arg.Keterangan,
		arg.IDMaterialListItem,
	)
	var i CreateSuratJalanClientRow
	err := row.Scan(
		&i.IDSuratJalanClient,
		&i.Tanggal,
		&i.Qty,
		&i.Keterangan,
		&i.IDMaterialList,
		&i.CreatedAt,
	)
	return i, err
}

const createSuratJalanInternal = `-- name: CreateSuratJalanInternal :one
INSERT INTO SURAT_JALAN_INTERNAL (
    id_wo,
    no_dokumen,
    deskripsi
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id_surat_jalan_internal, id_wo, no_dokumen, deskripsi, created_at
`

type CreateSuratJalanInternalParams struct {
	IDWo      pgtype.Int4 `json:"id_wo"`
	NoDokumen string      `json:"no_dokumen"`
	Deskripsi string      `json:"deskripsi"`
}

func (q *Queries) CreateSuratJalanInternal(ctx context.Context, arg CreateSuratJalanInternalParams) (SuratJalanInternal, error) {
	row := q.db.QueryRow(ctx, createSuratJalanInternal, arg.IDWo, arg.NoDokumen, arg.Deskripsi)
	var i SuratJalanInternal
	err := row.Scan(
		&i.IDSuratJalanInternal,
		&i.IDWo,
		&i.NoDokumen,
		&i.Deskripsi,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReceivedSimple = `-- name: DeleteReceivedSimple :exec
DELETE FROM RECEIVED WHERE id_received = $1
`

func (q *Queries) DeleteReceivedSimple(ctx context.Context, idReceived int32) error {
	_, err := q.db.Exec(ctx, deleteReceivedSimple, idReceived)
	return err
}

const deleteSuratJalanClient = `-- name: DeleteSuratJalanClient :exec
DELETE FROM SURAT_JALAN_CLIENT WHERE id_surat_jalan_client = $1
`

func (q *Queries) DeleteSuratJalanClient(ctx context.Context, idSuratJalanClient int32) error {
	_, err := q.db.Exec(ctx, deleteSuratJalanClient, idSuratJalanClient)
	return err
}

const getReceivedByID = `-- name: GetReceivedByID :one
SELECT
    r.id_received,
    r.tanggal,
    r.qty,
    r.keterangan,
    r.id_material_list_item,
    r.created_at,
    mli.item AS material_item,
    mli.description AS material_description,
    ml.id_wo
FROM RECEIVED r
JOIN MATERIAL_LIST_ITEM mli ON mli.id_material_list_item = r.id_material_list_item
JOIN MATERIAL_LIST ml ON ml.id_material_list = mli.id_material_list
WHERE r.id_received = $1
`

type GetReceivedByIDRow struct {
	IDReceived          int32              `json:"id_received"`
	Tanggal             pgtype.Date        `json:"tanggal"`
	Qty                 int32              `json:"qty"`
	Keterangan          string             `json:"keterangan"`
	IDMaterialListItem  int32              `json:"id_material_list_item"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	MaterialItem        string             `json:"material_item"`
	MaterialDescription string             `json:"material_description"`
	IDWo                int32              `json:"id_wo"`
}

func (q *Queries) GetReceivedByID(ctx context.Context, idReceived int32) (GetReceivedByIDRow, error) {
	row := q.db.QueryRow(ctx, getReceivedByID, idReceived)
	var i GetReceivedByIDRow
	err := row.Scan(
		&i.IDReceived,
		&i.Tanggal,
		&i.Qty,
		&i.Keterangan,
		&i.IDMaterialListItem,
		&i.CreatedAt,
		&i.MaterialItem,
		&i.MaterialDescription,
		&i.IDWo,
	)
	return i, err
}

const getRekonsiliasiMaterialStock = `-- name: GetRekonsiliasiMaterialStock :one
SELECT
    id_rekonsiliasi_material,
    balance,
    last_balance
FROM REKONSILIASI_MATERIAL
WHERE id_rekonsiliasi_material = $1
LIMIT 1
`

type GetRekonsiliasiMaterialStockRow struct {
	IDRekonsiliasiMaterial int32 `json:"id_rekonsiliasi_material"`
	Balance                int32 `json:"balance"`
	LastBalance            int32 `json:"last_balance"`
}

func (q *Queries) GetRekonsiliasiMaterialStock(ctx context.Context, idRekonsiliasiMaterial int32) (GetRekonsiliasiMaterialStockRow, error) {
	row := q.db.QueryRow(ctx, getRekonsiliasiMaterialStock, idRekonsiliasiMaterial)
	var i GetRekonsiliasiMaterialStockRow
	err := row.Scan(&i.IDRekonsiliasiMaterial, &i.Balance, &i.LastBalance)
	return i, err
}

const issueInventory = `-- name: IssueInventory :one
UPDATE REKONSILIASI_MATERIAL
SET
    last_balance = balance,
    balance = balance - $1
WHERE id_rekonsiliasi_material = $2
RETURNING id_rekonsiliasi_material, last_balance, balance
`

type IssueInventoryParams struct {
	Qty                    int32 `json:"qty"`
	IDRekonsiliasiMaterial int32 `json:"id_rekonsiliasi_material"`
}

type IssueInventoryRow struct {
	IDRekonsiliasiMaterial int32 `json:"id_rekonsiliasi_material"`
	LastBalance            int32 `json:"last_balance"`
	Balance                int32 `json:"balance"`
}

func (q *Queries) IssueInventory(ctx context.Context, arg IssueInventoryParams) (IssueInventoryRow, error) {
	row := q.db.QueryRow(ctx, issueInventory, arg.Qty, arg.IDRekonsiliasiMaterial)
	var i IssueInventoryRow
	err := row.Scan(&i.IDRekonsiliasiMaterial, &i.LastBalance, &i.Balance)
	return i, err
}

const listReceived = `-- name: ListReceived :many
SELECT
    r.id_received,
    r.tanggal,
    r.qty,
    r.keterangan,
    r.id_material_list_item,
    r.created_at,
    mli.item AS material_item,
    mli.description AS material_description,
    ml.id_wo,
    COUNT(*) OVER () AS total_count
FROM RECEIVED r
JOIN MATERIAL_LIST_ITEM mli ON mli.id_material_list_item = r.id_material_list_item
JOIN MATERIAL_LIST ml ON ml.id_material_list = mli.id_material_list
WHERE (
    $1::text = ''
    OR LOWER(mli.item) LIKE '%' || LOWER($1::text) || '%'
    OR LOWER(mli.description) LIKE '%' || LOWER($1::text) || '%'
    OR LOWER(r.keterangan) LIKE '%' || LOWER($1::text) || '%'
)
ORDER BY r.created_at DESC
LIMIT $3
OFFSET $2
`

type ListReceivedParams struct {
	Search string `json:"search"`
	Off    int32  `json:"off"`
	Lim    int32  `json:"lim"`
}

type ListReceivedRow struct {
	IDReceived          int32              `json:"id_received"`
	Tanggal             pgtype.Date        `json:"tanggal"`
	Qty                 int32              `json:"qty"`
	Keterangan          string             `json:"keterangan"`
	IDMaterialListItem  int32              `json:"id_material_list_item"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	MaterialItem        string             `json:"material_item"`
	MaterialDescription string             `json:"material_description"`
	IDWo                int32              `json:"id_wo"`
	TotalCount          int64              `json:"total_count"`
}

func (q *Queries) ListReceived(ctx context.Context, arg ListReceivedParams) ([]ListReceivedRow, error) {
	rows, err := q.db.Query(ctx, listReceived, arg.Search, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceivedRow
	for rows.Next() {
		var i ListReceivedRow
		if err := rows.Scan(
			&i.IDReceived,
			&i.Tanggal,
			&i.Qty,
			&i.Keterangan,
			&i.IDMaterialListItem,
			&i.CreatedAt,
			&i.MaterialItem,
			&i.MaterialDescription,
			&i.IDWo,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivedByMLI = `-- name: ListReceivedByMLI :many
SELECT id_received, tanggal, qty, keterangan, id_material_list_item, created_at
FROM RECEIVED
WHERE id_material_list_item = $1
ORDER BY created_at DESC
`

type ListReceivedByMLIRow struct {
	IDReceived         int32              `json:"id_received"`
	Tanggal            pgtype.Date        `json:"tanggal"`
	Qty                int32              `json:"qty"`
	Keterangan         string             `json:"keterangan"`
	IDMaterialListItem int32              `json:"id_material_list_item"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListReceivedByMLI(ctx context.Context, idMaterialListItem int32) ([]ListReceivedByMLIRow, error) {
	rows, err := q.db.Query(ctx, listReceivedByMLI, idMaterialListItem)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceivedByMLIRow
	for rows.Next() {
		var i ListReceivedByMLIRow
		if err := rows.Scan(
			&i.IDReceived,
			&i.Tanggal,
			&i.Qty,
			&i.Keterangan,
			&i.IDMaterialListItem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuratJalanClientByMLI = `-- name: ListSuratJalanClientByMLI :many
SELECT id_surat_jalan_client, tanggal, qty, keterangan, id_material_list_item, created_at
FROM SURAT_JALAN_CLIENT
WHERE id_material_list_item = $1
ORDER BY created_at DESC
`

type ListSuratJalanClientByMLIRow struct {
	IDSuratJalanClient int32              `json:"id_surat_jalan_client"`
	Tanggal            pgtype.Date        `json:"tanggal"`
	Qty                int32              `json:"qty"`
	Keterangan         string             `json:"keterangan"`
	IDMaterialListItem int32              `json:"id_material_list_item"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSuratJalanClientByMLI(ctx context.Context, idMaterialListItem int32) ([]ListSuratJalanClientByMLIRow, error) {
	rows, err := q.db.Query(ctx, listSuratJalanClientByMLI, idMaterialListItem)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSuratJalanClientByMLIRow
	for rows.Next() {
		var i ListSuratJalanClientByMLIRow
		if err := rows.Scan(
			&i.IDSuratJalanClient,
			&i.Tanggal,
			&i.Qty,
			&i.Keterangan,
			&i.IDMaterialListItem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const receiveInventory = `-- name: ReceiveInventory :one
WITH inserted_received AS (
    INSERT INTO RECEIVED (
        tanggal,
        qty,
        keterangan,
        id_material_list_item
    ) VALUES (
        $1::date,
        $2,
        $3,
        $4
    )
    RETURNING id_received, tanggal, qty, keterangan, id_material_list_item AS id_material_list, created_at
),
inserted_rekonsiliasi_terima AS (
    INSERT INTO REKONSILIASI_MATERIAL_TERIMA (
        keterangan,
        qty,
        id_rekonsiliasi_material
    ) VALUES (
        $3,
        $2,
        $5
    )
    RETURNING id_rekonsiliasi_material_terima
),
updated_rekonsiliasi AS (
    UPDATE REKONSILIASI_MATERIAL
    SET
        actual_kirim = actual_kirim + $2,
        balance = balance + $2
    WHERE id_rekonsiliasi_material = $5
    RETURNING id_rekonsiliasi_material, actual_kirim, balance
)
SELECT
    r.id_received,
    r.tanggal,
    r.qty,
    r.keterangan,
    r.id_material_list,
    r.created_at,
    t.id_rekonsiliasi_material_terima,
    u.id_rekonsiliasi_material,
    u.actual_kirim,
    u.balance
FROM inserted_received r
CROSS JOIN inserted_rekonsiliasi_terima t
CROSS JOIN updated_rekonsiliasi u
`

type ReceiveInventoryParams struct {
	Tanggal                pgtype.Date `json:"tanggal"`
	Qty                    int32       `json:"qty"`
	Keterangan             string      `json:"keterangan"`
	IDMaterialListItem     int32       `json:"id_material_list_item"`
	IDRekonsiliasiMaterial int32       `json:"id_rekonsiliasi_material"`
}

type ReceiveInventoryRow struct {
	IDReceived                   int32              `json:"id_received"`
	Tanggal                      pgtype.Date        `json:"tanggal"`
	Qty                          int32              `json:"qty"`
	Keterangan                   string             `json:"keterangan"`
	IDMaterialList               int32              `json:"id_material_list"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	IDRekonsiliasiMaterialTerima int32              `json:"id_rekonsiliasi_material_terima"`
	IDRekonsiliasiMaterial       int32              `json:"id_rekonsiliasi_material"`
	ActualKirim                  int32              `json:"actual_kirim"`
	Balance                      int32              `json:"balance"`
}

func (q *Queries) ReceiveInventory(ctx context.Context, arg ReceiveInventoryParams) (ReceiveInventoryRow, error) {
	row := q.db.QueryRow(ctx, receiveInventory,
		arg.Tanggal,
		arg.Qty,
		arg.Keterangan,
		arg.IDMaterialListItem,
		arg.IDRekonsiliasiMaterial,
	)
	var i ReceiveInventoryRow
	err := row.Scan(
		&i.IDReceived,
		&i.Tanggal,
		&i.Qty,
		&i.Keterangan,
		&i.IDMaterialList,
		&i.CreatedAt,
		&i.IDRekonsiliasiMaterialTerima,
		&i.IDRekonsiliasiMaterial,
		&i.ActualKirim,
		&i.Balance,
	)
	return i, err
}

const updateReceivedSimple = `-- name: UpdateReceivedSimple :one
UPDATE RECEIVED
SET tanggal = $1::date, qty = $2, keterangan = $3
WHERE id_received = $4
RETURNING id_received, tanggal, qty, keterangan, id_material_list_item, created_at
`

type UpdateReceivedSimpleParams struct {
	Tanggal    pgtype.Date `json:"tanggal"`
	Qty        int32       `json:"qty"`
	Keterangan string      `json:"keterangan"`
	IDReceived int32       `json:"id_received"`
}

type UpdateReceivedSimpleRow struct {
	IDReceived         int32              `json:"id_received"`
	Tanggal            pgtype.Date        `json:"tanggal"`
	Qty                int32              `json:"qty"`
	Keterangan         string             `json:"keterangan"`
	IDMaterialListItem int32              `json:"id_material_list_item"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateReceivedSimple(ctx context.Context, arg UpdateReceivedSimpleParams) (UpdateReceivedSimpleRow, error) {
	row := q.db.QueryRow(ctx, updateReceivedSimple,
		arg.Tanggal,
		arg.Qty,
		arg.Keterangan,
		arg.IDReceived,
	)
	var i UpdateReceivedSimpleRow
	err := row.Scan(
		&i.IDReceived,
		&i.Tanggal,
		&i.Qty,
		&i.Keterangan,
		&i.IDMaterialListItem,
		&i.CreatedAt,
	)
	return i, err
}

const assignPackingListToSuratJalan = `-- name: AssignPackingListToSuratJalan :exec
UPDATE PACKING_LIST
SET id_surat_jalan_internal = $1
WHERE id_packing_list = $2
`

type AssignPackingListToSuratJalanParams struct {
	IDSuratJalanInternal int32 `json:"id_surat_jalan_internal"`
	IDPackingList        int32 `json:"id_packing_list"`
}

func (q *Queries) AssignPackingListToSuratJalan(ctx context.Context, arg AssignPackingListToSuratJalanParams) error {
	_, err := q.db.Exec(ctx, assignPackingListToSuratJalan, arg.IDSuratJalanInternal, arg.IDPackingList)
	return err
}

const unassignPackingListFromSuratJalan = `-- name: UnassignPackingListFromSuratJalan :exec
UPDATE PACKING_LIST
SET id_surat_jalan_internal = NULL
WHERE id_packing_list = $1
`

func (q *Queries) UnassignPackingListFromSuratJalan(ctx context.Context, idPackingList int32) error {
	_, err := q.db.Exec(ctx, unassignPackingListFromSuratJalan, idPackingList)
	return err
}

const listPackingListsBySuratJalanID = `-- name: ListPackingListsBySuratJalanID :many
SELECT
    pl.id_packing_list,
    pl.total_garment_per_box,
    pl.total_reject,
    pl.id_wo,
    pl.id_surat_jalan_internal,
    pl.created_at
FROM PACKING_LIST pl
WHERE pl.id_surat_jalan_internal = $1
ORDER BY pl.id_packing_list ASC
`

type ListPackingListsBySuratJalanIDRow struct {
	IDPackingList        int32              `json:"id_packing_list"`
	TotalGarmentPerBox   int32              `json:"total_garment_per_box"`
	TotalReject          int32              `json:"total_reject"`
	IDWo                 int32              `json:"id_wo"`
	IDSuratJalanInternal pgtype.Int4        `json:"id_surat_jalan_internal"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPackingListsBySuratJalanID(ctx context.Context, idSuratJalanInternal int32) ([]ListPackingListsBySuratJalanIDRow, error) {
	rows, err := q.db.Query(ctx, listPackingListsBySuratJalanID, idSuratJalanInternal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPackingListsBySuratJalanIDRow
	for rows.Next() {
		var i ListPackingListsBySuratJalanIDRow
		if err := rows.Scan(
			&i.IDPackingList,
			&i.TotalGarmentPerBox,
			&i.TotalReject,
			&i.IDWo,
			&i.IDSuratJalanInternal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSuratJalanInternalItem = `-- name: CreateSuratJalanInternalItem :one
INSERT INTO SURAT_JALAN_INTERNAL_ITEM (
    id_surat_jalan_internal,
    no_urut,
    deskripsi,
    qty,
    note
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id_surat_jalan_internal_item, id_surat_jalan_internal, no_urut, deskripsi, qty, note, created_at
`

type CreateSuratJalanInternalItemParams struct {
	IDSuratJalanInternal int32  `json:"id_surat_jalan_internal"`
	NoUrut               int32  `json:"no_urut"`
	Deskripsi            string `json:"deskripsi"`
	Qty                  int32  `json:"qty"`
	Note                 string `json:"note"`
}

func (q *Queries) CreateSuratJalanInternalItem(ctx context.Context, arg CreateSuratJalanInternalItemParams) (SuratJalanInternalItem, error) {
	row := q.db.QueryRow(ctx, createSuratJalanInternalItem,
		arg.IDSuratJalanInternal,
		arg.NoUrut,
		arg.Deskripsi,
		arg.Qty,
		arg.Note,
	)
	var i SuratJalanInternalItem
	err := row.Scan(
		&i.IDSuratJalanInternalItem,
		&i.IDSuratJalanInternal,
		&i.NoUrut,
		&i.Deskripsi,
		&i.Qty,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listSuratJalanInternalItemsBySJID = `-- name: ListSuratJalanInternalItemsBySJID :many
SELECT
    id_surat_jalan_internal_item,
    id_surat_jalan_internal,
    no_urut,
    deskripsi,
    qty,
    note,
    created_at
FROM SURAT_JALAN_INTERNAL_ITEM
WHERE id_surat_jalan_internal = $1
ORDER BY no_urut ASC, id_surat_jalan_internal_item ASC
`

func (q *Queries) ListSuratJalanInternalItemsBySJID(ctx context.Context, idSuratJalanInternal int32) ([]SuratJalanInternalItem, error) {
	rows, err := q.db.Query(ctx, listSuratJalanInternalItemsBySJID, idSuratJalanInternal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuratJalanInternalItem
	for rows.Next() {
		var i SuratJalanInternalItem
		if err := rows.Scan(
			&i.IDSuratJalanInternalItem,
			&i.IDSuratJalanInternal,
			&i.NoUrut,
			&i.Deskripsi,
			&i.Qty,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
