// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: warna.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWarna = `-- name: CountWarna :one
SELECT COUNT(*)
FROM WARNA
WHERE (
    $1::text = '' OR
    nama_warna ILIKE '%' || $1::text || '%'
)
  AND NOT EXISTS (
      SELECT 1 FROM MASTER_DATA_DELETED mdd
      WHERE mdd.nama_tabel = 'WARNA' AND mdd.id_record = WARNA.id_warna
  )
`

func (q *Queries) CountWarna(ctx context.Context, searchTerm string) (int64, error) {
	row := q.db.QueryRow(ctx, countWarna, searchTerm)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWarna = `-- name: CreateWarna :one
INSERT INTO WARNA (nama_warna, kode_hex)
VALUES ($1, $2)
RETURNING id_warna, nama_warna, kode_hex, created_at
`

type CreateWarnaParams struct {
	NamaWarna string      `json:"nama_warna"`
	KodeHex   pgtype.Text `json:"kode_hex"`
}

func (q *Queries) CreateWarna(ctx context.Context, arg CreateWarnaParams) (Warna, error) {
	row := q.db.QueryRow(ctx, createWarna, arg.NamaWarna, arg.KodeHex)
	var i Warna
	err := row.Scan(
		&i.IDWarna,
		&i.NamaWarna,
		&i.KodeHex,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWarna = `-- name: DeleteWarna :execrows
DELETE FROM WARNA
WHERE id_warna = $1
`

func (q *Queries) DeleteWarna(ctx context.Context, idWarna int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWarna, idWarna)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWarnaByID = `-- name: GetWarnaByID :one
SELECT id_warna, nama_warna, kode_hex, created_at FROM WARNA
WHERE id_warna = $1
  AND NOT EXISTS (
      SELECT 1 FROM MASTER_DATA_DELETED mdd
      WHERE mdd.nama_tabel = 'WARNA' AND mdd.id_record = WARNA.id_warna
  )
LIMIT 1
`

func (q *Queries) GetWarnaByID(ctx context.Context, idWarna int32) (Warna, error) {
	row := q.db.QueryRow(ctx, getWarnaByID, idWarna)
	var i Warna
	err := row.Scan(
		&i.IDWarna,
		&i.NamaWarna,
		&i.KodeHex,
		&i.CreatedAt,
	)
	return i, err
}

const listWarna = `-- name: ListWarna :many
SELECT id_warna, nama_warna, kode_hex, created_at
FROM WARNA
WHERE (
    $1::text = '' OR
    nama_warna ILIKE '%' || $1::text || '%'
)
  AND NOT EXISTS (
      SELECT 1 FROM MASTER_DATA_DELETED mdd
      WHERE mdd.nama_tabel = 'WARNA' AND mdd.id_record = WARNA.id_warna
  )
ORDER BY
    CASE WHEN $2::text = 'created_at' AND NOT $3::bool THEN created_at END ASC,
    CASE WHEN $2::text = 'created_at' AND $3::bool THEN created_at END DESC,
    CASE WHEN $2::text = 'id_warna' AND NOT $3::bool THEN id_warna END ASC,
    CASE WHEN $2::text = 'id_warna' AND $3::bool THEN id_warna END DESC,
    CASE WHEN $2::text = 'nama_warna' AND NOT $3::bool THEN nama_warna END ASC,
    CASE WHEN $2::text = 'nama_warna' AND $3::bool THEN nama_warna END DESC,
    nama_warna ASC,
    id_warna ASC
LIMIT $5 OFFSET $4
`

type ListWarnaParams struct {
	SearchTerm string `json:"search_term"`
	SortBy     string `json:"sort_by"`
	SortDesc   bool   `json:"sort_desc"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

func (q *Queries) ListWarna(ctx context.Context, arg ListWarnaParams) ([]Warna, error) {
	rows, err := q.db.Query(ctx, listWarna,
		arg.SearchTerm,
		arg.SortBy,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Warna
	for rows.Next() {
		var i Warna
		if err := rows.Scan(
			&i.IDWarna,
			&i.NamaWarna,
			&i.KodeHex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWarna = `-- name: UpdateWarna :one
UPDATE WARNA
SET nama_warna = $2, kode_hex = $3
WHERE id_warna = $1
RETURNING id_warna, nama_warna, kode_hex, created_at
`

type UpdateWarnaParams struct {
	IDWarna   int32       `json:"id_warna"`
	NamaWarna string      `json:"nama_warna"`
	KodeHex   pgtype.Text `json:"kode_hex"`
}

func (q *Queries) UpdateWarna(ctx context.Context, arg UpdateWarnaParams) (Warna, error) {
	row := q.db.QueryRow(ctx, updateWarna, arg.IDWarna, arg.NamaWarna, arg.KodeHex)
	var i Warna
	err := row.Scan(
		&i.IDWarna,
		&i.NamaWarna,
		&i.KodeHex,
		&i.CreatedAt,
	)
	return i, err
}
