// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_order.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countConfiguredWorkOrdersByPOClientID = `-- name: CountConfiguredWorkOrdersByPOClientID :one
SELECT COUNT(*)
FROM WORK_ORDER wo
JOIN PO_CLIENT_ITEM pci ON pci.id_po_client_item = wo.id_po_client_item
LEFT JOIN WORK_ORDER_SHELL wos ON wos.id_wo = wo.id_wo
LEFT JOIN WORK_ORDER_TRIM wot ON wot.id_wo = wo.id_wo
LEFT JOIN MATERIAL_LIST_ITEM mli ON (
    mli.id_wo = wo.id_wo
    OR mli.id_wo_shell = wos.id_wo_shell
    OR mli.id_wo_trim = wot.id_wo_trim
)
LEFT JOIN MATERIAL_LIST ml ON ml.id_material_list_item = mli.id_material_list_item
WHERE pci.id_po_client = $1
  AND (wos.id_wo_shell IS NOT NULL OR wot.id_wo_trim IS NOT NULL OR ml.id_material_list IS NOT NULL)
`

func (q *Queries) CountConfiguredWorkOrdersByPOClientID(ctx context.Context, idPoClient int32) (int64, error) {
	row := q.db.QueryRow(ctx, countConfiguredWorkOrdersByPOClientID, idPoClient)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMaterialList = `-- name: CreateMaterialList :one
WITH inserted_item AS (
    INSERT INTO MATERIAL_LIST_ITEM (description, id_wo, id_wo_shell, id_wo_trim)
    VALUES (
        $5, 
        $4,
        $6, 
        $7
    )
    RETURNING id_material_list_item, description, id_wo, id_wo_shell, id_wo_trim
)
INSERT INTO MATERIAL_LIST (id_material_list_item)
SELECT id_material_list_item FROM inserted_item
RETURNING id_material_list,
          (SELECT description FROM inserted_item) AS description,
          (SELECT id_wo_shell FROM inserted_item) AS id_wo_shell,
          (SELECT id_wo_trim FROM inserted_item) AS id_wo_trim,
          $1::text AS size,
          $2::text AS color,
          $3::text AS uom,
          $4::integer AS id_wo,
          created_at
`

type CreateMaterialListParams struct {
	Size        string      `json:"size"`
	Color       string      `json:"color"`
	Uom         string      `json:"uom"`
	IDWo        int32       `json:"id_wo"`
	Description string      `json:"description"`
	IDWoShell   pgtype.Int4 `json:"id_wo_shell"`
	IDWoTrim    pgtype.Int4 `json:"id_wo_trim"`
}

type CreateMaterialListRow struct {
	IDMaterialList int32              `json:"id_material_list"`
	Description    string             `json:"description"`
	IDWoShell      pgtype.Int4        `json:"id_wo_shell"`
	IDWoTrim       pgtype.Int4        `json:"id_wo_trim"`
	Size           string             `json:"size"`
	Color          string             `json:"color"`
	Uom            string             `json:"uom"`
	IDWo           int32              `json:"id_wo"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateMaterialList(ctx context.Context, arg CreateMaterialListParams) (CreateMaterialListRow, error) {
	row := q.db.QueryRow(ctx, createMaterialList,
		arg.Size,
		arg.Color,
		arg.Uom,
		arg.IDWo,
		arg.Description,
		arg.IDWoShell,
		arg.IDWoTrim,
	)
	var i CreateMaterialListRow
	err := row.Scan(
		&i.IDMaterialList,
		&i.Description,
		&i.IDWoShell,
		&i.IDWoTrim,
		&i.Size,
		&i.Color,
		&i.Uom,
		&i.IDWo,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkOrder = `-- name: CreateWorkOrder :one
INSERT INTO WORK_ORDER (
    buyer,
    model,
    qty,
    fob_cmt,
    delivery,
    id_po_client_item
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5::date,
    $6
)
RETURNING id_wo, buyer, model, qty, fob_cmt, delivery, id_po_client_item, created_at
`

type CreateWorkOrderParams struct {
	Buyer          string      `json:"buyer"`
	Model          string      `json:"model"`
	Qty            int32       `json:"qty"`
	FobCmt         bool        `json:"fob_cmt"`
	Delivery       pgtype.Date `json:"delivery"`
	IDPoClientItem int32       `json:"id_po_client_item"`
}

func (q *Queries) CreateWorkOrder(ctx context.Context, arg CreateWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, createWorkOrder,
		arg.Buyer,
		arg.Model,
		arg.Qty,
		arg.FobCmt,
		arg.Delivery,
		arg.IDPoClientItem,
	)
	var i WorkOrder
	err := row.Scan(
		&i.IDWo,
		&i.Buyer,
		&i.Model,
		&i.Qty,
		&i.FobCmt,
		&i.Delivery,
		&i.IDPoClientItem,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkOrderShell = `-- name: CreateWorkOrderShell :one
INSERT INTO WORK_ORDER_SHELL (
    deskripsi,
    cons,
    color,
    allow,
    berat_1_yd,
    id_wo
) VALUES (
    $1,
    $2::numeric,
    $3,
    $4,
    $5::numeric,
    $6
)
RETURNING id_wo_shell, deskripsi, cons, color, allow, berat_1_yd, id_wo, created_at
`

type CreateWorkOrderShellParams struct {
	Deskripsi string         `json:"deskripsi"`
	Cons      pgtype.Numeric `json:"cons"`
	Color     string         `json:"color"`
	Allow     int32          `json:"allow"`
	Berat1Yd  pgtype.Numeric `json:"berat_1_yd"`
	IDWo      int32          `json:"id_wo"`
}

type CreateWorkOrderShellRow struct {
	IDWoShell int32              `json:"id_wo_shell"`
	Deskripsi string             `json:"deskripsi"`
	Cons      pgtype.Numeric     `json:"cons"`
	Color     string             `json:"color"`
	Allow     int32              `json:"allow"`
	Berat1Yd  pgtype.Numeric     `json:"berat_1_yd"`
	IDWo      int32              `json:"id_wo"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateWorkOrderShell(ctx context.Context, arg CreateWorkOrderShellParams) (CreateWorkOrderShellRow, error) {
	row := q.db.QueryRow(ctx, createWorkOrderShell,
		arg.Deskripsi,
		arg.Cons,
		arg.Color,
		arg.Allow,
		arg.Berat1Yd,
		arg.IDWo,
	)
	var i CreateWorkOrderShellRow
	err := row.Scan(
		&i.IDWoShell,
		&i.Deskripsi,
		&i.Cons,
		&i.Color,
		&i.Allow,
		&i.Berat1Yd,
		&i.IDWo,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkOrderShellSize = `-- name: CreateWorkOrderShellSize :one
INSERT INTO WORK_ORDER_SHELL_SIZE (
    size,
    qty,
    ratio,
    id_wo_shell
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id_wo_shell_size, size, qty, ratio, id_wo_shell, created_at
`

type CreateWorkOrderShellSizeParams struct {
	Size      string `json:"size"`
	Qty       int32  `json:"qty"`
	Ratio     int32  `json:"ratio"`
	IDWoShell int32  `json:"id_wo_shell"`
}

func (q *Queries) CreateWorkOrderShellSize(ctx context.Context, arg CreateWorkOrderShellSizeParams) (WorkOrderShellSize, error) {
	row := q.db.QueryRow(ctx, createWorkOrderShellSize,
		arg.Size,
		arg.Qty,
		arg.Ratio,
		arg.IDWoShell,
	)
	var i WorkOrderShellSize
	err := row.Scan(
		&i.IDWoShellSize,
		&i.Size,
		&i.Qty,
		&i.Ratio,
		&i.IDWoShell,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkOrderTrim = `-- name: CreateWorkOrderTrim :one
INSERT INTO WORK_ORDER_TRIM (
    item,
    description,
    color,
    code,
    cons,
    qty,
    uom,
    position,
    created_by,
    allow,
    id_wo
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5::numeric,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id_wo_trim, item, description, color, code, cons, qty, uom, position, created_by, allow, id_wo, created_at
`

type CreateWorkOrderTrimParams struct {
	Item        string         `json:"item"`
	Description string         `json:"description"`
	Color       string         `json:"color"`
	Code        string         `json:"code"`
	Cons        pgtype.Numeric `json:"cons"`
	Qty         int32          `json:"qty"`
	Uom         string         `json:"uom"`
	Position    string         `json:"position"`
	CreatedBy   string         `json:"created_by"`
	Allow       int32          `json:"allow"`
	IDWo        int32          `json:"id_wo"`
}

type CreateWorkOrderTrimRow struct {
	IDWoTrim    int32              `json:"id_wo_trim"`
	Item        string             `json:"item"`
	Description string             `json:"description"`
	Color       string             `json:"color"`
	Code        string             `json:"code"`
	Cons        pgtype.Numeric     `json:"cons"`
	Qty         int32              `json:"qty"`
	Uom         string             `json:"uom"`
	Position    string             `json:"position"`
	CreatedBy   string             `json:"created_by"`
	Allow       int32              `json:"allow"`
	IDWo        int32              `json:"id_wo"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateWorkOrderTrim(ctx context.Context, arg CreateWorkOrderTrimParams) (CreateWorkOrderTrimRow, error) {
	row := q.db.QueryRow(ctx, createWorkOrderTrim,
		arg.Item,
		arg.Description,
		arg.Color,
		arg.Code,
		arg.Cons,
		arg.Qty,
		arg.Uom,
		arg.Position,
		arg.CreatedBy,
		arg.Allow,
		arg.IDWo,
	)
	var i CreateWorkOrderTrimRow
	err := row.Scan(
		&i.IDWoTrim,
		&i.Item,
		&i.Description,
		&i.Color,
		&i.Code,
		&i.Cons,
		&i.Qty,
		&i.Uom,
		&i.Position,
		&i.CreatedBy,
		&i.Allow,
		&i.IDWo,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkOrdersByPOClientID = `-- name: DeleteWorkOrdersByPOClientID :exec
DELETE FROM WORK_ORDER
WHERE id_po_client_item IN (
    SELECT id_po_client_item
    FROM PO_CLIENT_ITEM
    WHERE id_po_client = $1
)
`

func (q *Queries) DeleteWorkOrdersByPOClientID(ctx context.Context, idPoClient int32) error {
	_, err := q.db.Exec(ctx, deleteWorkOrdersByPOClientID, idPoClient)
	return err
}

const workOrderShellTotalQty = `-- name: WorkOrderShellTotalQty :one
SELECT COALESCE(SUM(qty), 0)::bigint AS total_qty
FROM WORK_ORDER_SHELL_SIZE
WHERE id_wo_shell = $1
`

func (q *Queries) WorkOrderShellTotalQty(ctx context.Context, idWoShell int32) (int64, error) {
	row := q.db.QueryRow(ctx, workOrderShellTotalQty, idWoShell)
	var total_qty int64
	err := row.Scan(&total_qty)
	return total_qty, err
}
