// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_order.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMaterialList = `-- name: CreateMaterialList :one
INSERT INTO MATERIAL_LIST (
    description,
    size,
    color,
    uom,
    id_wo
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id_material_list, description, size, color, uom, id_wo, created_at
`

type CreateMaterialListParams struct {
	Description string `json:"description"`
	Size        string `json:"size"`
	Color       string `json:"color"`
	Uom         string `json:"uom"`
	IDWo        int32  `json:"id_wo"`
}

func (q *Queries) CreateMaterialList(ctx context.Context, arg CreateMaterialListParams) (MaterialList, error) {
	row := q.db.QueryRow(ctx, createMaterialList,
		arg.Description,
		arg.Size,
		arg.Color,
		arg.Uom,
		arg.IDWo,
	)
	var i MaterialList
	err := row.Scan(
		&i.IDMaterialList,
		&i.Description,
		&i.Size,
		&i.Color,
		&i.Uom,
		&i.IDWo,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkOrder = `-- name: CreateWorkOrder :one
INSERT INTO WORK_ORDER (
    buyer,
    model,
    qty,
    fob_cmt,
    delivery,
    id_po_client_item
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5::date,
    $6
)
RETURNING id_wo, buyer, model, qty, fob_cmt, delivery, id_po_client_item, created_at
`

type CreateWorkOrderParams struct {
	Buyer          string      `json:"buyer"`
	Model          string      `json:"model"`
	Qty            int32       `json:"qty"`
	FobCmt         bool        `json:"fob_cmt"`
	Delivery       pgtype.Date `json:"delivery"`
	IDPoClientItem int32       `json:"id_po_client_item"`
}

type CreateWorkOrderRow struct {
	IDWo           int32              `json:"id_wo"`
	Buyer          string             `json:"buyer"`
	Model          string             `json:"model"`
	Qty            int32              `json:"qty"`
	FobCmt         bool               `json:"fob_cmt"`
	Delivery       pgtype.Date        `json:"delivery"`
	IDPoClientItem int32              `json:"id_po_client_item"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateWorkOrder(ctx context.Context, arg CreateWorkOrderParams) (CreateWorkOrderRow, error) {
	row := q.db.QueryRow(ctx, createWorkOrder,
		arg.Buyer,
		arg.Model,
		arg.Qty,
		arg.FobCmt,
		arg.Delivery,
		arg.IDPoClientItem,
	)
	var i CreateWorkOrderRow
	err := row.Scan(
		&i.IDWo,
		&i.Buyer,
		&i.Model,
		&i.Qty,
		&i.FobCmt,
		&i.Delivery,
		&i.IDPoClientItem,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkOrderShell = `-- name: CreateWorkOrderShell :one
INSERT INTO WORK_ORDER_SHELL (
    fabric,
    cons,
    color,
    allow,
    berat_1_yd,
    id_wo
) VALUES (
    $1,
    $2::numeric,
    $3,
    $4,
    $5::numeric,
    $6
)
RETURNING id_wo_shell, fabric, cons, color, allow, berat_1_yd, id_wo, created_at
`

type CreateWorkOrderShellParams struct {
	Fabric   string         `json:"fabric"`
	Cons     pgtype.Numeric `json:"cons"`
	Color    string         `json:"color"`
	Allow    int32          `json:"allow"`
	Berat1Yd pgtype.Numeric `json:"berat_1_yd"`
	IDWo     int32          `json:"id_wo"`
}

func (q *Queries) CreateWorkOrderShell(ctx context.Context, arg CreateWorkOrderShellParams) (WorkOrderShell, error) {
	row := q.db.QueryRow(ctx, createWorkOrderShell,
		arg.Fabric,
		arg.Cons,
		arg.Color,
		arg.Allow,
		arg.Berat1Yd,
		arg.IDWo,
	)
	var i WorkOrderShell
	err := row.Scan(
		&i.IDWoShell,
		&i.Fabric,
		&i.Cons,
		&i.Color,
		&i.Allow,
		&i.Berat1Yd,
		&i.IDWo,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkOrderShellSize = `-- name: CreateWorkOrderShellSize :one
INSERT INTO WORK_ORDER_SHELL_SIZE (
    size,
    qty,
    ratio,
    id_wo_shell
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id_wo_shell_size, size, qty, ratio, id_wo_shell, created_at
`

type CreateWorkOrderShellSizeParams struct {
	Size      string `json:"size"`
	Qty       int32  `json:"qty"`
	Ratio     int32  `json:"ratio"`
	IDWoShell int32  `json:"id_wo_shell"`
}

func (q *Queries) CreateWorkOrderShellSize(ctx context.Context, arg CreateWorkOrderShellSizeParams) (WorkOrderShellSize, error) {
	row := q.db.QueryRow(ctx, createWorkOrderShellSize,
		arg.Size,
		arg.Qty,
		arg.Ratio,
		arg.IDWoShell,
	)
	var i WorkOrderShellSize
	err := row.Scan(
		&i.IDWoShellSize,
		&i.Size,
		&i.Qty,
		&i.Ratio,
		&i.IDWoShell,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkOrderTrim = `-- name: CreateWorkOrderTrim :one
INSERT INTO WORK_ORDER_TRIM (
    item,
    description,
    color,
    code,
    cons,
    qty,
    uom,
    position,
    created_by,
    allow,
    id_wo
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5::numeric,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id_wo_trim, item, description, color, code, cons, qty, uom, position, created_by, allow, id_wo, created_at
`

type CreateWorkOrderTrimParams struct {
	Item        string         `json:"item"`
	Description string         `json:"description"`
	Color       string         `json:"color"`
	Code        string         `json:"code"`
	Cons        pgtype.Numeric `json:"cons"`
	Qty         int32          `json:"qty"`
	Uom         string         `json:"uom"`
	Position    string         `json:"position"`
	CreatedBy   string         `json:"created_by"`
	Allow       int32          `json:"allow"`
	IDWo        int32          `json:"id_wo"`
}

func (q *Queries) CreateWorkOrderTrim(ctx context.Context, arg CreateWorkOrderTrimParams) (WorkOrderTrim, error) {
	row := q.db.QueryRow(ctx, createWorkOrderTrim,
		arg.Item,
		arg.Description,
		arg.Color,
		arg.Code,
		arg.Cons,
		arg.Qty,
		arg.Uom,
		arg.Position,
		arg.CreatedBy,
		arg.Allow,
		arg.IDWo,
	)
	var i WorkOrderTrim
	err := row.Scan(
		&i.IDWoTrim,
		&i.Item,
		&i.Description,
		&i.Color,
		&i.Code,
		&i.Cons,
		&i.Qty,
		&i.Uom,
		&i.Position,
		&i.CreatedBy,
		&i.Allow,
		&i.IDWo,
		&i.CreatedAt,
	)
	return i, err
}

const workOrderShellTotalQty = `-- name: WorkOrderShellTotalQty :one
SELECT COALESCE(SUM(qty), 0)::bigint AS total_qty
FROM WORK_ORDER_SHELL_SIZE
WHERE id_wo_shell = $1
`

func (q *Queries) WorkOrderShellTotalQty(ctx context.Context, idWoShell int32) (int64, error) {
	row := q.db.QueryRow(ctx, workOrderShellTotalQty, idWoShell)
	var total_qty int64
	err := row.Scan(&total_qty)
	return total_qty, err
}
