-- name: CreateMarkerPlan :one
INSERT INTO MARKER_PLAN (
    NO_DOKUMEN, TANGGAL_EFEKTIF, ID_WO_SHELL
) VALUES (
    $1, $2, $3
) RETURNING ID_MARKER_PLAN, NO_DOKUMEN, TANGGAL_EFEKTIF, ID_WO_SHELL, created_at;

-- name: CreateKomponenMarkerPlan :one
INSERT INTO KOMPONEN_MARKER_PLAN (
    ID_MARKER_PLAN, NAMA_KOMPONEN
) VALUES (
    $1, $2
) RETURNING ID_KOMPONEN_MARKER, ID_MARKER_PLAN, NAMA_KOMPONEN, created_at;

-- name: CreateRatioMarker :one
INSERT INTO RATIO_MARKER (
    ID_KOMPONEN_MARKER, ID_WO_SHELL, CONS, PLAN_SPREADING_GELARAN,
    PANJANG_MARKER, EFFICIENCY_MARKER, ALLOWANCE, CONS_BUYER,
    ROLL_QTY, SAMBUNGAN_ROLL, PLOT, LEBAR_KAIN, PANJANG_MARKER_UNIT, KET
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING ID_RATIO_MARKER, ID_KOMPONEN_MARKER, ID_WO_SHELL, CONS, PLAN_SPREADING_GELARAN, PANJANG_MARKER, EFFICIENCY_MARKER, ALLOWANCE, CONS_BUYER, ROLL_QTY, SAMBUNGAN_ROLL, PLOT, LEBAR_KAIN, PANJANG_MARKER_UNIT, KET, created_at;

-- name: CreateRatioSizeMarker :copyfrom
INSERT INTO RATIO_SIZE_MARKER (
    ID_RATIO_MARKER, ID_WO_SHELL_SIZE, QTY_PLAN
) VALUES (
    $1, $2, $3
);

-- name: GetMarkerPlanByID :one
SELECT ID_MARKER_PLAN, NO_DOKUMEN, TANGGAL_EFEKTIF, ID_WO_SHELL, created_at
FROM MARKER_PLAN
WHERE ID_MARKER_PLAN = $1 LIMIT 1;

-- name: ListKomponenByMarkerPlanID :many
SELECT ID_KOMPONEN_MARKER, ID_MARKER_PLAN, NAMA_KOMPONEN, created_at
FROM KOMPONEN_MARKER_PLAN
WHERE ID_MARKER_PLAN = $1
ORDER BY ID_KOMPONEN_MARKER ASC;

-- name: ListRatioByKomponenID :many
SELECT ID_RATIO_MARKER, ID_KOMPONEN_MARKER, ID_WO_SHELL, CONS, PLAN_SPREADING_GELARAN,
       PANJANG_MARKER, EFFICIENCY_MARKER, ALLOWANCE, CONS_BUYER, ROLL_QTY, SAMBUNGAN_ROLL,
       PLOT, LEBAR_KAIN, PANJANG_MARKER_UNIT, KET, created_at
FROM RATIO_MARKER
WHERE ID_KOMPONEN_MARKER = $1
ORDER BY ID_RATIO_MARKER ASC;

-- name: ListRatioSizeByRatioID :many
SELECT rsm.ID_RATIO_SIZE_MARKER, rsm.ID_RATIO_MARKER, rsm.ID_WO_SHELL_SIZE, rsm.QTY_PLAN, wss.SIZE
FROM RATIO_SIZE_MARKER rsm
JOIN WORK_ORDER_SHELL_SIZE wss ON rsm.ID_WO_SHELL_SIZE = wss.ID_WO_SHELL_SIZE
WHERE rsm.ID_RATIO_MARKER = $1
ORDER BY rsm.ID_RATIO_SIZE_MARKER ASC;
