-- name: CreateApprovalHeader :one
INSERT INTO OTORITAS_DOKUMEN (NAMA_TABEL_DOKUMEN, ID_DOKUMEN, STATUS_GLOBAL)
VALUES ($1, $2, $3) RETURNING ID_OTORITAS;

-- name: CreateApprovalDetail :one
INSERT INTO OTORITAS_DOKUMEN_DETAIL (ID_OTORITAS, ID_USER, TIPE_PERAN, IS_ACTION_DONE, WAKTU_AKSI, CATATAN)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING ID_OTORITAS_DETAIL, ID_OTORITAS, ID_USER, TIPE_PERAN, IS_ACTION_DONE, WAKTU_AKSI, CATATAN;

-- name: GetApprovalHeaderByDoc :one
SELECT ID_OTORITAS, NAMA_TABEL_DOKUMEN, ID_DOKUMEN, STATUS_GLOBAL, created_at
FROM OTORITAS_DOKUMEN
WHERE NAMA_TABEL_DOKUMEN = $1 AND ID_DOKUMEN = $2
LIMIT 1;

-- name: GetApprovalHeaderByID :one
SELECT ID_OTORITAS, NAMA_TABEL_DOKUMEN, ID_DOKUMEN, STATUS_GLOBAL, created_at
FROM OTORITAS_DOKUMEN
WHERE ID_OTORITAS = $1
LIMIT 1;

-- name: GetApprovalDetailByID :one
SELECT ID_OTORITAS_DETAIL, ID_OTORITAS, ID_USER, TIPE_PERAN, IS_ACTION_DONE, WAKTU_AKSI, CATATAN, created_at
FROM OTORITAS_DOKUMEN_DETAIL
WHERE ID_OTORITAS_DETAIL = $1
LIMIT 1;

-- name: ListApprovalDetailsByHeaderID :many
SELECT ID_OTORITAS_DETAIL, ID_OTORITAS, ID_USER, TIPE_PERAN, IS_ACTION_DONE, WAKTU_AKSI, CATATAN, created_at
FROM OTORITAS_DOKUMEN_DETAIL
WHERE ID_OTORITAS = $1
ORDER BY ID_OTORITAS_DETAIL ASC;

-- name: UpdateApprovalStep :one
UPDATE OTORITAS_DOKUMEN_DETAIL
SET IS_ACTION_DONE = $1, WAKTU_AKSI = $2, CATATAN = $3
WHERE ID_OTORITAS_DETAIL = $4
RETURNING ID_OTORITAS_DETAIL, ID_OTORITAS, ID_USER, TIPE_PERAN, IS_ACTION_DONE, WAKTU_AKSI, CATATAN;

-- name: UpdateGlobalStatus :one
UPDATE OTORITAS_DOKUMEN
SET STATUS_GLOBAL = $1
WHERE ID_OTORITAS = $2
RETURNING ID_OTORITAS, NAMA_TABEL_DOKUMEN, ID_DOKUMEN, STATUS_GLOBAL;

-- name: HasPreviousPendingSteps :one
SELECT EXISTS (
    SELECT 1 FROM OTORITAS_DOKUMEN_DETAIL
    WHERE ID_OTORITAS = $1
      AND ID_OTORITAS_DETAIL < $2
      AND IS_ACTION_DONE = FALSE
)::boolean;

-- name: HasPendingSteps :one
SELECT EXISTS (
    SELECT 1 FROM OTORITAS_DOKUMEN_DETAIL
    WHERE ID_OTORITAS = $1
      AND IS_ACTION_DONE = FALSE
)::boolean;

-- name: GetTruePendingApprovalsByUser :many
SELECT 
    od.ID_OTORITAS, 
    od.NAMA_TABEL_DOKUMEN, 
    od.ID_DOKUMEN, 
    odd.ID_OTORITAS_DETAIL,
    odd.TIPE_PERAN,
    od.created_at AS requested_at
FROM OTORITAS_DOKUMEN_DETAIL odd
JOIN OTORITAS_DOKUMEN od ON odd.ID_OTORITAS = od.ID_OTORITAS
WHERE odd.ID_USER = $1 
  AND odd.IS_ACTION_DONE = FALSE
  AND LOWER(od.STATUS_GLOBAL) = 'pending'
  AND NOT EXISTS (
      SELECT 1 FROM OTORITAS_DOKUMEN_DETAIL prev
      WHERE prev.ID_OTORITAS = odd.ID_OTORITAS
        AND prev.ID_OTORITAS_DETAIL < odd.ID_OTORITAS_DETAIL
        AND prev.IS_ACTION_DONE = FALSE
  )
ORDER BY od.created_at ASC;

-- name: ListApprovalHistory :many
SELECT 
    ID_OTORITAS, 
    NAMA_TABEL_DOKUMEN, 
    ID_DOKUMEN, 
    STATUS_GLOBAL, 
    created_at,
    COUNT(*) OVER() AS total_count
FROM OTORITAS_DOKUMEN
WHERE 
    (sqlc.arg(status_filter)::text = '' OR LOWER(STATUS_GLOBAL) = LOWER(sqlc.arg(status_filter)))
    AND (sqlc.arg(table_filter)::text = '' OR LOWER(NAMA_TABEL_DOKUMEN) = LOWER(sqlc.arg(table_filter)))
ORDER BY created_at DESC
LIMIT sqlc.arg(page_limit) OFFSET sqlc.arg(page_offset);
