-- name: CreateApprovalHeader :one
INSERT INTO OTORITAS_DOKUMEN (NAMA_TABEL_DOKUMEN, ID_DOKUMEN, STATUS_GLOBAL)
VALUES ($1, $2, $3) RETURNING ID_OTORITAS;

-- name: CreateApprovalDetail :copyfrom
INSERT INTO OTORITAS_DOKUMEN_DETAIL (ID_OTORITAS, ID_USER, TIPE_PERAN, IS_ACTION_DONE, WAKTU_AKSI)
VALUES ($1, $2, $3, $4, $5);

-- name: GetPendingApprovalsByUser :many
SELECT od.ID_OTORITAS, od.NAMA_TABEL_DOKUMEN, od.ID_DOKUMEN, odd.TIPE_PERAN 
FROM OTORITAS_DOKUMEN_DETAIL odd
JOIN OTORITAS_DOKUMEN od ON odd.ID_OTORITAS = od.ID_OTORITAS
WHERE odd.ID_USER = $1 AND odd.IS_ACTION_DONE = FALSE;
