// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@permatatex.local"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "Authenticates user using username, password, and Turnstile token, then returns JWT access token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Sign In",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.LoginSuccessDoc"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.LoginBadRequestDoc"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.LoginUnauthorizedDoc"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/model.LoginTooManyRequestsDoc"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/model.LoginBadGatewayDoc"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/model.LoginServiceUnavailableDoc"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns authenticated user ID extracted from JWT token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get Current User Profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GetMeSuccessDoc"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.GetMeUnauthorizedDoc"
                        }
                    }
                }
            }
        },
        "/api/v1/master/barang": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "List Items",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit (default 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ListBarangSuccessDoc"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Create Item",
                "parameters": [
                    {
                        "description": "Item payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateBarangRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.CreateBarangSuccessDoc"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/model.LoginBadRequestDoc"
                        }
                    }
                }
            }
        },
        "/api/v1/master/barang/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Get Item Detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.CreateBarangSuccessDoc"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Update Item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Item payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateBarangRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.CreateBarangSuccessDoc"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/model.LoginBadRequestDoc"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Delete Item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/master/company": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Get Company Data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.CompanySuccessDoc"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Create Company Data",
                "parameters": [
                    {
                        "description": "Company payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateCompanyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.CompanySuccessDoc"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/model.LoginBadRequestDoc"
                        }
                    }
                }
            }
        },
        "/api/v1/master/company/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Get Company Detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Company ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.CompanySuccessDoc"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Update Company Data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Company ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Company payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateCompanyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.CompanySuccessDoc"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Delete Company Data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Company ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/master/departemen": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "List Departments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ListDepartemenSuccessDoc"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Create Department",
                "parameters": [
                    {
                        "description": "Department payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateDepartemenRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.CreateDepartemenSuccessDoc"
                        }
                    }
                }
            }
        },
        "/api/v1/master/departemen/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Get Department Detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Department ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.CreateDepartemenSuccessDoc"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Update Department",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Department ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Department payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateDepartemenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.CreateDepartemenSuccessDoc"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Delete Department",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Department ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/master/jenis-barang": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "List Item Types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ListJenisBarangSuccessDoc"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Create Item Type",
                "parameters": [
                    {
                        "description": "Item type payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateJenisBarangRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.CreateJenisBarangSuccessDoc"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/model.LoginBadRequestDoc"
                        }
                    }
                }
            }
        },
        "/api/v1/master/jenis-barang/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Get Item Type Detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Item Type ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.CreateJenisBarangSuccessDoc"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Update Item Type",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Item Type ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Item type payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateJenisBarangRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.CreateJenisBarangSuccessDoc"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/model.LoginBadRequestDoc"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Delete Item Type",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Item Type ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/master/mitra": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "List Partners",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ListMitraSuccessDoc"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Create Partner",
                "parameters": [
                    {
                        "description": "Partner payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateMitraRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.CreateMitraSuccessDoc"
                        }
                    }
                }
            }
        },
        "/api/v1/master/mitra/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Get Partner Detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Partner ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.CreateMitraSuccessDoc"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Update Partner",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Partner ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Partner payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateMitraRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.CreateMitraSuccessDoc"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Delete Partner",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Partner ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/master/permissions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "List Available Permissions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ListPermissionsSuccessDoc"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Create Permission",
                "parameters": [
                    {
                        "description": "Permission payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateHakAksesRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.HakAksesSuccessDoc"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/model.LoginBadRequestDoc"
                        }
                    }
                }
            }
        },
        "/api/v1/master/permissions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Get Permission Detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Permission ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.HakAksesSuccessDoc"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Update Permission",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Permission ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Permission payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateHakAksesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.HakAksesSuccessDoc"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Delete Permission",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Permission ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of users with their department and mitra names.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "List Users",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit (default 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UserListSuccessDoc"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.GetMeUnauthorizedDoc"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new user and assigns permissions in a single transaction.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Create New User",
                "parameters": [
                    {
                        "description": "Create user payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.UserSuccessDoc"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.LoginBadRequestDoc"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.GetMeUnauthorizedDoc"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/model.LoginBadRequestDoc"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/model.LoginServiceUnavailableDoc"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single user detail with permissions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get User Detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UserSuccessDoc"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.GetMeUnauthorizedDoc"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.LoginBadRequestDoc"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates user profile and permissions in a single transaction. Password is optional.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update User",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update user payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UserSuccessDoc"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.LoginBadRequestDoc"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.GetMeUnauthorizedDoc"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.LoginBadRequestDoc"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/model.LoginBadRequestDoc"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a user by ID. Protects Super Admin (ID 1) from deletion.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Delete User",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.LoginBadRequestDoc"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.GetMeUnauthorizedDoc"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.LoginBadRequestDoc"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns service health status, including database connectivity.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/response.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AuthServiceUnavailableErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "auth_service_unavailable"
                }
            }
        },
        "model.BarangResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id_barang": {
                    "type": "integer"
                },
                "kode": {
                    "type": "string"
                },
                "nama_barang": {
                    "type": "string"
                },
                "nama_jenis_barang": {
                    "type": "string"
                },
                "nama_perusahaan": {
                    "type": "string"
                }
            }
        },
        "model.CompanyResponse": {
            "type": "object",
            "properties": {
                "about": {
                    "type": "string"
                },
                "alamat": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id_company": {
                    "type": "integer"
                },
                "logo": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "no_telp": {
                    "type": "string"
                }
            }
        },
        "model.CompanySuccessDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/model.CompanyResponse"
                },
                "message": {
                    "type": "string",
                    "example": "company data retrieved"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.CreateBarangRequest": {
            "type": "object",
            "required": [
                "id_jenis_barang",
                "id_mitra",
                "kode",
                "nama_barang"
            ],
            "properties": {
                "id_jenis_barang": {
                    "type": "integer"
                },
                "id_mitra": {
                    "type": "integer"
                },
                "kode": {
                    "type": "string"
                },
                "nama_barang": {
                    "type": "string"
                }
            }
        },
        "model.CreateBarangSuccessDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/model.BarangResponse"
                },
                "message": {
                    "type": "string",
                    "example": "barang created"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.CreateCompanyRequest": {
            "type": "object",
            "required": [
                "nama"
            ],
            "properties": {
                "about": {
                    "type": "string"
                },
                "alamat": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "no_telp": {
                    "type": "string"
                }
            }
        },
        "model.CreateDepartemenRequest": {
            "type": "object",
            "required": [
                "nama_departemen"
            ],
            "properties": {
                "nama_departemen": {
                    "type": "string"
                }
            }
        },
        "model.CreateDepartemenSuccessDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/model.DepartemenResponse"
                },
                "message": {
                    "type": "string",
                    "example": "departemen created"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.CreateHakAksesRequest": {
            "type": "object",
            "required": [
                "nama_halaman"
            ],
            "properties": {
                "nama_halaman": {
                    "type": "string"
                }
            }
        },
        "model.CreateJenisBarangRequest": {
            "type": "object",
            "required": [
                "kode",
                "nama_jenis_barang"
            ],
            "properties": {
                "kode": {
                    "type": "string"
                },
                "nama_jenis_barang": {
                    "type": "string"
                }
            }
        },
        "model.CreateJenisBarangSuccessDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/model.JenisBarangResponse"
                },
                "message": {
                    "type": "string",
                    "example": "jenis barang created"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.CreateMitraRequest": {
            "type": "object",
            "required": [
                "nama_perusahaan",
                "no_telp",
                "tipe_perusahaan"
            ],
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "kode_pos": {
                    "type": "string"
                },
                "kota": {
                    "type": "string"
                },
                "nama_perusahaan": {
                    "type": "string"
                },
                "no_telp": {
                    "type": "string"
                },
                "tipe_perusahaan": {
                    "type": "string"
                }
            }
        },
        "model.CreateMitraSuccessDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/model.MitraResponse"
                },
                "message": {
                    "type": "string",
                    "example": "mitra created"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.CreateUserRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "hak_akses_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id_departemen": {
                    "type": "integer"
                },
                "id_mitra": {
                    "type": "integer"
                },
                "is_manager": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.DepartemenResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id_departemen": {
                    "type": "integer"
                },
                "nama_departemen": {
                    "type": "string"
                }
            }
        },
        "model.GetMeResponse": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.GetMeSuccessDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/model.GetMeResponse"
                },
                "message": {
                    "type": "string",
                    "example": "profile retrieved"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.GetMeUnauthorizedDoc": {
            "type": "object",
            "properties": {
                "error": {},
                "message": {
                    "type": "string",
                    "example": "unauthorized"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "model.HakAksesResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id_hak_akses": {
                    "type": "integer"
                },
                "nama_halaman": {
                    "type": "string"
                }
            }
        },
        "model.HakAksesSuccessDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/model.HakAksesResponse"
                },
                "message": {
                    "type": "string",
                    "example": "permission created"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.JenisBarangResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id_jenis_barang": {
                    "type": "integer"
                },
                "kode": {
                    "type": "string"
                },
                "nama_jenis_barang": {
                    "type": "string"
                }
            }
        },
        "model.ListBarangSuccessDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.BarangResponse"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "barang retrieved"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.ListDepartemenSuccessDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.DepartemenResponse"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "departemen retrieved"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.ListJenisBarangSuccessDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.JenisBarangResponse"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "jenis barang retrieved"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.ListMitraSuccessDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.MitraResponse"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "mitra retrieved"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.ListPermissionsSuccessDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.HakAksesResponse"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "permissions retrieved"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.LoginBadGatewayDoc": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/model.TurnstileErrorDetail"
                },
                "message": {
                    "type": "string",
                    "example": "captcha verification service unavailable"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "model.LoginBadRequestDoc": {
            "type": "object",
            "properties": {
                "error": {},
                "message": {
                    "type": "string",
                    "example": "bad request"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "model.LoginRateLimitErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "too_many_login_attempts"
                },
                "retry_after_seconds": {
                    "type": "integer",
                    "example": 60
                }
            }
        },
        "model.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "turnstile_token",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "turnstile_token": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "model.LoginServiceUnavailableDoc": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/model.AuthServiceUnavailableErrorDetail"
                },
                "message": {
                    "type": "string",
                    "example": "authentication service unavailable"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "model.LoginSuccessDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/model.LoginResponse"
                },
                "message": {
                    "type": "string",
                    "example": "login successful"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.LoginTooManyRequestsDoc": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/model.LoginRateLimitErrorDetail"
                },
                "message": {
                    "type": "string",
                    "example": "too many login attempts, please try again later"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "model.LoginUnauthorizedDoc": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "invalid username or password"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "model.MitraResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id_mitra": {
                    "type": "integer"
                },
                "nama_perusahaan": {
                    "type": "string"
                },
                "no_telp": {
                    "type": "string"
                },
                "tipe_perusahaan": {
                    "type": "string"
                }
            }
        },
        "model.TurnstileErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "captcha_invalid"
                },
                "error_codes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.UpdateBarangRequest": {
            "type": "object",
            "required": [
                "id_jenis_barang",
                "id_mitra",
                "kode",
                "nama_barang"
            ],
            "properties": {
                "id_jenis_barang": {
                    "type": "integer"
                },
                "id_mitra": {
                    "type": "integer"
                },
                "kode": {
                    "type": "string"
                },
                "nama_barang": {
                    "type": "string"
                }
            }
        },
        "model.UpdateCompanyRequest": {
            "type": "object",
            "required": [
                "nama"
            ],
            "properties": {
                "about": {
                    "type": "string"
                },
                "alamat": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "no_telp": {
                    "type": "string"
                }
            }
        },
        "model.UpdateDepartemenRequest": {
            "type": "object",
            "required": [
                "nama_departemen"
            ],
            "properties": {
                "nama_departemen": {
                    "type": "string"
                }
            }
        },
        "model.UpdateHakAksesRequest": {
            "type": "object",
            "required": [
                "nama_halaman"
            ],
            "properties": {
                "nama_halaman": {
                    "type": "string"
                }
            }
        },
        "model.UpdateJenisBarangRequest": {
            "type": "object",
            "required": [
                "kode",
                "nama_jenis_barang"
            ],
            "properties": {
                "kode": {
                    "type": "string"
                },
                "nama_jenis_barang": {
                    "type": "string"
                }
            }
        },
        "model.UpdateMitraRequest": {
            "type": "object",
            "required": [
                "nama_perusahaan",
                "no_telp",
                "tipe_perusahaan"
            ],
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "kode_pos": {
                    "type": "string"
                },
                "kota": {
                    "type": "string"
                },
                "nama_perusahaan": {
                    "type": "string"
                },
                "no_telp": {
                    "type": "string"
                },
                "tipe_perusahaan": {
                    "type": "string"
                }
            }
        },
        "model.UpdateUserRequest": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "hak_akses_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id_departemen": {
                    "type": "integer"
                },
                "id_mitra": {
                    "type": "integer"
                },
                "is_manager": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.UserListSuccessDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.UserResponse"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "users retrieved"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id_user": {
                    "type": "integer"
                },
                "is_manager": {
                    "type": "boolean"
                },
                "nama_departemen": {
                    "type": "string"
                },
                "nama_perusahaan": {
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.UserSuccessDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/model.UserResponse"
                },
                "message": {
                    "type": "string",
                    "example": "user created"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "response.BaseResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "response.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Permatatex IT Inventory API",
	Description:      "API documentation for Permatatex IT Inventory System backend.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
