// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@permatatex.local"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/turnstile/verify": {
            "post": {
                "description": "Validates frontend Turnstile token via Cloudflare siteverify API.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Verify Turnstile Token",
                "parameters": [
                    {
                        "description": "Turnstile payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.VerifyTurnstileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.VerifyTurnstileSuccessDoc"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.VerifyTurnstileBadRequestDoc"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/model.VerifyTurnstileBadGatewayDoc"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns service health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.TurnstileErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "captcha_invalid"
                },
                "error_codes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.VerifyTurnstileBadGatewayDoc": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/model.TurnstileErrorDetail"
                },
                "message": {
                    "type": "string",
                    "example": "captcha verification service unavailable"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "model.VerifyTurnstileBadRequestDoc": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/model.TurnstileErrorDetail"
                },
                "message": {
                    "type": "string",
                    "example": "captcha verification failed"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "model.VerifyTurnstileRequest": {
            "type": "object",
            "required": [
                "turnstile_token"
            ],
            "properties": {
                "turnstile_token": {
                    "type": "string",
                    "maxLength": 2048
                }
            }
        },
        "model.VerifyTurnstileResponse": {
            "type": "object",
            "properties": {
                "verified": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "model.VerifyTurnstileSuccessDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/model.VerifyTurnstileResponse"
                },
                "message": {
                    "type": "string",
                    "example": "captcha verification succeeded"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "response.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Permatatex IT Inventory API",
	Description:      "API documentation for Permatatex IT Inventory System backend.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
